// Base coordinates for Ahmedabad (approximate center)
const baseLat = 23.0225;
const baseLon = 72.5714;

export const ahmedabadRestaurants = [
  // --- Famous & Fine Dining (First 5 ) ---
  // {
  //   name: 'Agashiye',
  //   description:
  //     'An iconic rooftop restaurant offering an authentic Gujarati thali experience in a heritage setting.',
  //   address: {
  //     street: 'The House of MG, Lal Darwaja',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.06, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9909982013', email: 'agashiye@houseofmg.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch', 'Desserts'],
  //   rating: 4.8,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 10,
  //   is_veg: true,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Vishalla',
  //   description:
  //     'A unique village-themed restaurant serving traditional Gujarati food with folk music and a utensils museum.',
  //   address: {
  //     street: 'Opp. Vasna Tol Naka',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380007',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat - 0.05],
  //     },
  //   },
  //   contact: { phone: '9879601808', email: 'info@vishalla.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch', 'Street-Food'],
  //   rating: 4.6,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Tuesday', open: '19:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 1000,
  //   delivery_radius_km: 12,
  //   is_veg: true,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Earthen Oven - Fortune Landmark',
  //   description:
  //     'A fine-dining restaurant known for its exquisite North-West Frontier cuisine and kebabs.',
  //   address: {
  //     street: 'Ashram Road',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380013',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9099035201', email: 'landmark@fortunehotels.in' },
  //   cuisine_type: ['North-Indian', 'BBQ', 'Indian', 'Dinner', 'Lunch'],
  //   rating: 4.7,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Wednesday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 3000,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'The Green House - The House of MG',
  //   description:
  //     'A charming courtyard cafe offering a mix of Indian and continental dishes all day.',
  //   address: {
  //     street: 'Lal Darwaja',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.061, baseLat + 0.011],
  //     },
  //   },
  //   contact: { phone: '9909982013', email: 'greenhouse@houseofmg.com' },
  //   cuisine_type: ['Beverages', 'Desserts', 'Indian', 'Breakfast', 'Lunch', 'Sandwiches'],
  //   rating: 4.5,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Thursday', open: '07:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 10,
  //   is_veg: true,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Gordhan Thal',
  //   description:
  //     'A very popular restaurant for unlimited Gujarati and Rajasthani thalis.',
  //   address: {
  //     street: 'S.G. Highway, Bodakdev',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.1, baseLat + 0.05],
  //     },
  //   },
  //   contact: { phone: '9825032555', email: 'info@gordhanthal.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Lunch', 'Dinner', 'Desserts'],
  //   rating: 4.4,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 12,
  //   is_veg: true,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 50,
  // },
  // --- Second 5
  // {
  //   name: 'Patang - The Revolving Restaurant',
  //   description:
  //     'Iconic revolving restaurant offering panoramic city views and a multi-cuisine buffet.',
  //   address: {
  //     street: 'Near Nehru Bridge, Ashram Road',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9099032732', email: 'info@patanghotel.com' },
  //   cuisine_type: ['North-Indian', 'Chinese', 'Dinner', 'Lunch', 'Desserts'],
  //   rating: 4.3,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Saturday', open: '19:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 1200,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 3500,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Swati Snacks',
  //   description:
  //     'A beloved eatery serving traditional Gujarati snacks with a modern, hygienic twist.',
  //   address: {
  //     street: 'Near Law Garden, C.G. Road',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.032, baseLat + 0.022],
  //     },
  //   },
  //   contact: { phone: '7926405901', email: 'swati@swatisnacks.com' },
  //   cuisine_type: ['Indian', 'Street-Food', 'South-Indian', 'Healthy', 'Breakfast', 'Fast-Food'],
  //   rating: 4.9,
  //   numberOfReviews: 6800,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '22:45' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Sasuji Dining Hall',
  //   description: 'An old and famous place for an authentic, homely Gujarati thali.',
  //   address: {
  //     street: 'Lal Darwaja',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.055, baseLat + 0.008],
  //     },
  //   },
  //   contact: { phone: '7925506193', email: 'contact@sasuji.in' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Lunch', 'Dinner'],
  //   rating: 4.5,
  //   numberOfReviews: 4100,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 9,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Tomato\'s',
  //   description:
  //     'A retro-themed American diner with a multi-cuisine menu, famous for its ambiance.',
  //   address: {
  //     street: 'C.G. Road, Navrangpura',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.035, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '7926467888', email: 'info@tomatos.co.in' },
  //   cuisine_type: ['Mexican', 'North-Indian', 'Italian', 'Pizza', 'Burgers'],
  //   rating: 4.4,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Barbeque Nation',
  //   description:
  //     'The original live-on-the-table grill restaurant with a lavish buffet.',
  //   address: {
  //     street: 'Prahlad Nagar',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.08, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '8069028721', email: 'feedback@barbequenation.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Indian', 'Dinner', 'Lunch'],
  //   rating: 4.7,
  //   numberOfReviews: 7500,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // --- Street Food & Local Legends (third 5 ) ---
  // {
  //   name: 'Manek Chowk Night Market',
  //   description:
  //     'A bustling night market famous for Gwalior Dosa, Pav Bhaji, and unique sandwiches.',
  //   address: {
  //     street: 'Manek Chowk, Old City',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: 'N/A', email: 'N/A' },
  //   cuisine_type: ['Street-Food', 'Indian', 'Fast-Food', 'Dinner'],
  //   rating: 4.7,
  //   numberOfReviews: 9800,
  //   opening_hours: [{ day: 'Thursday', open: '20:00', close: '01:30' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Law Garden Khau Gali',
  //   description:
  //     'An evening food street offering a variety of snacks from rolls to chaat.',
  //   address: {
  //     street: 'Law Garden, Ellisbridge',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: 'N/A', email: 'N/A' },
  //   cuisine_type: ['Street-Food', 'Chinese', 'Fast-Food', 'Indian'],
  //   rating: 4.3,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Friday', open: '18:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Induben Khakhrawala',
  //   description:
  //     'A legendary store for authentic Gujarati snacks like Khakhra, Fafda, and more.',
  //   address: {
  //     street: 'C.G. Road, Navrangpura',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.038, baseLat + 0.028],
  //     },
  //   },
  //   contact: { phone: '7926425638', email: 'info@induben.com' },
  //   cuisine_type: ['Indian', 'Street-Food', 'Fast-Food', 'Breakfast'],
  //   rating: 4.8,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Saturday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 10,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Das Khaman House',
  //   description:
  //     'Famous for its soft and fluffy Khaman, a quintessential Gujarati snack.',
  //   address: {
  //     street: 'Multiple Locations',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9825003895', email: 'contact@daskhaman.com' },
  //   cuisine_type: ['Indian', 'Street-Food', 'Breakfast', 'Fast-Food'],
  //   rating: 4.6,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Sunday', open: '07:00', close: '20:00' }],
  //   is_active: true,
  //   min_order_value: 50,
  //   delivery_radius_km: 9,
  //   is_veg: true,
  //   cost_for_two: 100,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Karnavati Dabeli Centre',
  //   description: 'A go-to place for authentic and spicy Kutchi Dabeli.',
  //   address: {
  //     street: 'Maninagar',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380008',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9988776655', email: 'dabeli@example.com' },
  //   cuisine_type: ['Street-Food', 'Fast-Food', 'Indian', 'Sandwiches'],
  //   rating: 4.5,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Monday', open: '16:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 60,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 120,
  //   delivery_time_mins: 25,
  // },
  // fourth 5
  // {
  //   name: 'Salim Bhai\'s Burger',
  //   description:
  //     'A legendary non-veg street food stall famous for its unique mutton burgers.',
  //   address: {
  //     street: 'Bhatiyar Gali, Old City',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.045, baseLat + 0.002],
  //     },
  //   },
  //   contact: { phone: 'N/A', email: 'N/A' },
  //   cuisine_type: ['Street-Food', 'Burgers', 'Fast-Food', 'Dinner'],
  //   rating: 4.4,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Tuesday', open: '18:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 250,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Jassuben Old Pizza',
  //   description:
  //     'Serving a unique, Indian-style pizza that is an Ahmedabad classic.',
  //   address: {
  //     street: 'Navrangpura',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.033, baseLat + 0.033],
  //     },
  //   },
  //   contact: { phone: '9876512345', email: 'jassuben@example.com' },
  //   cuisine_type: ['Pizza', 'Street-Food', 'Fast-Food'],
  //   rating: 4.2,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Shakti - The Sandwich Shop',
  //   description:
  //     'A very popular sandwich stall known for its huge and loaded sandwiches.',
  //   address: {
  //     street: 'IIM Road',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat + 0.04],
  //     },
  //   },
  //   contact: { phone: '9998887776', email: 'shaktisandwich@example.com' },
  //   cuisine_type: ['Sandwiches', 'Street-Food', 'Fast-Food'],
  //   rating: 4.6,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Thursday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'RK Egg Eatery',
  //   description:
  //     'A famous spot for egg lovers, serving dozens of innovative egg dishes.',
  //   address: {
  //     street: 'Vastrapur',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.06, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9824012345', email: 'rkegg@example.com' },
  //   cuisine_type: ['Street-Food', 'Fast-Food', 'Dinner'],
  //   rating: 4.3,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Friday', open: '17:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 250,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Asharfi Kulfi',
  //   description:
  //     'A household name in Ahmedabad for delicious and traditional kulfis.',
  //   address: {
  //     street: 'Multiple Locations',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.028, baseLat + 0.021],
  //     },
  //   },
  //   contact: { phone: '7940020400', email: 'info@asharfikulfi.com' },
  //   cuisine_type: ['Desserts', 'Indian-Sweets', 'Beverages'],
  //   rating: 4.7,
  //   numberOfReviews: 4000,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 9,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 20,
  // },
  // --- Popular Cafes & Bakeries (sixth 5 ) ---
  // {
  //   name: 'Mocha Cafe & Bar',
  //   description:
  //     'A trendy and vibrant cafe with a global menu, famous for its coffee and desserts.',
  //   address: {
  //     street: 'Bodakdev',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.09, baseLat + 0.04],
  //     },
  //   },
  //   contact: { phone: '9879596888', email: 'mocha.ahd@example.com' },
  //   cuisine_type: ['Italian', 'Desserts', 'Beverages', 'Fast-Food', 'Sandwiches', 'Soups'],
  //   rating: 4.4,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Project Cafe',
  //   description:
  //     'A unique concept cafe combining food, art, and design. Known for its ambiance.',
  //   address: {
  //     street: 'Ambavadi',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9909937033', email: 'info@theprojectcafe.in' },
  //   cuisine_type: ['Italian', 'Healthy', 'Salads', 'Beverages', 'Desserts', 'Sandwiches'],
  //   rating: 4.5,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Zen Cafe',
  //   description:
  //     'A serene and minimalist cafe located in a garden setting, perfect for a quiet coffee.',
  //   address: {
  //     street: 'Navrangpura',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9825334285', email: 'zencafe@example.com' },
  //   cuisine_type: ['Beverages', 'Fast-Food', 'Desserts', 'Sandwiches', 'Soups'],
  //   rating: 4.3,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Little French Cafe',
  //   description:
  //     'A charming bakery and cafe with authentic French pastries and desserts.',
  //   address: {
  //     street: 'Prahlad Nagar',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.085, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9925183456', email: 'frenchcafe@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Breakfast', 'Sandwiches', 'Soups'],
  //   rating: 4.6,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Wednesday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Starbucks',
  //   description:
  //     'The premier roaster and retailer of specialty coffee in the world.',
  //   address: {
  //     street: 'One World Capital, S.G. Highway',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.11, baseLat + 0.06],
  //     },
  //   },
  //   contact: { phone: '18602660010', email: 'contact@tatastarbucks.com' },
  //   cuisine_type: ['Beverages', 'Desserts', 'Sandwiches', 'Breakfast', 'Fast-Food'],
  //   rating: 4.4,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Thursday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 30,
  // },
  // seven 5
  // {
  //   name: 'The Chocolate Room',
  //   description:
  //     'A paradise for chocolate lovers with a variety of desserts, shakes, and fondues.',
  //   address: {
  //     street: 'Vastrapur',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.065, baseLat + 0.035],
  //     },
  //   },
  //   contact: { phone: '9876543211', email: 'tcr.vastrapur@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Fast-Food', 'Pizza', 'Sandwiches'],
  //   rating: 4.2,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Cafe De Italiano',
  //   description: 'A cozy cafe known for its Italian food and relaxed vibe.',
  //   address: {
  //     street: 'Bodakdev',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.095, baseLat + 0.045],
  //     },
  //   },
  //   contact: { phone: '9988776655', email: 'italiano@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Desserts', 'Beverages', 'Soups'],
  //   rating: 4.1,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'VarieTea',
  //   description:
  //     'A popular spot for tea lovers, offering a huge variety of teas and snacks.',
  //   address: {
  //     street: 'Prahlad Nagar',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.082, baseLat - 0.012],
  //     },
  //   },
  //   contact: { phone: '9876511223', email: 'varietea@example.com' },
  //   cuisine_type: ['Beverages', 'Fast-Food', 'Sandwiches', 'Desserts', 'Breakfast'],
  //   rating: 4.3,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Sunday', open: '09:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Java+ - Courtyard by Marriott',
  //   description:
  //     'A 24/7 deli and coffee shop offering gourmet sandwiches, pastries, and coffee.',
  //   address: {
  //     street: 'Satellite',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.07, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '7966185000', email: 'courtyard.ahmedabad@marriott.com' },
  //   cuisine_type: ['Desserts', 'Sandwiches', 'Beverages', 'Breakfast', 'Soups'],
  //   rating: 4.6,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Monday', open: '00:00', close: '23:59' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Blue Oven',
  //   description:
  //     'A popular bakery known for its artisanal breads, cakes, and pastries.',
  //   address: {
  //     street: 'Navrangpura',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.042, baseLat + 0.028],
  //     },
  //   },
  //   contact: { phone: '9825188888', email: 'blueoven@example.com' },
  //   cuisine_type: ['Desserts', 'Fast-Food', 'Beverages', 'Breakfast', 'Sandwiches'],
  //   rating: 4.5,
  //   numberOfReviews: 1600,
  //   opening_hours: [{ day: 'Tuesday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // eight 5
  // {
  //   name: 'Turquoise Villa',
  //   description:
  //     'A vibrant cafe with a global menu, known for its lively ambiance and hookah.',
  //   address: {
  //     street: 'S.G. Highway, Thaltej',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380059',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.12, baseLat + 0.07],
  //     },
  //   },
  //   contact: { phone: '9909904444', email: 'tvilla@example.com' },
  //   cuisine_type: ['Italian', 'Mexican', 'Pizza', 'Beverages', 'Desserts'],
  //   rating: 4.0,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1300,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Huber & Holly',
  //   description:
  //     'A premium ice cream parlor and cafe with unique flavors and live ice cream making.',
  //   address: {
  //     street: 'Bodakdev',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.092, baseLat + 0.042],
  //     },
  //   },
  //   contact: { phone: '7940097799', email: 'info@huberandholly.com' },
  //   cuisine_type: ['Ice Cream', 'Desserts', 'Pizza', 'Fast-Food'],
  //   rating: 4.7,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 9,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Kaffa',
  //   description:
  //     'A 24-hour coffee shop that is a popular hangout spot for the youth.',
  //   address: {
  //     street: 'Navrangpura',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.036, baseLat + 0.026],
  //     },
  //   },
  //   contact: { phone: '9876541230', email: 'kaffa@example.com' },
  //   cuisine_type: ['Cafe', 'Beverages', 'Fast-Food', 'Sandwiches'],
  //   rating: 3.9,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Friday', open: '00:00', close: '23:59' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Buttercupp',
  //   description:
  //     'A cute little bakery famous for its cupcakes, macarons, and custom cakes.',
  //   address: {
  //     street: 'Bodakdev',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.098, baseLat + 0.048],
  //     },
  //   },
  //   contact: { phone: '9998765432', email: 'hello@buttercupp.in' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Breakfast'],
  //   rating: 4.6,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Brewgarten',
  //   description:
  //     'A microbrewery and cafe with a relaxed vibe and good food.',
  //   address: {
  //     street: 'S.G. Highway, Makarba',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380051',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.09, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9876556789', email: 'brewgarten@example.com' },
  //   cuisine_type: ['Italian', 'Beverages', 'Pizza', 'Fast-Food', 'Sandwiches'],
  //   rating: 4.2,
  //   numberOfReviews: 1400,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 40,
  // },
  // nine 5
  // --- Mid-Range & Casual Dining (Next 20) ---
  // {
  //   name: 'Honest',
  //   description:
  //     'A very popular local chain famous for its Pav Bhaji and multi-cuisine menu.',
  //   address: {
  //     street: 'Multiple Locations',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.075, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '9925188800', email: 'info@honest.co.in' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Fast-Food', 'Pizza', 'Chinese'],
  //   rating: 4.1,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 10,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Havmor Restaurant',
  //   description:
  //     'An old and trusted name for North Indian food, sizzlers, and of course, ice cream.',
  //   address: {
  //     street: 'Navrangpura',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat + 0.022],
  //     },
  //   },
  //   contact: { phone: '7926445555', email: 'info@havmor.com' },
  //   cuisine_type: ['North-Indian', 'Chinese', 'Desserts', 'Fast-Food'],
  //   rating: 4.3,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Sankalp',
  //   description:
  //     'Famous for its incredibly long dosas and authentic South Indian flavors.',
  //   address: {
  //     street: 'C.G. Road',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.037, baseLat + 0.027],
  //     },
  //   },
  //   contact: { phone: '7926467890', email: 'sankalp.cg@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch'],
  //   rating: 4.4,
  //   numberOfReviews: 3900,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Iscon Thal',
  //   description: 'A popular thali restaurant serving Gujarati and Kathiyawadi food.',
  //   address: {
  //     street: 'S.G. Highway, Bodakdev',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.105, baseLat + 0.055],
  //     },
  //   },
  //   contact: { phone: '9909999999', email: 'info@isconthal.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Lunch', 'Dinner'],
  //   rating: 4.2,
  //   numberOfReviews: 3300,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 11,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Mirch Masala',
  //   description:
  //     'A Bollywood-themed restaurant serving delicious North Indian cuisine.',
  //   address: {
  //     street: 'C.G. Road',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.039, baseLat + 0.029],
  //     },
  //   },
  //   contact: { phone: '7926467889', email: 'info@mirchmasala.co.in' },
  //   cuisine_type: ['North-Indian', 'Indian', 'BBQ', 'Dinner', 'Lunch'],
  //   rating: 4.3,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 40,
  // },
  // ten 5
  // {
  //   name: 'Dakshinayan',
  //   description:
  //     'A premium South Indian restaurant known for its authentic taste and quality.',
  //   address: {
  //     street: 'Bodakdev',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.093, baseLat + 0.043],
  //     },
  //   },
  //   contact: { phone: '9876512346', email: 'dakshinayan@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Breakfast', 'Lunch'],
  //   rating: 4.6,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 9,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Upper Crust Cafe',
  //   description:
  //     'A long-standing cafe famous for its sizzlers, sandwiches, and baked goods.',
  //   address: {
  //     street: 'Vastrapur',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.062, baseLat + 0.032],
  //     },
  //   },
  //   contact: { phone: '7926747121', email: 'uppercrust@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Desserts', 'Beverages', 'Sandwiches'],
  //   rating: 4.2,
  //   numberOfReviews: 2600,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Nini\'s Kitchen',
  //   description:
  //     'A popular spot among youngsters for its Indian-style pastas and North Indian food.',
  //   address: {
  //     street: 'Prahlad Nagar',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.083, baseLat - 0.013],
  //     },
  //   },
  //   contact: { phone: '9898006098', email: 'niniskitchen@example.com' },
  //   cuisine_type: ['North-Indian', 'Italian', 'Fast-Food', 'Dinner'],
  //   rating: 4.4,
  //   numberOfReviews: 3400,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 9,
  //   is_veg: true,
  //   cost_for_two: 750,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Gamthi',
  //   description: 'Serving authentic and spicy Kathiyawadi cuisine.',
  //   address: {
  //     street: 'S.G. Highway',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380058',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.13, baseLat + 0.08],
  //     },
  //   },
  //   contact: { phone: '9876543212', email: 'gamthi@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch'],
  //   rating: 4.1,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Tuesday', open: '18:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 12,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Global Desi Tadka',
  //   description:
  //     'A casual dining restaurant with a vibrant ambiance and a multi-cuisine menu.',
  //   address: {
  //     street: 'Vastrapur',
  //     city: 'Ahmedabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.068, baseLat + 0.038],
  //     },
  //   },
  //   contact: { phone: '9988776654', email: 'gdt@example.com' },
  //   cuisine_type: ['North-Indian', 'Chinese', 'Mexican', 'Pizza'],
  //   rating: 4.0,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // 50 Restaurants has been seeded till here :
  //   {
  //     name: 'Jugaad Nights',
  //     description:
  //       'A late-night delivery kitchen known for its comfort food. Often gets mixed reviews.',
  //     address: {
  //       street: 'Cloud Kitchen, Bodakdev',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380054',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.091, baseLat + 0.041],
  //       },
  //     },
  //     contact: { phone: '9876543213', email: 'jugaad@example.com' },
  //     cuisine_type: ['North-Indian', 'Fast-Food', 'Chinese', 'Dinner'],
  //     rating: 3.4,
  //     numberOfReviews: 1500,
  //     opening_hours: [{ day: 'Thursday', open: '19:00', close: '04:00' }],
  //     is_active: true,
  //     min_order_value: 200,
  //     delivery_radius_km: 10,
  //     is_veg: false,
  //     cost_for_two: 500,
  //     delivery_time_mins: 50,
  //   },
  //   {
  //     name: 'New Freeze Land',
  //     description:
  //       'A classic fast food joint, popular for its sandwiches, pizzas, and milkshakes.',
  //     address: {
  //       street: 'Navrangpura',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380009',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.041, baseLat + 0.021],
  //       },
  //     },
  //     contact: { phone: '7926441122', email: 'freezeland@example.com' },
  //     cuisine_type: ['Fast-Food', 'Sandwiches', 'Pizza', 'Beverages'],
  //     rating: 4.2,
  //     numberOfReviews: 3100,
  //     opening_hours: [{ day: 'Friday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 150,
  //     delivery_radius_km: 8,
  //     is_veg: true,
  //     cost_for_two: 550,
  //     delivery_time_mins: 30,
  //   },
  //   {
  //     name: 'Jay Bhavani Vadapav',
  //     description:
  //       'A massive local chain for quick and affordable Vadapav and other fast food.',
  //     address: {
  //       street: 'Multiple Locations',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380008',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon + 0.015, baseLat - 0.035],
  //       },
  //     },
  //     contact: { phone: '9998887770', email: 'info@jaybhavani.com' },
  //     cuisine_type: ['Street-Food', 'Fast-Food', 'Sandwiches'],
  //     rating: 4.0,
  //     numberOfReviews: 5500,
  //     opening_hours: [{ day: 'Saturday', open: '09:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 50,
  //     delivery_radius_km: 9,
  //     is_veg: true,
  //     cost_for_two: 150,
  //     delivery_time_mins: 25,
  //   },
  //   {
  //     name: 'Choice Snack Bar',
  //     description:
  //       'An old-school snack bar with a loyal following for its unique sandwiches and snacks.',
  //     address: {
  //       street: 'C.G. Road',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380009',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.038, baseLat + 0.024],
  //       },
  //     },
  //     contact: { phone: '7926424569', email: 'choicesnack@example.com' },
  //     cuisine_type: ['Fast-Food', 'Street-Food', 'Sandwiches'],
  //     rating: 4.4,
  //     numberOfReviews: 2800,
  //     opening_hours: [{ day: 'Sunday', open: '11:00', close: '22:00' }],
  //     is_active: true,
  //     min_order_value: 100,
  //     delivery_radius_km: 7,
  //     is_veg: true,
  //     cost_for_two: 350,
  //     delivery_time_mins: 28,
  //   },
  //   {
  //     name: 'Curries',
  //     description:
  //       'A simple, no-frills restaurant serving decent North Indian and Chinese food.',
  //     address: {
  //       street: 'Prahlad Nagar',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.081, baseLat - 0.011],
  //       },
  //     },
  //     contact: { phone: '9876543214', email: 'curries.ahd@example.com' },
  //     cuisine_type: ['North-Indian', 'Chinese', 'Dinner', 'Lunch'],
  //     rating: 3.8,
  //     numberOfReviews: 1200,
  //     opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 250,
  //     delivery_radius_km: 8,
  //     is_veg: false,
  //     cost_for_two: 700,
  //     delivery_time_mins: 40,
  //   },
  //   {
  //     name: 'Purohit Thali',
  //     description:
  //       'A budget-friendly thali place that is often crowded and has average service.',
  //     address: {
  //       street: 'Near Kalupur Station',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380002',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.03, baseLat - 0.005],
  //       },
  //     },
  //     contact: { phone: '9988776653', email: 'purohit@example.com' },
  //     cuisine_type: ['Indian', 'North-Indian', 'Lunch', 'Dinner'],
  //     rating: 3.2,
  //     numberOfReviews: 950,
  //     opening_hours: [{ day: 'Tuesday', open: '11:00', close: '15:00' }],
  //     is_active: true,
  //     min_order_value: 150,
  //     delivery_radius_km: 6,
  //     is_veg: true,
  //     cost_for_two: 300,
  //     delivery_time_mins: 35,
  //   },
  //   {
  //     name: 'The Great Indian Khichdi',
  //     description:
  //       'A delivery-focused kitchen serving a huge variety of Khichdi from across India.',
  //     address: {
  //       street: 'Cloud Kitchen, Satellite',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.072, baseLat + 0.012],
  //       },
  //     },
  //     contact: { phone: '9876543215', email: 'tgik@example.com' },
  //     cuisine_type: ['Indian', 'Healthy', 'North-Indian', 'Dinner'],
  //     rating: 4.5,
  //     numberOfReviews: 1800,
  //     opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 180,
  //     delivery_radius_km: 9,
  //     is_veg: true,
  //     cost_for_two: 400,
  //     delivery_time_mins: 30,
  //   },
  //   {
  //     name: 'Magic Chicken',
  //     description:
  //       'A non-veg takeaway joint with questionable hygiene and service.',
  //     address: {
  //       street: 'Juhapura',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380055',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.05, baseLat - 0.06],
  //       },
  //     },
  //     contact: { phone: '9988776652', email: 'magicchicken@example.com' },
  //     cuisine_type: ['Fast-Food', 'BBQ', 'North-Indian', 'Dinner'],
  //     rating: 2.7,
  //     numberOfReviews: 800,
  //     opening_hours: [{ day: 'Thursday', open: '17:00', close: '01:00' }],
  //     is_active: true,
  //     min_order_value: 150,
  //     delivery_radius_km: 7,
  //     is_veg: false,
  //     cost_for_two: 450,
  //     delivery_time_mins: 50,
  //   },
  //   {
  //     name: 'Fresh Box',
  //     description:
  //       'A health-focused cafe serving salads, juices, and sandwiches.',
  //     address: {
  //       street: 'Prahlad Nagar',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.084, baseLat - 0.014],
  //       },
  //     },
  //     contact: { phone: '9876543216', email: 'freshbox@example.com' },
  //     cuisine_type: ['Healthy', 'Salads', 'Beverages', 'Sandwiches', 'Vegan'],
  //     rating: 4.6,
  //     numberOfReviews: 950,
  //     opening_hours: [{ day: 'Friday', open: '10:00', close: '22:00' }],
  //     is_active: true,
  //     min_order_value: 200,
  //     delivery_radius_km: 8,
  //     is_veg: true,
  //     cost_for_two: 600,
  //     delivery_time_mins: 30,
  //   },
  //   {
  //     name: 'Punjab Paratha Point',
  //     description:
  //       'A simple eatery serving a wide variety of stuffed parathas with butter.',
  //     address: {
  //       street: 'Chandkheda',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '382424',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.02, baseLat + 0.1],
  //       },
  //     },
  //     contact: { phone: '9988776651', email: 'punjabparatha@example.com' },
  //     cuisine_type: ['North-Indian', 'Street-Food', 'Breakfast', 'Lunch'],
  //     rating: 3.9,
  //     numberOfReviews: 1100,
  //     opening_hours: [{ day: 'Saturday', open: '09:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 120,
  //     delivery_radius_km: 7,
  //     is_veg: true,
  //     cost_for_two: 300,
  //     delivery_time_mins: 35,
  //   },
  //   // --- Pizza, Burgers & Fast Food Chains (Next 15) ---
  //   {
  //     name: "La Pino'z Pizza",
  //     description: 'Famous for giant pizza slices and a wide range of toppings.',
  //     address: {
  //       street: 'Vastrapur',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.063, baseLat + 0.033],
  //       },
  //     },
  //     contact: { phone: '9876543217', email: 'lapinoz.vastrapur@example.com' },
  //     cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Beverages'],
  //     rating: 4.4,
  //     numberOfReviews: 4200,
  //     opening_hours: [{ day: 'Sunday', open: '11:00', close: '01:00' }],
  //     is_active: true,
  //     min_order_value: 200,
  //     delivery_radius_km: 9,
  //     is_veg: false,
  //     cost_for_two: 600,
  //     delivery_time_mins: 35,
  //   },
  //   {
  //     name: "Domino's Pizza",
  //     description: 'Your favorite pizza delivery chain.',
  //     address: {
  //       street: 'Prahlad Nagar',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.085, baseLat - 0.015],
  //       },
  //     },
  //     contact: { phone: '18602100000', email: 'guestcaredominos@jublfood.com' },
  //     cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Desserts'],
  //     rating: 4.0,
  //     numberOfReviews: 3800,
  //     opening_hours: [{ day: 'Monday', open: '11:00', close: '00:00' }],
  //     is_active: true,
  //     min_order_value: 150,
  //     delivery_radius_km: 8,
  //     is_veg: false,
  //     cost_for_two: 500,
  //     delivery_time_mins: 30,
  //   },
  //   {
  //     name: 'Pizza Hut',
  //     description:
  //       'Global pizza chain serving a variety of pizzas, pastas, and sides.',
  //     address: {
  //       street: 'Himalaya Mall, Drive-in Road',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380052',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.05, baseLat + 0.05],
  //       },
  //     },
  //     contact: { phone: '18002022022', email: 'pizzahut.care@yum.com' },
  //     cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Beverages'],
  //     rating: 3.8,
  //     numberOfReviews: 2900,
  //     opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 250,
  //     delivery_radius_km: 9,
  //     is_veg: false,
  //     cost_for_two: 700,
  //     delivery_time_mins: 40,
  //   },
  //   {
  //     name: "McDonald's",
  //     description:
  //       'The iconic global fast-food chain for burgers, fries, and shakes.',
  //     address: {
  //       street: 'S.G. Highway, Thaltej',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380059',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.125, baseLat + 0.075],
  //       },
  //     },
  //     contact: { phone: '9876543218', email: 'mcd.sg@example.com' },
  //     cuisine_type: ['Burgers', 'Fast-Food', 'Beverages', 'Desserts'],
  //     rating: 4.1,
  //     numberOfReviews: 4500,
  //     opening_hours: [{ day: 'Wednesday', open: '10:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 100,
  //     delivery_radius_km: 10,
  //     is_veg: false,
  //     cost_for_two: 400,
  //     delivery_time_mins: 30,
  //   },
  //   {
  //     name: 'Burger King',
  //     description: 'Global fast-food chain known for its flame-grilled burgers.',
  //     address: {
  //       street: 'One Mall, Vastrapur',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.066, baseLat + 0.036],
  //       },
  //     },
  //     contact: { phone: '9876543219', email: 'bk.vastrapur@example.com' },
  //     cuisine_type: ['Burgers', 'Fast-Food', 'Beverages', 'Desserts'],
  //     rating: 4.0,
  //     numberOfReviews: 3300,
  //     opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 120,
  //     delivery_radius_km: 8,
  //     is_veg: false,
  //     cost_for_two: 450,
  //     delivery_time_mins: 32,
  //   },
  //   {
  //     name: 'Subway',
  //     description: 'Customizable submarine sandwiches and salads.',
  //     address: {
  //       street: 'C.G. Road',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380009',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.039, baseLat + 0.021],
  //       },
  //     },
  //     contact: { phone: '9876543220', email: 'subway.cgroad@example.com' },
  //     cuisine_type: ['Sandwiches', 'Salads', 'Healthy', 'Fast-Food'],
  //     rating: 4.2,
  //     numberOfReviews: 1800,
  //     opening_hours: [{ day: 'Friday', open: '10:00', close: '22:00' }],
  //     is_active: true,
  //     min_order_value: 150,
  //     delivery_radius_km: 7,
  //     is_veg: false,
  //     cost_for_two: 500,
  //     delivery_time_mins: 28,
  //   },
  //   {
  //     name: 'KFC',
  //     description:
  //       "Famous for its fried chicken, a global chain with a signature secret recipe.",
  //     address: {
  //       street: 'Prahlad Nagar',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.086, baseLat - 0.016],
  //       },
  //     },
  //     contact: { phone: '9876543221', email: 'kfc.prahladnagar@example.com' },
  //     cuisine_type: ['Burgers', 'Fast-Food', 'BBQ', 'Beverages'],
  //     rating: 4.1,
  //     numberOfReviews: 3600,
  //     opening_hours: [{ day: 'Saturday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 200,
  //     delivery_radius_km: 9,
  //     is_veg: false,
  //     cost_for_two: 550,
  //     delivery_time_mins: 35,
  //   },
  //   {
  //     name: 'Taco Bell',
  //     description:
  //       'Fast-food chain serving Mexican-inspired fare such as tacos, quesadillas, and nachos.',
  //     address: {
  //       street: 'S.G. Highway, Bodakdev',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380054',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.102, baseLat + 0.052],
  //       },
  //     },
  //     contact: { phone: '9876543222', email: 'tacobell.sg@example.com' },
  //     cuisine_type: ['Mexican', 'Fast-Food', 'Tacos', 'Beverages'],
  //     rating: 4.2,
  //     numberOfReviews: 2100,
  //     opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 180,
  //     delivery_radius_km: 10,
  //     is_veg: false,
  //     cost_for_two: 600,
  //     delivery_time_mins: 38,
  //   },
  //   {
  //     name: 'Fozzie\'s Pizzaiolo',
  //     description:
  //       'Gourmet, wood-fired pizzas with high-quality ingredients. A local favorite.',
  //     address: {
  //       street: 'Bodakdev',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380054',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.094, baseLat + 0.044],
  //       },
  //     },
  //     contact: { phone: '9876543223', email: 'fozzies@example.com' },
  //     cuisine_type: ['Pizza', 'Italian', 'Desserts'],
  //     rating: 4.7,
  //     numberOfReviews: 1900,
  //     opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 400,
  //     delivery_radius_km: 8,
  //     is_veg: false,
  //     cost_for_two: 1200,
  //     delivery_time_mins: 45,
  //   },
  //   {
  //     name: 'William John\'s Pizza',
  //     description:
  //       'A popular local pizza chain known for its unlimited pizza deals.',
  //     address: {
  //       street: 'Multiple Locations',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380008',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon + 0.012, baseLat - 0.032],
  //       },
  //     },
  //     contact: { phone: '9876543224', email: 'wjpizza@example.com' },
  //     cuisine_type: ['Pizza', 'Fast-Food', 'Salads', 'Beverages'],
  //     rating: 3.9,
  //     numberOfReviews: 3500,
  //     opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 200,
  //     delivery_radius_km: 9,
  //     is_veg: true,
  //     cost_for_two: 500,
  //     delivery_time_mins: 40,
  //   },
  //   {
  //     name: 'Burgerlicious',
  //     description: 'A takeaway joint with a focus on loaded and juicy burgers.',
  //     address: {
  //       street: 'Prahlad Nagar',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.087, baseLat - 0.017],
  //       },
  //     },
  //     contact: { phone: '9876543225', email: 'burgerlicious@example.com' },
  //     cuisine_type: ['Burgers', 'Fast-Food', 'Sandwiches'],
  //     rating: 4.3,
  //     numberOfReviews: 1500,
  //     opening_hours: [{ day: 'Wednesday', open: '12:00', close: '00:00' }],
  //     is_active: true,
  //     min_order_value: 150,
  //     delivery_radius_km: 8,
  //     is_veg: false,
  //     cost_for_two: 450,
  //     delivery_time_mins: 35,
  //   },
  //   {
  //     name: 'Real Paprika',
  //     description:
  //       'Another local chain for unlimited pizza, often with inconsistent quality.',
  //     address: {
  //       street: 'Bopal',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380058',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.15, baseLat + 0.02],
  //       },
  //     },
  //     contact: { phone: '9876543226', email: 'realpaprika@example.com' },
  //     cuisine_type: ['Pizza', 'Fast-Food', 'Salads', 'Beverages'],
  //     rating: 3.1,
  //     numberOfReviews: 2800,
  //     opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 200,
  //     delivery_radius_km: 10,
  //     is_veg: true,
  //     cost_for_two: 450,
  //     delivery_time_mins: 45,
  //   },
  //   {
  //     name: 'Ovenstory Pizza',
  //     description: 'Pizzas with exciting toppings and a standout cheese base.',
  //     address: {
  //       street: 'Cloud Kitchen, Satellite',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.073, baseLat + 0.013],
  //       },
  //     },
  //     contact: { phone: '9876543227', email: 'ovenstory.ahd@example.com' },
  //     cuisine_type: ['Pizza', 'Italian', 'Fast-Food'],
  //     rating: 4.1,
  //     numberOfReviews: 1900,
  //     opening_hours: [{ day: 'Friday', open: '11:00', close: '23:30' }],
  //     is_active: true,
  //     min_order_value: 300,
  //     delivery_radius_km: 9,
  //     is_veg: false,
  //     cost_for_two: 700,
  //     delivery_time_mins: 42,
  //   },
  //   {
  //     name: 'Behrouz Biryani',
  //     description: 'Royal biryanis delivered with a premium experience.',
  //     address: {
  //       street: 'Cloud Kitchen, Bodakdev',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380054',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.096, baseLat + 0.046],
  //       },
  //     },
  //     contact: { phone: '9876543228', email: 'behrouz.ahd@example.com' },
  //     cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch'],
  //     rating: 4.4,
  //     numberOfReviews: 2500,
  //     opening_hours: [{ day: 'Saturday', open: '11:00', close: '23:30' }],
  //     is_active: true,
  //     min_order_value: 450,
  //     delivery_radius_km: 10,
  //     is_veg: false,
  //     cost_for_two: 900,
  //     delivery_time_mins: 45,
  //   },
  //   {
  //     name: 'Faasos - Wraps & Rolls',
  //     description:
  //       'A leading name in wraps, serving a variety of exciting flavors.',
  //     address: {
  //       street: 'Cloud Kitchen, Navrangpura',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380009',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.043, baseLat + 0.023],
  //       },
  //     },
  //     contact: { phone: '9876543229', email: 'faasos.ahd@example.com' },
  //     cuisine_type: ['Street-Food', 'Fast-Food', 'North-Indian', 'Lunch'],
  //     rating: 4.0,
  //     numberOfReviews: 2100,
  //     opening_hours: [{ day: 'Sunday', open: '10:00', close: '00:00' }],
  //     is_active: true,
  //     min_order_value: 120,
  //     delivery_radius_km: 8,
  //     is_veg: false,
  //     cost_for_two: 350,
  //     delivery_time_mins: 28,
  //   },
  //   // --- Remaining 40 to reach 100 (Mixed Bag) ---
  //   {
  //     name: 'The Good Bowl',
  //     description:
  //       'Serving wholesome and delicious bowls that are a fusion of global and Indian flavors.',
  //     address: {
  //       street: 'Cloud Kitchen, Prahlad Nagar',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.088, baseLat - 0.018],
  //       },
  //     },
  //     contact: { phone: '9876543230', email: 'goodbowl.ahd@example.com' },
  //     cuisine_type: ['Healthy', 'Salads', 'North-Indian', 'Indian'],
  //     rating: 4.3,
  //     numberOfReviews: 1100,
  //     opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 180,
  //     delivery_radius_km: 9,
  //     is_veg: false,
  //     cost_for_two: 550,
  //     delivery_time_mins: 32,
  //   },
  //   {
  //     name: 'Mad Over Donuts',
  //     description:
  //       'A popular spot for a wide variety of gourmet donuts and coffee.',
  //     address: {
  //       street: 'Alpha One Mall, Vastrapur',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380054',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.067, baseLat + 0.037],
  //       },
  //     },
  //     contact: { phone: '9876543231', email: 'mod.ahd@example.com' },
  //     cuisine_type: ['Desserts', 'Beverages', 'Fast-Food'],
  //     rating: 4.3,
  //     numberOfReviews: 1500,
  //     opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 100,
  //     delivery_radius_km: 8,
  //     is_veg: true,
  //     cost_for_two: 350,
  //     delivery_time_mins: 30,
  //   },
  //   {
  //     name: 'Gwalia Sweets',
  //     description:
  //       'A famous brand for Indian sweets, snacks, and a multi-cuisine vegetarian restaurant.',
  //     address: {
  //       street: 'Prahlad Nagar',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.089, baseLat - 0.019],
  //       },
  //     },
  //     contact: { phone: '9909909900', email: 'info@gwalia.com' },
  //     cuisine_type: [
  //       'Indian-Sweets',
  //       'North-Indian',
  //       'Street-Food',
  //       'Desserts',
  //     ],
  //     rating: 4.2,
  //     numberOfReviews: 4000,
  //     opening_hours: [{ day: 'Wednesday', open: '09:00', close: '22:30' }],
  //     is_active: true,
  //     min_order_value: 150,
  //     delivery_radius_km: 9,
  //     is_veg: true,
  //     cost_for_two: 400,
  //     delivery_time_mins: 35,
  //   },
  //   {
  //     name: 'Yanki Sizzlers',
  //     description: 'One of the oldest and most popular sizzler joints in the city.',
  //     address: {
  //       street: 'Navrangpura',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380009',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.044, baseLat + 0.024],
  //       },
  //     },
  //     contact: { phone: '7926442886', email: 'yanki@example.com' },
  //     cuisine_type: ['Continental', 'Mexican', 'Italian', 'Dinner'],
  //     rating: 4.1,
  //     numberOfReviews: 2300,
  //     opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 400,
  //     delivery_radius_km: 8,
  //     is_veg: false,
  //     cost_for_two: 1200,
  //     delivery_time_mins: 45,
  //   },
  //   {
  //     name: 'Urban Khichdi',
  //     description: 'A modern take on the classic Khichdi with many variations.',
  //     address: {
  //       street: 'Bodakdev',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380054',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.097, baseLat + 0.047],
  //       },
  //     },
  //     contact: { phone: '9876543232', email: 'urbankhichdi@example.com' },
  //     cuisine_type: ['Indian', 'Healthy', 'Dinner', 'Lunch'],
  //     rating: 4.4,
  //     numberOfReviews: 1600,
  //     opening_hours: [{ day: 'Friday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 200,
  //     delivery_radius_km: 9,
  //     is_veg: true,
  //     cost_for_two: 500,
  //     delivery_time_mins: 35,
  //   },
  //   {
  //     name: 'Shambhu\'s Coffee Bar',
  //     description:
  //       'A very popular local coffee chain, famous for its cold coffee.',
  //     address: {
  //       street: 'Multiple Locations',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.074, baseLat + 0.014],
  //       },
  //     },
  //     contact: { phone: '9876543233', email: 'shambhus@example.com' },
  //     cuisine_type: ['Cafe', 'Beverages', 'Fast-Food', 'Sandwiches'],
  //     rating: 4.3,
  //     numberOfReviews: 3900,
  //     opening_hours: [{ day: 'Saturday', open: '10:00', close: '00:00' }],
  //     is_active: true,
  //     min_order_value: 100,
  //     delivery_radius_km: 8,
  //     is_veg: true,
  //     cost_for_two: 300,
  //     delivery_time_mins: 25,
  //   },
  //   {
  //     name: 'New Irani Restaurant',
  //     description:
  //       'An old-world Irani cafe known for its chai, bun maska, and non-veg snacks.',
  //     address: {
  //       street: 'Bhadra, Old City',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380001',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.052, baseLat + 0.002],
  //       },
  //     },
  //     contact: { phone: '9876543234', email: 'irani@example.com' },
  //     cuisine_type: ['Cafe', 'Street-Food', 'Breakfast', 'North-Indian'],
  //     rating: 4.2,
  //     numberOfReviews: 1700,
  //     opening_hours: [{ day: 'Sunday', open: '06:00', close: '22:00' }],
  //     is_active: true,
  //     min_order_value: 80,
  //     delivery_radius_km: 7,
  //     is_veg: false,
  //     cost_for_two: 200,
  //     delivery_time_mins: 30,
  //   },
  //   {
  //     name: 'Royal Punjab',
  //     description:
  //       'A budget non-veg restaurant with a reputation for slow service.',
  //     address: {
  //       street: 'Sarkhej',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '382210',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.1, baseLat - 0.05],
  //       },
  //     },
  //     contact: { phone: '9876543235', email: 'royalpunjab@example.com' },
  //     cuisine_type: ['North-Indian', 'BBQ', 'Dinner'],
  //     rating: 2.9,
  //     numberOfReviews: 900,
  //     opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 200,
  //     delivery_radius_km: 8,
  //     is_veg: false,
  //     cost_for_two: 600,
  //     delivery_time_mins: 55,
  //   },
  //   {
  //     name: 'Iqbal Hotel',
  //     description:
  //       'A famous non-veg restaurant in the old city, known for its tandoori items.',
  //     address: {
  //       street: 'Jamalpur',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380001',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.04, baseLat - 0.02],
  //       },
  //     },
  //     contact: { phone: '9876543236', email: 'iqbalhotel@example.com' },
  //     cuisine_type: ['North-Indian', 'BBQ', 'Indian', 'Dinner'],
  //     rating: 4.3,
  //     numberOfReviews: 2500,
  //     opening_hours: [{ day: 'Tuesday', open: '12:00', close: '00:00' }],
  //     is_active: true,
  //     min_order_value: 250,
  //     delivery_radius_km: 7,
  //     is_veg: false,
  //     cost_for_two: 700,
  //     delivery_time_mins: 40,
  //   },
  //   {
  //     name: 'The Belgian Waffle Co.',
  //     description:
  //       'Specialty waffle shop serving freshly baked waffles with a variety of toppings.',
  //     address: {
  //       street: 'Vastrapur',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.064, baseLat + 0.034],
  //       },
  //     },
  //     contact: { phone: '9876543237', email: 'belgianwaffle.ahd@example.com' },
  //     cuisine_type: ['Desserts', 'Bakery', 'Beverages', 'Fast-Food'],
  //     rating: 4.4,
  //     numberOfReviews: 1800,
  //     opening_hours: [{ day: 'Wednesday', open: '11:00', close: '00:00' }],
  //     is_active: true,
  //     min_order_value: 150,
  //     delivery_radius_km: 8,
  //     is_veg: true,
  //     cost_for_two: 400,
  //     delivery_time_mins: 25,
  //   },
  //   // Add 30 more to reach 100
  //   {
  //     name: 'China Gate',
  //     description: 'A casual dining place for Indian-style Chinese food.',
  //     address: {
  //       street: 'Prahlad Nagar',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380015',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.089, baseLat - 0.011],
  //       },
  //     },
  //     contact: { phone: '9876543238', email: 'chinagate@example.com' },
  //     cuisine_type: ['Chinese', 'Soups', 'Fast-Food', 'Dinner'],
  //     rating: 3.7,
  //     numberOfReviews: 1400,
  //     opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 250,
  //     delivery_radius_km: 9,
  //     is_veg: false,
  //     cost_for_two: 800,
  //     delivery_time_mins: 40,
  //   },
  //   {
  //     name: 'Puffizza',
  //     description: 'A unique concept of pizzas made on a puff pastry base.',
  //     address: {
  //       street: 'University Area',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380009',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.048, baseLat + 0.038],
  //       },
  //     },
  //     contact: { phone: '9876543239', email: 'puffizza@example.com' },
  //     cuisine_type: ['Pizza', 'Fast-Food', 'Italian'],
  //     rating: 4.1,
  //     numberOfReviews: 1600,
  //     opening_hours: [{ day: 'Friday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 180,
  //     delivery_radius_km: 8,
  //     is_veg: true,
  //     cost_for_two: 500,
  //     delivery_time_mins: 35,
  //   },
  //   {
  //     name: 'Dangee Dums',
  //     description: 'A very popular cake and pastry shop.',
  //     address: {
  //       street: 'Multiple Locations',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380054',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.099, baseLat + 0.049],
  //       },
  //     },
  //     contact: { phone: '9898989898', email: 'info@dangeedums.com' },
  //     cuisine_type: ['Desserts', 'Bakery', 'Cakes'],
  //     rating: 4.5,
  //     numberOfReviews: 3000,
  //     opening_hours: [{ day: 'Saturday', open: '10:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 200,
  //     delivery_radius_km: 10,
  //     is_veg: true,
  //     cost_for_two: 400,
  //     delivery_time_mins: 30,
  //   },
  //   {
  //     name: 'Jalaram Parotha House',
  //     description: 'A simple place for parathas and sabzi, but service is slow.',
  //     address: {
  //       street: 'Ghatlodia',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380061',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.07, baseLat + 0.08],
  //       },
  //     },
  //     contact: { phone: '9876543240', email: 'jalaram@example.com' },
  //     cuisine_type: ['North-Indian', 'Indian', 'Lunch'],
  //     rating: 3.3,
  //     numberOfReviews: 700,
  //     opening_hours: [{ day: 'Sunday', open: '11:00', close: '22:00' }],
  //     is_active: true,
  //     min_order_value: 150,
  //     delivery_radius_km: 7,
  //     is_veg: true,
  //     cost_for_two: 250,
  //     delivery_time_mins: 45,
  //   },
  //   {
  //     name: 'Mahalaxmi Pav Bhaji',
  //     description: 'A local favorite for buttery and spicy pav bhaji.',
  //     address: {
  //       street: 'Paldi',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380007',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.02, baseLat - 0.02],
  //       },
  //     },
  //     contact: { phone: '9876543241', email: 'mahalaxmipavbhaji@example.com' },
  //     cuisine_type: ['Street-Food', 'Fast-Food', 'Indian'],
  //     rating: 4.4,
  //     numberOfReviews: 2200,
  //     opening_hours: [{ day: 'Monday', open: '18:00', close: '00:00' }],
  //     is_active: true,
  //     min_order_value: 100,
  //     delivery_radius_km: 8,
  //     is_veg: true,
  //     cost_for_two: 300,
  //     delivery_time_mins: 30,
  //   },
  //   {
  //     name: 'Crazy Crush',
  //     description: 'A small cafe with a large menu that tries to do too much.',
  //     address: {
  //       street: 'Maninagar',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380008',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon + 0.011, baseLat - 0.031],
  //       },
  //     },
  //     contact: { phone: '9876543242', email: 'crazycrush@example.com' },
  //     cuisine_type: ['Cafe', 'Fast-Food', 'Pizza', 'Sandwiches'],
  //     rating: 3.0,
  //     numberOfReviews: 1100,
  //     opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 150,
  //     delivery_radius_km: 7,
  //     is_veg: true,
  //     cost_for_two: 400,
  //     delivery_time_mins: 40,
  //   },
  //   {
  //     name: 'Natural Ice Cream',
  //     description:
  //       'Serving delicious ice creams made from real fruits, milk, and sugar.',
  //     address: {
  //       street: 'Navrangpura',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380009',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.045, baseLat + 0.025],
  //       },
  //     },
  //     contact: { phone: '9876543243', email: 'natural.ahd@example.com' },
  //     cuisine_type: ['Ice Cream', 'Desserts', 'Beverages'],
  //     rating: 4.7,
  //     numberOfReviews: 2800,
  //     opening_hours: [{ day: 'Wednesday', open: '11:00', close: '00:30' }],
  //     is_active: true,
  //     min_order_value: 120,
  //     delivery_radius_km: 8,
  //     is_veg: true,
  //     cost_for_two: 250,
  //     delivery_time_mins: 25,
  //   },
  //   {
  //     name: 'The Eatery - Four Points by Sheraton',
  //     description: 'All-day dining with a lavish buffet and a-la-carte menu.',
  //     address: {
  //       street: 'Ellisbridge',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380006',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.025, baseLat + 0.005],
  //       },
  //     },
  //     contact: { phone: '7930912345', email: 'fourpoints.ahd@sheraton.com' },
  //     cuisine_type: ['North-Indian', 'Continental', 'Chinese', 'Dinner'],
  //     rating: 4.5,
  //     numberOfReviews: 1500,
  //     opening_hours: [{ day: 'Thursday', open: '07:00', close: '23:30' }],
  //     is_active: true,
  //     min_order_value: 800,
  //     delivery_radius_km: 9,
  //     is_veg: false,
  //     cost_for_two: 2000,
  //     delivery_time_mins: 50,
  //   },
  //   {
  //     name: 'Mad by Heart',
  //     description: 'A quirky cafe with a vibrant ambiance and comfort food.',
  //     address: {
  //       street: 'University Area',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380009',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.049, baseLat + 0.039],
  //       },
  //     },
  //     contact: { phone: '9876543244', email: 'madbyheart@example.com' },
  //     cuisine_type: ['Cafe', 'Fast-Food', 'Mexican', 'Beverages'],
  //     rating: 4.1,
  //     numberOfReviews: 1900,
  //     opening_hours: [{ day: 'Friday', open: '11:00', close: '23:00' }],
  //     is_active: true,
  //     min_order_value: 200,
  //     delivery_radius_km: 8,
  //     is_veg: true,
  //     cost_for_two: 700,
  //     delivery_time_mins: 35,
  //   },
  //   {
  //     name: 'Lucky Tea Stall',
  //     description:
  //       'A unique tea stall built around a graveyard. Famous for its chai and bun maska.',
  //     address: {
  //       street: 'Lal Darwaja',
  //       city: 'Ahmedabad',
  //       state: 'Gujarat',
  //       zip_code: '380001',
  //       location: {
  //         type: 'Point',
  //         coordinates: [baseLon - 0.058, baseLat + 0.008],
  //       },
  //     },
  //     contact: { phone: '9876543245', email: 'luckytea@example.com' },
  //     cuisine_type: ['Cafe', 'Street-Food', 'Breakfast'],
  //     rating: 4.3,
  //     numberOfReviews: 3200,
  //     opening_hours: [{ day: 'Saturday', open: '05:00', close: '00:00' }],
  //     is_active: true,
  //     min_order_value: 50,
  //     delivery_radius_km: 7,
  //     is_veg: true,
  //     cost_for_two: 150,
  //     delivery_time_mins: 25,
  //   },
];
