// Base coordinates for Ahmedabad (approximate center)
const baseLat = 23.0225;
const baseLon = 72.5714;

const ahmadabadRestaurants = [
  // --- Restaurants 1-10 ---
  // {
  //   name: 'The Global Kitchen',
  //   description:
  //     'A fine dining experience with a curated menu of international and Indian classics.',
  //   address: {
  //     street: '101, C.G. Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876543211', email: 'globalkitchen.ahd@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Italian',
  //     'Dinner',
  //     'Lunch',
  //     'Salads',
  //     'Soups',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Manek Chowk Eatery',
  //   description:
  //     "Experience the vibrant flavors of Ahmedabad's most famous night market.",
  //   address: {
  //     street: 'Manek Chowk, Old City',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9876543212', email: 'manekchowk@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Indian',
  //     'Fast-Food',
  //     'Desserts',
  //     'Indian-Sweets',
  //     'Beverages',
  //   ],
  //   rating: 4.8,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Tuesday', open: '19:00', close: '02:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Pizza Paradise',
  //   description:
  //     'Gourmet wood-fired pizzas with a variety of classic and exotic toppings.',
  //   address: {
  //     street: '23, Bodakdev',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9876543213', email: 'pizzaparadise.ahd@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Beverages', 'Salads'],
  //   rating: 4.5,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Burger Barn',
  //   description:
  //     'Juicy, handcrafted burgers, loaded fries, and decadent milkshakes.',
  //   address: {
  //     street: 'Vastrapur Lake Area',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9876543214', email: 'burgerbarn.ahd@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Beverages',
  //     'Sandwiches',
  //     'Desserts',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Agashiye - The House of MG',
  //   description:
  //     'An authentic Gujarati thali experience on a beautiful rooftop terrace.',
  //   address: {
  //     street: 'Lal Darwaja',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9876543215', email: 'agashiye@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'North-Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Healthy',
  //     'Desserts',
  //   ],
  //   rating: 4.9,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Swati Snacks',
  //   description:
  //     'A beloved spot for traditional Gujarati snacks and light meals.',
  //   address: {
  //     street: 'Law Garden',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9876543216', email: 'swatisnacks@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Indian',
  //     'South-Indian',
  //     'Breakfast',
  //     'Lunch',
  //     'Healthy',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Wok Box',
  //   description: 'Customizable Asian stir-fry bowls with fresh ingredients.',
  //   address: {
  //     street: 'Prahlad Nagar',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.06, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876543217', email: 'wokbox.ahd@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Japanese',
  //     'Soups',
  //     'Healthy',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 220,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Kyoto Fresh',
  //   description: 'Authentic and fresh sushi, sashimi, and ramen bowls.',
  //   address: {
  //     street: 'S.G. Highway, Thaltej',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380059',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.08, baseLat + 0.05],
  //     },
  //   },
  //   contact: { phone: '9876543218', email: 'kyotofresh@example.com' },
  //   cuisine_type: ['Sushi', 'Japanese', 'Healthy', 'Soups', 'Dinner', 'Salads'],
  //   rating: 4.8,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Monday', open: '18:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'El Mexicano',
  //   description: 'Vibrant and spicy Mexican food, from tacos to enchiladas.',
  //   address: {
  //     street: 'Sindhu Bhavan Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380059',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.07, baseLat + 0.04],
  //     },
  //   },
  //   contact: { phone: '9876543219', email: 'elmexicano@example.com' },
  //   cuisine_type: [
  //     'Mexican',
  //     'Fast-Food',
  //     'Dinner',
  //     'Beverages',
  //     'Salads',
  //     'Lunch',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Tuesday', open: '13:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Green Leaf Cafe',
  //   description:
  //     'A paradise for vegetarians and vegans with a creative plant-based menu.',
  //   address: {
  //     street: 'Navrangpura',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9876543220', email: 'greenleaf.ahd@example.com' },
  //   cuisine_type: [
  //     'Vegan',
  //     'Healthy',
  //     'Salads',
  //     'Soups',
  //     'Breakfast',
  //     'Beverages',
  //     'Italian',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 980,
  //   opening_hours: [{ day: 'Wednesday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // seeded till here :
  // --- Restaurants 11-20 ---
  // {
  //   name: 'Smoky BBQ Joint',
  //   description:
  //     'Authentic American-style barbecue with slow-smoked meats and classic sides.',
  //   address: {
  //     street: 'Satellite Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.055, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9876543221', email: 'smokybbq@example.com' },
  //   cuisine_type: ['BBQ', 'Dinner', 'Burgers', 'Sandwiches', 'Fast-Food'],
  //   rating: 4.5,
  //   numberOfReviews: 850,
  //   opening_hours: [{ day: 'Thursday', open: '18:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'The Breakfast Club',
  //   description: 'All-day breakfast spot serving pancakes, waffles, and more.',
  //   address: {
  //     street: 'Judges Bungalow Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.045, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '9876543222', email: 'breakfastclub.ahd@example.com' },
  //   cuisine_type: [
  //     'Breakfast',
  //     'Sandwiches',
  //     'Beverages',
  //     'Desserts',
  //     'Healthy',
  //     'Fast-Food',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Friday', open: '08:00', close: '20:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Das Khaman',
  //   description: 'Iconic shop for authentic Gujarati Khaman and Dhokla.',
  //   address: {
  //     street: 'Ambawadi',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.005, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9876543223', email: 'daskhaman@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Indian',
  //     'Breakfast',
  //     'Healthy',
  //     'Vegan',
  //   ],
  //   rating: 4.8,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Saturday', open: '07:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 50,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 150,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'La Bella Vita',
  //   description: 'A cozy bistro for classic Italian pasta and desserts.',
  //   address: {
  //     street: 'Bopal',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380058',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.1, baseLat - 0.05],
  //     },
  //   },
  //   contact: { phone: '9876543224', email: 'labellavita@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Pizza',
  //     'Desserts',
  //     'Dinner',
  //     'Soups',
  //     'Salads',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 750,
  //   opening_hours: [{ day: 'Sunday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Karnavati Dabeli',
  //   description: 'Famous for its spicy and sweet Kutchi Dabeli.',
  //   address: {
  //     street: 'University Area',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9876543225', email: 'karnavatidabeli@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Indian',
  //     'Fast-Food',
  //     'Sandwiches',
  //     'Vegan',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 60,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 120,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'The Shake Maker',
  //   description: 'An extensive menu of thick shakes, smoothies, and coolers.',
  //   address: {
  //     street: 'Chandkheda',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '382424',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.05, baseLat + 0.08],
  //     },
  //   },
  //   contact: { phone: '9876543226', email: 'shakemaker@example.com' },
  //   cuisine_type: ['Beverages', 'Desserts', 'Fast-Food', 'Indian-Sweets'],
  //   rating: 4.2,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Gordhan Thal',
  //   description:
  //     'A grand thali restaurant serving unlimited Gujarati and Rajasthani food.',
  //   address: {
  //     street: 'S.G. Highway',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.075, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9876543227', email: 'gordhanthal@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'North-Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Desserts',
  //     'Indian-Sweets',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Wednesday', open: '11:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 9,
  //   is_veg: true,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Dakshinayan',
  //   description: 'Authentic and high-quality South Indian vegetarian cuisine.',
  //   address: {
  //     street: 'Gulbai Tekra',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.008, baseLat + 0.008],
  //     },
  //   },
  //   contact: { phone: '9876543228', email: 'dakshinayan@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //     'Healthy',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Thursday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Salad Bar',
  //   description: 'Fresh, crisp, and customizable salads for a healthy meal.',
  //   address: {
  //     street: 'Maninagar',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380008',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9876543229', email: 'saladbar.ahd@example.com' },
  //   cuisine_type: ['Salads', 'Healthy', 'Vegan', 'Soups', 'Beverages', 'Lunch'],
  //   rating: 4.4,
  //   numberOfReviews: 650,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Kandoi Bhogilal Mulchand',
  //   description:
  //     "A legendary sweet shop offering a vast array of traditional Indian sweets.",
  //   address: {
  //     street: 'Relief Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876543230', email: 'kandoi@example.com' },
  //   cuisine_type: [
  //     'Indian-Sweets',
  //     'Desserts',
  //     'Street-Food',
  //     'Breakfast',
  //     'Indian',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 30,
  // },
  // seeded till here
  // --- Restaurants 21-30 ---
  // {
  //   name: 'Urban Roti',
  //   description: 'Modern Indian kitchen with a focus on North Indian breads and curries.',
  //   address: {
  //     street: 'Iscon Ambli Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380058',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.09, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9876543231', email: 'urbanroti@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ', 'Soups'],
  //   rating: 4.3,
  //   numberOfReviews: 1400,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Blue Oven',
  //   description: 'Artisanal bakery and cafe known for its breads, pastries, and coffee.',
  //   address: {
  //     street: 'Off C.G. Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9876543232', email: 'blueoven@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Breakfast', 'Sandwiches', 'Italian', 'Fast-Food'],
  //   rating: 4.6,
  //   numberOfReviews: 1600,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Jasuben Old Pizza',
  //   description: 'A unique and iconic Ahmedabad-style pizza that is a must-try.',
  //   address: {
  //     street: 'Law Garden',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.012, baseLat + 0.007],
  //     },
  //   },
  //   contact: { phone: '9876543233', email: 'jasubenpizza@example.com' },
  //   cuisine_type: ['Pizza', 'Street-Food', 'Fast-Food', 'Indian', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Tuesday', open: '17:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Nini\'s Kitchen',
  //   description: 'Comfort food with a creative twist, serving Indian and continental dishes.',
  //   address: {
  //     street: 'Prahlad Nagar',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.065, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9876543234', email: 'niniskitchen@example.com' },
  //   cuisine_type: ['North-Indian', 'Italian', 'Mexican', 'Fast-Food', 'Dinner', 'Beverages'],
  //   rating: 4.4,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'IIM-A Road Food Stalls',
  //   description: 'A bustling hub of street food stalls popular with students.',
  //   address: {
  //     street: 'Near IIM Ahmedabad, Vastrapur',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.035, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9876543235', email: 'iimaroad@example.com' },
  //   cuisine_type: ['Street-Food', 'Fast-Food', 'Chinese', 'Sandwiches', 'Beverages', 'Indian'],
  //   rating: 4.3,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Thursday', open: '18:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 70,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 200,
  //   delivery_time_mins: 25,
  // },
  // --- Restaurants 26-30 ---
  // {
  //   name: 'The Sushi Point',
  //   description: 'A delivery-focused kitchen for affordable sushi and Japanese snacks.',
  //   address: {
  //     street: 'Cloud Kitchen, Bodakdev',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.052, baseLat + 0.032],
  //     },
  //   },
  //   contact: { phone: '9876543236', email: 'sushipoint.ahd@example.com' },
  //   cuisine_type: ['Sushi', 'Japanese', 'Soups', 'Fast-Food', 'Dinner'],
  //   rating: 4.0,
  //   numberOfReviews: 700,
  //   opening_hours: [{ day: 'Friday', open: '17:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Mocha Cafe',
  //   description: 'A trendy cafe with a diverse menu, from coffee and shakes to full meals.',
  //   address: {
  //     street: 'Bodakdev',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.058, baseLat + 0.038],
  //     },
  //   },
  //   contact: { phone: '9876543237', email: 'mocha.ahd@example.com' },
  //   cuisine_type: ['Beverages', 'Desserts', 'Italian', 'Mexican', 'Fast-Food', 'Breakfast', 'Salads'],
  //   rating: 4.2,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Fresh Roast',
  //   description: 'A quiet coffee shop perfect for work, serving excellent brews and light bites.',
  //   address: {
  //     street: 'Paldi',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380007',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9876543238', email: 'freshroast@example.com' },
  //   cuisine_type: ['Beverages', 'Breakfast', 'Sandwiches', 'Desserts', 'Healthy'],
  //   rating: 4.5,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Sunday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Havmor Restaurant',
  //   description: 'A family-friendly restaurant with a multi-cuisine menu and famous ice creams.',
  //   address: {
  //     street: 'Navrangpura',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.018, baseLat + 0.012],
  //     },
  //   },
  //   contact: { phone: '9876543239', email: 'havmor@example.com' },
  //   cuisine_type: ['North-Indian', 'Chinese', 'Fast-Food', 'Desserts', 'Indian-Sweets', 'Pizza', 'Lunch', 'Dinner'],
  //   rating: 4.1,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Iscon Gathiya',
  //   description: 'A famous spot for traditional Gujarati Gathiya and other fried snacks.',
  //   address: {
  //     street: 'S.G. Highway',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.07, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9876543240', email: 'iscongathiya@example.com' },
  //   cuisine_type: ['Street-Food', 'Indian', 'Breakfast', 'Fast-Food', 'Beverages'],
  //   rating: 4.4,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Tuesday', open: '06:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 22,
  // },
  // seeded till here
  // --- Restaurants 31-40 ---
  // {
  //   name: 'Barbeque Nation',
  //   description: 'The original live-on-the-table grill restaurant with a lavish buffet.',
  //   address: {
  //     street: 'Prahlad Nagar',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.062, baseLat - 0.012],
  //     },
  //   },
  //   contact: { phone: '9876543241', email: 'bbqnation.ahd@example.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Indian', 'Dinner', 'Lunch', 'Desserts', 'Salads'],
  //   rating: 4.7,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Sankalp Restaurant',
  //   description: 'Famous for its incredibly long dosas and authentic South Indian flavors.',
  //   address: {
  //     street: 'C.G. Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.022, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9876543242', email: 'sankalp.ahd@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Breakfast', 'Lunch', 'Dinner', 'Vegan'],
  //   rating: 4.5,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Thursday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Burger King',
  //   description: 'Global fast-food chain known for its flame-grilled burgers.',
  //   address: {
  //     street: 'Alpha One Mall, Vastrapur',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.042, baseLat + 0.012],
  //     },
  //   },
  //   contact: { phone: '9876543243', email: 'bk.ahd@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Beverages', 'Desserts', 'Lunch', 'Dinner'],
  //   rating: 4.1,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Mainland China',
  //   description: 'A fine-dining restaurant offering authentic cuisine from major provinces of China.',
  //   address: {
  //     street: 'Gulmohar Park Mall, Satellite',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.053, baseLat - 0.003],
  //     },
  //   },
  //   contact: { phone: '9876543244', email: 'mainlandchina.ahd@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Dinner', 'Lunch', 'Soups', 'Sushi'],
  //   rating: 4.6,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Saturday', open: '12:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'The Belgian Waffle Co.',
  //   description: 'Specialty waffle shop serving freshly baked waffles with a variety of toppings.',
  //   address: {
  //     street: 'Vastrapur',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.038, baseLat + 0.011],
  //     },
  //   },
  //   contact: { phone: '9876543245', email: 'belgianwaffle.ahd@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Breakfast', 'Fast-Food'],
  //   rating: 4.4,
  //   numberOfReviews: 1600,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'La Pino\'z Pizza',
  //   description: 'Famous for giant pizza slices and a wide range of toppings.',
  //   address: {
  //     street: 'Maninagar',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380008',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.032, baseLat - 0.042],
  //     },
  //   },
  //   contact: { phone: '9876543246', email: 'lapinoz.ahd@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Beverages', 'Dinner'],
  //   rating: 4.3,
  //   numberOfReviews: 3300,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 33,
  // },
  // {
  //   name: 'Greenhouse Cafe',
  //   description: 'A beautiful cafe focused on healthy, organic, and wholesome food.',
  //   address: {
  //     street: 'Bodakdev',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.051, baseLat + 0.031],
  //     },
  //   },
  //   contact: { phone: '9876543247', email: 'greenhouse.ahd@example.com' },
  //   cuisine_type: ['Healthy', 'Salads', 'Vegan', 'Soups', 'Breakfast', 'Beverages'],
  //   rating: 4.8,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Tuesday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Taco Bell',
  //   description: 'Fast-food chain serving Mexican-inspired fare like tacos, quesadillas, and nachos.',
  //   address: {
  //     street: 'S.G. Highway, Bodakdev',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.072, baseLat + 0.022],
  //     },
  //   },
  //   contact: { phone: '9876543248', email: 'tacobell.ahd@example.com' },
  //   cuisine_type: ['Mexican', 'Fast-Food', 'Dinner', 'Lunch', 'Beverages'],
  //   rating: 4.1,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Fozzie\'s Pizzaiolo',
  //   description: 'Authentic Neapolitan pizzas with premium imported ingredients.',
  //   address: {
  //     street: 'Bodakdev',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.056, baseLat + 0.036],
  //     },
  //   },
  //   contact: { phone: '9876543249', email: 'fozzies.ahd@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Dinner', 'Salads', 'Desserts'],
  //   rating: 4.9,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Thursday', open: '18:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Subway',
  //   description: 'Customizable submarine sandwiches and salads.',
  //   address: {
  //     street: 'Navrangpura',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.016, baseLat + 0.016],
  //     },
  //   },
  //   contact: { phone: '9876543250', email: 'subway.ahd@example.com' },
  //   cuisine_type: ['Sandwiches', 'Salads', 'Healthy', 'Fast-Food', 'Breakfast', 'Lunch'],
  //   rating: 4.2,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Friday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // seeded till here
  // --- Restaurants 41-50 ---
  // {
  //   name: 'The Dosa Hub',
  //   description: 'A modern take on South Indian cuisine with over 100 varieties of dosas.',
  //   address: {
  //     street: 'Bopal',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380058',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.105, baseLat - 0.045],
  //     },
  //   },
  //   contact: { phone: '9876543251', email: 'dosahub.ahd@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Fast-Food', 'Breakfast', 'Lunch'],
  //   rating: 4.3,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Punjab Grill',
  //   description: 'A celebration of the culinary heritage of Punjab with a fine-dining experience.',
  //   address: {
  //     street: 'Sindhu Bhavan Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380059',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.075, baseLat + 0.045],
  //     },
  //   },
  //   contact: { phone: '9876543252', email: 'punjabgrill.ahd@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'BBQ', 'Dinner', 'Lunch', 'Desserts'],
  //   rating: 4.5,
  //   numberOfReviews: 2600,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'KFC',
  //   description: 'Famous for its fried chicken, a global chain with a signature secret recipe.',
  //   address: {
  //     street: 'Himalaya Mall, Drive-In Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380052',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9876543253', email: 'kfc.ahd@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'BBQ', 'Beverages', 'Lunch', 'Dinner'],
  //   rating: 4.0,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Gwalia Sweets',
  //   description: 'A famous brand for traditional Indian sweets, snacks, and fast food.',
  //   address: {
  //     street: 'Satellite',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.054, baseLat - 0.004],
  //     },
  //   },
  //   contact: { phone: '9876543254', email: 'gwalia.ahd@example.com' },
  //   cuisine_type: ['Indian-Sweets', 'Desserts', 'Street-Food', 'Fast-Food', 'Indian', 'Breakfast'],
  //   rating: 4.4,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Tuesday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Philosophy Club',
  //   description: 'A high-end, exclusive club with a global cuisine menu and artisanal cocktails.',
  //   address: {
  //     street: 'S.G. Highway',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.078, baseLat + 0.018],
  //     },
  //   },
  //   contact: { phone: '9876543255', email: 'philosophy.ahd@example.com' },
  //   cuisine_type: ['Italian', 'Mexican', 'Japanese', 'Dinner', 'Beverages', 'Salads', 'Sushi'],
  //   rating: 4.9,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Wednesday', open: '19:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 1500,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 3500,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Honest Restaurant',
  //   description: 'A local chain famous for its Pav Bhaji, pizzas, and multi-cuisine vegetarian fare.',
  //   address: {
  //     street: 'Multiple Locations',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.048, baseLat + 0.008],
  //     },
  //   },
  //   contact: { phone: '9876543256', email: 'honest.ahd@example.com' },
  //   cuisine_type: ['Street-Food', 'Indian', 'Pizza', 'Fast-Food', 'South-Indian', 'Lunch', 'Dinner'],
  //   rating: 4.2,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'EatFit',
  //   description: 'Healthy and calorie-counted Indian and fusion meals.',
  //   address: {
  //     street: 'Cloud Kitchen, Prahlad Nagar',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.063, baseLat - 0.013],
  //     },
  //   },
  //   contact: { phone: '9876543257', email: 'eatfit.ahd@example.com' },
  //   cuisine_type: ['Healthy', 'Indian', 'Salads', 'Breakfast', 'Lunch', 'Dinner', 'Soups'],
  //   rating: 4.4,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Friday', open: '08:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Jugaad Nights',
  //   description: 'Late-night delivery for comfort food cravings like Maggi, sandwiches, and rolls.',
  //   address: {
  //     street: 'Cloud Kitchen, University Area',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.012, baseLat + 0.022],
  //     },
  //   },
  //   contact: { phone: '9876543258', email: 'jugaad.ahd@example.com' },
  //   cuisine_type: ['Fast-Food', 'Street-Food', 'Sandwiches', 'Beverages', 'Dinner', 'Chinese'],
  //   rating: 4.0,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Saturday', open: '19:00', close: '04:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 300,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Good Bowl',
  //   description: 'Wholesome and delicious bowls that are a fusion of global and Indian flavors.',
  //   address: {
  //     street: 'Cloud Kitchen, Satellite',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.057, baseLat - 0.007],
  //     },
  //   },
  //   contact: { phone: '9876543259', email: 'goodbowl.ahd@example.com' },
  //   cuisine_type: ['Healthy', 'Salads', 'North-Indian', 'Indian', 'Lunch', 'Dinner', 'Mexican'],
  //   rating: 4.3,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 32,
  // },
  // {
  //   name: 'Shambhu\'s Coffee Bar',
  //   description: 'A very popular local chain for coffee, shakes, and quick bites.',
  //   address: {
  //     street: 'Near Vastrapur Lake',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.041, baseLat + 0.011],
  //     },
  //   },
  //   contact: { phone: '9876543260', email: 'shambhus.ahd@example.com' },
  //   cuisine_type: ['Beverages', 'Fast-Food', 'Sandwiches', 'Desserts', 'Breakfast'],
  //   rating: 4.5,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // seeded till here
  //   // --- Restaurants 51-100 ---
  //   // Adding 50 more restaurants to reach the goal of 100.
  // {
  //   name: 'Toritos',
  //   description: 'Lively spot for authentic Mexican food and vibrant cocktails.',
  //   address: {
  //     street: 'Prahlad Nagar',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.066, baseLat - 0.016],
  //     },
  //   },
  //   contact: { phone: '9876543261', email: 'toritos.ahd@example.com' },
  //   cuisine_type: ['Mexican', 'Italian', 'Dinner', 'Lunch', 'Beverages', 'Salads'],
  //   rating: 4.4,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Yanki Sizzlers',
  //   description: 'Famous for its wide variety of sizzling hot plates.',
  //   address: {
  //     street: 'Bodakdev',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.059, baseLat + 0.039],
  //     },
  //   },
  //   contact: { phone: '9876543262', email: 'yanki.ahd@example.com' },
  //   cuisine_type: ['BBQ', 'Chinese', 'Mexican', 'Italian', 'Dinner', 'Lunch'],
  //   rating: 4.3,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 48,
  // },
  // {
  //   name: 'McDonald\'s',
  //   description: 'The iconic global fast-food chain for burgers, fries, and shakes.',
  //   address: {
  //     street: 'Drive-In Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '9876543263', email: 'mcd.ahd@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Desserts', 'Beverages', 'Breakfast', 'Lunch'],
  //   rating: 4.0,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Thursday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Domino\'s Pizza',
  //   description: 'Well-known chain for a wide range of pizzas and a variety of other dishes & sides.',
  //   address: {
  //     street: 'Chandkheda',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '382424',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.052, baseLat + 0.082],
  //     },
  //   },
  //   contact: { phone: '9876543264', email: 'dominos.ahd@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Desserts', 'Beverages'],
  //   rating: 4.0,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Asharfi Kulfi',
  //   description: 'A legendary brand in Ahmedabad for rich, creamy, and traditional kulfi.',
  //   address: {
  //     street: 'Law Garden',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.011, baseLat + 0.006],
  //     },
  //   },
  //   contact: { phone: '9876543265', email: 'asharfi.ahd@example.com' },
  //   cuisine_type: ['Indian-Sweets', 'Desserts', 'Beverages'],
  //   rating: 4.8,
  //   numberOfReviews: 4000,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 20,
  // },
  // --- Restaurants 56-65 ---
  // {
  //   name: 'Spice Villa',
  //   description: 'A journey through the aromatic spices of India.',
  //   address: {
  //     street: 'Anandnagar Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380007',
  //     location: { type: 'Point', coordinates: [baseLon - 0.04, baseLat - 0.02] },
  //   },
  //   contact: { phone: '9876543266', email: 'spicevilla@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'Soups', 'BBQ'],
  //   rating: 4.2,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'The Urban Grill',
  //   description: 'Sizzling grills, juicy burgers, and a vibrant atmosphere.',
  //   address: {
  //     street: 'Thaltej',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380059',
  //     location: { type: 'Point', coordinates: [baseLon - 0.085, baseLat + 0.055] },
  //   },
  //   contact: { phone: '9876543267', email: 'urbangrill@example.com' },
  //   cuisine_type: ['Burgers', 'BBQ', 'Fast-Food', 'Sandwiches', 'Dinner'],
  //   rating: 4.4,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Tuesday', open: '17:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 750,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Curry Kingdom',
  //   description: 'Royal Indian curries and breads fit for a king.',
  //   address: {
  //     street: 'Ghatlodia',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380061',
  //     location: { type: 'Point', coordinates: [baseLon - 0.02, baseLat + 0.06] },
  //   },
  //   contact: { phone: '9876543268', email: 'currykingdom@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Vegan', 'Dinner', 'Lunch'],
  //   rating: 4.1,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Wednesday', open: '11:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Pasta Factory',
  //   description: 'Handmade pasta and authentic Italian sauces.',
  //   address: {
  //     street: 'Vastral',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '382418',
  //     location: { type: 'Point', coordinates: [baseLon + 0.1, baseLat - 0.03] },
  //   },
  //   contact: { phone: '9876543269', email: 'pastafactory@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Salads', 'Soups', 'Dinner'],
  //   rating: 4.3,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 42,
  // },
  // seeded till here
  // {
  //   name: 'Sweet Escape',
  //   description: 'A haven for dessert lovers with cakes, pastries, and more.',
  //   address: {
  //     street: 'Naranpura',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380013',
  //     location: { type: 'Point', coordinates: [baseLon - 0.01, baseLat + 0.04] },
  //   },
  //   contact: { phone: '9876543270', email: 'sweetescape@example.com' },
  //   cuisine_type: ['Desserts', 'Indian-Sweets', 'Beverages', 'Breakfast'],
  //   rating: 4.7,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Friday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Liquid Lounge',
  //   description: 'Creative mocktails, fresh juices, and healthy smoothies.',
  //   address: {
  //     street: 'Ashram Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: { type: 'Point', coordinates: [baseLon - 0.005, baseLat + 0.005] },
  //   },
  //   contact: { phone: '9876543271', email: 'liquidlounge@example.com' },
  //   cuisine_type: ['Beverages', 'Healthy', 'Breakfast', 'Fast-Food'],
  //   rating: 4.0,
  //   numberOfReviews: 700,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Morning Bites',
  //   description: 'Your perfect start to the day with delicious breakfast options.',
  //   address: {
  //     street: 'South Bopal',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380058',
  //     location: { type: 'Point', coordinates: [baseLon - 0.11, baseLat - 0.06] },
  //   },
  //   contact: { phone: '9876543272', email: 'morningbites@example.com' },
  //   cuisine_type: ['Breakfast', 'Sandwiches', 'Healthy', 'Beverages', 'South-Indian'],
  //   rating: 4.5,
  //   numberOfReviews: 980,
  //   opening_hours: [{ day: 'Sunday', open: '07:00', close: '14:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Green Goodness',
  //   description: 'Fresh salads, wholesome bowls, and nutritious smoothies.',
  //   address: {
  //     street: 'Ambli',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380058',
  //     location: { type: 'Point', coordinates: [baseLon - 0.095, baseLat - 0.025] },
  //   },
  //   contact: { phone: '9876543273', email: 'greengoodness@example.com' },
  //   cuisine_type: ['Healthy', 'Salads', 'Vegan', 'Soups', 'Beverages', 'Lunch'],
  //   rating: 4.8,
  //   numberOfReviews: 650,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Quick Eats',
  //   description: 'Fast, fresh, and flavorful meals for people on the go.',
  //   address: {
  //     street: 'Gota',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '382481',
  //     location: { type: 'Point', coordinates: [baseLon - 0.04, baseLat + 0.09] },
  //   },
  //   contact: { phone: '9876543274', email: 'quickeats@example.com' },
  //   cuisine_type: ['Fast-Food', 'Sandwiches', 'Burgers', 'Chinese', 'Beverages'],
  //   rating: 3.9,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 90,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Taco Town',
  //   description: 'Authentic Mexican street tacos, burritos, and quesadillas.',
  //   address: {
  //     street: 'Vejalpur',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380051',
  //     location: { type: 'Point', coordinates: [baseLon - 0.03, baseLat - 0.03] },
  //   },
  //   contact: { phone: '9876543275', email: 'tacotown@example.com' },
  //   cuisine_type: ['Mexican', 'Fast-Food', 'Salads', 'Beverages', 'Dinner'],
  //   rating: 4.2,
  //   numberOfReviews: 880,
  //   opening_hours: [{ day: 'Wednesday', open: '13:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 650,
  //   delivery_time_mins: 38,
  // },
  // // --- Restaurants 66-75 ---
  // {
  //   name: 'Vegan Delight',
  //   description: 'Creative and delicious 100% plant-based cuisine.',
  //   address: {
  //     street: 'Makarba',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380051',
  //     location: { type: 'Point', coordinates: [baseLon - 0.05, baseLat - 0.04] },
  //   },
  //   contact: { phone: '9876543276', email: 'vegandelight@example.com' },
  //   cuisine_type: ['Vegan', 'Healthy', 'Salads', 'Desserts', 'Italian', 'Lunch'],
  //   rating: 4.9,
  //   numberOfReviews: 720,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 950,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Sushi Central',
  //   description: 'Premium sushi rolls, sashimi, and Japanese appetizers.',
  //   address: {
  //     street: 'Science City Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380060',
  //     location: { type: 'Point', coordinates: [baseLon - 0.07, baseLat + 0.07] },
  //   },
  //   contact: { phone: '9876543277', email: 'sushicentral@example.com' },
  //   cuisine_type: ['Sushi', 'Japanese', 'Soups', 'Salads', 'Dinner'],
  //   rating: 4.6,
  //   numberOfReviews: 1150,
  //   opening_hours: [{ day: 'Friday', open: '18:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'The Sandwich Co.',
  //   description: 'Gourmet sandwiches, paninis, and wraps with fresh fillings.',
  //   address: {
  //     street: 'Shahibaug',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380004',
  //     location: { type: 'Point', coordinates: [baseLon + 0.01, baseLat + 0.03] },
  //   },
  //   contact: { phone: '9876543278', email: 'sandwichco@example.com' },
  //   cuisine_type: ['Sandwiches', 'Fast-Food', 'Breakfast', 'Healthy', 'Beverages'],
  //   rating: 4.3,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Saturday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 350,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Salad Stories',
  //   description: 'Craft your own salad story with our fresh ingredients.',
  //   address: {
  //     street: 'Nikol',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '382350',
  //     location: { type: 'Point', coordinates: [baseLon + 0.12, baseLat + 0.01] },
  //   },
  //   contact: { phone: '9876543279', email: 'saladstories@example.com' },
  //   cuisine_type: ['Salads', 'Healthy', 'Vegan', 'Soups', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 550,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 550,
  //   delivery_time_mins: 30,
  // },
  // seeded till here
  // {
  //   name: 'Soup Station',
  //   description: 'A wide variety of comforting and hearty soups from around the world.',
  //   address: {
  //     street: 'Odhav',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '382415',
  //     location: { type: 'Point', coordinates: [baseLon + 0.08, baseLat - 0.01] },
  //   },
  //   contact: { phone: '9876543280', email: 'soupstation@example.com' },
  //   cuisine_type: ['Soups', 'Healthy', 'Salads', 'Vegan', 'Lunch', 'Dinner'],
  //   rating: 4.1,
  //   numberOfReviews: 400,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 32,
  // },
  // {
  //   name: 'Grill & Chill',
  //   description: 'The perfect spot to chill with friends over grilled food and mocktails.',
  //   address: {
  //     street: 'Chandlodiya',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '382481',
  //     location: { type: 'Point', coordinates: [baseLon - 0.03, baseLat + 0.08] },
  //   },
  //   contact: { phone: '9876543281', email: 'grillnchill@example.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Fast-Food', 'Dinner', 'Beverages'],
  //   rating: 4.0,
  //   numberOfReviews: 1050,
  //   opening_hours: [{ day: 'Tuesday', open: '18:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 220,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Dine Fine',
  //   description: 'An elegant fine dining experience with a multi-cuisine menu.',
  //   address: {
  //     street: 'Near Ellis Bridge',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380006',
  //     location: { type: 'Point', coordinates: [baseLon - 0.01, baseLat - 0.01] },
  //   },
  //   contact: { phone: '9876543282', email: 'dinefine@example.com' },
  //   cuisine_type: ['Dinner', 'Lunch', 'North-Indian', 'Italian', 'Soups', 'Desserts'],
  //   rating: 4.7,
  //   numberOfReviews: 1600,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'The Lunch Box',
  //   description: 'Quick, convenient, and delicious lunch thalis and combos.',
  //   address: {
  //     street: 'Corporate Road, Prahlad Nagar',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: { type: 'Point', coordinates: [baseLon - 0.068, baseLat - 0.018] },
  //   },
  //   contact: { phone: '9876543283', email: 'lunchbox@example.com' },
  //   cuisine_type: ['Lunch', 'Indian', 'North-Indian', 'Healthy', 'Salads'],
  //   rating: 4.3,
  //   numberOfReviews: 1400,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '16:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Northern Spice',
  //   description: 'Authentic flavors from the heart of North India.',
  //   address: {
  //     street: 'Ranip',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '382480',
  //     location: { type: 'Point', coordinates: [baseLon + 0.01, baseLat + 0.07] },
  //   },
  //   contact: { phone: '9876543284', email: 'northernspice@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ'],
  //   rating: 4.4,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 280,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Dosa Corner',
  //   description: 'A huge variety of crispy dosas and South Indian snacks.',
  //   address: {
  //     street: 'Jodhpur Village',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: { type: 'Point', coordinates: [baseLon - 0.04, baseLat - 0.01] },
  //   },
  //   contact: { phone: '9876543285', email: 'dosacorner@example.com' },
  //   cuisine_type: ['South-Indian', 'Street-Food', 'Breakfast', 'Lunch', 'Indian'],
  //   rating: 4.2,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 22,
  // },
  // // --- Restaurants 76-85 ---
  // {
  //   name: 'Wok Stars',
  //   description: 'Pan-Asian street food with a modern, stellar twist.',
  //   address: {
  //     street: 'Naroda',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '382330',
  //     location: { type: 'Point', coordinates: [baseLon + 0.07, baseLat + 0.05] },
  //   },
  //   contact: { phone: '9876543286', email: 'wokstars@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Fast-Food', 'Soups', 'Dinner'],
  //   rating: 4.1,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Tokyo Bites',
  //   description: 'Quick and delicious Japanese bites, from sushi to katsu.',
  //   address: {
  //     street: 'Memnagar',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380052',
  //     location: { type: 'Point', coordinates: [baseLon - 0.025, baseLat + 0.035] },
  //   },
  //   contact: { phone: '9876543287', email: 'tokyobites@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Fast-Food', 'Lunch', 'Dinner'],
  //   rating: 4.3,
  //   numberOfReviews: 780,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Street Bites',
  //   description: 'A culinary tour of India\'s best street food.',
  //   address: {
  //     street: 'Bapunagar',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380024',
  //     location: { type: 'Point', coordinates: [baseLon + 0.06, baseLat + 0.01] },
  //   },
  //   contact: { phone: '9876543288', email: 'streetbites@example.com' },
  //   cuisine_type: ['Street-Food', 'Indian', 'Fast-Food', 'Beverages', 'Desserts'],
  //   rating: 4.6,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Tuesday', open: '16:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Mithai Mahal',
  //   description: 'A palace of traditional Indian sweets and savory snacks.',
  //   address: {
  //     street: 'Paldi',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380007',
  //     location: { type: 'Point', coordinates: [baseLon - 0.008, baseLat - 0.028] },
  //   },
  //   contact: { phone: '9876543289', email: 'mithaimahal@example.com' },
  //   cuisine_type: ['Indian-Sweets', 'Desserts', 'Street-Food', 'Breakfast'],
  //   rating: 4.8,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Wednesday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 25,
  // },
  // seeded till here
  // {
  //   name: 'Pizza Planet',
  //   description: 'Out of this world pizzas with a galaxy of toppings.',
  //   address: {
  //     street: 'Isanpur',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '382443',
  //     location: { type: 'Point', coordinates: [baseLon + 0.04, baseLat - 0.06] },
  //   },
  //   contact: { phone: '9876543290', email: 'pizzaplanet@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Beverages', 'Dinner'],
  //   rating: 4.0,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 220,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Burger Baron',
  //   description: 'Royally good burgers, fit for a baron.',
  //   address: {
  //     street: 'Vatva',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '382440',
  //     location: { type: 'Point', coordinates: [baseLon + 0.08, baseLat - 0.08] },
  //   },
  //   contact: { phone: '9876543291', email: 'burgerbaron@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Sandwiches', 'Beverages', 'Desserts'],
  //   rating: 4.1,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Royal Indian',
  //   description: 'A majestic feast of authentic Indian cuisine.',
  //   address: {
  //     street: 'Sabarmati',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380005',
  //     location: { type: 'Point', coordinates: [baseLon, baseLat + 0.05] },
  //   },
  //   contact: { phone: '9876543292', email: 'royalindian@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch', 'Desserts'],
  //   rating: 4.5,
  //   numberOfReviews: 2300,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Bella Italia',
  //   description: 'Beautifully crafted Italian dishes that taste like Italy.',
  //   address: {
  //     street: 'Sarkhej',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '382210',
  //     location: { type: 'Point', coordinates: [baseLon - 0.08, baseLat - 0.05] },
  //   },
  //   contact: { phone: '9876543293', email: 'bellaitalia@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Salads', 'Dinner', 'Soups'],
  //   rating: 4.4,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Sunday', open: '12:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 9,
  //   is_veg: true,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 48,
  // },
  // {
  //   name: 'Dessert Den',
  //   description: 'A cozy den to indulge in all your dessert fantasies.',
  //   address: {
  //     street: 'Jivraj Park',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380051',
  //     location: { type: 'Point', coordinates: [baseLon - 0.02, baseLat - 0.04] },
  //   },
  //   contact: { phone: '9876543294', email: 'dessertden@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Indian-Sweets', 'Fast-Food'],
  //   rating: 4.6,
  //   numberOfReviews: 1700,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 22,
  // },
  // {
  //   name: 'Juice Junction',
  //   description: 'The meeting point for all things fresh, fruity, and juicy.',
  //   address: {
  //     street: 'Usmanpura',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380014',
  //     location: { type: 'Point', coordinates: [baseLon - 0.005, baseLat + 0.025] },
  //   },
  //   contact: { phone: '9876543295', email: 'juicejunction@example.com' },
  //   cuisine_type: ['Beverages', 'Healthy', 'Breakfast', 'Street-Food'],
  //   rating: 4.2,
  //   numberOfReviews: 850,
  //   opening_hours: [{ day: 'Tuesday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 150,
  //   delivery_time_mins: 18,
  // },
  // // --- Restaurants 86-100 ---
  // {
  //   name: 'Sunrise Cafe',
  //   description: 'Start your day with a beautiful sunrise and a perfect breakfast.',
  //   address: {
  //     street: 'Bodakdev',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: { type: 'Point', coordinates: [baseLon - 0.055, baseLat + 0.035] },
  //   },
  //   contact: { phone: '9876543296', email: 'sunrisecafe@example.com' },
  //   cuisine_type: ['Breakfast', 'Healthy', 'Beverages', 'Sandwiches', 'South-Indian'],
  //   rating: 4.5,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Wednesday', open: '07:00', close: '15:00' }],
  //   is_active: true,
  //   min_order_value: 160,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Fit Fuel',
  //   description: 'Fuel your body with our healthy and protein-packed meals.',
  //   address: {
  //     street: 'Prahlad Nagar',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: { type: 'Point', coordinates: [baseLon - 0.061, baseLat - 0.011] },
  //   },
  //   contact: { phone: '9876543297', email: 'fitfuel@example.com' },
  //   cuisine_type: ['Healthy', 'Salads', 'Soups', 'Vegan', 'Lunch', 'Dinner'],
  //   rating: 4.7,
  //   numberOfReviews: 750,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 220,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Speedy Snacks',
  //   description: 'Your favorite snacks, delivered at lightning speed.',
  //   address: {
  //     street: 'Maninagar East',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380008',
  //     location: { type: 'Point', coordinates: [baseLon + 0.035, baseLat - 0.045] },
  //   },
  //   contact: { phone: '9876543298', email: 'speedysnacks@example.com' },
  //   cuisine_type: ['Fast-Food', 'Street-Food', 'Sandwiches', 'Beverages', 'Chinese'],
  //   rating: 3.8,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 250,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'MexiCali',
  //   description: 'A fusion of Mexican and Californian flavors.',
  //   address: {
  //     street: 'Sindhu Bhavan Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380059',
  //     location: { type: 'Point', coordinates: [baseLon - 0.072, baseLat + 0.042] },
  //   },
  //   contact: { phone: '9876543299', email: 'mexicali@example.com' },
  //   cuisine_type: ['Mexican', 'Salads', 'Healthy', 'Dinner', 'Lunch'],
  //   rating: 4.4,
  //   numberOfReviews: 920,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Plant Power',
  //   description: 'Harness the power of plants with our vegan menu.',
  //   address: {
  //     street: 'Navrangpura',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: { type: 'Point', coordinates: [baseLon + 0.017, baseLat + 0.017] },
  //   },
  //   contact: { phone: '9876543300', email: 'plantpower@example.com' },
  //   cuisine_type: ['Vegan', 'Healthy', 'Salads', 'Soups', 'Breakfast'],
  //   rating: 4.8,
  //   numberOfReviews: 810,
  //   opening_hours: [{ day: 'Sunday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 850,
  //   delivery_time_mins: 35,
  // },
  // seeded till here
  // {
  //   name: 'Roll & Bowl',
  //   description: 'Delicious rolls and hearty bowls for a complete meal.',
  //   address: {
  //     street: 'Vastrapur',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: { type: 'Point', coordinates: [baseLon - 0.038, baseLat + 0.018] },
  //   },
  //   contact: { phone: '9876543301', email: 'rollnbowl@example.com' },
  //   cuisine_type: ['Fast-Food', 'Indian', 'Chinese', 'Lunch', 'Dinner'],
  //   rating: 4.1,
  //   numberOfReviews: 1350,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Sub Hub',
  //   description: 'The central hub for all your submarine sandwich cravings.',
  //   address: {
  //     street: 'C.G. Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: { type: 'Point', coordinates: [baseLon + 0.021, baseLat - 0.009] },
  //   },
  //   contact: { phone: '9876543302', email: 'subhub@example.com' },
  //   cuisine_type: ['Sandwiches', 'Salads', 'Healthy', 'Fast-Food', 'Breakfast'],
  //   rating: 4.2,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Tuesday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 140,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Crisp & Green',
  //   description: 'Salads so crisp and greens so fresh, you\'ll be back for more.',
  //   address: {
  //     street: 'Satellite',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: { type: 'Point', coordinates: [baseLon - 0.052, baseLat - 0.002] },
  //   },
  //   contact: { phone: '9876543303', email: 'crispngreen@example.com' },
  //   cuisine_type: ['Salads', 'Healthy', 'Vegan', 'Soups', 'Beverages'],
  //   rating: 4.6,
  //   numberOfReviews: 680,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '21:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 33,
  // },
  // {
  //   name: 'Hot Pots',
  //   description: 'Warm, comforting, and flavorful one-pot meals.',
  //   address: {
  //     street: 'Thaltej',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380059',
  //     location: { type: 'Point', coordinates: [baseLon - 0.082, baseLat + 0.052] },
  //   },
  //   contact: { phone: '9876543304', email: 'hotpots@example.com' },
  //   cuisine_type: ['Soups', 'Indian', 'Chinese', 'Dinner', 'Lunch'],
  //   rating: 4.0,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Smokeyard BBQ',
  //   description: 'Authentic smokey flavors from our backyard to your plate.',
  //   address: {
  //     street: 'Bopal',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380058',
  //     location: { type: 'Point', coordinates: [baseLon - 0.102, baseLat - 0.052] },
  //   },
  //   contact: { phone: '9876543305', email: 'smokeyard@example.com' },
  //   cuisine_type: ['BBQ', 'Dinner', 'Burgers', 'North-Indian', 'Fast-Food'],
  //   rating: 4.5,
  //   numberOfReviews: 1250,
  //   opening_hours: [{ day: 'Friday', open: '18:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1300,
  //   delivery_time_mins: 48,
  // },
  // {
  //   name: 'The Chai Stop',
  //   description: 'A quick stop for a refreshing cup of chai and snacks.',
  //   address: {
  //     street: 'University Road',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380009',
  //     location: { type: 'Point', coordinates: [baseLon - 0.015, baseLat + 0.025] },
  //   },
  //   contact: { phone: '9876543306', email: 'chaistop@example.com' },
  //   cuisine_type: ['Beverages', 'Street-Food', 'Breakfast', 'Sandwiches'],
  //   rating: 4.3,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Saturday', open: '07:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 50,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 100,
  //   delivery_time_mins: 15,
  // },
  // {
  //   name: 'Pizza Pie',
  //   description: 'Deliciously round pizzas that are as easy as pie to eat.',
  //   address: {
  //     street: 'Ghatlodia',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380061',
  //     location: { type: 'Point', coordinates: [baseLon - 0.025, baseLat + 0.065] },
  //   },
  //   contact: { phone: '9876543307', email: 'pizzapie@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Desserts'],
  //   rating: 4.1,
  //   numberOfReviews: 1400,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 32,
  // },
  // {
  //   name: 'The Momo Spot',
  //   description: 'A dedicated spot for delicious steamed and fried momos.',
  //   address: {
  //     street: 'Prahlad Nagar',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: { type: 'Point', coordinates: [baseLon - 0.063, baseLat - 0.013] },
  //   },
  //   contact: { phone: '9876543308', email: 'momospot@example.com' },
  //   cuisine_type: ['Chinese', 'Fast-Food', 'Street-Food', 'Soups'],
  //   rating: 4.4,
  //   numberOfReviews: 1600,
  //   opening_hours: [{ day: 'Monday', open: '16:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 350,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Paratha Palace',
  //   description: 'A royal treat of stuffed parathas from all over India.',
  //   address: {
  //     street: 'Satellite',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380015',
  //     location: { type: 'Point', coordinates: [baseLon - 0.051, baseLat - 0.001] },
  //   },
  //   contact: { phone: '9876543309', email: 'parathapalace@example.com' },
  //   cuisine_type: ['North-Indian', 'Breakfast', 'Lunch', 'Street-Food', 'Indian'],
  //   rating: 4.3,
  //   numberOfReviews: 1750,
  //   opening_hours: [{ day: 'Tuesday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Global Bites',
  //   description: 'A world of flavors in every bite. Multi-cuisine cloud kitchen.',
  //   address: {
  //     street: 'Cloud Kitchen, Bodakdev',
  //     city: 'Ahmadabad',
  //     state: 'Gujarat',
  //     zip_code: '380054',
  //     location: { type: 'Point', coordinates: [baseLon - 0.054, baseLat + 0.034] },
  //   },
  //   contact: { phone: '9876543310', email: 'globalbites@example.com' },
  //   cuisine_type: ['Italian', 'Mexican', 'Chinese', 'North-Indian', 'Dinner', 'Lunch'],
  //   rating: 4.0,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
];

export default ahmadabadRestaurants;
