// Base coordinates for Bangalore (approximate center)
const baseLat = 12.9629;
const baseLon = 77.5775;

const bangaloreRestaurants = [
  // --- Restaurants 1-10 ---
  {
    name: 'MTR - Mavalli Tiffin Rooms',
    description:
      'A legendary, century-old establishment serving authentic Karnataka-style breakfast and meals.',
    address: {
      street: 'Lalbagh Road',
      city: 'Bangalore',
      state: 'Karnataka',
      zip_code: '560004',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.01, baseLat - 0.02],
      },
    },
    contact: { phone: '9876560001', email: 'mtr.bangalore@example.com' },
    cuisine_type: ['South-Indian', 'Breakfast', 'Indian', 'Beverages', 'Lunch'],
    rating: 4.8,
    numberOfReviews: 9500,
    opening_hours: [{ day: 'Tuesday', open: '06:30', close: '21:30' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 300,
    delivery_time_mins: 30,
  },
  {
    name: 'Toit',
    description:
      "One of Bangalore's most famous brewpubs, offering craft beers and delicious food.",
    address: {
      street: '100 Feet Road, Indiranagar',
      city: 'Bangalore',
      state: 'Karnataka',
      zip_code: '560038',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.06, baseLat + 0.01],
      },
    },
    contact: { phone: '9876560002', email: 'toit.blr@example.com' },
    cuisine_type: ['Pizza', 'Burgers', 'Italian', 'BBQ', 'Dinner', 'Beverages'],
    rating: 4.7,
    numberOfReviews: 8200,
    opening_hours: [{ day: 'Wednesday', open: '12:00', close: '01:00' }],
    is_active: true,
    min_order_value: 600,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 2000,
    delivery_time_mins: 50,
  },
  {
    name: 'Vidyarthi Bhavan',
    description:
      'An iconic heritage restaurant in Basavanagudi, famous for its crispy Masala Dosa.',
    address: {
      street: 'Gandhi Bazaar, Basavanagudi',
      city: 'Bangalore',
      state: 'Karnataka',
      zip_code: '560004',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.02, baseLat - 0.03],
      },
    },
    contact: { phone: '9876560003', email: 'vidyarthibhavan@example.com' },
    cuisine_type: [
      'South-Indian',
      'Breakfast',
      'Street-Food',
      'Indian',
      'Beverages',
    ],
    rating: 4.9,
    numberOfReviews: 11000,
    opening_hours: [{ day: 'Thursday', open: '06:30', close: '20:00' }],
    is_active: true,
    min_order_value: 80,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 250,
    delivery_time_mins: 25,
  },
  {
    name: 'Truffles',
    description:
      'A hugely popular spot for all-American burgers, subs, and decadent desserts.',
    address: {
      street: 'St. Marks Road',
      city: 'Bangalore',
      state: 'Karnataka',
      zip_code: '560001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.01, baseLat],
      },
    },
    contact: { phone: '9876560004', email: 'truffles.blr@example.com' },
    cuisine_type: [
      'Burgers',
      'Fast-Food',
      'Sandwiches',
      'Desserts',
      'Beverages',
    ],
    rating: 4.6,
    numberOfReviews: 15000,
    opening_hours: [{ day: 'Friday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 900,
    delivery_time_mins: 40,
  },
  {
    name: 'Meghana Foods',
    description:
      'Famous across the city for its flavorful and spicy Andhra-style biryani.',
    address: {
      street: 'Koramangala 5th Block',
      city: 'Bangalore',
      state: 'Karnataka',
      zip_code: '560095',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.03, baseLat - 0.04],
      },
    },
    contact: { phone: '9876560005', email: 'meghanafoods@example.com' },
    cuisine_type: ['Indian', 'North-Indian', 'South-Indian', 'Dinner', 'Lunch'],
    rating: 4.5,
    numberOfReviews: 12500,
    opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 700,
    delivery_time_mins: 35,
  },
  {
    name: 'The Green Theory',
    description:
      'A charming vegetarian cafe with a focus on healthy and organic continental dishes.',
    address: {
      street: 'Residency Road',
      city: 'Bangalore',
      state: 'Karnataka',
      zip_code: '560025',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.02, baseLat - 0.01],
      },
    },
    contact: { phone: '9876560006', email: 'greentheory@example.com' },
    cuisine_type: [
      'Vegan',
      'Healthy',
      'Italian',
      'Salads',
      'Soups',
      'Breakfast',
    ],
    rating: 4.4,
    numberOfReviews: 1500,
    opening_hours: [{ day: 'Sunday', open: '11:00', close: '22:30' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 1000,
    delivery_time_mins: 45,
  },
  {
    name: 'Shiro',
    description:
      'A high-end restaurant offering stunning views and an exquisite Pan-Asian menu.',
    address: {
      street: 'UB City, Vittal Mallya Road',
      city: 'Bangalore',
      state: 'Karnataka',
      zip_code: '560001',
      location: {
        type: 'Point',
        coordinates: [baseLon, baseLat - 0.01],
      },
    },
    contact: { phone: '9876560007', email: 'shiro.blr@example.com' },
    cuisine_type: ['Japanese', 'Sushi', 'Chinese', 'Dinner', 'Soups'],
    rating: 4.7,
    numberOfReviews: 2800,
    opening_hours: [{ day: 'Monday', open: '12:30', close: '00:00' }],
    is_active: true,
    min_order_value: 1500,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 4000,
    delivery_time_mins: 60,
  },
  {
    name: 'Corner House Ice Cream',
    description:
      'A legendary ice cream parlor famous for its Death by Chocolate (DBC).',
    address: {
      street: 'Residency Road',
      city: 'Bangalore',
      state: 'Karnataka',
      zip_code: '560025',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.022, baseLat - 0.012],
      },
    },
    contact: { phone: '9876560008', email: 'cornerhouse@example.com' },
    cuisine_type: ['Desserts', 'Indian-Sweets', 'Beverages'],
    rating: 4.8,
    numberOfReviews: 9900,
    opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:30' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 300,
    delivery_time_mins: 20,
  },
  {
    name: 'Taco Bell',
    description:
      'Fast-food chain serving Mexican-inspired fare like tacos, quesadillas, and nachos.',
    address: {
      street: 'Ascendas Park Square Mall, Whitefield',
      city: 'Bangalore',
      state: 'Karnataka',
      zip_code: '560066',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.15, baseLat + 0.02],
      },
    },
    contact: { phone: '9876560009', email: 'tacobell.blr@example.com' },
    cuisine_type: ['Mexican', 'Fast-Food', 'Dinner', 'Lunch', 'Beverages'],
    rating: 4.1,
    numberOfReviews: 2500,
    opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 600,
    delivery_time_mins: 38,
  },
  {
    name: 'The Only Place',
    description:
      'A classic restaurant famous for its steaks, burgers, and apple pie.',
    address: {
      street: 'Museum Road, Church Street',
      city: 'Bangalore',
      state: 'Karnataka',
      zip_code: '560001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.015, baseLat - 0.005],
      },
    },
    contact: { phone: '9876560010', email: 'theonlyplace@example.com' },
    cuisine_type: ['BBQ', 'Burgers', 'Dinner', 'Salads', 'Desserts'],
    rating: 4.5,
    numberOfReviews: 4800,
    opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 1500,
    delivery_time_mins: 45,
  },
];

export default bangaloreRestaurants;
