// Base coordinates for Bangalore (approximate center)
const baseLat = 12.9629;
const baseLon = 77.5775;

const bangaloreRestaurants = [
  // --- Restaurants 1-10 ---
  // {
  //   name: 'MTR - Mavalli Tiffin Rooms',
  //   description:
  //     'A legendary, century-old establishment serving authentic Karnataka-style breakfast and meals.',
  //   address: {
  //     street: 'Lalbagh Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9876560001', email: 'mtr.bangalore@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Indian', 'Beverages', 'Lunch'],
  //   rating: 4.8,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Tuesday', open: '06:30', close: '21:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Toit',
  //   description:
  //     "One of Bangalore's most famous brewpubs, offering craft beers and delicious food.",
  //   address: {
  //     street: '100 Feet Road, Indiranagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.06, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9876560002', email: 'toit.blr@example.com' },
  //   cuisine_type: ['Pizza', 'Burgers', 'Italian', 'BBQ', 'Dinner', 'Beverages'],
  //   rating: 4.7,
  //   numberOfReviews: 8200,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Vidyarthi Bhavan',
  //   description:
  //     'An iconic heritage restaurant in Basavanagudi, famous for its crispy Masala Dosa.',
  //   address: {
  //     street: 'Gandhi Bazaar, Basavanagudi',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9876560003', email: 'vidyarthibhavan@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Breakfast',
  //     'Street-Food',
  //     'Indian',
  //     'Beverages',
  //   ],
  //   rating: 4.9,
  //   numberOfReviews: 11000,
  //   opening_hours: [{ day: 'Thursday', open: '06:30', close: '20:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Truffles',
  //   description:
  //     'A hugely popular spot for all-American burgers, subs, and decadent desserts.',
  //   address: {
  //     street: 'St. Marks Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat],
  //     },
  //   },
  //   contact: { phone: '9876560004', email: 'truffles.blr@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Sandwiches',
  //     'Desserts',
  //     'Beverages',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 15000,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Meghana Foods',
  //   description:
  //     'Famous across the city for its flavorful and spicy Andhra-style biryani.',
  //   address: {
  //     street: 'Koramangala 5th Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560095',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9876560005', email: 'meghanafoods@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'South-Indian', 'Dinner', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 12500,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Green Theory',
  //   description:
  //     'A charming vegetarian cafe with a focus on healthy and organic continental dishes.',
  //   address: {
  //     street: 'Residency Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560025',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876560006', email: 'greentheory@example.com' },
  //   cuisine_type: [
  //     'Vegan',
  //     'Healthy',
  //     'Italian',
  //     'Salads',
  //     'Soups',
  //     'Breakfast',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Shiro',
  //   description:
  //     'A high-end restaurant offering stunning views and an exquisite Pan-Asian menu.',
  //   address: {
  //     street: 'UB City, Vittal Mallya Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876560007', email: 'shiro.blr@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Chinese', 'Dinner', 'Soups'],
  //   rating: 4.7,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Monday', open: '12:30', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 1500,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 4000,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Corner House Ice Cream',
  //   description:
  //     'A legendary ice cream parlor famous for its Death by Chocolate (DBC).',
  //   address: {
  //     street: 'Residency Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560025',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.022, baseLat - 0.012],
  //     },
  //   },
  //   contact: { phone: '9876560008', email: 'cornerhouse@example.com' },
  //   cuisine_type: ['Desserts', 'Indian-Sweets', 'Beverages'],
  //   rating: 4.8,
  //   numberOfReviews: 9900,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Taco Bell',
  //   description:
  //     'Fast-food chain serving Mexican-inspired fare like tacos, quesadillas, and nachos.',
  //   address: {
  //     street: 'Ascendas Park Square Mall, Whitefield',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560066',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.15, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9876560009', email: 'tacobell.blr@example.com' },
  //   cuisine_type: ['Mexican', 'Fast-Food', 'Dinner', 'Lunch', 'Beverages'],
  //   rating: 4.1,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'The Only Place',
  //   description:
  //     'A classic restaurant famous for its steaks, burgers, and apple pie.',
  //   address: {
  //     street: 'Museum Road, Church Street',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9876560010', email: 'theonlyplace@example.com' },
  //   cuisine_type: ['BBQ', 'Burgers', 'Dinner', 'Salads', 'Desserts'],
  //   rating: 4.5,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 45,
  // },
  // seeded till here :
  // --- Restaurants 11-20 ---
  // {
  //   name: 'CTR - Shri Sagar',
  //   description:
  //     'Another iconic spot, beloved for its Benne Masala Dosa and classic South Indian tiffins.',
  //   address: {
  //     street: 'Margosa Road, Malleshwaram',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9876560011', email: 'ctr.blr@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Indian', 'Beverages'],
  //   rating: 4.7,
  //   numberOfReviews: 8800,
  //   opening_hours: [{ day: 'Friday', open: '07:30', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Karavalli',
  //   description:
  //     'A fine-dining restaurant celebrating the coastal cuisines of Southwest India.',
  //   address: {
  //     street: 'Residency Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560025',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9876560012', email: 'karavalli.blr@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'Healthy'],
  //   rating: 4.6,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Saturday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 3500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Koshy\'s Bar & Restaurant',
  //   description:
  //     'A Bangalore institution with an old-world charm, serving comfort food and drinks.',
  //   address: {
  //     street: 'St. Marks Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.012, baseLat - 0.002],
  //     },
  //   },
  //   contact: { phone: '9876560013', email: 'koshys.blr@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'North-Indian',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //     'Beverages',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Sunday', open: '09:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Brik Oven',
  //   description:
  //     'Famous for its authentic Neapolitan-style, wood-fired pizzas.',
  //   address: {
  //     street: 'Church Street',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.018, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9876560014', email: 'brikoven@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Desserts', 'Beverages'],
  //   rating: 4.5,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'VV Puram Food Street',
  //   description:
  //     'A bustling street food paradise offering a variety of local delicacies.',
  //   address: {
  //     street: 'Visveswarapuram',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9876560015', email: 'vvpuram@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'South-Indian',
  //     'Indian',
  //     'Desserts',
  //     'Beverages',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 7800,
  //   opening_hours: [{ day: 'Tuesday', open: '18:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 50,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Hole in the Wall Cafe',
  //   description:
  //     'A cozy and popular cafe known for its hearty all-day English breakfast.',
  //   address: {
  //     street: 'Koramangala 4th Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.035, baseLat - 0.035],
  //     },
  //   },
  //   contact: { phone: '9876560016', email: 'holeinthewall@example.com' },
  //   cuisine_type: [
  //     'Breakfast',
  //     'Burgers',
  //     'Sandwiches',
  //     'Desserts',
  //     'Beverages',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Wednesday', open: '08:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Nagarjuna',
  //   description:
  //     'A go-to place for authentic Andhra cuisine, especially their meals served on banana leaves.',
  //   address: {
  //     street: 'Residency Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560025',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.023, baseLat - 0.013],
  //     },
  //   },
  //   contact: { phone: '9876560017', email: 'nagarjuna.blr@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Lunch', 'Dinner'],
  //   rating: 4.4,
  //   numberOfReviews: 8500,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Burma Burma',
  //   description:
  //     'An authentic Burmese vegetarian restaurant offering unique flavors and dishes.',
  //   address: {
  //     street: '12th Main, Indiranagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.065, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9876560018', email: 'burmaburma.blr@example.com' },
  //   cuisine_type: ['Healthy', 'Vegan', 'Soups', 'Salads', 'Dinner', 'Lunch'],
  //   rating: 4.8,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Empire Restaurant',
  //   description:
  //     'A late-night favorite known for its kebabs, biryanis, and non-vegetarian fare.',
  //   address: {
  //     street: 'Church Street',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.016, baseLat - 0.006],
  //     },
  //   },
  //   contact: { phone: '9876560019', email: 'empire.blr@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'BBQ',
  //     'Dinner',
  //     'Fast-Food',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 18000,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '02:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 750,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Chinita Real Mexican Food',
  //   description:
  //     'A cozy place serving authentic, home-style Mexican dishes.',
  //   address: {
  //     street: 'Koramangala 5th Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560095',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.032, baseLat - 0.042],
  //     },
  //   },
  //   contact: { phone: '9876560020', email: 'chinita.blr@example.com' },
  //   cuisine_type: ['Mexican', 'Salads', 'Dinner', 'Lunch', 'Beverages'],
  //   rating: 4.5,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 45,
  // },
  // seeded till here
  // --- Restaurants 21-30 ---
  // {
  //   name: 'Brahmins\' Coffee Bar',
  //   description:
  //     'A legendary, standing-only joint famous for its soft idlis and crispy vadas.',
  //   address: {
  //     street: 'Ranga Rao Road, Shankarapura',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat - 0.028],
  //     },
  //   },
  //   contact: { phone: '9876560021', email: 'brahmins.blr@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Indian', 'Beverages'],
  //   rating: 4.8,
  //   numberOfReviews: 7200,
  //   opening_hours: [{ day: 'Monday', open: '06:00', close: '12:00' }],
  //   is_active: true,
  //   min_order_value: 50,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 150,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Arbor Brewing Company',
  //   description:
  //     'A popular microbrewery with a great ambiance, craft beers, and American pub grub.',
  //   address: {
  //     street: 'Magrath Road, Ashok Nagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560025',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.028, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9876560022', email: 'arbor.blr@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Pizza',
  //     'BBQ',
  //     'Fast-Food',
  //     'Dinner',
  //     'Beverages',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2200,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Go-Native',
  //   description:
  //     'A unique concept store and cafe focusing on sustainable, organic, and traditional Indian food.',
  //   address: {
  //     street: 'Jayanagar 5th Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560041',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat - 0.05],
  //     },
  //   },
  //   contact: { phone: '9876560023', email: 'gonative.blr@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Vegan',
  //     'Indian',
  //     'South-Indian',
  //     'Breakfast',
  //     'Salads',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Wednesday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Smoke House Deli',
  //   description:
  //     'A chic all-day cafe with hand-drawn decor, serving European comfort food.',
  //   address: {
  //     street: 'Lavelle Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.008, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9876560024', email: 'shd.blr@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Sandwiches',
  //     'Salads',
  //     'Breakfast',
  //     'Desserts',
  //     'Beverages',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Thursday', open: '09:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 48,
  // },
  // {
  //   name: 'Halli Mane',
  //   description:
  //     'A village-themed restaurant offering traditional Karnataka cuisine and festive meals.',
  //   address: {
  //     street: 'Malleshwaram',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.028, baseLat + 0.022],
  //     },
  //   },
  //   contact: { phone: '9876560025', email: 'hallimane.blr@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //     'Healthy',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Friday', open: '07:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Fatty Bao',
  //   description:
  //     'A vibrant and quirky Asian gastropub known for its baos, ramen, and sushi.',
  //   address: {
  //     street: '12th Main, Indiranagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.062, baseLat + 0.012],
  //     },
  //   },
  //   contact: { phone: '9876560026', email: 'fattybao.blr@example.com' },
  //   cuisine_type: ['Japanese', 'Chinese', 'Sushi', 'Soups', 'Dinner'],
  //   rating: 4.6,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Veena Stores',
  //   description:
  //     'A tiny, legendary takeaway joint in Malleshwaram serving some of the best idlis and vadas.',
  //   address: {
  //     street: 'Margosa Road, Malleshwaram',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.031, baseLat + 0.021],
  //     },
  //   },
  //   contact: { phone: '9876560027', email: 'veenastores@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Street-Food', 'Indian'],
  //   rating: 4.7,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Sunday', open: '06:30', close: '12:00' }],
  //   is_active: true,
  //   min_order_value: 40,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 100,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Polar Bear',
  //   description:
  //     'A popular ice cream parlor with a huge variety of sundaes and unique flavors.',
  //   address: {
  //     street: 'Multiple Locations',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.038, baseLat - 0.038],
  //     },
  //   },
  //   contact: { phone: '9876560028', email: 'polarbear@example.com' },
  //   cuisine_type: ['Desserts', 'Indian-Sweets', 'Beverages', 'Fast-Food'],
  //   rating: 4.4,
  //   numberOfReviews: 6200,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Leon Grill',
  //   description:
  //     'A fast-growing chain known for its peri-peri chicken, burgers, and wraps.',
  //   address: {
  //     street: 'Koramangala 6th Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560095',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.028, baseLat - 0.045],
  //     },
  //   },
  //   contact: { phone: '9876560029', email: 'leongrill@example.com' },
  //   cuisine_type: [
  //     'Fast-Food',
  //     'Burgers',
  //     'BBQ',
  //     'Salads',
  //     'Dinner',
  //     'Beverages',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Fenny\'s Lounge & Kitchen',
  //   description:
  //     'A Mediterranean-themed lounge with a lively ambiance, great cocktails, and wood-fired pizzas.',
  //   address: {
  //     street: 'Koramangala 7th Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560095',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat - 0.048],
  //     },
  //   },
  //   contact: { phone: '9876560030', email: 'fennys@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Pizza',
  //     'Mexican',
  //     'Dinner',
  //     'Beverages',
  //     'Salads',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 4100,
  //   opening_hours: [{ day: 'Wednesday', open: '11:30', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 50,
  // },
  // seeded till here :
  // // --- Restaurants 31-40 ---
  // {
  //   name: 'Carrot-Slaw',
  //   description: 'A health-focused cafe offering fresh salads, juices, and sandwiches.',
  //   address: {
  //     street: 'HSR Layout, Sector 4',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560102',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.08, baseLat - 0.06],
  //     },
  //   },
  //   contact: { phone: '9876560031', email: 'carrotslaw@example.com' },
  //   cuisine_type: ['Healthy', 'Salads', 'Soups', 'Beverages', 'Sandwiches'],
  //   rating: 4.6,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Thursday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Rameshwaram Cafe',
  //   description: 'A bustling, quick-service spot famous for its Ghee Podi Idli and Dosas.',
  //   address: {
  //     street: '12th Main, Indiranagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.063, baseLat + 0.013],
  //     },
  //   },
  //   contact: { phone: '9876560032', email: 'rameshwaramcafe@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Fast-Food', 'Indian'],
  //   rating: 4.8,
  //   numberOfReviews: 14000,
  //   opening_hours: [{ day: 'Friday', open: '06:30', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Harima',
  //   description: 'An authentic Japanese restaurant with a traditional ambiance and menu.',
  //   address: {
  //     street: 'Residency Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560025',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.024, baseLat - 0.014],
  //     },
  //   },
  //   contact: { phone: '9876560033', email: 'harima.blr@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Soups', 'Dinner', 'Healthy'],
  //   rating: 4.5,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Khan Saheb Grills and Rolls',
  //   description: 'A popular chain for delicious and affordable Kathi rolls and grills.',
  //   address: {
  //     street: 'Koramangala 1st Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9876560034', email: 'khansaheb@example.com' },
  //   cuisine_type: ['North-Indian', 'Street-Food', 'Fast-Food', 'BBQ', 'Dinner'],
  //   rating: 4.2,
  //   numberOfReviews: 7500,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Anand Sweets and Savouries',
  //   description: 'A famous sweet shop offering a vast array of Indian sweets, chaat, and snacks.',
  //   address: {
  //     street: 'Commercial Street',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9876560035', email: 'anandsweets@example.com' },
  //   cuisine_type: ['Indian-Sweets', 'Desserts', 'Street-Food', 'Fast-Food', 'Indian'],
  //   rating: 4.5,
  //   numberOfReviews: 6800,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Onesta',
  //   description: 'Known for its unlimited pizza and dessert offers, popular among students.',
  //   address: {
  //     street: 'CMH Road, Indiranagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.058, baseLat + 0.011],
  //     },
  //   },
  //   contact: { phone: '9876560036', email: 'onesta.blr@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Desserts', 'Beverages'],
  //   rating: 4.0,
  //   numberOfReviews: 8100,
  //   opening_hours: [{ day: 'Tuesday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'U.B. City',
  //   description: 'A luxury dining destination with multiple high-end restaurants and bars.',
  //   address: {
  //     street: 'Vittal Mallya Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon, baseLat - 0.011],
  //     },
  //   },
  //   contact: { phone: '9876560037', email: 'ubcity@example.com' },
  //   cuisine_type: ['Dinner', 'Italian', 'Japanese', 'Mexican', 'North-Indian', 'Beverages'],
  //   rating: 4.6,
  //   numberOfReviews: 5000,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 1000,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 3000,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Suryawanshi',
  //   description: 'Authentic Maharashtrian cuisine, from coastal delicacies to spicy Kolhapuri dishes.',
  //   address: {
  //     street: 'Whitefield Main Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560066',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.16, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9876560038', email: 'suryawanshi@example.com' },
  //   cuisine_type: ['Indian', 'South-Indian', 'North-Indian', 'Dinner', 'Lunch'],
  //   rating: 4.3,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'JustBe Cafe',
  //   description: 'A whole-food, plant-based cafe promoting healthy and mindful eating.',
  //   address: {
  //     street: 'Sadashivanagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560080',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9876560039', email: 'justbe@example.com' },
  //   cuisine_type: ['Vegan', 'Healthy', 'Salads', 'Soups', 'Desserts', 'Beverages'],
  //   rating: 4.7,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Smally\'s Resto Cafe',
  //   description: 'Known for its cozy ambiance and delicious, value-for-money burgers and shakes.',
  //   address: {
  //     street: 'Church Street',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.017, baseLat - 0.007],
  //     },
  //   },
  //   contact: { phone: '9876560040', email: 'smallys@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Beverages', 'Desserts', 'Sandwiches'],
  //   rating: 4.2,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 38,
  // },
  // seeded till here ;
  // // --- Restaurants 41-50 ---
  // {
  //   name: 'The Bangalore Pantry',
  //   description: 'A cloud kitchen specializing in gourmet sandwiches and fresh salads.',
  //   address: {
  //     street: 'Cloud Kitchen, Indiranagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.068, baseLat + 0.008],
  //     },
  //   },
  //   contact: { phone: '9876560041', email: 'pantry.blr@example.com' },
  //   cuisine_type: ['Sandwiches', 'Salads', 'Healthy', 'Beverages', 'Breakfast'],
  //   rating: 4.4,
  //   numberOfReviews: 850,
  //   opening_hours: [{ day: 'Sunday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Lazy Suzy',
  //   description: 'A charming cafe known for its exquisite desserts, pastries, and savory bites.',
  //   address: {
  //     street: '80 Feet Road, Indiranagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.055, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9876560042', email: 'lazysuzy@example.com' },
  //   cuisine_type: ['Desserts', 'Italian', 'Sandwiches', 'Beverages', 'Breakfast'],
  //   rating: 4.3,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Oota',
  //   description: 'A restaurant dedicated to showcasing the diverse cuisines of Karnataka.',
  //   address: {
  //     street: 'Whitefield Main Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560066',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.155, baseLat + 0.018],
  //     },
  //   },
  //   contact: { phone: '9876560043', email: 'oota.blr@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'Healthy'],
  //   rating: 4.5,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Tuesday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Communiti',
  //   description: 'A pet-friendly microbrewery with a large outdoor space and varied food menu.',
  //   address: {
  //     street: 'Residency Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560025',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.021, baseLat - 0.011],
  //     },
  //   },
  //   contact: { phone: '9876560044', email: 'communiti.blr@example.com' },
  //   cuisine_type: ['Beverages', 'Pizza', 'Burgers', 'Fast-Food', 'Dinner', 'BBQ'],
  //   rating: 4.2,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Wednesday', open: '11:30', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1700,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'K.C. Das',
  //   description: 'A legendary sweet shop from Kolkata, famous for its Rosogolla and Sandesh.',
  //   address: {
  //     street: 'St. Marks Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.011, baseLat - 0.001],
  //     },
  //   },
  //   contact: { phone: '9876560045', email: 'kcdas.blr@example.com' },
  //   cuisine_type: ['Indian-Sweets', 'Desserts', 'Street-Food', 'Breakfast'],
  //   rating: 4.4,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Thursday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Permit Room',
  //   description: 'A quirky bar and restaurant offering a modern take on South Indian food and cocktails.',
  //   address: {
  //     street: 'Magrath Road, Ashok Nagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560025',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.029, baseLat - 0.009],
  //     },
  //   },
  //   contact: { phone: '9876560046', email: 'permitroom@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Beverages', 'Dinner', 'Fast-Food'],
  //   rating: 4.3,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'EatFit',
  //   description: 'A popular cloud kitchen for healthy, calorie-counted meals, thalis, and bowls.',
  //   address: {
  //     street: 'Cloud Kitchen, HSR Layout',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560102',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.082, baseLat - 0.062],
  //     },
  //   },
  //   contact: { phone: '9876560047', email: 'eatfit.blr@example.com' },
  //   cuisine_type: ['Healthy', 'Indian', 'Salads', 'Soups', 'Lunch', 'Dinner'],
  //   rating: 4.4,
  //   numberOfReviews: 9800,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Smoor',
  //   description: 'A luxury chocolate brand with cafes offering exquisite desserts, cakes, and coffee.',
  //   address: {
  //     street: '100 Feet Road, Indiranagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.061, baseLat + 0.011],
  //     },
  //   },
  //   contact: { phone: '9876560048', email: 'smoor.blr@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Italian', 'Fast-Food'],
  //   rating: 4.5,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Sunday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Barbeque Nation',
  //   description: 'The original live-on-the-table grill restaurant with a lavish buffet.',
  //   address: {
  //     street: 'Koramangala 1st Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.041, baseLat - 0.031],
  //     },
  //   },
  //   contact: { phone: '9876560049', email: 'bbqnation.blr@example.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Indian', 'Dinner', 'Lunch', 'Desserts'],
  //   rating: 4.6,
  //   numberOfReviews: 11000,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Chai Point',
  //   description: 'A leading chain for tea, offering a variety of chai and snacks.',
  //   address: {
  //     street: 'Multiple Locations',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.005, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9876560050', email: 'chaipoint@example.com' },
  //   cuisine_type: ['Beverages', 'Breakfast', 'Street-Food', 'Fast-Food'],
  //   rating: 4.1,
  //   numberOfReviews: 8500,
  //   opening_hours: [{ day: 'Tuesday', open: '07:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 25,
  // },
  // // --- Restaurants 51-60 ---
  // {
  //   name: 'The Asian Curry House',
  //   description: 'A fine dining experience with a curated menu of Asian curries.',
  //   address: {
  //     street: 'Jayanagar 4th Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.008, baseLat - 0.048],
  //     },
  //   },
  //   contact: { phone: '9876560051', email: 'asiancurry@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Soups', 'Dinner', 'Lunch'],
  //   rating: 4.4,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Glen\'s Bakehouse',
  //   description: 'A charming bakery and cafe famous for its red velvet cupcakes and relaxed ambiance.',
  //   address: {
  //     street: 'Lavelle Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.007, baseLat - 0.007],
  //     },
  //   },
  //   contact: { phone: '9876560052', email: 'glens@example.com' },
  //   cuisine_type: ['Desserts', 'Breakfast', 'Italian', 'Pizza', 'Beverages'],
  //   rating: 4.5,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Thursday', open: '09:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Brahma\'s',
  //   description: 'A local favorite for traditional South Indian vegetarian meals and tiffins.',
  //   address: {
  //     street: 'Basavanagudi',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.022, baseLat - 0.032],
  //     },
  //   },
  //   contact: { phone: '9876560053', email: 'brahmas@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Breakfast', 'Lunch'],
  //   rating: 4.3,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Friday', open: '07:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Sly Granny',
  //   description: 'A quirky, eclectic restaurant with a global menu and creative cocktails.',
  //   address: {
  //     street: '12th Main, Indiranagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.066, baseLat + 0.011],
  //     },
  //   },
  //   contact: { phone: '9876560054', email: 'slygranny@example.com' },
  //   cuisine_type: ['Italian', 'Mexican', 'North-Indian', 'Dinner', 'Beverages'],
  //   rating: 4.4,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Kanti Sweets',
  //   description: 'A major sweet and savoury chain in Bangalore, offering a wide variety of treats.',
  //   address: {
  //     street: 'Malleshwaram',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.029, baseLat + 0.023],
  //     },
  //   },
  //   contact: { phone: '9876560055', email: 'kantisweets@example.com' },
  //   cuisine_type: ['Indian-Sweets', 'Desserts', 'Street-Food', 'Fast-Food'],
  //   rating: 4.3,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Sunday', open: '08:30', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The London Curry House',
  //   description: 'A vegetarian restaurant offering a fusion of Indian and British culinary styles.',
  //   address: {
  //     street: 'Race Course Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9876560056', email: 'londoncurry@example.com' },
  //   cuisine_type: ['North-Indian', 'Italian', 'Mexican', 'Dinner', 'Vegan'],
  //   rating: 4.2,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Asha Tiffins',
  //   description: 'A no-frills, quick-service restaurant for delicious and affordable South Indian food.',
  //   address: {
  //     street: 'HSR Layout, Sector 1',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560102',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.078, baseLat - 0.058],
  //     },
  //   },
  //   contact: { phone: '9876560057', email: 'ashatiffins@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Street-Food', 'Indian'],
  //   rating: 4.5,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Tuesday', open: '07:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 60,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 150,
  //   delivery_time_mins: 22,
  // },
  // {
  //   name: '1522 - The Pub',
  //   description: 'A popular pub with a rock music theme, serving a multi-cuisine menu and drinks.',
  //   address: {
  //     street: 'Malleshwaram',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '9876560058', email: '1522pub@example.com' },
  //   cuisine_type: ['North-Indian', 'Chinese', 'Fast-Food', 'Dinner', 'Beverages'],
  //   rating: 4.3,
  //   numberOfReviews: 3900,
  //   opening_hours: [{ day: 'Wednesday', open: '11:30', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1300,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Art of Delight',
  //   description: 'A dedicated dessert parlor known for its sundaes, waffles, and cheesecakes.',
  //   address: {
  //     street: 'Residency Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560025',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.024, baseLat - 0.014],
  //     },
  //   },
  //   contact: { phone: '9876560059', email: 'artofdelight@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Indian-Sweets', 'Fast-Food'],
  //   rating: 4.6,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Black Pearl',
  //   description: 'A pirate-themed restaurant offering a massive buffet with live grills.',
  //   address: {
  //     street: 'Koramangala 5th Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560095',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.033, baseLat - 0.043],
  //     },
  //   },
  //   contact: { phone: '9876560060', email: 'blackpearl@example.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Dinner', 'Lunch', 'Desserts', 'Salads'],
  //   rating: 4.1,
  //   numberOfReviews: 5200,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 50,
  // },
  // seeded till here :
  // // --- Restaurants 61-75 ---
  // {
  //   name: 'Soup Station',
  //   description: 'A healthy-eating spot focused on a wide variety of soups and salads.',
  //   address: {
  //     street: 'Indiranagar',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.069, baseLat + 0.009],
  //     },
  //   },
  //   contact: { phone: '9876560061', email: 'soupstation.blr@example.com' },
  //   cuisine_type: ['Soups', 'Salads', 'Healthy', 'Vegan', 'Lunch'],
  //   rating: 4.3,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Al-Bek',
  //   description: 'A budget-friendly place famous for its shawarma rolls and grilled chicken.',
  //   address: {
  //     street: 'Malleshwaram',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.027, baseLat + 0.027],
  //     },
  //   },
  //   contact: { phone: '9876560062', email: 'albek.blr@example.com' },
  //   cuisine_type: ['Fast-Food', 'BBQ', 'North-Indian', 'Dinner', 'Street-Food'],
  //   rating: 3.9,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Beijing Bites',
  //   description: 'A popular chain for affordable and tasty Indo-Chinese food.',
  //   address: {
  //     street: 'Marathahalli',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560037',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.12, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876560063', email: 'beijingbites@example.com' },
  //   cuisine_type: ['Chinese', 'Fast-Food', 'Soups', 'Lunch', 'Dinner'],
  //   rating: 3.8,
  //   numberOfReviews: 6200,
  //   opening_hours: [{ day: 'Monday', open: '11:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'California Burrito',
  //   description: 'A quick-service chain for build-your-own Mexican burritos, bowls, and tacos.',
  //   address: {
  //     street: 'Manyata Tech Park',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560045',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat + 0.08],
  //     },
  //   },
  //   contact: { phone: '9876560064', email: 'calburrito.blr@example.com' },
  //   cuisine_type: ['Mexican', 'Healthy', 'Salads', 'Fast-Food', 'Lunch'],
  //   rating: 4.2,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Tuesday', open: '10:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Lakeview Milk Bar',
  //   description: 'One of Bangalore\'s oldest ice cream parlors, serving classic sundaes and sandwiches.',
  //   address: {
  //     street: 'MG Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.019, baseLat - 0.009],
  //     },
  //   },
  //   contact: { phone: '9876560065', email: 'lakeview@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Sandwiches', 'Fast-Food'],
  //   rating: 4.1,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Wednesday', open: '10:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 450,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Pasta Street',
  //   description: 'A casual dining restaurant specializing in a variety of pastas and Italian dishes.',
  //   address: {
  //     street: 'Koramangala 5th Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560095',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.031, baseLat - 0.041],
  //     },
  //   },
  //   contact: { phone: '9876560066', email: 'pastastreet@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Salads', 'Soups', 'Dinner'],
  //   rating: 4.0,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'A2B - Adyar Ananda Bhavan',
  //   description: 'A massive chain serving a wide range of South Indian, North Indian, and Chinese vegetarian food.',
  //   address: {
  //     street: 'BTM Layout',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560076',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.045, baseLat - 0.055],
  //     },
  //   },
  //   contact: { phone: '9876560067', email: 'a2b.blr@example.com' },
  //   cuisine_type: ['South-Indian', 'North-Indian', 'Chinese', 'Indian-Sweets', 'Breakfast', 'Lunch'],
  //   rating: 4.2,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Friday', open: '07:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Imperial Restaurant (Imp-e-rial)',
  //   description: 'A no-frills restaurant famous for its Donne Biryani and non-veg meals.',
  //   address: {
  //     street: 'Residency Road',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560025',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.026, baseLat - 0.016],
  //     },
  //   },
  //   contact: { phone: '9876560068', email: 'imperial.blr@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'North-Indian', 'Dinner', 'Lunch'],
  //   rating: 4.1,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Yauatcha',
  //   description: 'A high-end London-based dim sum teahouse with a modern touch.',
  //   address: {
  //     street: '1 MG Road Mall',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560008',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat + 0.002],
  //     },
  //   },
  //   contact: { phone: '9876560069', email: 'yauatcha.blr@example.com' },
  //   cuisine_type: ['Chinese', 'Desserts', 'Dinner', 'Soups', 'Beverages'],
  //   rating: 4.6,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 1200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 3000,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Thalassery Restaurant',
  //   description: 'Authentic Kerala and Malabar cuisine, especially known for its seafood.',
  //   address: {
  //     street: 'Marathahalli',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560037',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.125, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9876560070', email: 'thalassery.blr@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ'],
  //   rating: 4.2,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Monday', open: '11:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'TBC Sky Lounge',
  //   description: 'A rooftop lounge with great views, music, and a multi-cuisine menu.',
  //   address: {
  //     street: 'HSR Layout',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560102',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.085, baseLat - 0.065],
  //     },
  //   },
  //   contact: { phone: '9876560071', email: 'tbcsky@example.com' },
  //   cuisine_type: ['North-Indian', 'Italian', 'Chinese', 'Dinner', 'Beverages'],
  //   rating: 4.0,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Tuesday', open: '17:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Sri Udupi Park',
  //   description: 'A classic vegetarian restaurant chain for quick and tasty South Indian food.',
  //   address: {
  //     street: 'Jayanagar 4th Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.007, baseLat - 0.047],
  //     },
  //   },
  //   contact: { phone: '9876560072', email: 'udupipark@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Lunch', 'Indian', 'Beverages'],
  //   rating: 4.1,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Wednesday', open: '07:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Globe Grub',
  //   description: 'A restaurant offering a large global cuisine buffet.',
  //   address: {
  //     street: 'Marathahalli',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560037',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.122, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9876560073', email: 'globegrub@example.com' },
  //   cuisine_type: ['North-Indian', 'Italian', 'Mexican', 'Chinese', 'Dinner', 'Lunch'],
  //   rating: 3.9,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Fresh Pressery Cafe',
  //   description: 'A health cafe known for its cold-pressed juices, salads, and healthy bowls.',
  //   address: {
  //     street: 'Koramangala 4th Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.036, baseLat - 0.036],
  //     },
  //   },
  //   contact: { phone: '9876560074', email: 'pressery@example.com' },
  //   cuisine_type: ['Healthy', 'Beverages', 'Salads', 'Breakfast', 'Vegan'],
  //   rating: 4.3,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Friday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Mangii Ferra',
  //   description: 'A romantic Italian restaurant with a cozy ambiance and wood-fired pizzas.',
  //   address: {
  //     street: 'Koramangala 5th Block',
  //     city: 'Bangalore',
  //     state: 'Karnataka',
  //     zip_code: '560095',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.034, baseLat - 0.044],
  //     },
  //   },
  //   contact: { phone: '9876560075', email: 'mangiiferra@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Dinner', 'Desserts', 'Beverages'],
  //   rating: 4.1,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 50,
  // },
];

export default bangaloreRestaurants;
