const baseLat = 23.2599;
const baseLon = 77.4126;

const bhopalRestaurants = [
  // --- Restaurants 1-20 ---
  {
    name: 'Bapu Ki Kutia',
    description: 'Simple, homely, and delicious vegetarian Indian meals.',
    address: {
      street: '7 TT Nagar',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.015, baseLat + 0.005],
      },
    },
    contact: { phone: '9876510003', email: 'bapukikutia@example.com' },
    cuisine_type: [
      'Indian',
      'North-Indian',
      'Healthy',
      'Lunch',
      'Dinner',
      'Vegan',
    ],
    rating: 4.4,
    numberOfReviews: 2200,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 300,
    delivery_time_mins: 25,
  },
  {
    name: 'Hakeem’s Restaurant',
    description: 'A legendary spot in Bhopal for authentic Mughlai cuisine.',
    address: {
      street: '51, Hamidia Road',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.009, baseLat - 0.011],
      },
    },
    contact: { phone: '9876510004', email: 'hakeems@example.com' },
    cuisine_type: ['North-Indian', 'Indian', 'BBQ', 'Dinner', 'Lunch'],
    rating: 4.5,
    numberOfReviews: 3200,
    opening_hours: [{ day: 'Monday', open: '12:00', close: '00:00' }],
    is_active: true,
    min_order_value: 350,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 900,
    delivery_time_mins: 40,
  },
  {
    name: 'Pind Balluchi',
    description:
      'A village-themed restaurant offering a rustic Punjabi dining experience.',
    address: {
      street: 'DB City Mall, Arera Hills',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462011',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.04, baseLat + 0.02],
      },
    },
    contact: { phone: '9876510005', email: 'pindballuchi.bpl@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'BBQ',
      'Dinner',
      'Lunch',
      'Beverages',
    ],
    rating: 4.3,
    numberOfReviews: 2800,
    opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 1200,
    delivery_time_mins: 45,
  },
  {
    name: 'Biryani By Kilo',
    description: 'Authentic biryani cooked in traditional handis.',
    address: {
      street: 'MP Nagar Zone II',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462011',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.038, baseLat - 0.012],
      },
    },
    contact: { phone: '9876510024', email: 'bbk.bpl@example.com' },
    cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch', 'BBQ'],
    rating: 4.5,
    numberOfReviews: 1500,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 800,
    delivery_time_mins: 50,
  },
  {
    name: 'Indian Coffee House',
    description:
      'A classic spot with old-world charm, serving South Indian staples and coffee.',
    address: {
      street: '1, New Market',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.01, baseLat - 0.005],
      },
    },
    contact: { phone: '9876510006', email: 'ich.bhopal@example.com' },
    cuisine_type: [
      'South-Indian',
      'Indian',
      'Breakfast',
      'Lunch',
      'Beverages',
      'Fast-Food',
    ],
    rating: 4.3,
    numberOfReviews: 3500,
    opening_hours: [{ day: 'Monday', open: '09:00', close: '22:00' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 250,
    delivery_time_mins: 28,
  },
  {
    name: 'Sankalp Restaurant',
    description:
      'Famous for its incredibly long dosas and authentic South Indian flavors.',
    address: {
      street: 'DB City Mall, MP Nagar',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462011',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.042, baseLat + 0.021],
      },
    },
    contact: { phone: '9876510007', email: 'sankalp.bpl@example.com' },
    cuisine_type: [
      'South-Indian',
      'Indian',
      'Dinner',
      'Lunch',
      'Vegan',
      'Breakfast',
    ],
    rating: 4.5,
    numberOfReviews: 1900,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 700,
    delivery_time_mins: 35,
  },
  {
    name: 'Anna Ka Dosa',
    description: 'A popular spot for quick, delicious, and affordable dosas.',
    address: {
      street: '10 No. Market, Arera Colony',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462016',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.05, baseLat + 0.03],
      },
    },
    contact: { phone: '9876510008', email: 'annakadosa@example.com' },
    cuisine_type: [
      'South-Indian',
      'Indian',
      'Street-Food',
      'Breakfast',
      'Lunch',
    ],
    rating: 4.2,
    numberOfReviews: 1500,
    opening_hours: [{ day: 'Monday', open: '08:00', close: '22:00' }],
    is_active: true,
    min_order_value: 80,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 200,
    delivery_time_mins: 22,
  },
  {
    name: 'Kerala Cafe',
    description: 'Authentic flavors from the coast of Kerala.',
    address: {
      street: 'Kolar Road',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462042',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.08, baseLat - 0.09],
      },
    },
    contact: { phone: '9876510022', email: 'keralacafe.bpl@example.com' },
    cuisine_type: [
      'South-Indian',
      'Indian',
      'Dinner',
      'Lunch',
      'Breakfast',
      'Healthy',
    ],
    rating: 4.5,
    numberOfReviews: 850,
    opening_hours: [{ day: 'Monday', open: '09:00', close: '22:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 600,
    delivery_time_mins: 35,
  },
  {
    name: 'Sharma & Vishnu Fast Food',
    description:
      'A legendary street food joint known for its sandwiches and fast food.',
    address: {
      street: 'New Market, TT Nagar',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.012, baseLat - 0.007],
      },
    },
    contact: { phone: '9876510009', email: 'sharmavishnu@example.com' },
    cuisine_type: [
      'Street-Food',
      'Fast-Food',
      'Sandwiches',
      'Indian',
      'Lunch',
      'Beverages',
    ],
    rating: 4.8,
    numberOfReviews: 5500,
    opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 250,
    delivery_time_mins: 20,
  },
  {
    name: 'Jodhpur Sweets',
    description: 'Famous for its Mawa Bati, Kachoris, and other Indian sweets.',
    address: {
      street: 'Hamidia Road',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.015, baseLat - 0.012],
      },
    },
    contact: { phone: '9876510010', email: 'jodhpursweets@example.com' },
    cuisine_type: [
      'Indian-Sweets',
      'Desserts',
      'Street-Food',
      'Breakfast',
      'Indian',
    ],
    rating: 4.6,
    numberOfReviews: 2100,
    opening_hours: [{ day: 'Monday', open: '08:00', close: '22:00' }],
    is_active: true,
    min_order_value: 50,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 150,
    delivery_time_mins: 18,
  },

  // {
  //   name: 'Sagar Gaire Fast Food',
  //   description: 'A go-to spot for college students for fast food and shakes.',
  //   address: {
  //     street: 'MP Nagar Zone-II',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.035, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9876510011', email: 'sagargaire@example.com' },
  //   cuisine_type: [
  //     'Fast-Food',
  //     'Burgers',
  //     'Sandwiches',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'The Kathi Roll Express',
  //   description: 'Delicious and filling kathi rolls with various stuffings.',
  //   address: {
  //     street: '10 No. Market',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.052, baseLat + 0.031],
  //     },
  //   },
  //   contact: { phone: '9876510020', email: 'kathiroll.bpl@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Fast-Food',
  //     'Indian',
  //     'North-Indian',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Bengali Sweet House',
  //   description: 'Authentic Bengali sweets like Rasgulla and Sandesh.',
  //   address: {
  //     street: 'Indrapuri',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462022',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.065, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9876510025', email: 'bengalisweets@example.com' },
  //   cuisine_type: [
  //     'Indian-Sweets',
  //     'Desserts',
  //     'Street-Food',
  //     'Indian',
  //     'Breakfast',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Bake N Shake',
  //   description: 'Trendy cafe for shakes, pastries, burgers, and quick bites.',
  //   address: {
  //     street: 'Arera Colony, E-3',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat + 0.035],
  //     },
  //   },
  //   contact: { phone: '9876510012', email: 'bakenshake@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Beverages',
  //     'Fast-Food',
  //     'Burgers',
  //     'Sandwiches',
  //     'Breakfast',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 32,
  // },
  // {
  //   name: 'The Chocolate Room',
  //   description: 'A paradise for chocolate lovers with a variety of desserts.',
  //   address: {
  //     street: 'Aura Mall, Gulmohar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462039',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat + 0.055],
  //     },
  //   },
  //   contact: { phone: '9876510013', email: 'chocolateroom.bpl@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Beverages',
  //     'Breakfast',
  //     'Fast-Food',
  //     'Italian',
  //     'Sandwiches',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Breakfast Story',
  //   description: 'All-day breakfast with English and American classics.',
  //   address: {
  //     street: 'Arera Colony E-5',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.048, baseLat + 0.028],
  //     },
  //   },
  //   contact: { phone: '9876510026', email: 'breakfaststory@example.com' },
  //   cuisine_type: [
  //     'Breakfast',
  //     'Healthy',
  //     'Beverages',
  //     'Sandwiches',
  //     'Desserts',
  //     'Salads',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '16:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Chicago Pizza',
  //   description: 'Serving authentic deep-dish Chicago-style pizzas.',
  //   address: {
  //     street: 'DB City Mall, Food Court',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.041, baseLat + 0.022],
  //     },
  //   },
  //   contact: { phone: '9876510014', email: 'chicagopizza.bpl@example.com' },
  //   cuisine_type: [
  //     'Pizza',
  //     'Italian',
  //     'Fast-Food',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Burger King',
  //   description: 'Global fast-food chain known for its flame-grilled burgers.',
  //   address: {
  //     street: 'Aashima Mall, Hoshangabad Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462026',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.05, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9876510015', email: 'bk.bhopal@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //     'Desserts',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Monday', open: '10:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: "La Pino'z Pizza",
  //   description: 'Famous for giant pizza slices and a wide range of toppings.',
  //   address: {
  //     street: 'MP Nagar Zone-I',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.031, baseLat - 0.019],
  //     },
  //   },
  //   contact: { phone: '9876510027', email: 'lapinoz.bpl@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Beverages', 'Dinner'],
  //   rating: 4.4,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 33,
  // },
  // {
  //   name: 'Wat-a-Burger',
  //   description: 'Indian burger chain with a fusion of local flavors.',
  //   address: {
  //     street: 'Kolar Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462042',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.075, baseLat - 0.085],
  //     },
  //   },
  //   contact: { phone: '9876510028', email: 'wataburger.bpl@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //     'Indian',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 300,
  //   delivery_time_mins: 28,
  // },
  // // --- Restaurants 21-40 ---
  // {
  //   name: 'Wok On Fire',
  //   description: 'Sizzling woks with customizable Chinese and Thai flavors.',
  //   address: {
  //     street: 'Indrapuri, Sector C',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462022',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.06, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9876510016', email: 'wokonfire@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Japanese',
  //     'Soups',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 750,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Kyoto - The Japanese Kitchen',
  //   description: 'Authentic sushi, sashimi, and Japanese main courses.',
  //   address: {
  //     street: 'Shyamla Hills',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9876510017', email: 'kyoto.bpl@example.com' },
  //   cuisine_type: [
  //     'Japanese',
  //     'Sushi',
  //     'Soups',
  //     'Healthy',
  //     'Dinner',
  //     'Lunch',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Monday', open: '13:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'The Momo Factory',
  //   description: 'A huge variety of steamed, fried, and tandoori momos.',
  //   address: {
  //     street: 'MP Nagar Zone I',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.033, baseLat - 0.018],
  //     },
  //   },
  //   contact: { phone: '9876510023', email: 'momofactory.bpl@example.com' },
  //   cuisine_type: ['Chinese', 'Fast-Food', 'Soups', 'Dinner', 'Lunch'],
  //   rating: 4.2,
  //   numberOfReviews: 1400,
  //   opening_hours: [{ day: 'Monday', open: '13:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Yo! China',
  //   description: 'A popular chain for casual Chinese dining.',
  //   address: {
  //     street: 'DB City Mall',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.044, baseLat + 0.024],
  //     },
  //   },
  //   contact: { phone: '9876510029', email: 'yochina.bpl@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Japanese',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //     'Sushi',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 1600,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Greenr Cafe',
  //   description:
  //     'A plant-based cafe serving innovative and delicious vegan food.',
  //   address: {
  //     street: 'Arera Colony, E-7',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.045, baseLat + 0.038],
  //     },
  //   },
  //   contact: { phone: '9876510018', email: 'greenr.bpl@example.com' },
  //   cuisine_type: [
  //     'Vegan',
  //     'Healthy',
  //     'Salads',
  //     'Soups',
  //     'Breakfast',
  //     'Lunch',
  //     'Beverages',
  //   ],
  //   rating: 4.8,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: "Chili's American Grill & Bar",
  //   description: 'Classic American Tex-Mex, burgers, and sizzling fajitas.',
  //   address: {
  //     street: 'DB City Mall',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.043, baseLat + 0.023],
  //     },
  //   },
  //   contact: { phone: '9876510019', email: 'chilis.bpl@example.com' },
  //   cuisine_type: [
  //     'Mexican',
  //     'Burgers',
  //     'Salads',
  //     'Dinner',
  //     'Lunch',
  //     'Beverages',
  //     'BBQ',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Little Italy',
  //   description:
  //     'Authentic and fine-dining vegetarian Italian & Mexican cuisine.',
  //   address: {
  //     street: 'Shyamla Hills',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.032, baseLat + 0.022],
  //     },
  //   },
  //   contact: { phone: '9876510021', email: 'littleitaly.bpl@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Pizza',
  //     'Mexican',
  //     'Vegan',
  //     'Salads',
  //     'Dinner',
  //     'Lunch',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 1700,
  //   opening_hours: [{ day: 'Monday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'The Salad Story',
  //   description: 'Create your own fresh and healthy salads and bowls.',
  //   address: {
  //     street: 'Lalghati',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462030',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.06, baseLat + 0.05],
  //     },
  //   },
  //   contact: { phone: '9876510030', email: 'saladstory.bpl@example.com' },
  //   cuisine_type: [
  //     'Salads',
  //     'Healthy',
  //     'Vegan',
  //     'Soups',
  //     'Lunch',
  //     'Beverages',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 700,
  //   opening_hours: [{ day: 'Monday', open: '10:30', close: '21:30' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Barbeque Nation',
  //   description:
  //     'Casual dining chain specializing in live grills and BBQ buffets.',
  //   address: {
  //     street: 'Maharana Pratap Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9876500007', email: 'bbqnationbhopal@example.com' },
  //   cuisine_type: [
  //     'BBQ',
  //     'Dinner',
  //     'Indian',
  //     'North-Indian',
  //     'Lunch',
  //     'Salads',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'California Burrito',
  //   description: 'Freshly made burritos and bowls with a healthy twist.',
  //   address: {
  //     street: 'Aura Mall',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462039',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.022, baseLat + 0.052],
  //     },
  //   },
  //   contact: { phone: '9876510031', email: 'calburrito.bpl@example.com' },
  //   cuisine_type: [
  //     'Mexican',
  //     'Fast-Food',
  //     'Healthy',
  //     'Lunch',
  //     'Dinner',
  //     'Salads',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 850,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Shahnama - Jehan Numa Palace',
  //   description:
  //     'An opulent fine-dining experience with a focus on royal Indian cuisine.',
  //   address: {
  //     street: '157, Shyamla Hills',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462013',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.035, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9876510032', email: 'shahnama@jehannuma.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'North-Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Desserts',
  //     'BBQ',
  //   ],
  //   rating: 4.9,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Rolls Mania',
  //   description:
  //     'A popular chain for delicious and affordable wraps and rolls.',
  //   address: {
  //     street: 'MP Nagar, Zone II',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.033, baseLat - 0.014],
  //     },
  //   },
  //   contact: { phone: '9876510033', email: 'rollsmania.bpl@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Fast-Food',
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Sandwiches',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 250,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Top N Town',
  //   description:
  //     "Bhopal's favorite ice cream parlor with a wide range of flavors.",
  //   address: {
  //     street: 'New Market',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.014, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9876510034', email: 'topntown@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Indian-Sweets'],
  //   rating: 4.6,
  //   numberOfReviews: 3000,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Mocha Cafe & Bar',
  //   description:
  //     'A chic cafe with a global menu, coffee, and vibrant ambiance.',
  //   address: {
  //     street: 'Aashima Mall',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462026',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.052, baseLat - 0.042],
  //     },
  //   },
  //   contact: { phone: '9876510035', email: 'mocha.bpl@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Mexican',
  //     'Desserts',
  //     'Beverages',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 1600,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Behrouz Biryani',
  //   description: 'Royal biryanis delivered with a premium experience.',
  //   address: {
  //     street: 'Arera Colony',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.042, baseLat + 0.033],
  //     },
  //   },
  //   contact: { phone: '9876510036', email: 'behrouz.bpl@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch', 'Desserts'],
  //   rating: 4.4,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 450,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Subway',
  //   description: 'Customizable submarine sandwiches and salads.',
  //   address: {
  //     street: 'MP Nagar, Zone I',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat - 0.017],
  //     },
  //   },
  //   contact: { phone: '9876510037', email: 'subway.mpnagar@example.com' },
  //   cuisine_type: [
  //     'Sandwiches',
  //     'Salads',
  //     'Healthy',
  //     'Fast-Food',
  //     'Breakfast',
  //     'Lunch',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Manohar Dairy & Restaurant',
  //   description:
  //     'A legendary destination in Bhopal for sweets, snacks, and full-course vegetarian meals.',
  //   address: {
  //     street: '6, Hamidia Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.008, baseLat - 0.013],
  //     },
  //   },
  //   contact: { phone: '9876510038', email: 'manohar@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'North-Indian',
  //     'South-Indian',
  //     'Street-Food',
  //     'Indian-Sweets',
  //     'Desserts',
  //     'Breakfast',
  //     'Lunch',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 8500,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: "Domino's Pizza",
  //   description:
  //     'Well-known chain for a wide range of pizzas and a variety of other dishes & sides.',
  //   address: {
  //     street: 'Kolar Road, Danish Kunj',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462042',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.078, baseLat - 0.088],
  //     },
  //   },
  //   contact: { phone: '9876510039', email: 'dominos.kolar@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Desserts', 'Beverages'],
  //   rating: 4.0,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Good Bowl',
  //   description:
  //     'Serving wholesome and delicious bowls that are a fusion of global and Indian flavors.',
  //   address: {
  //     street: 'Saket Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462024',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.045, baseLat - 0.035],
  //     },
  //   },
  //   contact: { phone: '9876510040', email: 'goodbowl.bpl@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Salads',
  //     'North-Indian',
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 750,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 32,
  // },
  // {
  //   name: 'Faasos - Wraps & Rolls',
  //   description:
  //     'A leading name in wraps, serving a variety of exciting flavors.',
  //   address: {
  //     street: 'Ayodhya Bypass Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462041',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.09, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9876510041', email: 'faasos.bpl@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Fast-Food',
  //     'North-Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Sandwiches',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 1150,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 350,
  //   delivery_time_mins: 28,
  // },
  // // --- Restaurants 41-60 ---
  // {
  //   name: 'Ovenstory Pizza',
  //   description: 'Pizzas with exciting toppings and a standout cheese base.',
  //   address: {
  //     street: 'Gulmohar Colony',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462039',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.028, baseLat + 0.058],
  //     },
  //   },
  //   contact: { phone: '9876510042', email: 'ovenstory.bpl@example.com' },
  //   cuisine_type: [
  //     'Pizza',
  //     'Italian',
  //     'Fast-Food',
  //     'Dinner',
  //     'Beverages',
  //     'Desserts',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 980,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 42,
  // },
  // {
  //   name: 'Zam Zam Fast Food',
  //   description:
  //     'A local favorite in Old Bhopal for delicious Mughlai and BBQ dishes.',
  //   address: {
  //     street: 'Chowk Bazaar, Old Bhopal',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.005, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9876510043', email: 'zamzam.bpl@example.com' },
  //   cuisine_type: ['North-Indian', 'BBQ', 'Indian', 'Dinner', 'Lunch'],
  //   rating: 3.9,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Monday', open: '17:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Belgian Waffle Co.',
  //   description:
  //     'Specialty waffle shop serving freshly baked waffles with a variety of toppings.',
  //   address: {
  //     street: 'MP Nagar, Zone II',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.036, baseLat - 0.016],
  //     },
  //   },
  //   contact: { phone: '9876510044', email: 'belgianwaffle.bpl@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Breakfast', 'Fast-Food'],
  //   rating: 4.4,
  //   numberOfReviews: 1400,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Pizza Hut',
  //   description:
  //     'Global pizza chain serving a variety of pizzas, pastas, and sides.',
  //   address: {
  //     street: 'Indrapuri, Sector B',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462022',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.062, baseLat - 0.028],
  //     },
  //   },
  //   contact: { phone: '9876510045', email: 'pizzahut.bpl@example.com' },
  //   cuisine_type: [
  //     'Pizza',
  //     'Italian',
  //     'Fast-Food',
  //     'Salads',
  //     'Desserts',
  //     'Beverages',
  //   ],
  //   rating: 3.8,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 650,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Burger Singh - Big Punjabi Burgers',
  //   description:
  //     'Indian burger chain with a fusion of Indian spices and classic burgers.',
  //   address: {
  //     street: 'MP Nagar, Zone I',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.032, baseLat - 0.018],
  //     },
  //   },
  //   contact: { phone: '9876510046', email: 'burgersingh.bpl@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'North-Indian',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 1950,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: "McDonald's",
  //   description:
  //     'The iconic global fast-food chain for burgers, fries, and shakes.',
  //   address: {
  //     street: 'DB City Mall, Lower Ground Floor',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat + 0.021],
  //     },
  //   },
  //   contact: { phone: '9876510047', email: 'mcd.dbcity@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Desserts',
  //     'Beverages',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 3300,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 33,
  // },
  // {
  //   name: 'KFC',
  //   description:
  //     "Famous for its fried chicken, a global chain with a signature secret recipe.",
  //   address: {
  //     street: 'Hoshangabad Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462026',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.051, baseLat - 0.041],
  //     },
  //   },
  //   contact: { phone: '9876510048', email: 'kfc.hbpl@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'BBQ',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Tea Factory',
  //   description:
  //     'A cozy spot for tea lovers, offering a wide range of teas and snacks.',
  //   address: {
  //     street: 'Anand Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462021',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.07, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876510049', email: 'teafactory.bpl@example.com' },
  //   cuisine_type: [
  //     'Beverages',
  //     'Fast-Food',
  //     'Sandwiches',
  //     'Desserts',
  //     'Breakfast',
  //   ],
  //   rating: 3.7,
  //   numberOfReviews: 850,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Poha Center',
  //   description:
  //     "An iconic local spot serving Bhopal's signature breakfast - Poha Jalebi.",
  //   address: {
  //     street: 'Bairagarh Market',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462030',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.07, baseLat + 0.04],
  //     },
  //   },
  //   contact: { phone: '9876510050', email: 'pohacenter.bpl@example.com' },
  //   cuisine_type: ['Street-Food', 'Breakfast', 'Indian', 'Fast-Food'],
  //   rating: 4.6,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Monday', open: '06:00', close: '13:00' }],
  //   is_active: true,
  //   min_order_value: 50,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 100,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Al-Beik',
  //   description:
  //     'Famous for its broasted chicken and Arabian-style grilled dishes.',
  //   address: {
  //     street: 'Koh-e-Fiza',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.04],
  //     },
  //   },
  //   contact: { phone: '9876510051', email: 'albeik.bpl@example.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Fast-Food', 'Burgers', 'Dinner'],
  //   rating: 4.3,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Monday', open: '13:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'New Inn Restaurant',
  //   description:
  //     'A simple, budget-friendly restaurant with a multi-cuisine menu.',
  //   address: {
  //     street: 'Berasia Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat - 0.05],
  //     },
  //   },
  //   contact: { phone: '9876510052', email: 'newinn.bpl@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Chinese', 'Lunch', 'Dinner'],
  //   rating: 3.5,
  //   numberOfReviews: 600,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Rice Bowl',
  //   description:
  //     'A small eatery focusing on quick and affordable Chinese bowl meals.',
  //   address: {
  //     street: 'Shakti Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462024',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.048, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9876510053', email: 'ricebowl.bpl@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Soups', 'Lunch', 'Dinner'],
  //   rating: 3.2,
  //   numberOfReviews: 450,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 350,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Pasta House',
  //   description:
  //     'A restaurant with a wide pasta menu that often struggles with consistency.',
  //   address: {
  //     street: 'Awadhpuri',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462022',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.08, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9876510054', email: 'pastahouse.bpl@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Pizza',
  //     'Salads',
  //     'Desserts',
  //     'Beverages',
  //     'Dinner',
  //   ],
  //   rating: 2.9,
  //   numberOfReviews: 780,
  //   opening_hours: [{ day: 'Monday', open: '13:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Salad Bar & Co.',
  //   description:
  //     'A modern cafe focusing on fresh, healthy, and customizable salads.',
  //   address: {
  //     street: 'E-8, Arera Colony',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462039',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat + 0.05],
  //     },
  //   },
  //   contact: { phone: '9876510055', email: 'saladbar.bpl@example.com' },
  //   cuisine_type: [
  //     'Salads',
  //     'Healthy',
  //     'Vegan',
  //     'Soups',
  //     'Beverages',
  //     'Lunch',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 650,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'FreshMenu',
  //   description:
  //     'A cloud kitchen delivering fresh, multi-cuisine meals with a daily changing menu.',
  //   address: {
  //     street: 'Cloud Kitchen, MP Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9876510056', email: 'freshmenu.bpl@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Indian',
  //     'Chinese',
  //     'Italian',
  //     'Salads',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'EatFit',
  //   description: 'Healthy and calorie-counted Indian and fusion meals.',
  //   address: {
  //     street: 'Cloud Kitchen, Arera Colony',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.045, baseLat + 0.032],
  //     },
  //   },
  //   contact: { phone: '9876510057', email: 'eatfit.bpl@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Indian',
  //     'Salads',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Monday', open: '08:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Mad Over Donuts',
  //   description:
  //     'A popular spot for a wide variety of gourmet donuts and coffee.',
  //   address: {
  //     street: 'DB City Mall',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.041, baseLat + 0.021],
  //     },
  //   },
  //   contact: { phone: '9876510058', email: 'mod.bpl@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Fast-Food', 'Breakfast'],
  //   rating: 4.3,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Starbucks',
  //   description:
  //     'The premier roaster and retailer of specialty coffee in the world.',
  //   address: {
  //     street: 'DB City Mall, Arera Hills',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.042, baseLat + 0.022],
  //     },
  //   },
  //   contact: { phone: '9876510059', email: 'starbucks.db@example.com' },
  //   cuisine_type: [
  //     'Beverages',
  //     'Desserts',
  //     'Sandwiches',
  //     'Breakfast',
  //     'Fast-Food',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Taco Bell',
  //   description:
  //     'Fast-food chain serving Mexican-inspired fare such as tacos, quesadillas, and nachos.',
  //   address: {
  //     street: 'Aashima Anupama Mall, Hoshangabad Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462026',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.051, baseLat - 0.042],
  //     },
  //   },
  //   contact: { phone: '9876510060', email: 'tacobell.bpl@example.com' },
  //   cuisine_type: [
  //     'Mexican',
  //     'Fast-Food',
  //     'Burgers',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 1400,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Firangi Bake',
  //   description:
  //     'A cloud kitchen offering a fusion of Italian and Indian flavors with baked dishes.',
  //   address: {
  //     street: 'Cloud Kitchen, Indrapuri',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462022',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.065, baseLat - 0.026],
  //     },
  //   },
  //   contact: { phone: '9876510061', email: 'firangibake.bpl@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Mexican',
  //     'Pizza',
  //     'Healthy',
  //     'Dinner',
  //     'Lunch',
  //   ],
  //   rating: 3.9,
  //   numberOfReviews: 600,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 45,
  // },
  // // --- Restaurants 61-80 ---
  // {
  //   name: 'Sweet Truth',
  //   description:
  //     'A dessert-focused cloud kitchen for cakes, pastries, and other sweet treats.',
  //   address: {
  //     street: 'Cloud Kitchen, Kolar Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462042',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.082, baseLat - 0.092],
  //     },
  //   },
  //   contact: { phone: '9876510062', email: 'sweettruth.bpl@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Indian-Sweets',
  //     'Beverages',
  //     'Fast-Food',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 880,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Chai Sutta Bar',
  //   description:
  //     'A popular chain known for serving tea in traditional kulhads and a vibrant atmosphere.',
  //   address: {
  //     street: '10 No. Market',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.051, baseLat + 0.032],
  //     },
  //   },
  //   contact: { phone: '9876510063', email: 'csb.bpl@example.com' },
  //   cuisine_type: ['Beverages', 'Fast-Food', 'Sandwiches', 'Breakfast'],
  //   rating: 4.0,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 22,
  // },
  // {
  //   name: "Giani's Ice Cream",
  //   description:
  //     'A classic ice cream parlor known for its rich, traditional Indian ice cream flavors.',
  //   address: {
  //     street: 'Arera Colony, E-7',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.046, baseLat + 0.037],
  //     },
  //   },
  //   contact: { phone: '9876510064', email: 'gianis.bpl@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Indian-Sweets'],
  //   rating: 4.6,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Baskin Robbins',
  //   description: 'Global ice cream chain with a vast array of creative flavors.',
  //   address: {
  //     street: 'New Market, TT Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.013, baseLat - 0.006],
  //     },
  //   },
  //   contact: { phone: '9876510065', email: 'baskinrobbins.bpl@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Indian-Sweets'],
  //   rating: 4.4,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: "Haldiram's",
  //   description:
  //     'A major Indian sweets and snacks manufacturer, also offering full meals.',
  //   address: {
  //     street: 'DB City Mall',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '9876510066', email: 'haldirams.bpl@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'North-Indian',
  //     'South-Indian',
  //     'Chinese',
  //     'Street-Food',
  //     'Indian-Sweets',
  //     'Desserts',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Chinese Wok',
  //   description:
  //     'Quick-service restaurant specializing in customizable Chinese woks.',
  //   address: {
  //     street: 'MP Nagar, Zone II',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.034, baseLat - 0.013],
  //     },
  //   },
  //   contact: { phone: '9876510067', email: 'chinesewok.bpl@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Japanese',
  //     'Soups',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Mainland China',
  //   description:
  //     'A fine-dining restaurant offering authentic cuisine from major provinces of China.',
  //   address: {
  //     street: 'Shyamla Hills',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.031, baseLat + 0.021],
  //     },
  //   },
  //   contact: { phone: '9876510068', email: 'mainlandchina.bpl@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Japanese',
  //     'Soups',
  //     'Dinner',
  //     'Lunch',
  //     'Desserts',
  //     'Sushi',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Monday', open: '12:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Punjab Grill',
  //   description:
  //     'A celebration of the culinary heritage of Punjab with a fine-dining experience.',
  //   address: {
  //     street: 'DB City Mall',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.044, baseLat + 0.023],
  //     },
  //   },
  //   contact: { phone: '9876510069', email: 'punjabgrill.bpl@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'BBQ',
  //     'Dinner',
  //     'Lunch',
  //     'Desserts',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 2400,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'The Biryani House',
  //   description:
  //     'A delivery-only kitchen with a focus on a wide variety of biryanis.',
  //   address: {
  //     street: 'Cloud Kitchen, Lalghati',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462030',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.062, baseLat + 0.052],
  //     },
  //   },
  //   contact: { phone: '9876510070', email: 'biryanihouse.bpl@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch'],
  //   rating: 3.6,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Paradise Biryani',
  //   description: 'Famous Hyderabadi biryani chain, now delivering in Bhopal.',
  //   address: {
  //     street: 'Cloud Kitchen, MP Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.035, baseLat - 0.012],
  //     },
  //   },
  //   contact: { phone: '9876510071', email: 'paradise.bpl@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'South-Indian', 'Dinner', 'Lunch'],
  //   rating: 4.0,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: "SardarG's Kitchen",
  //   description: 'A simple eatery known for its homely Punjabi food.',
  //   address: {
  //     street: 'Karond',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat - 0.06],
  //     },
  //   },
  //   contact: { phone: '9876510072', email: 'sardarg.bpl@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Lunch', 'Dinner', 'Street-Food'],
  //   rating: 3.8,
  //   numberOfReviews: 550,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Dilliwale Da Paratha',
  //   description:
  //     'Serving a huge variety of stuffed parathas, just like in Delhi.',
  //   address: {
  //     street: '10 No. Market',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.053, baseLat + 0.033],
  //     },
  //   },
  //   contact: { phone: '9876510073', email: 'dilliwale.bpl@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Street-Food',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 980,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Bombay Chowpatty',
  //   description: 'Bringing the flavors of Mumbai street food to Bhopal.',
  //   address: {
  //     street: 'Aura Mall Food Court',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462039',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.026, baseLat + 0.056],
  //     },
  //   },
  //   contact: { phone: '9876510074', email: 'bombaychowpatty.bpl@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Fast-Food',
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Beverages',
  //   ],
  //   rating: 3.9,
  //   numberOfReviews: 700,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Vrindavan Dhaba',
  //   description:
  //     'A highway-style dhaba offering rustic and flavorful vegetarian food.',
  //   address: {
  //     street: 'Airport Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462030',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.08, baseLat + 0.06],
  //     },
  //   },
  //   contact: { phone: '9876510075', email: 'vrindavan.bpl@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'Healthy'],
  //   rating: 4.0,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Health Pantry',
  //   description:
  //     'A cafe dedicated to healthy eating, with keto, gluten-free, and vegan options.',
  //   address: {
  //     street: 'Arera Colony, E-5',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.047, baseLat + 0.029],
  //     },
  //   },
  //   contact: { phone: '9876510076', email: 'healthpantry.bpl@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Vegan',
  //     'Salads',
  //     'Soups',
  //     'Breakfast',
  //     'Beverages',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 550,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Vegan Vibes',
  //   description:
  //     'A 100% plant-based cafe with creative and delicious vegan dishes.',
  //   address: {
  //     street: 'Shakti Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462024',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.049, baseLat - 0.031],
  //     },
  //   },
  //   contact: { phone: '9876510077', email: 'veganvibes.bpl@example.com' },
  //   cuisine_type: [
  //     'Vegan',
  //     'Healthy',
  //     'Salads',
  //     'Desserts',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.8,
  //   numberOfReviews: 400,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Sushi Central',
  //   description:
  //     'A delivery kitchen that gets poor reviews for its authenticity and freshness.',
  //   address: {
  //     street: 'Cloud Kitchen, TT Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.016, baseLat + 0.004],
  //     },
  //   },
  //   contact: { phone: '9876510078', email: 'sushicentral.bpl@example.com' },
  //   cuisine_type: ['Sushi', 'Japanese', 'Soups', 'Chinese', 'Dinner'],
  //   rating: 2.6,
  //   numberOfReviews: 350,
  //   opening_hours: [{ day: 'Monday', open: '13:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Tandoori Nights',
  //   description:
  //     'Specializing in tandoori kebabs, tikkas, and other grilled delicacies.',
  //   address: {
  //     street: 'Jahangirabad',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462008',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.002, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9876510079', email: 'tandoorinights.bpl@example.com' },
  //   cuisine_type: ['North-Indian', 'BBQ', 'Indian', 'Dinner', 'Lunch'],
  //   rating: 4.2,
  //   numberOfReviews: 1600,
  //   opening_hours: [{ day: 'Monday', open: '18:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Kebabsville',
  //   description:
  //     'A casual dining spot focused on a wide variety of Indian kebabs.',
  //   address: {
  //     street: 'Sayaji Hotel, Van Vihar Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.038, baseLat + 0.018],
  //     },
  //   },
  //   contact: { phone: '9876510080', email: 'kebabsville.bpl@example.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Indian', 'Dinner', 'Lunch'],
  //   rating: 4.6,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Monday', open: '19:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2200,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Curry Leaf',
  //   description:
  //     'A simple restaurant serving authentic South Indian vegetarian meals.',
  //   address: {
  //     street: 'Indrapuri, Sector C',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462022',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.061, baseLat - 0.031],
  //     },
  //   },
  //   contact: { phone: '9876510081', email: 'curryleaf.bpl@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //     'Vegan',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 30,
  // },
  // // --- Restaurants 81-100 ---
  // {
  //   name: 'Idli & Co.',
  //   description:
  //     'A small joint specializing in different varieties of idlis and vadas.',
  //   address: {
  //     street: 'Kolar Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462042',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.076, baseLat - 0.086],
  //     },
  //   },
  //   contact: { phone: '9876510082', email: 'idlico.bpl@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Healthy', 'Street-Food'],
  //   rating: 4.3,
  //   numberOfReviews: 650,
  //   opening_hours: [{ day: 'Monday', open: '07:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 150,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Sandwich Shop',
  //   description:
  //     'A takeaway spot with a large menu of sandwiches, but average taste.',
  //   address: {
  //     street: 'MP Nagar, Zone I',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.031, baseLat - 0.016],
  //     },
  //   },
  //   contact: { phone: '9876510083', email: 'sandwichshop.bpl@example.com' },
  //   cuisine_type: ['Sandwiches', 'Fast-Food', 'Breakfast', 'Beverages'],
  //   rating: 3.4,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 250,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Juice Lounge',
  //   description:
  //     'A popular spot for fresh juices, smoothies, and healthy snacks.',
  //   address: {
  //     street: '10 No. Market',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.052, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9876510084', email: 'juicelounge.bpl@example.com' },
  //   cuisine_type: [
  //     'Beverages',
  //     'Healthy',
  //     'Salads',
  //     'Breakfast',
  //     'Fast-Food',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 750,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Shake It Off',
  //   description:
  //     'A trendy cafe specializing in a wide variety of milkshakes and thick shakes.',
  //   address: {
  //     street: 'Arera Colony, E-3',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.041, baseLat + 0.036],
  //     },
  //   },
  //   contact: { phone: '9876510085', email: 'shakeitoff.bpl@example.com' },
  //   cuisine_type: ['Beverages', 'Desserts', 'Fast-Food', 'Indian-Sweets'],
  //   rating: 4.4,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Bakehouse',
  //   description:
  //     'A classic bakery with a reputation for stale products at times.',
  //   address: {
  //     street: 'New Market',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.011, baseLat - 0.004],
  //     },
  //   },
  //   contact: { phone: '9876510086', email: 'bakehouse.bpl@example.com' },
  //   cuisine_type: ['Desserts', 'Fast-Food', 'Sandwiches', 'Breakfast'],
  //   rating: 3.1,
  //   numberOfReviews: 680,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: "Cakes 'n' Craft",
  //   description:
  //     'A popular local cake shop for custom cakes, pastries, and baked goods.',
  //   address: {
  //     street: 'Kolar Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462042',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.079, baseLat - 0.089],
  //     },
  //   },
  //   contact: { phone: '9876510087', email: 'cakesncraft.bpl@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Fast-Food', 'Indian-Sweets'],
  //   rating: 4.5,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Chocolate Heaven',
  //   description:
  //     'A cafe dedicated to all things chocolate, from shakes to fondues.',
  //   address: {
  //     street: 'Aashima Mall',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462026',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.053, baseLat - 0.043],
  //     },
  //   },
  //   contact: { phone: '9876510088', email: 'chocolateheaven.bpl@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Fast-Food', 'Italian'],
  //   rating: 4.3,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 750,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Grill Masters',
  //   description:
  //     'A takeaway joint for grilled sandwiches and burgers with slow service.',
  //   address: {
  //     street: 'Indrapuri',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462022',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.063, baseLat - 0.027],
  //     },
  //   },
  //   contact: { phone: '9876510089', email: 'grillmasters.bpl@example.com' },
  //   cuisine_type: ['Fast-Food', 'Burgers', 'Sandwiches', 'BBQ'],
  //   rating: 3.3,
  //   numberOfReviews: 500,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: "Smokin' Joe's Pizza",
  //   description:
  //     'An Indian pizza chain offering a variety of classic and desi-style pizzas.',
  //   address: {
  //     street: 'Arera Colony, E-7',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.044, baseLat + 0.039],
  //     },
  //   },
  //   contact: { phone: '9876510090', email: 'smokinjoes.bpl@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Beverages'],
  //   rating: 3.9,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Royal Cafe',
  //   description:
  //     'A multi-cuisine restaurant with a very large menu, but inconsistent quality.',
  //   address: {
  //     street: 'Near Chetak Bridge',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462023',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.05, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9876510091', email: 'royalcafe.bpl@example.com' },
  //   cuisine_type: ['North-Indian', 'Chinese', 'Indian', 'Lunch', 'Dinner'],
  //   rating: 2.8,
  //   numberOfReviews: 850,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Filfora',
  //   description:
  //     'A well-regarded restaurant for authentic Mughlai and Lucknowi cuisine.',
  //   address: {
  //     street: 'Koh-e-Fiza',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.022, baseLat + 0.042],
  //     },
  //   },
  //   contact: { phone: '9876510092', email: 'filfora.bpl@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'BBQ', 'Dinner', 'Lunch'],
  //   rating: 4.4,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Cafe Coffee Day',
  //   description:
  //     'A classic Indian cafe chain, perfect for coffee, conversations, and quick bites.',
  //   address: {
  //     street: 'MP Nagar, Zone I',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat - 0.011],
  //     },
  //   },
  //   contact: { phone: '9876510093', email: 'ccd.bpl@example.com' },
  //   cuisine_type: [
  //     'Beverages',
  //     'Fast-Food',
  //     'Desserts',
  //     'Sandwiches',
  //     'Breakfast',
  //   ],
  //   rating: 3.9,
  //   numberOfReviews: 1400,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Natural Ice Cream',
  //   description:
  //     'Serving delicious ice creams made from real fruits, milk, and sugar.',
  //   address: {
  //     street: 'Arera Colony, E-3',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.042, baseLat + 0.034],
  //     },
  //   },
  //   contact: { phone: '9876510094', email: 'natural.bpl@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Indian-Sweets'],
  //   rating: 4.7,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Goila Butter Chicken',
  //   description:
  //     'A delivery kitchen by Chef Saransh Goila, famous for its signature butter chicken.',
  //   address: {
  //     street: 'Cloud Kitchen, Arera Colony',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.048, baseLat + 0.035],
  //     },
  //   },
  //   contact: { phone: '9876510095', email: 'goila.bpl@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Gupta Juice Center',
  //   description: 'A no-frills local juice shop, known for being unhygienic.',
  //   address: {
  //     street: 'Near Bhopal Railway Station',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462010',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9876510096', email: 'guptajuice.bpl@example.com' },
  //   cuisine_type: ['Beverages', 'Street-Food', 'Healthy', 'Breakfast'],
  //   rating: 2.5,
  //   numberOfReviews: 450,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 50,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 100,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Bhopali Zaika',
  //   description:
  //     'A restaurant attempting to serve authentic Bhopali cuisine, with mixed results.',
  //   address: {
  //     street: 'Ibrahimpura',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.006, baseLat - 0.018],
  //     },
  //   },
  //   contact: { phone: '9876510097', email: 'bhopalizaika@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'BBQ', 'Dinner', 'Lunch'],
  //   rating: 3.1,
  //   numberOfReviews: 700,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 650,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Pappu Chai Wala',
  //   description:
  //     'A simple roadside tea stall, famous among locals for its strong tea.',
  //   address: {
  //     street: 'GTB Complex, TT Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat - 0.009],
  //     },
  //   },
  //   contact: { phone: '9876510098', email: 'pappuchai@example.com' },
  //   cuisine_type: ['Beverages', 'Street-Food', 'Breakfast', 'Indian'],
  //   rating: 4.4,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Monday', open: '06:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 40,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 80,
  //   delivery_time_mins: 15,
  // },
  // {
  //   name: "Wendy's",
  //   description:
  //     'American fast-food chain known for its square burgers, sea salt fries, and Frosty.',
  //   address: {
  //     street: 'Cloud Kitchen, MP Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.037, baseLat - 0.011],
  //     },
  //   },
  //   contact: { phone: '9876510099', email: 'wendys.bpl@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Beverages',
  //     'Desserts',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 32,
  // },
  // {
  //   name: 'Bikanervala',
  //   description:
  //     'A chain offering a mix of North Indian, South Indian, and Chinese food, plus sweets.',
  //   address: {
  //     street: 'Hoshangabad Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462026',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.055, baseLat - 0.045],
  //     },
  //   },
  //   contact: { phone: '9876510100', email: 'bikanervala.bpl@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'South-Indian',
  //     'Chinese',
  //     'Street-Food',
  //     'Indian-Sweets',
  //     'Desserts',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 550,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Oh! Calcutta',
  //   description:
  //     'A fine-dining restaurant that brings the colonial-era Bengali cuisine to Bhopal.',
  //   address: {
  //     street: 'Shyamla Hills',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462013',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.036, baseLat + 0.016],
  //     },
  //   },
  //   contact: { phone: '9876510101', email: 'ohcalcutta.bpl@example.com' },
  //   cuisine_type: ['Indian', 'Desserts', 'Dinner', 'Lunch', 'North-Indian'],
  //   rating: 4.5,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Monday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1700,
  //   delivery_time_mins: 55,
  // },
];

export default bhopalRestaurants;
