const baseLat = 23.2599;
const baseLon = 77.4126;

export const bhopalRestaurants = [
  // {
  //   name: 'Zaika Bhopali',
  //   description: 'Authentic Bhopali cuisine with traditional flavors.',
  //   address: {
  //     street: '45 Hamidia Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876500010', email: 'zaikabhopali@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Lunch', 'Dinner'],
  //   rating: 4.4,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 32,
  //   imagePath:
  //     'https://media.istockphoto.com/id/1397973112/photo/assortment-of-various-kinds-of-indian-cousine-on-dark-rusty-table.jpg?s=612x612&w=0&k=20&c=R5XnXgP1jWnGM5PF7OUfvLW_NQhAcaGuJlWp6hl0SoQ=',
  // },
  // {
  //   name: 'Bhopal Burger House',
  //   description: 'Juicy burgers and quick bites in the heart of Bhopal.',
  //   address: {
  //     street: '12 MP Nagar Zone II',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9876500011', email: 'burgerhousebhopal@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Beverages',
  //     'Sandwiches',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 28,
  //   imagePath:
  //     'https://media.istockphoto.com/id/495204032/photo/fresh-tasty-burger.jpg?s=612x612&w=0&k=20&c=k6X_gSHlo-WdKsqTnfBjoEbjdhrlz6RNhUs23ivpIxk=',
  // },

  {
    name: 'Pizza Junction Bhopal',
    description: 'Delicious wood-fired pizzas with fresh toppings.',
    address: {
      street: '20 New Market',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462003',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.015, baseLat + 0.012],
      },
    },
    contact: { phone: '9876500012', email: 'pizzajunctionbhopal@example.com' },
    cuisine_type: [
      'Pizza',
      'Italian',
      'Fast-Food',
      'Beverages',
      'Lunch',
      'Dinner',
    ],
    rating: 4.3,
    numberOfReviews: 950,
    opening_hours: [{ day: 'Monday', open: '11:30', close: '23:30' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 600,
    delivery_time_mins: 30,
    imagePath:
      'https://media.istockphoto.com/id/1214334140/photo/hot-pizza.jpg?s=612x612',
  },
  {
    name: 'Healthy Greens Bhopal',
    description: 'Wholesome salads, soups, and healthy meals.',
    address: {
      street: '5 Arera Colony',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462016',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.008, baseLat + 0.009],
      },
    },
    contact: { phone: '9876500013', email: 'healthygreensbhopal@example.com' },
    cuisine_type: ['Healthy', 'Salads', 'Soups', 'Vegan', 'Lunch', 'Beverages'],
    rating: 4.6,
    numberOfReviews: 650,
    opening_hours: [{ day: 'Monday', open: '09:00', close: '21:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 500,
    delivery_time_mins: 27,
    imagePath:
      'https://media.istockphoto.com/id/1132006401/photo/vegetable-salad.jpg?s=612x612',
  },
  {
    name: 'Mexicano Fiesta',
    description: 'Spicy and flavorful Mexican delicacies.',
    address: {
      street: '8 TT Nagar',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462003',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.018, baseLat - 0.014],
      },
    },
    contact: { phone: '9876500014', email: 'mexicanofiesta@example.com' },
    cuisine_type: [
      'Mexican',
      'Fast-Food',
      'Lunch',
      'Dinner',
      'Beverages',
      'Salads',
    ],
    rating: 4.1,
    numberOfReviews: 720,
    opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 550,
    delivery_time_mins: 33,
    imagePath:
      'https://media.istockphoto.com/id/1151110346/photo/mexican-tacos.jpg?s=612x612',
  },
  {
    name: 'Zaika-e-Bhopal',
    description:
      'A traditional Bhopali restaurant serving rich Mughlai and Indian dishes.',
    address: {
      street: '12 New Market Road',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462001',
      location: { type: 'Point', coordinates: [77.4126, 23.2599] },
    },
    contact: { phone: '9876500001', email: 'zaika@example.com' },
    cuisine_type: ['Indian', 'North-Indian', 'Lunch', 'Dinner'],
    rating: 4.4,
    numberOfReviews: 1320,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 700,
    delivery_time_mins: 30,
    imagePath:
      'https://media.istockphoto.com/id/1405532287/photo/indian-thali-top-view.jpg?s=612x612&w=0&k=20&c=9H_TugPL2h5x0MyMUpSn6fLxkIsJjLDrmFk0zE-3HZI=',
  },
  {
    name: 'The Bhopal Slice',
    description: 'Cheesy and fresh pizzas with local flavors.',
    address: {
      street: '22 MP Nagar Zone-1',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462011',
      location: { type: 'Point', coordinates: [77.4311, 23.2437] },
    },
    contact: { phone: '9876500002', email: 'bhopalslice@example.com' },
    cuisine_type: [
      'Pizza',
      'Fast-Food',
      'Italian',
      'Beverages',
      'Lunch',
      'Dinner',
    ],
    rating: 4.2,
    numberOfReviews: 890,
    opening_hours: [{ day: 'Monday', open: '10:00', close: '23:30' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 500,
    delivery_time_mins: 25,
    imagePath:
      'https://media.istockphoto.com/id/1279109393/photo/freshly-baked-pizza.jpg?s=612x612&w=0&k=20&c=3VYg6qGq3_pjO3LBM9hN5phXj0rbfK3ny14hM-4JfAk=',
  },
  {
    name: 'Burger Junction',
    description: 'Juicy burgers served with crispy fries and shakes.',
    address: {
      street: '5 TT Nagar',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462003',
      location: { type: 'Point', coordinates: [77.3975, 23.2545] },
    },
    contact: { phone: '9876500003', email: 'burgerjunction@example.com' },
    cuisine_type: [
      'Burgers',
      'Fast-Food',
      'Beverages',
      'Sandwiches',
      'Lunch',
      'Dinner',
    ],
    rating: 4.1,
    numberOfReviews: 1020,
    opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 4,
    is_veg: false,
    cost_for_two: 450,
    delivery_time_mins: 20,
    imagePath:
      'https://media.istockphoto.com/id/1272912092/photo/delicious-burger-with-french-fries.jpg?s=612x612&w=0&k=20&c=fxAyjXlD3oGht3WjcOaK3vQpPGW-7r8x4KNYNLy0wkk=',
  },
  {
    name: 'Saffron Bites',
    description: 'Authentic Indian curries and Biryani specialties.',
    address: {
      street: '17 Lalghati Road',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462030',
      location: { type: 'Point', coordinates: [77.3732, 23.2851] },
    },
    contact: { phone: '9876500004', email: 'saffronbites@example.com' },
    cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch'],
    rating: 4.5,
    numberOfReviews: 1420,
    opening_hours: [{ day: 'Monday', open: '11:30', close: '22:30' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 650,
    delivery_time_mins: 32,
    imagePath:
      'https://media.istockphoto.com/id/1316145936/photo/indian-biryani-rice-with-chicken.jpg?s=612x612&w=0&k=20&c=pr6Q0aLaa9SxvE3LuFApy6KGHh3Zy4aEIfhT-mLt_sU=',
  },
  {
    name: 'Tandoori Tales',
    description: 'BBQ and tandoor delights cooked to perfection.',
    address: {
      street: '33 Arera Colony',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462016',
      location: { type: 'Point', coordinates: [77.4419, 23.2156] },
    },
    contact: { phone: '9876500005', email: 'tandooritales@example.com' },
    cuisine_type: ['BBQ', 'Indian', 'North-Indian', 'Dinner', 'Lunch'],
    rating: 4.6,
    numberOfReviews: 1100,
    opening_hours: [{ day: 'Monday', open: '12:00', close: '23:30' }],
    is_active: true,
    min_order_value: 350,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 800,
    delivery_time_mins: 40,
    imagePath:
      'https://media.istockphoto.com/id/639704480/photo/tandoori-chicken.jpg?s=612x612&w=0&k=20&c=bVqkm6WAVlR6VfOU7r5kCIGU7ixQj45ktY76t09nVxQ=',
  },
  {
    name: 'Green Bowl',
    description: 'Healthy salads and soups made with fresh ingredients.',
    address: {
      street: '44 Kolar Road',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462042',
      location: { type: 'Point', coordinates: [77.4955, 23.1691] },
    },
    contact: { phone: '9876500006', email: 'greenbowl@example.com' },
    cuisine_type: ['Healthy', 'Salads', 'Soups', 'Vegan', 'Lunch', 'Beverages'],
    rating: 4.3,
    numberOfReviews: 780,
    opening_hours: [{ day: 'Monday', open: '10:00', close: '22:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 550,
    delivery_time_mins: 28,
    imagePath:
      'https://media.istockphoto.com/id/1183053361/photo/fresh-salad-bowl.jpg?s=612x612&w=0&k=20&c=fZ7K5JKj36k8XOnY1mrbiLiw3X9oyvTX6U1Vls15fN0=',
  },
  {
    name: 'La Pasta',
    description: 'Delicious Italian pastas and pizzas served hot.',
    address: {
      street: '28 Habibganj Road',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462024',
      location: { type: 'Point', coordinates: [77.4608, 23.2225] },
    },
    contact: { phone: '9876500007', email: 'lapasta@example.com' },
    cuisine_type: [
      'Italian',
      'Pizza',
      'Fast-Food',
      'Lunch',
      'Dinner',
      'Beverages',
    ],
    rating: 4.2,
    numberOfReviews: 980,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 600,
    delivery_time_mins: 27,
    imagePath:
      'https://media.istockphoto.com/id/1453469035/photo/spaghetti-pasta-with-tomato-sauce.jpg?s=612x612&w=0&k=20&c=UJrhcAcEjM8JfiToPAJGkpMu8n4ABrBrB7ozW7rjCy0=',
  },
  {
    name: 'Morning Vibes',
    description: 'Perfect breakfast spot with sandwiches, eggs, and coffee.',
    address: {
      street: '3 Hoshangabad Road',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462026',
      location: { type: 'Point', coordinates: [77.4963, 23.1782] },
    },
    contact: { phone: '9876500008', email: 'morningvibes@example.com' },
    cuisine_type: [
      'Breakfast',
      'Sandwiches',
      'Beverages',
      'Healthy',
      'Fast-Food',
    ],
    rating: 4.0,
    numberOfReviews: 650,
    opening_hours: [{ day: 'Monday', open: '07:00', close: '12:00' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 3,
    is_veg: true,
    cost_for_two: 300,
    delivery_time_mins: 15,
    imagePath:
      'https://media.istockphoto.com/id/1147329806/photo/healthy-breakfast-with-coffee.jpg?s=612x612&w=0&k=20&c=-H3kHgKCOQ0CBwexRnJm71P8YYcEJTk6vFWyoG4J9cU=',
  },
  {
    name: 'Fiesta Mexicana',
    description: 'Spicy and authentic Mexican food with modern vibes.',
    address: {
      street: '14 Ashoka Garden',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462023',
      location: { type: 'Point', coordinates: [77.4182, 23.2471] },
    },
    contact: { phone: '9876500009', email: 'fiestamexicana@example.com' },
    cuisine_type: [
      'Mexican',
      'Fast-Food',
      'Lunch',
      'Dinner',
      'Beverages',
      'Salads',
    ],
    rating: 4.1,
    numberOfReviews: 720,
    opening_hours: [{ day: 'Monday', open: '12:00', close: '22:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 5,
    is_veg: false,
    cost_for_two: 550,
    delivery_time_mins: 26,
    imagePath:
      'https://media.istockphoto.com/id/1316145936/photo/tacos-with-vegetables.jpg?s=612x612&w=0&k=20&c=6cDVBkz9jDFPrsHj8KNEDrRYPoa4IbC07UzGOh3Bt3E=',
  },
  {
    name: 'Tokyo Sushi Bar',
    description: 'Fresh sushi rolls and Japanese flavors in Bhopal.',
    address: {
      street: '20 Shahpura Road',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462039',
      location: { type: 'Point', coordinates: [77.4822, 23.1957] },
    },
    contact: { phone: '9876500010', email: 'tokyosushi@example.com' },
    cuisine_type: ['Sushi', 'Japanese', 'Healthy', 'Dinner', 'Lunch', 'Soups'],
    rating: 4.4,
    numberOfReviews: 560,
    opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 350,
    delivery_radius_km: 5,
    is_veg: false,
    cost_for_two: 900,
    delivery_time_mins: 38,
    imagePath:
      'https://media.istockphoto.com/id/1204075635/photo/assorted-sushi-rolls.jpg?s=612x612&w=0&k=20&c=8ZqGg-b0qfqyVPlsg_dDqkWkwK1lJ4kFZ_f1bX5n8V4=',
  },
  {
    name: "Domino's Pizza",
    description:
      'Famous pizza chain serving a variety of pizzas, sides and desserts.',
    address: {
      street: 'DB Mall, Arera Hills',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462011',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.04, baseLat + 0.02],
      },
    },
    contact: { phone: '9876500001', email: 'dominosbhopal@example.com' },
    cuisine_type: [
      'Pizza',
      'Fast-Food',
      'Italian',
      'Desserts',
      'Beverages',
      'Lunch',
      'Dinner',
    ],
    rating: 4.3,
    numberOfReviews: 2400,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 500,
    delivery_time_mins: 30,
    imagePath:
      'https://media.istockphoto.com/id/458400321/photo/pizza.jpg?s=612x612&w=0&k=20&c=b3P7s-7FtHzfUIBx9Kn7O0T0N2ewbRPeovS6M93N7gM=',
  },
  {
    name: 'KFC',
    description: 'Global fast-food chain known for fried chicken and burgers.',
    address: {
      street: 'New Market, TT Nagar',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.01, baseLat - 0.03],
      },
    },
    contact: { phone: '9876500002', email: 'kfc_bhopal@example.com' },
    cuisine_type: ['Fast-Food', 'Burgers', 'Dinner', 'Lunch', 'Beverages'],
    rating: 4.2,
    numberOfReviews: 2100,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '23:30' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 600,
    delivery_time_mins: 28,
    imagePath:
      'https://media.istockphoto.com/id/1214395185/photo/fried-chicken.jpg?s=612x612&w=0&k=20&c=z6yGvVg-VqZQwF-2Zn0BptwOHlDqxlG0T2j7FYiFwMQ=',
  },
  {
    name: "Haldiram's",
    description: 'Popular chain offering Indian snacks, thalis, and sweets.',
    address: {
      street: 'MP Nagar Zone 1',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462011',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.03, baseLat - 0.02],
      },
    },
    contact: { phone: '9876500003', email: 'haldiramsbhopal@example.com' },
    cuisine_type: [
      'Indian',
      'Street-Food',
      'Desserts',
      'Indian-Sweets',
      'Lunch',
      'Dinner',
    ],
    rating: 4.6,
    numberOfReviews: 3100,
    opening_hours: [{ day: 'Monday', open: '10:00', close: '22:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 400,
    delivery_time_mins: 25,
    imagePath:
      'https://media.istockphoto.com/id/1393132924/photo/indian-thali.jpg?s=612x612&w=0&k=20&c=4QynwP9z3P5yI4Xy0eQ1VskThGx5_6yTSQeU3u8Q65w=',
  },
  {
    name: 'Cafe Coffee Day',
    description: 'Popular café chain offering coffee, snacks, and desserts.',
    address: {
      street: 'Arera Colony',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462016',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.05, baseLat + 0.04],
      },
    },
    contact: { phone: '9876500004', email: 'ccd_bhopal@example.com' },
    cuisine_type: [
      'Beverages',
      'Desserts',
      'Fast-Food',
      'Sandwiches',
      'Breakfast',
    ],
    rating: 4.0,
    numberOfReviews: 1600,
    opening_hours: [{ day: 'Monday', open: '09:00', close: '22:30' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 4,
    is_veg: true,
    cost_for_two: 500,
    delivery_time_mins: 20,
    imagePath:
      'https://media.istockphoto.com/id/1309350505/photo/cafe-coffee-cappuccino.jpg?s=612x612&w=0&k=20&c=MQwWrWkQd7ltxHsgsVnO1kUVXPLj9XyClJsw6lK2TZ0=',
  },
  {
    name: 'Subway',
    description:
      'Fast-food restaurant chain serving customizable sandwiches and salads.',
    address: {
      street: 'Aura Mall, Gulmohar Colony',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462039',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.02, baseLat + 0.05],
      },
    },
    contact: { phone: '9876500005', email: 'subwaybhopal@example.com' },
    cuisine_type: [
      'Sandwiches',
      'Salads',
      'Healthy',
      'Fast-Food',
      'Beverages',
      'Lunch',
    ],
    rating: 4.1,
    numberOfReviews: 1900,
    opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 550,
    delivery_time_mins: 27,
    imagePath:
      'https://media.istockphoto.com/id/1222537286/photo/sandwich.jpg?s=612x612&w=0&k=20&c=asNfVXYkW7ruVUM1I4ajgZziHT4lZdt0jL1mwY1vKwE=',
  },
  {
    name: 'Bikanervala',
    description:
      'Famous chain serving Indian sweets, snacks, and vegetarian meals.',
    address: {
      street: 'Bitton Market',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462002',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.04, baseLat - 0.01],
      },
    },
    contact: { phone: '9876500006', email: 'bikanervala_bhopal@example.com' },
    cuisine_type: [
      'Indian',
      'Desserts',
      'Indian-Sweets',
      'Street-Food',
      'Lunch',
      'Dinner',
    ],
    rating: 4.5,
    numberOfReviews: 2200,
    opening_hours: [{ day: 'Monday', open: '09:30', close: '22:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 450,
    delivery_time_mins: 23,
    imagePath:
      'https://media.istockphoto.com/id/1450283222/photo/rasgulla.jpg?s=612x612&w=0&k=20&c=KkncK6Pp3Pj9C0j3u8bFQlHT9-wcV6Yjz1dRslBkkGw=',
  },
  {
    name: 'Barbeque Nation',
    description:
      'Casual dining chain specializing in live grills and BBQ buffets.',
    address: {
      street: 'Maharana Pratap Nagar',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462011',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.01, baseLat - 0.04],
      },
    },
    contact: { phone: '9876500007', email: 'bbqnationbhopal@example.com' },
    cuisine_type: ['BBQ', 'Dinner', 'Indian', 'North-Indian', 'Lunch'],
    rating: 4.7,
    numberOfReviews: 3500,
    opening_hours: [{ day: 'Monday', open: '12:00', close: '23:30' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 1600,
    delivery_time_mins: 40,
    imagePath:
      'https://media.istockphoto.com/id/1162114735/photo/grilled-meat.jpg?s=612x612&w=0&k=20&c=if2g4AIlEqRja28U4k0vTg2jSlb8l1K_0f41jIhvKrg=',
  },
  {
    name: 'Mocha Cafe',
    description:
      'Trendy café serving fusion food, coffee, and continental dishes.',
    address: {
      street: '6 No Stop, Shivaji Nagar',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462016',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.06, baseLat + 0.03],
      },
    },
    contact: { phone: '9876500008', email: 'mochacafe_bhopal@example.com' },
    cuisine_type: [
      'Italian',
      'Beverages',
      'Desserts',
      'Fast-Food',
      'Sandwiches',
      'Lunch',
    ],
    rating: 4.4,
    numberOfReviews: 1200,
    opening_hours: [{ day: 'Monday', open: '10:00', close: '23:30' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 900,
    delivery_time_mins: 32,
    imagePath:
      'https://media.istockphoto.com/id/1401986313/photo/mocha-coffee.jpg?s=612x612&w=0&k=20&c=sdGOn-mr0TgbLOg4l35DizruRlfHk96KoB6sw8UX_HA=',
  },
  {
    name: 'Tandoor & Curries',
    description:
      'Authentic Indian food with rich curries and tandoori delights.',
    address: {
      street: 'Hamidia Road',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.05, baseLat - 0.02],
      },
    },
    contact: {
      phone: '9876500009',
      email: 'tandoorcurries_bhopal@example.com',
    },
    cuisine_type: ['Indian', 'North-Indian', 'BBQ', 'Dinner', 'Lunch'],
    rating: 4.2,
    numberOfReviews: 900,
    opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 5,
    is_veg: false,
    cost_for_two: 750,
    delivery_time_mins: 30,
    imagePath:
      'https://media.istockphoto.com/id/1317314227/photo/indian-chicken-curry.jpg?s=612x612&w=0&k=20&c=EdX4Y43R3BwZih2LPbXc8lBt7QF8eNaNcJxx5HcAeww=',
  },
  {
    name: 'Rajhans Bhojanalaya',
    description: 'Traditional bhojanalaya serving wholesome vegetarian meals.',
    address: {
      street: 'Laxmi Talkies Road',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      zip_code: '462003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.03, baseLat + 0.01],
      },
    },
    contact: { phone: '9876500010', email: 'rajhansbhojanalaya@example.com' },
    cuisine_type: ['Indian', 'North-Indian', 'Lunch', 'Dinner'],
    rating: 4.3,
    numberOfReviews: 1100,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '22:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 4,
    is_veg: true,
    cost_for_two: 350,
    delivery_time_mins: 22,
    imagePath:
      'https://media.istockphoto.com/id/1363048256/photo/vegetarian-thali.jpg?s=612x612&w=0&k=20&c=jQGZc3ZQ37DtfBFy_zsCE-nfaySkCflYdmZ9Xh4R3t0=',
  },
];
