const baseLat = 23.2599;
const baseLon = 77.4126;

export const bhopalRestaurants = [
  // first 4
  // {
  //   name: 'Bapu Ki Kutia',
  //   description: 'Simple, homely, and delicious vegetarian Indian meals.',
  //   address: {
  //     street: '7 TT Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9876510003', email: 'bapukikutia@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Healthy', 'Lunch', 'Dinner'],
  //   rating: 4.4,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Hakeem’s Restaurant',
  //   description: 'A legendary spot in Bhopal for authentic Mughlai cuisine.',
  //   address: {
  //     street: '51, Hamidia Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.009, baseLat - 0.011],
  //     },
  //   },
  //   contact: { phone: '9876510004', email: 'hakeems@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'BBQ', 'Dinner', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Pind Balluchi',
  //   description:
  //     'A village-themed restaurant offering a rustic Punjabi dining experience.',
  //   address: {
  //     street: 'DB City Mall, Arera Hills',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9876510005', email: 'pindballuchi.bpl@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'BBQ',
  //     'Dinner',
  //     'Lunch',
  //     'Beverages',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Biryani By Kilo',
  //   description: 'Authentic biryani cooked in traditional handis.',
  //   address: {
  //     street: 'MP Nagar Zone II',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.038, baseLat - 0.012],
  //     },
  //   },
  //   contact: { phone: '9876510024', email: 'bbk.bpl@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 50,
  // },
  // // South Indian Focused
  // {
  //   name: 'Indian Coffee House',
  //   description:
  //     'A classic spot with old-world charm, serving South Indian staples and coffee.',
  //   address: {
  //     street: '1, New Market',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9876510006', email: 'ich.bhopal@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Breakfast',
  //     'Lunch',
  //     'Beverages',
  //     'Fast-Food',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Sankalp Restaurant',
  //   description:
  //     'Famous for its incredibly long dosas and authentic South Indian flavors.',
  //   address: {
  //     street: 'DB City Mall, MP Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.042, baseLat + 0.021],
  //     },
  //   },
  //   contact: { phone: '9876510007', email: 'sankalp.bpl@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'Vegan'],
  //   rating: 4.5,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Anna Ka Dosa',
  //   description: 'A popular spot for quick, delicious, and affordable dosas.',
  //   address: {
  //     street: '10 No. Market, Arera Colony',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9876510008', email: 'annakadosa@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Street-Food',
  //     'Breakfast',
  //     'Lunch',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 22,
  // },
  // {
  //   name: 'Kerala Cafe',
  //   description: 'Authentic flavors from the coast of Kerala.',
  //   address: {
  //     street: 'Kolar Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462042',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.08, baseLat - 0.09],
  //     },
  //   },
  //   contact: { phone: '9876510022', email: 'keralacafe.bpl@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'Breakfast'],
  //   rating: 4.5,
  //   numberOfReviews: 850,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // // Street Food & Sweets
  // {
  //   name: 'Sharma & Vishnu Fast Food',
  //   description:
  //     'A legendary street food joint known for its sandwiches and fast food.',
  //   address: {
  //     street: 'New Market, TT Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.012, baseLat - 0.007],
  //     },
  //   },
  //   contact: { phone: '9876510009', email: 'sharmavishnu@example.com' },
  //   cuisine_type: ['Street-Food', 'Fast-Food', 'Sandwiches', 'Indian', 'Lunch'],
  //   rating: 4.8,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Jodhpur Sweets',
  //   description: 'Famous for its Mawa Bati, Kachoris, and other Indian sweets.',
  //   address: {
  //     street: 'Hamidia Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat - 0.012],
  //     },
  //   },
  //   contact: { phone: '9876510010', email: 'jodhpursweets@example.com' },
  //   cuisine_type: [
  //     'Indian-Sweets',
  //     'Desserts',
  //     'Street-Food',
  //     'Breakfast',
  //     'Indian',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 50,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 150,
  //   delivery_time_mins: 18,
  // },
  // {
  //   name: 'Sagar Gaire Fast Food',
  //   description: 'A go-to spot for college students for fast food and shakes.',
  //   address: {
  //     street: 'MP Nagar Zone-II',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.035, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9876510011', email: 'sagargaire@example.com' },
  //   cuisine_type: [
  //     'Fast-Food',
  //     'Burgers',
  //     'Sandwiches',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'The Kathi Roll Express',
  //   description: 'Delicious and filling kathi rolls with various stuffings.',
  //   address: {
  //     street: '10 No. Market',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.052, baseLat + 0.031],
  //     },
  //   },
  //   contact: { phone: '9876510020', email: 'kathiroll.bpl@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Fast-Food',
  //     'Indian',
  //     'North-Indian',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Bengali Sweet House',
  //   description: 'Authentic Bengali sweets like Rasgulla and Sandesh.',
  //   address: {
  //     street: 'Indrapuri',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462022',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.065, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9876510025', email: 'bengalisweets@example.com' },
  //   cuisine_type: ['Indian-Sweets', 'Desserts', 'Street-Food', 'Indian'],
  //   rating: 4.5,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 20,
  // },
  // // Cafes & Bakeries
  // {
  //   name: 'Bake N Shake',
  //   description: 'Trendy cafe for shakes, pastries, burgers, and quick bites.',
  //   address: {
  //     street: 'Arera Colony, E-3',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat + 0.035],
  //     },
  //   },
  //   contact: { phone: '9876510012', email: 'bakenshake@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Beverages',
  //     'Fast-Food',
  //     'Burgers',
  //     'Sandwiches',
  //     'Breakfast',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 32,
  // },
  // {
  //   name: 'The Chocolate Room',
  //   description: 'A paradise for chocolate lovers with a variety of desserts.',
  //   address: {
  //     street: 'Aura Mall, Gulmohar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462039',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat + 0.055],
  //     },
  //   },
  //   contact: { phone: '9876510013', email: 'chocolateroom.bpl@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Beverages',
  //     'Breakfast',
  //     'Fast-Food',
  //     'Italian',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Breakfast Story',
  //   description: 'All-day breakfast with English and American classics.',
  //   address: {
  //     street: 'Arera Colony E-5',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.048, baseLat + 0.028],
  //     },
  //   },
  //   contact: { phone: '9876510026', email: 'breakfaststory@example.com' },
  //   cuisine_type: [
  //     'Breakfast',
  //     'Healthy',
  //     'Beverages',
  //     'Sandwiches',
  //     'Desserts',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '16:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // // Pizza & Burgers
  // {
  //   name: 'Chicago Pizza',
  //   description: 'Serving authentic deep-dish Chicago-style pizzas.',
  //   address: {
  //     street: 'DB City Mall, Food Court',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.041, baseLat + 0.022],
  //     },
  //   },
  //   contact: { phone: '9876510014', email: 'chicagopizza.bpl@example.com' },
  //   cuisine_type: [
  //     'Pizza',
  //     'Italian',
  //     'Fast-Food',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Burger King',
  //   description: 'Global fast-food chain known for its flame-grilled burgers.',
  //   address: {
  //     street: 'Aashima Mall, Hoshangabad Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462026',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.05, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9876510015', email: 'bk.bhopal@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //     'Desserts',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Monday', open: '10:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: "La Pino'z Pizza",
  //   description: 'Famous for giant pizza slices and a wide range of toppings.',
  //   address: {
  //     street: 'MP Nagar Zone-I',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.031, baseLat - 0.019],
  //     },
  //   },
  //   contact: { phone: '9876510027', email: 'lapinoz.bpl@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Beverages', 'Dinner'],
  //   rating: 4.4,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 33,
  // },
  // {
  //   name: 'Wat-a-Burger',
  //   description: 'Indian burger chain with a fusion of local flavors.',
  //   address: {
  //     street: 'Kolar Road',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462042',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.075, baseLat - 0.085],
  //     },
  //   },
  //   contact: { phone: '9876510028', email: 'wataburger.bpl@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Beverages', 'Lunch', 'Dinner'],
  //   rating: 4.0,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 300,
  //   delivery_time_mins: 28,
  // },
  // // Asian Cuisine
  // {
  //   name: 'Wok On Fire',
  //   description: 'Sizzling woks with customizable Chinese and Thai flavors.',
  //   address: {
  //     street: 'Indrapuri, Sector C',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462022',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.06, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9876510016', email: 'wokonfire@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Japanese',
  //     'Soups',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 750,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Kyoto - The Japanese Kitchen',
  //   description: 'Authentic sushi, sashimi, and Japanese main courses.',
  //   address: {
  //     street: 'Shyamla Hills',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9876510017', email: 'kyoto.bpl@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Soups', 'Healthy', 'Dinner', 'Lunch'],
  //   rating: 4.7,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Monday', open: '13:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'The Momo Factory',
  //   description: 'A huge variety of steamed, fried, and tandoori momos.',
  //   address: {
  //     street: 'MP Nagar Zone I',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.033, baseLat - 0.018],
  //     },
  //   },
  //   contact: { phone: '9876510023', email: 'momofactory.bpl@example.com' },
  //   cuisine_type: ['Chinese', 'Fast-Food', 'Soups', 'Dinner', 'Lunch'],
  //   rating: 4.2,
  //   numberOfReviews: 1400,
  //   opening_hours: [{ day: 'Monday', open: '13:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Yo! China',
  //   description: 'A popular chain for casual Chinese dining.',
  //   address: {
  //     street: 'DB City Mall',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.044, baseLat + 0.024],
  //     },
  //   },
  //   contact: { phone: '9876510029', email: 'yochina.bpl@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Fast-Food', 'Dinner', 'Lunch'],
  //   rating: 4.0,
  //   numberOfReviews: 1600,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // // Specialty (Healthy, Vegan, Mexican)
  // {
  //   name: 'Greenr Cafe',
  //   description:
  //     'A plant-based cafe serving innovative and delicious vegan food.',
  //   address: {
  //     street: 'Arera Colony, E-7',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.045, baseLat + 0.038],
  //     },
  //   },
  //   contact: { phone: '9876510018', email: 'greenr.bpl@example.com' },
  //   cuisine_type: [
  //     'Vegan',
  //     'Healthy',
  //     'Salads',
  //     'Soups',
  //     'Breakfast',
  //     'Lunch',
  //     'Beverages',
  //   ],
  //   rating: 4.8,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: "Chili's American Grill & Bar",
  //   description: 'Classic American Tex-Mex, burgers, and sizzling fajitas.',
  //   address: {
  //     street: 'DB City Mall',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.043, baseLat + 0.023],
  //     },
  //   },
  //   contact: { phone: '9876510019', email: 'chilis.bpl@example.com' },
  //   cuisine_type: [
  //     'Mexican',
  //     'Burgers',
  //     'Salads',
  //     'Dinner',
  //     'Lunch',
  //     'Beverages',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Little Italy',
  //   description:
  //     'Authentic and fine-dining vegetarian Italian & Mexican cuisine.',
  //   address: {
  //     street: 'Shyamla Hills',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.032, baseLat + 0.022],
  //     },
  //   },
  //   contact: { phone: '9876510021', email: 'littleitaly.bpl@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Pizza',
  //     'Mexican',
  //     'Vegan',
  //     'Salads',
  //     'Dinner',
  //     'Lunch',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 1700,
  //   opening_hours: [{ day: 'Monday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'The Salad Story',
  //   description: 'Create your own fresh and healthy salads and bowls.',
  //   address: {
  //     street: 'Lalghati',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462030',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.06, baseLat + 0.05],
  //     },
  //   },
  //   contact: { phone: '9876510030', email: 'saladstory.bpl@example.com' },
  //   cuisine_type: ['Salads', 'Healthy', 'Vegan', 'Soups', 'Lunch', 'Beverages'],
  //   rating: 4.7,
  //   numberOfReviews: 700,
  //   opening_hours: [{ day: 'Monday', open: '10:30', close: '21:30' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Barbeque Nation',
  //   description:
  //     'Casual dining chain specializing in live grills and BBQ buffets.',
  //   address: {
  //     street: 'Maharana Pratap Nagar',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9876500007', email: 'bbqnationbhopal@example.com' },
  //   cuisine_type: [
  //     'BBQ',
  //     'Dinner',
  //     'Indian',
  //     'North-Indian',
  //     'Lunch',
  //     'Salads',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'California Burrito',
  //   description: 'Freshly made burritos and bowls with a healthy twist.',
  //   address: {
  //     street: 'Aura Mall',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462039',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.022, baseLat + 0.052],
  //     },
  //   },
  //   contact: { phone: '9876510031', email: 'calburrito.bpl@example.com' },
  //   cuisine_type: [
  //     'Mexican',
  //     'Fast-Food',
  //     'Healthy',
  //     'Lunch',
  //     'Dinner',
  //     'Salads',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 850,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Shahnama - Jehan Numa Palace',
  //   description:
  //     'An opulent fine-dining experience with a focus on royal Indian cuisine.',
  //   address: {
  //     street: '157, Shyamla Hills',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462013',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.035, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9876510032', email: 'shahnama@jehannuma.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch', 'Desserts'],
  //   rating: 4.9,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Rolls Mania',
  //   description:
  //     'A popular chain for delicious and affordable wraps and rolls.',
  //   address: {
  //     street: 'MP Nagar, Zone II',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.033, baseLat - 0.014],
  //     },
  //   },
  //   contact: { phone: '9876510033', email: 'rollsmania.bpl@example.com' },
  //   cuisine_type: ['Street-Food', 'Fast-Food', 'Indian', 'Lunch', 'Dinner'],
  //   rating: 4.1,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 250,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Top N Town',
  //   description:
  //     "Bhopal's favorite ice cream parlor with a wide range of flavors.",
  //   address: {
  //     street: 'New Market',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.014, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9876510034', email: 'topntown@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Indian-Sweets'],
  //   rating: 4.6,
  //   numberOfReviews: 3000,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Mocha Cafe & Bar',
  //   description:
  //     'A chic cafe with a global menu, coffee, and vibrant ambiance.',
  //   address: {
  //     street: 'Aashima Mall',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462026',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.052, baseLat - 0.042],
  //     },
  //   },
  //   contact: { phone: '9876510035', email: 'mocha.bpl@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Mexican',
  //     'Desserts',
  //     'Beverages',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 1600,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Behrouz Biryani',
  //   description: 'Royal biryanis delivered with a premium experience.',
  //   address: {
  //     street: 'Arera Colony',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.042, baseLat + 0.033],
  //     },
  //   },
  //   contact: { phone: '9876510036', email: 'behrouz.bpl@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch'],
  //   rating: 4.4,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 450,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Subway',
  //   description: 'Customizable submarine sandwiches and salads.',
  //   address: {
  //     street: 'MP Nagar, Zone I',
  //     city: 'Bhopal',
  //     state: 'Madhya Pradesh',
  //     zip_code: '462011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat - 0.017],
  //     },
  //   },
  //   contact: { phone: '9876510037', email: 'subway.mpnagar@example.com' },
  //   cuisine_type: [
  //     'Sandwiches',
  //     'Salads',
  //     'Healthy',
  //     'Fast-Food',
  //     'Breakfast',
  //     'Lunch',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
];
