// Base coordinates for Kolkata (approximate center)
const baseLat = 22.5726;
const baseLon = 88.3639;

const calcuttaRestaurants = [
  // --- Restaurants 1-10 ---
  {
    name: 'Peter Cat',
    description:
      'An iconic Park Street restaurant famous for its Chelo Kebab and continental dishes.',
    address: {
      street: '18A, Park Street',
      city: 'Kolkata',
      state: 'West Bengal',
      zip_code: '700071',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.01, baseLat - 0.02],
      },
    },
    contact: { phone: '9876570001', email: 'petercat.kol@example.com' },
    cuisine_type: ['North-Indian', 'BBQ', 'Dinner', 'Lunch', 'Indian'],
    rating: 4.7,
    numberOfReviews: 9500,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 1500,
    delivery_time_mins: 45,
  },
  {
    name: 'Arsalan',
    description:
      'A legendary destination for authentic Mughlai Biryani and kebabs.',
    address: {
      street: 'Park Circus Area',
      city: 'Kolkata',
      state: 'West Bengal',
      zip_code: '700017',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.03, baseLat - 0.03],
      },
    },
    contact: { phone: '9876570002', email: 'arsalan.kol@example.com' },
    cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ'],
    rating: 4.6,
    numberOfReviews: 12500,
    opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:45' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 800,
    delivery_time_mins: 40,
  },
  {
    name: 'Flurys',
    description:
      'A historic tearoom on Park Street, famous for its English breakfast and pastries.',
    address: {
      street: '18, Park Street',
      city: 'Kolkata',
      state: 'West Bengal',
      zip_code: '700071',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.011, baseLat - 0.021],
      },
    },
    contact: { phone: '9876570003', email: 'flurys.kol@example.com' },
    cuisine_type: [
      'Breakfast',
      'Desserts',
      'Sandwiches',
      'Beverages',
      'Salads',
    ],
    rating: 4.5,
    numberOfReviews: 7800,
    opening_hours: [{ day: 'Wednesday', open: '07:30', close: '22:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 1000,
    delivery_time_mins: 35,
  },
  {
    name: 'Mocambo',
    description:
      'A classic fine-dining restaurant with a retro vibe, serving Continental and Indian dishes.',
    address: {
      street: '25B, Park Street',
      city: 'Kolkata',
      state: 'West Bengal',
      zip_code: '700016',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.012, baseLat - 0.022],
      },
    },
    contact: { phone: '9876570004', email: 'mocambo.kol@example.com' },
    cuisine_type: ['Italian', 'North-Indian', 'Dinner', 'Lunch', 'Soups'],
    rating: 4.6,
    numberOfReviews: 8200,
    opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:30' }],
    is_active: true,
    min_order_value: 600,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 1800,
    delivery_time_mins: 50,
  },
  {
    name: 'Kusum Rolls',
    description: 'An iconic spot for authentic Kolkata-style Kathi Rolls.',
    address: {
      street: 'Karnani Mansion, Park Street',
      city: 'Kolkata',
      state: 'West Bengal',
      zip_code: '700016',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.013, baseLat - 0.023],
      },
    },
    contact: { phone: '9876570005', email: 'kusumrolls@example.com' },
    cuisine_type: ['Street-Food', 'Fast-Food', 'Indian', 'Lunch', 'Dinner'],
    rating: 4.7,
    numberOfReviews: 9800,
    opening_hours: [{ day: 'Friday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 250,
    delivery_time_mins: 25,
  },
  // {
  //   name: 'Balaram Mullick & Radharaman Mullick',
  //   description:
  //     'A legendary sweet shop famous for its traditional and fusion Bengali sweets.',
  //   address: {
  //     street: 'Ballygunge',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700019',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9876570006', email: 'balarammullick@example.com' },
  //   cuisine_type: ['Indian-Sweets', 'Desserts'],
  //   rating: 4.8,
  //   numberOfReviews: 11000,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Olypub',
  //   description:
  //     'A classic, no-frills pub on Park Street, known for its beef steak.',
  //   address: {
  //     street: '21, Park Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.014, baseLat - 0.024],
  //     },
  //   },
  //   contact: { phone: '9876570007', email: 'olypub@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Beverages', 'Dinner', 'BBQ'],
  //   rating: 4.2,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: '6 Ballygunge Place',
  //   description:
  //     'A fine-dining restaurant offering authentic and traditional Bengali cuisine.',
  //   address: {
  //     street: 'Ballygunge',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700019',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.041, baseLat - 0.041],
  //     },
  //   },
  //   contact: { phone: '9876570008', email: '6ballygunge@example.com' },
  //   cuisine_type: ['Indian', 'Dinner', 'Lunch', 'Desserts', 'South-Indian'],
  //   rating: 4.6,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Fire and Ice Pizzeria',
  //   description:
  //     'An authentic Italian pizzeria known for its wood-fired pizzas.',
  //   address: {
  //     street: 'Camac Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9876570009', email: 'fireandice@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Salads', 'Dinner', 'Beverages'],
  //   rating: 4.5,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Bohemian',
  //   description:
  //     'A contemporary Bengali restaurant with a creative and modern menu.',
  //   address: {
  //     street: 'Ballygunge',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700019',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.042, baseLat - 0.042],
  //     },
  //   },
  //   contact: { phone: '9876570010', email: 'bohemian@example.com' },
  //   cuisine_type: ['Indian', 'Healthy', 'Dinner', 'Lunch', 'Soups'],
  //   rating: 4.7,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Wednesday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 55,
  // },

  // seeded till here :

  // --- Restaurants 11-20 ---
  // {
  //   name: 'Oh! Calcutta',
  //   description:
  //     'A fine-dining chain celebrating the rich culinary heritage of Bengal.',
  //   address: {
  //     street: 'Forum Mall, Elgin Road',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700020',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat - 0.035],
  //     },
  //   },
  //   contact: { phone: '9876570011', email: 'ohcalcutta@example.com' },
  //   cuisine_type: ['Indian', 'Dinner', 'Lunch', 'Desserts', 'Beverages'],
  //   rating: 4.6,
  //   numberOfReviews: 6200,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Peter Hu?',
  //   description:
  //     'A trendy Asian restaurant with a focus on dim sum and innovative cocktails.',
  //   address: {
  //     street: 'Park Street Area',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat - 0.026],
  //     },
  //   },
  //   contact: { phone: '9876570012', email: 'peterhu@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Sushi', 'Dinner', 'Beverages'],
  //   rating: 4.5,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 900,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 2200,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'The Corner Courtyard',
  //   description:
  //     'A boutique hotel with a charming cafe serving global comfort food.',
  //   address: {
  //     street: 'Sarat Bose Road',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700025',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.035, baseLat - 0.045],
  //     },
  //   },
  //   contact: { phone: '9876570013', email: 'cornercourtyard@example.com' },
  //   cuisine_type: ['Italian', 'Salads', 'Breakfast', 'Desserts', 'Healthy'],
  //   rating: 4.4,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Wise Owl Steakhouse',
  //   description:
  //     'A popular spot for steaks, burgers, and American-style breakfast.',
  //   address: {
  //     street: 'Purna Das Road',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700029',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.05, baseLat - 0.05],
  //     },
  //   },
  //   contact: { phone: '9876570014', email: 'wiseowl@example.com' },
  //   cuisine_type: ['Burgers', 'BBQ', 'Dinner', 'Breakfast', 'Sandwiches'],
  //   rating: 4.3,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Sunday', open: '07:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Tung Fong',
  //   description:
  //     'A classic Chinese restaurant in Park Street known for its authentic flavors.',
  //   address: {
  //     street: 'Park Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.016, baseLat - 0.027],
  //     },
  //   },
  //   contact: { phone: '9876570015', email: 'tungfong@example.com' },
  //   cuisine_type: ['Chinese', 'Soups', 'Dinner', 'Lunch', 'Fast-Food'],
  //   rating: 4.2,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 48,
  // },
  // {
  //   name: 'Naturals Ice Cream',
  //   description:
  //     'Famous for its ice creams made from real fruits, milk, and sugar.',
  //   address: {
  //     street: 'Park Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.017, baseLat - 0.028],
  //     },
  //   },
  //   contact: { phone: '9876570016', email: 'naturals.kol@example.com' },
  //   cuisine_type: ['Desserts', 'Indian-Sweets', 'Beverages'],
  //   rating: 4.8,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Indian Coffee House',
  //   description: 'A historic and iconic coffee house with an old-world charm.',
  //   address: {
  //     street: 'College Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700073',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9876570017', email: 'ich.kol@example.com' },
  //   cuisine_type: [
  //     'Breakfast',
  //     'Beverages',
  //     'Indian',
  //     'Fast-Food',
  //     'Sandwiches',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 8800,
  //   opening_hours: [{ day: 'Wednesday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 300,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Daily Cafe',
  //   description:
  //     'A cozy cafe perfect for coffee, sandwiches, and healthy bites.',
  //   address: {
  //     street: 'Sarat Bose Road',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700029',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.045, baseLat - 0.048],
  //     },
  //   },
  //   contact: { phone: '9876570018', email: 'dailycafe@example.com' },
  //   cuisine_type: ['Healthy', 'Salads', 'Sandwiches', 'Beverages', 'Breakfast'],
  //   rating: 4.5,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Thursday', open: '08:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Taco Bell',
  //   description:
  //     'Fast-food chain serving Mexican-inspired fare like tacos and burritos.',
  //   address: {
  //     street: 'South City Mall',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700068',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.06],
  //     },
  //   },
  //   contact: { phone: '9876570019', email: 'tacobell.kol@example.com' },
  //   cuisine_type: ['Mexican', 'Fast-Food', 'Dinner', 'Lunch', 'Beverages'],
  //   rating: 4.1,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Bar-B-Q',
  //   description:
  //     'A popular restaurant in Park Street for Chinese and North Indian food.',
  //   address: {
  //     street: '43, Park Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.018, baseLat - 0.029],
  //     },
  //   },
  //   contact: { phone: '9876570020', email: 'barbq.kol@example.com' },
  //   cuisine_type: ['Chinese', 'North-Indian', 'BBQ', 'Dinner', 'Lunch'],
  //   rating: 4.4,
  //   numberOfReviews: 7200,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 50,
  // },

  // seeded till here :
  //   // --- Restaurants 21-30 ---
  // {
  //   name: 'Aminia',
  //   description:
  //     'Another iconic name for Mughlai food, especially its biryani and chaap.',
  //   address: {
  //     street: 'New Market Area',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700087',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876570021', email: 'aminia@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ'],
  //   rating: 4.3,
  //   numberOfReviews: 9200,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Fatty Bao',
  //   description:
  //     'A vibrant Asian gastropub known for its baos, ramen, and sushi.',
  //   address: {
  //     street: 'Camac Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.021, baseLat - 0.026],
  //     },
  //   },
  //   contact: { phone: '9876570022', email: 'fattybao.kol@example.com' },
  //   cuisine_type: ['Japanese', 'Chinese', 'Sushi', 'Soups', 'Dinner'],
  //   rating: 4.5,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Ganguram Sweets',
  //   description:
  //     'A heritage sweet shop offering a wide range of Bengali sweets.',
  //   address: {
  //     street: 'Maniktala',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9876570023', email: 'ganguram@example.com' },
  //   cuisine_type: ['Indian-Sweets', 'Desserts', 'Street-Food'],
  //   rating: 4.6,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Tuesday', open: '07:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'My Big Fat Belly',
  //   description: 'A popular cafe for gourmet burgers, pasta, and shakes.',
  //   address: {
  //     street: 'Sarat Bose Road',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700029',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.046, baseLat - 0.049],
  //     },
  //   },
  //   contact: { phone: '9876570024', email: 'mybigfatbelly@example.com' },
  //   cuisine_type: ['Burgers', 'Italian', 'Fast-Food', 'Beverages', 'Salads'],
  //   rating: 4.4,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Wednesday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Sienna Store & Cafe',
  //   description:
  //     'A charming cafe with a focus on organic, healthy, and artisanal food.',
  //   address: {
  //     street: 'Hindustan Park',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700029',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.055, baseLat - 0.055],
  //     },
  //   },
  //   contact: { phone: '9876570025', email: 'siennacafe@example.com' },
  //   cuisine_type: ['Healthy', 'Vegan', 'Salads', 'Breakfast', 'Beverages'],
  //   rating: 4.6,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Mainland China',
  //   description:
  //     'A fine-dining restaurant offering authentic cuisine from major provinces of China.',
  //   address: {
  //     street: 'Gurusaday Road',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700019',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.038, baseLat - 0.038],
  //     },
  //   },
  //   contact: { phone: '9876570026', email: 'mainlandchina.kol@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Dinner', 'Lunch', 'Soups'],
  //   rating: 4.5,
  //   numberOfReviews: 5200,
  //   opening_hours: [{ day: 'Friday', open: '12:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Golbari',
  //   description:
  //     'A century-old institution famous for its spicy mutton curry (Kosha Mangsho).',
  //   address: {
  //     street: 'Shyambazar',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9876570027', email: 'golbari@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch'],
  //   rating: 4.7,
  //   numberOfReviews: 7500,
  //   opening_hours: [{ day: 'Saturday', open: '12:30', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Irish House',
  //   description:
  //     'A lively pub with a great selection of beers, burgers, and pub grub.',
  //   address: {
  //     street: 'Quest Mall, Ballygunge',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.031, baseLat - 0.031],
  //     },
  //   },
  //   contact: { phone: '9876570028', email: 'irishhouse.kol@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Beverages', 'Dinner', 'Italian'],
  //   rating: 4.3,
  //   numberOfReviews: 4100,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1900,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Pa Pa Ya',
  //   description:
  //     'A modern Asian bistro offering a radical take on Asian cuisine with sushi and more.',
  //   address: {
  //     street: 'Park Street Area',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.019, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9876570029', email: 'papaya.kol@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Chinese', 'Dinner', 'Desserts'],
  //   rating: 4.6,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Kaidi Kitchen',
  //   description:
  //     'A unique jail-themed vegetarian restaurant serving multi-cuisine food.',
  //   address: {
  //     street: 'Camac Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.022, baseLat - 0.027],
  //     },
  //   },
  //   contact: { phone: '9876570030', email: 'kaidikitchen@example.com' },
  //   cuisine_type: ['North-Indian', 'Italian', 'Mexican', 'Chinese', 'Vegan'],
  //   rating: 4.2,
  //   numberOfReviews: 5800,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1300,
  //   delivery_time_mins: 45,
  // },

  // seeded till here :

  //   // --- Restaurants 31-40 ---
  // {
  //   name: 'Barbeque Nation',
  //   description:
  //     'The original live-on-the-table grill restaurant with a lavish buffet.',
  //   address: {
  //     street: 'Salt Lake, Sector V',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700091',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.1, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9876570031', email: 'bbqnation.kol@example.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Indian', 'Dinner', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'PizzaExpress',
  //   description: 'A global chain serving authentic Italian pizzas and pastas.',
  //   address: {
  //     street: 'Quest Mall, Ballygunge',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.032, baseLat - 0.032],
  //     },
  //   },
  //   contact: { phone: '9876570032', email: 'pizzaexpress.kol@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Salads', 'Desserts', 'Beverages'],
  //   rating: 4.4,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 48,
  // },
  // {
  //   name: 'Mitra Cafe',
  //   description:
  //     'A legendary cabin-style restaurant famous for its Brain Chop and other cutlets.',
  //   address: {
  //     street: 'Shobhabazar',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.008, baseLat + 0.035],
  //     },
  //   },
  //   contact: { phone: '9876570033', email: 'mitracafe@example.com' },
  //   cuisine_type: ['Street-Food', 'Indian', 'Fast-Food', 'Dinner', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 6800,
  //   opening_hours: [{ day: 'Friday', open: '17:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: "The Biker's Cafe",
  //   description:
  //     'A themed cafe with a rugged vibe, serving global cuisine and all-day breakfast.',
  //   address: {
  //     street: 'Elgin Road',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700020',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.026, baseLat - 0.036],
  //     },
  //   },
  //   contact: { phone: '9876570034', email: 'bikerscafe@example.com' },
  //   cuisine_type: [
  //     'Breakfast',
  //     'Burgers',
  //     'Sandwiches',
  //     'Healthy',
  //     'Beverages',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 3900,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Hindustan Sweets',
  //   description:
  //     'A well-known sweet shop for traditional Bengali sweets and snacks.',
  //   address: {
  //     street: 'Jadavpur',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700032',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat - 0.07],
  //     },
  //   },
  //   contact: { phone: '9876570035', email: 'hindustansweets@example.com' },
  //   cuisine_type: ['Indian-Sweets', 'Desserts', 'Street-Food', 'Breakfast'],
  //   rating: 4.4,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Sunday', open: '07:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: "Chili's Grill & Bar",
  //   description:
  //     'American casual dining with a Tex-Mex twist, famous for burgers and fajitas.',
  //   address: {
  //     street: 'Quest Mall, Ballygunge',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.033, baseLat - 0.033],
  //     },
  //   },
  //   contact: { phone: '9876570036', email: 'chilis.kol@example.com' },
  //   cuisine_type: ['Mexican', 'Burgers', 'BBQ', 'Dinner', 'Beverages'],
  //   rating: 4.4,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1700,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Hatari',
  //   description:
  //     'A budget-friendly restaurant popular for its Chinese and North Indian dishes.',
  //   address: {
  //     street: 'Rash Behari Avenue',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700029',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.048, baseLat - 0.052],
  //     },
  //   },
  //   contact: { phone: '9876570037', email: 'hatari@example.com' },
  //   cuisine_type: ['Chinese', 'North-Indian', 'Fast-Food', 'Soups', 'Dinner'],
  //   rating: 4.0,
  //   numberOfReviews: 6200,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Wall',
  //   description:
  //     'A fine-dining restaurant specializing in authentic Oriental cuisine.',
  //   address: {
  //     street: 'Sarat Bose Road',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700020',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.028, baseLat - 0.038],
  //     },
  //   },
  //   contact: { phone: '9876570038', email: 'thewall@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Sushi', 'Dinner', 'Soups'],
  //   rating: 4.5,
  //   numberOfReviews: 3300,
  //   opening_hours: [{ day: 'Wednesday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 900,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Mama Mia!',
  //   description:
  //     'A popular dessert parlor known for its gelatos, cakes, and sundaes.',
  //   address: {
  //     street: 'Ballygunge',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700019',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.043, baseLat - 0.043],
  //     },
  //   },
  //   contact: { phone: '9876570039', email: 'mamamia@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Pizza', 'Fast-Food'],
  //   rating: 4.6,
  //   numberOfReviews: 5100,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Shiraz Golden Restaurant',
  //   description:
  //     'Another legendary name for Kolkata-style Biryani and Mughlai dishes.',
  //   address: {
  //     street: 'Park Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat - 0.031],
  //     },
  //   },
  //   contact: { phone: '9876570040', email: 'shiraz@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ'],
  //   rating: 4.4,
  //   numberOfReviews: 8500,
  //   opening_hours: [{ day: 'Friday', open: '11:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 280,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 750,
  //   delivery_time_mins: 42,
  // },

  // seeded till here

  //   // --- Restaurants 41-50 ---
  // {
  //   name: 'Koshe Kosha',
  //   description:
  //     'A restaurant dedicated to serving authentic Bengali cuisine, especially kosha mangsho.',
  //   address: {
  //     street: 'Golpark',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700029',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.052, baseLat - 0.052],
  //     },
  //   },
  //   contact: { phone: '9876570041', email: 'koshekosha@example.com' },
  //   cuisine_type: ['Indian', 'Dinner', 'Lunch', 'South-Indian', 'Desserts'],
  //   rating: 4.3,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Monkey Bar',
  //   description:
  //     'A trendy gastropub with a great view, creative cocktails, and fusion food.',
  //   address: {
  //     street: 'Camac Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.023, baseLat - 0.028],
  //     },
  //   },
  //   contact: { phone: '9876570042', email: 'monkeybar.kol@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Beverages',
  //     'Dinner',
  //     'North-Indian',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 5100,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Fabcafe by Fabindia',
  //   description: 'A cafe focusing on healthy, organic, and modern Indian food.',
  //   address: {
  //     street: 'Loudon Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.024, baseLat - 0.034],
  //     },
  //   },
  //   contact: { phone: '9876570043', email: 'fabcafe.kol@example.com' },
  //   cuisine_type: ['Healthy', 'Vegan', 'Salads', 'Breakfast', 'Indian'],
  //   rating: 4.5,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Monday', open: '08:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1300,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'La Macario Cafe',
  //   description:
  //     'A chic cafe with beautiful decor, serving Italian and Continental food.',
  //   address: {
  //     street: 'Wood Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat - 0.029],
  //     },
  //   },
  //   contact: { phone: '9876570044', email: 'lamacario@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Desserts', 'Beverages', 'Healthy'],
  //   rating: 4.6,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Zeeshan',
  //   description: 'A popular spot for Mughlai rolls, biryani, and kebabs.',
  //   address: {
  //     street: 'Park Circus',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.031, baseLat - 0.034],
  //     },
  //   },
  //   contact: { phone: '9876570045', email: 'zeeshan@example.com' },
  //   cuisine_type: ['Street-Food', 'North-Indian', 'BBQ', 'Dinner', 'Fast-Food'],
  //   rating: 4.2,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Blue Poppy',
  //   description:
  //     'Authentic Tibetan and Bhutanese food, famous for its momos and thukpa.',
  //   address: {
  //     street: 'Sikkim House, Camac Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.026, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9876570046', email: 'bluepoppy@example.com' },
  //   cuisine_type: ['Chinese', 'Soups', 'Healthy', 'Dinner', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Kookie Jar',
  //   description: 'A legendary bakery for cakes, pastries, and savory snacks.',
  //   address: {
  //     street: 'Rawdon Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.027, baseLat - 0.031],
  //     },
  //   },
  //   contact: { phone: '9876570047', email: 'kookiejar@example.com' },
  //   cuisine_type: ['Desserts', 'Sandwiches', 'Fast-Food', 'Beverages'],
  //   rating: 4.7,
  //   numberOfReviews: 6200,
  //   opening_hours: [{ day: 'Friday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'One Step Up',
  //   description: 'A classic continental restaurant with a cozy ambiance.',
  //   address: {
  //     street: 'Park Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.021, baseLat - 0.032],
  //     },
  //   },
  //   contact: { phone: '9876570048', email: 'onestepup@example.com' },
  //   cuisine_type: ['Italian', 'Soups', 'Salads', 'Dinner', 'Lunch'],
  //   rating: 4.3,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 48,
  // },
  // {
  //   name: 'Bhojohori Manna',
  //   description: 'A popular chain for authentic, home-style Bengali food.',
  //   address: {
  //     street: 'Hindustan Road',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700029',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.053, baseLat - 0.053],
  //     },
  //   },
  //   contact: { phone: '9876570049', email: 'bhojohorimanna@example.com' },
  //   cuisine_type: ['Indian', 'South-Indian', 'Dinner', 'Lunch', 'Desserts'],
  //   rating: 4.4,
  //   numberOfReviews: 7100,
  //   opening_hours: [{ day: 'Sunday', open: '11:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Steak Factory',
  //   description: 'A haven for meat lovers, specializing in steaks and grills.',
  //   address: {
  //     street: 'Southern Avenue',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700029',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.049, baseLat - 0.054],
  //     },
  //   },
  //   contact: { phone: '9876570050', email: 'steakfactory@example.com' },
  //   cuisine_type: ['BBQ', 'Burgers', 'Dinner', 'Italian', 'Salads'],
  //   rating: 4.5,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Monday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 50,
  // },

  // seeded till here ;

  //   // --- Restaurants 51-60 ---
  // {
  //   name: 'Zen - The Park',
  //   description:
  //     'A high-end restaurant offering authentic Japanese, Thai, and Chinese cuisine.',
  //   address: {
  //     street: 'The Park Hotel, Park Street',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.022, baseLat - 0.033],
  //     },
  //   },
  //   contact: { phone: '9876570051', email: 'zen.kol@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Chinese', 'Dinner', 'Soups'],
  //   rating: 4.7,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Tuesday', open: '19:00', close: '23:45' }],
  //   is_active: true,
  //   min_order_value: 1500,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 4000,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Karma Kettle',
  //   description:
  //     'A specialty tea room offering a wide range of exotic teas and snacks.',
  //   address: {
  //     street: 'Ballygunge',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700019',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.044, baseLat - 0.044],
  //     },
  //   },
  //   contact: { phone: '9876570052', email: 'karmakettle@example.com' },
  //   cuisine_type: [
  //     'Beverages',
  //     'Breakfast',
  //     'Healthy',
  //     'Sandwiches',
  //     'Desserts',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Wednesday', open: '10:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Royal Indian Restaurant',
  //   description:
  //     'One of the oldest restaurants in Kolkata, famous for its Chaap and Biryani.',
  //   address: {
  //     street: 'Chitpur',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700073',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9876570053', email: 'royalindian@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch', 'BBQ'],
  //   rating: 4.4,
  //   numberOfReviews: 8100,
  //   opening_hours: [{ day: 'Thursday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Paris Cafe',
  //   description:
  //     'A charming Parisian-themed cafe with delightful desserts and coffee.',
  //   address: {
  //     street: 'Ballygunge',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700019',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.045, baseLat - 0.046],
  //     },
  //   },
  //   contact: { phone: '9876570054', email: 'pariscafe@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Breakfast', 'Italian', 'Pizza'],
  //   rating: 4.3,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Friday', open: '09:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Aaheli - The Peerless Inn',
  //   description:
  //     'A fine-dining restaurant offering an authentic Bengali thali experience.',
  //   address: {
  //     street: 'Jawaharlal Nehru Road',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700013',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.005, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9876570055', email: 'aaheli@peerless.com' },
  //   cuisine_type: ['Indian', 'South-Indian', 'Dinner', 'Lunch', 'Desserts'],
  //   rating: 4.5,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Saturday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 1000,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'The Salt House',
  //   description:
  //     'A contemporary restaurant with a focus on modern European and Bengali fusion.',
  //   address: {
  //     street: 'Shakespeare Sarani',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.029, baseLat - 0.039],
  //     },
  //   },
  //   contact: { phone: '9876570056', email: 'salthouse@example.com' },
  //   cuisine_type: ['Italian', 'Healthy', 'Salads', 'Dinner', 'Beverages'],
  //   rating: 4.6,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Denzong Kitchen',
  //   description:
  //     'A budget-friendly spot for delicious Tibetan food, especially momos.',
  //   address: {
  //     street: 'Jadavpur',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700032',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.031, baseLat - 0.071],
  //     },
  //   },
  //   contact: { phone: '9876570057', email: 'denzong@example.com' },
  //   cuisine_type: ['Chinese', 'Fast-Food', 'Soups', 'Street-Food', 'Dinner'],
  //   rating: 4.4,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 300,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Good-With-Food Co.',
  //   description: 'A dummy restaurant for healthy and vegan options.',
  //   address: {
  //     street: 'Salt Lake, Sector I',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700064',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.08, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9876570058', email: 'goodwithfood@example.com' },
  //   cuisine_type: ['Healthy', 'Vegan', 'Salads', 'Soups', 'Breakfast'],
  //   rating: 4.8,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Tuesday', open: '10:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Mexico-City',
  //   description: 'A dummy restaurant serving authentic Mexican street food.',
  //   address: {
  //     street: 'New Town, Action Area I',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700156',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.15, baseLat + 0.05],
  //     },
  //   },
  //   contact: { phone: '9876570059', email: 'mexicocity@example.com' },
  //   cuisine_type: ['Mexican', 'Fast-Food', 'Salads', 'Beverages', 'Dinner'],
  //   rating: 4.1,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Southy',
  //   description:
  //     'A dummy restaurant for quick and delicious South Indian meals.',
  //   address: {
  //     street: 'Behala',
  //     city: 'Kolkata',
  //     state: 'West Bengal',
  //     zip_code: '700034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat - 0.08],
  //     },
  //   },
  //   contact: { phone: '9876570060', email: 'southy@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Indian', 'Lunch', 'Healthy'],
  //   rating: 4.2,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Thursday', open: '07:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 30,
  // },

  // all these restaruants have been seeded
];

export default calcuttaRestaurants;
