// Base coordinates for Chennai (approx center)
const baseLat = 13.0827;
const baseLon = 80.2707;
/**
 * Data structure for restaurants in Chennai, ensuring wide coverage of all 24 supported cuisine types.
 * 50 restaurants are generated to ensure at least 9-10 restaurants are available for every supported category.
 */
const chennaiRestaurants = [
  // --- Restaurants 1-10 ---
  // {
  //   name: 'Murugan Idli Shop',
  //   description:
  //     'Legendary South Indian breakfast & lunch place, especially known for idli, dosa & filter coffee.',
  //   address: {
  //     street: 'Besant Nagar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600090',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9876580001', email: 'muruganidli.chen@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Breakfast',
  //     'Indian',
  //     'Lunch',
  //     'Street-Food',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 12000,
  //   opening_hours: [{ day: 'Monday', open: '06:30', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Annalakshmi Restaurant',
  //   description:
  //     'Vegetarian restaurant offering wholesome North & South Indian meals in a temple-style ambiance.',
  //   address: {
  //     street: 'Nungambakkam',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9876580002', email: 'annalakshmi.chen@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'South-Indian',
  //     'Indian',
  //     'Indian-Sweets',
  //     'Desserts',
  //     'Dinner',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 8500,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Tuscana Pizzeria',
  //   description:
  //     'Fine Italian & wood-fired pizzas, pasta and a cozy ambience in Chennai.',
  //   address: {
  //     street: 'Adyar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600020',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876580003', email: 'tuscana.chen@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Desserts', 'Beverages', 'Salads'],
  //   rating: 4.3,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'BurgerMan',
  //   description:
  //     'Serves gourmet pizzas, sandwiches, burgers & shakes with a modern twist.',
  //   address: {
  //     street: 'Besant Nagar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600090',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.012, baseLat - 0.022],
  //     },
  //   },
  //   contact: { phone: '9876580004', email: 'burgerman.chen@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Sandwiches',
  //     'Beverages',
  //     'Dinner',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Thursday', open: '11:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'KooX Rooftop Asian Grill',
  //   description:
  //     'Trendy rooftop spot with Pan-Asian, sushi, Chinese, Japanese & BBQ offerings.',
  //   address: {
  //     street: 'Nandanam',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600035',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9876580005', email: 'koox.chen@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Chinese', 'BBQ', 'Dinner', 'Beverages'],
  //   rating: 4.4,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Friday', open: '17:00', close: '23:59' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Ratna Café',
  //   description:
  //     'Classic South-Indian & breakfast café, famous for idli, dosa, filter coffee.',
  //   address: {
  //     street: 'Triplicane',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.001, baseLat + 0.001],
  //     },
  //   },
  //   contact: { phone: '9876580006', email: 'ratnacafe.chen@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Lunch', 'Indian', 'Beverages'],
  //   rating: 4.1,
  //   numberOfReviews: 11000,
  //   opening_hours: [{ day: 'Saturday', open: '06:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Sandy’s Chocolate Laboratory',
  //   description:
  //     'Dessert heaven with ice creams, waffles, chocolate creations & beverages.',
  //   address: {
  //     street: 'Nungambakkam',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.012, baseLat + 0.006],
  //     },
  //   },
  //   contact: { phone: '9876580007', email: 'sandys.chen@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Fast-Food', 'Breakfast'],
  //   rating: 4.5,
  //   numberOfReviews: 7200,
  //   opening_hours: [{ day: 'Sunday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Leaf',
  //   description:
  //     'Healthy café offering salads, smoothie bowls, wraps, vegan & gluten free options.',
  //   address: {
  //     street: 'Sholinganallur',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600119',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9876580008', email: 'theleaf.chen@example.com' },
  //   cuisine_type: ['Healthy', 'Vegan', 'Salads', 'Beverages', 'Lunch', 'Soups'],
  //   rating: 4.2,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 10,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Roll Baby Roll',
  //   description:
  //     'Street-food style roll & wrap joint serving Indian, Mexican and fusion rolls.',
  //   address: {
  //     street: 'T. Nagar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9876580009', email: 'rollbaby.chen@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Indian',
  //     'Mexican',
  //     'Fast-Food',
  //     'North-Indian',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 3000,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 350,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'The Dragon',
  //   description:
  //     'Modern place for Chinese, sushi, soups and Asian fusion dinners.',
  //   address: {
  //     street: 'Nungambakkam',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.011, baseLat + 0.007],
  //     },
  //   },
  //   contact: { phone: '9876580010', email: 'thedragon.chen@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Sushi', 'Dinner', 'Soups', 'BBQ'],
  //   rating: 4.3,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1300,
  //   delivery_time_mins: 45,
  // },
  // --- Restaurants 11-20 ---
  // {
  //   name: 'Dindigul Thalappakatti',
  //   description:
  //     'Famous for its unique style of biryani and traditional Tamil Nadu cuisine.',
  //   address: {
  //     street: 'Anna Nagar East',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600102',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9876580011', email: 'thalappakatti.chen@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ'],
  //   rating: 4.1,
  //   numberOfReviews: 15000,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Amelie’s Cafe & Creamery',
  //   description:
  //     'A charming cafe known for its desserts, ice creams, and continental snacks.',
  //   address: {
  //     street: 'Alwarpet',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600018',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9876580012', email: 'amelies.chen@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Beverages',
  //     'Breakfast',
  //     'Fast-Food',
  //     'Sandwiches',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Friday', open: '10:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 750,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Flying Elephant',
  //   description:
  //     'A multi-level fine-dining restaurant with a global culinary offering.',
  //   address: {
  //     street: 'Park Hyatt, Guindy',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600032',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9876580013', email: 'flyingelephant.chen@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Italian',
  //     'Japanese',
  //     'Dinner',
  //     'BBQ',
  //     'Sushi',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Saturday', open: '18:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 1500,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 3500,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Nair Mess',
  //   description:
  //     'An iconic, no-frills mess serving authentic Chettinad meals on a banana leaf.',
  //   address: {
  //     street: 'Triplicane',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.002, baseLat + 0.002],
  //     },
  //   },
  //   contact: { phone: '9876580014', email: 'nairmess.chen@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Lunch', 'Dinner'],
  //   rating: 4.5,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '16:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Taco Bell',
  //   description:
  //     'Fast-food chain serving Mexican-inspired fare like tacos and burritos.',
  //   address: {
  //     street: 'Express Avenue Mall, Royapettah',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600014',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon, baseLat],
  //     },
  //   },
  //   contact: { phone: '9876580015', email: 'tacobell.chen@example.com' },
  //   cuisine_type: ['Mexican', 'Fast-Food', 'Dinner', 'Lunch', 'Beverages'],
  //   rating: 4.0,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Sangeetha Veg Restaurant',
  //   description:
  //     'A popular chain for high-quality vegetarian South Indian and North Indian food.',
  //   address: {
  //     street: 'Velachery',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600042',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.005, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9876580016', email: 'sangeetha.chen@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'North-Indian',
  //     'Indian',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 18000,
  //   opening_hours: [{ day: 'Tuesday', open: '07:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Barbeque Nation',
  //   description:
  //     'The original live-on-the-table grill restaurant with a lavish buffet.',
  //   address: {
  //     street: 'T. Nagar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.018, baseLat - 0.007],
  //     },
  //   },
  //   contact: { phone: '9876580017', email: 'bbqnation.chen@example.com' },
  //   cuisine_type: [
  //     'BBQ',
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Desserts',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 14000,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'A2B - Adyar Ananda Bhavan',
  //   description:
  //     'A massive chain serving a wide range of South Indian, North Indian, and Chinese vegetarian food.',
  //   address: {
  //     street: 'Adyar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600020',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.011, baseLat - 0.011],
  //     },
  //   },
  //   contact: { phone: '9876580018', email: 'a2b.chen@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'North-Indian',
  //     'Chinese',
  //     'Indian-Sweets',
  //     'Breakfast',
  //     'Street-Food',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 19500,
  //   opening_hours: [{ day: 'Thursday', open: '07:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 450,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Old Madras Baking Company',
  //   description:
  //     'Artisanal bakery known for its fresh breads, croissants, and coffee.',
  //   address: {
  //     street: 'Alwarpet',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600018',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.006, baseLat - 0.009],
  //     },
  //   },
  //   contact: { phone: '9876580019', email: 'ombc.chen@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Breakfast',
  //     'Sandwiches',
  //     'Beverages',
  //     'Healthy',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Friday', open: '08:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Pantry d’or',
  //   description:
  //     'A European-style cafe with a focus on desserts, pasta, and baked goods.',
  //   address: {
  //     street: 'Anna Nagar East',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600102',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.022, baseLat + 0.022],
  //     },
  //   },
  //   contact: { phone: '9876580020', email: 'pantrydor.chen@example.com' },
  //   cuisine_type: ['Italian', 'Desserts', 'Pizza', 'Beverages', 'Breakfast'],
  //   rating: 4.1,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Saturday', open: '09:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // // --- Restaurants 21-30 ---
  // {
  //   name: 'Absolute Thai',
  //   description:
  //     'Authentic Thai cuisine with a focus on curries, noodles, and street food.',
  //   address: {
  //     street: 'Cenotaph Road, Teynampet',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600018',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.008, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9876580021', email: 'absolutethai.chen@example.com' },
  //   cuisine_type: ['Chinese', 'Soups', 'Dinner', 'Lunch', 'Healthy'],
  //   rating: 4.4,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Hamsa',
  //   description:
  //     'A fine-dining vegetarian restaurant serving royal Indian cuisine.',
  //   address: {
  //     street: 'Adyar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600020',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.013, baseLat - 0.013],
  //     },
  //   },
  //   contact: { phone: '9876580022', email: 'hamsa.chen@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Desserts',
  //     'Indian-Sweets',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'The Fruit Shop on Greams Road',
  //   description:
  //     'A legendary juice and milkshake bar, famous for its fresh fruit creations.',
  //   address: {
  //     street: 'Greams Road, Thousand Lights',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.009, baseLat + 0.009],
  //     },
  //   },
  //   contact: { phone: '9876580023', email: 'fruitshop.chen@example.com' },
  //   cuisine_type: ['Beverages', 'Desserts', 'Healthy', 'Vegan'],
  //   rating: 4.7,
  //   numberOfReviews: 15000,
  //   opening_hours: [{ day: 'Tuesday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Kaidi Kitchen',
  //   description:
  //     'A unique jail-themed vegetarian restaurant serving multi-cuisine food.',
  //   address: {
  //     street: 'Mylapore',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.005, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9876580024', email: 'kaidi.chen@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Italian',
  //     'Mexican',
  //     'Chinese',
  //     'Vegan',
  //     'Dinner',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 5800,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1300,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Mainland China',
  //   description:
  //     'A fine-dining restaurant offering authentic cuisine from major provinces of China.',
  //   address: {
  //     street: 'Nungambakkam',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.013, baseLat + 0.008],
  //     },
  //   },
  //   contact: { phone: '9876580025', email: 'mainlandchina.chen@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Dinner', 'Lunch', 'Soups', 'Sushi'],
  //   rating: 4.5,
  //   numberOfReviews: 5200,
  //   opening_hours: [{ day: 'Thursday', open: '12:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Eatza Pizza',
  //   description:
  //     'A budget-friendly pizza place with a variety of local and classic toppings.',
  //   address: {
  //     street: 'Porur',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600116',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876580026', email: 'eatza.chen@example.com' },
  //   cuisine_type: ['Pizza', 'Fast-Food', 'Italian', 'Beverages'],
  //   rating: 3.8,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Burger Club',
  //   description:
  //     'A gourmet burger joint with a focus on fresh ingredients and unique sauces.',
  //   address: {
  //     street: 'OMR Food Street, Navalur',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600130',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9876580027', email: 'burgerclub.chen@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Sandwiches', 'Beverages', 'Dinner'],
  //   rating: 4.3,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Sree Gupta Bhavan',
  //   description:
  //     'A famous sweet shop offering a wide range of North and South Indian sweets and snacks.',
  //   address: {
  //     street: 'T. Nagar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.016, baseLat - 0.006],
  //     },
  //   },
  //   contact: { phone: '9876580028', email: 'guptabhavan.chen@example.com' },
  //   cuisine_type: [
  //     'Indian-Sweets',
  //     'Desserts',
  //     'Street-Food',
  //     'Fast-Food',
  //     'Indian',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 8800,
  //   opening_hours: [{ day: 'Sunday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Noodle Theory',
  //   description:
  //     'A casual dining spot for customizable Asian noodle bowls and appetizers.',
  //   address: {
  //     street: 'Velachery',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600042',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.008, baseLat - 0.032],
  //     },
  //   },
  //   contact: { phone: '9876580029', email: 'noodletheory.chen@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Soups', 'Healthy', 'Dinner', 'Lunch'],
  //   rating: 4.1,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Royal Indianaa',
  //   description:
  //     'A fine-dining restaurant at The Accord Metropolitan serving authentic Indian cuisines.',
  //   address: {
  //     street: 'The Accord Metropolitan, T. Nagar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.019, baseLat - 0.009],
  //     },
  //   },
  //   contact: { phone: '9876580030', email: 'royalindiana.chen@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'South-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Desserts',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Tuesday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 900,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // // --- Restaurants 31-40 ---
  // {
  //   name: 'The Vegan Engine',
  //   description:
  //     'A 100% plant-based cafe offering creative and delicious vegan dishes.',
  //   address: {
  //     street: 'Alwarpet',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600018',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.007, baseLat - 0.007],
  //     },
  //   },
  //   contact: { phone: '9876580031', email: 'veganengine.chen@example.com' },
  //   cuisine_type: [
  //     'Vegan',
  //     'Healthy',
  //     'Salads',
  //     'Desserts',
  //     'Burgers',
  //     'Italian',
  //   ],
  //   rating: 4.8,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Drizzle’s',
  //   description:
  //     'A popular spot for sizzlers, steaks, and continental food.',
  //   address: {
  //     street: 'Anna Nagar East',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600102',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '9876580032', email: 'drizzles.chen@example.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Dinner', 'Lunch', 'Soups'],
  //   rating: 4.2,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Ciclo Cafe',
  //   description:
  //     'A unique cycle-themed cafe serving European and American food.',
  //   address: {
  //     street: 'Kotturpuram',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600085',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.002, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9876580033', email: 'ciclo.chen@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Burgers',
  //     'Sandwiches',
  //     'Breakfast',
  //     'Beverages',
  //     'Healthy',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Friday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Hoppipola',
  //   description:
  //     'A fun, casual bar with games, vibrant decor, and a multi-cuisine menu.',
  //   address: {
  //     street: 'Nungambakkam',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.014, baseLat + 0.004],
  //     },
  //   },
  //   contact: { phone: '9876580034', email: 'hoppipola.chen@example.com' },
  //   cuisine_type: [
  //     'Fast-Food',
  //     'Pizza',
  //     'Burgers',
  //     'Beverages',
  //     'Dinner',
  //     'Mexican',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 4100,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 48,
  // },
  // {
  //   name: 'Kakada Ramprasad',
  //   description:
  //     'A famous spot in Sowcarpet for authentic North Indian sweets and chaat.',
  //   address: {
  //     street: 'Sowcarpet',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600079',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9876580035', email: 'kakada.chen@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Indian-Sweets',
  //     'Desserts',
  //     'North-Indian',
  //     'Beverages',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 7500,
  //   opening_hours: [{ day: 'Sunday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Marina',
  //   description:
  //     'A fine-dining restaurant specializing in fresh seafood and coastal cuisine.',
  //   address: {
  //     street: 'Nungambakkam',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.008],
  //     },
  //   },
  //   contact: { phone: '9876580036', email: 'themarina.chen@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'BBQ', 'Soups'],
  //   rating: 4.4,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Pumpkin Tales',
  //   description:
  //     'A family-friendly cafe with a global menu and a dedicated play area for kids.',
  //   address: {
  //     street: 'Alwarpet',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600018',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.004, baseLat - 0.006],
  //     },
  //   },
  //   contact: { phone: '9876580037', email: 'pumpkin.chen@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Breakfast',
  //     'Italian',
  //     'Salads',
  //     'Sandwiches',
  //     'Beverages',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Tuesday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Writer’s Cafe',
  //   description:
  //     'A cozy cafe with a library, supporting a good cause, and serving simple, tasty food.',
  //   address: {
  //     street: 'Gopalapuram',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600086',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.001, baseLat - 0.001],
  //     },
  //   },
  //   contact: { phone: '9876580038', email: 'writerscafe.chen@example.com' },
  //   cuisine_type: [
  //     'Breakfast',
  //     'Sandwiches',
  //     'Desserts',
  //     'Beverages',
  //     'Fast-Food',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Wednesday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Pakwan Chennai',
  //   description:
  //     'A royal vegetarian dining experience with a lavish North Indian menu.',
  //   address: {
  //     street: 'T. Nagar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.017, baseLat - 0.007],
  //     },
  //   },
  //   contact: { phone: '9876580039', email: 'pakwan.chen@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Desserts',
  //     'Indian-Sweets',
  //     'Vegan',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 6200,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 48,
  // },
  // {
  //   name: 'The Sushi Haus',
  //   description:
  //     'A delivery-focused kitchen for affordable and fresh sushi rolls.',
  //   address: {
  //     street: 'Cloud Kitchen, Alwarpet',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600018',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876580040', email: 'sushihaus.chen@example.com' },
  //   cuisine_type: ['Sushi', 'Japanese', 'Soups', 'Healthy'],
  //   rating: 4.1,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 45,
  // },
  // // --- Restaurants 41-50 ---
  // {
  //   name: 'Ente Keralam',
  //   description:
  //     'A fine-dining restaurant offering authentic cuisine from the heart of Kerala.',
  //   address: {
  //     street: 'Poes Garden',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600086',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.003, baseLat - 0.003],
  //     },
  //   },
  //   contact: { phone: '9876580041', email: 'entekeralam.chen@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'Healthy'],
  //   rating: 4.5,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Chili’s American Grill & Bar',
  //   description:
  //     'American casual dining with a Tex-Mex twist, famous for burgers and fajitas.',
  //   address: {
  //     street: 'Express Avenue Mall',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600014',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.001, baseLat + 0.001],
  //     },
  //   },
  //   contact: { phone: '9876580042', email: 'chilis.chen@example.com' },
  //   cuisine_type: ['Mexican', 'Burgers', 'BBQ', 'Dinner', 'Beverages', 'Salads'],
  //   rating: 4.3,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1700,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Bombay Lassi',
  //   description:
  //     'A small, popular spot for thick, creamy lassis and other milk-based drinks.',
  //   address: {
  //     street: 'Triplicane',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.003, baseLat + 0.003],
  //     },
  //   },
  //   contact: { phone: '9876580043', email: 'bombaylassi.chen@example.com' },
  //   cuisine_type: ['Beverages', 'Desserts', 'Indian-Sweets', 'Street-Food'],
  //   rating: 4.6,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 150,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'The Soup Mill',
  //   description:
  //     'A healthy food joint specializing in a wide variety of global soups.',
  //   address: {
  //     street: 'Kilpauk',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600010',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9876580044', email: 'soupmill.chen@example.com' },
  //   cuisine_type: ['Soups', 'Healthy', 'Salads', 'Vegan', 'Lunch'],
  //   rating: 4.2,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Keventers',
  //   description:
  //     'A legendary brand serving classic and flavored milkshakes in iconic glass bottles.',
  //   address: {
  //     street: 'Besant Nagar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600090',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.014, baseLat - 0.021],
  //     },
  //   },
  //   contact: { phone: '9876580045', email: 'keventers.chen@example.com' },
  //   cuisine_type: ['Beverages', 'Desserts', 'Fast-Food', 'Indian-Sweets'],
  //   rating: 4.1,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Anjappar Chettinad',
  //   description:
  //     'A global chain famous for its authentic and spicy Chettinad cuisine.',
  //   address: {
  //     street: 'Nungambakkam',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.011, baseLat + 0.009],
  //     },
  //   },
  //   contact: { phone: '9876580046', email: 'anjappar.chen@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ'],
  //   rating: 4.3,
  //   numberOfReviews: 11000,
  //   opening_hours: [{ day: 'Thursday', open: '11:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Little Italy',
  //   description:
  //     'A fine-dining vegetarian restaurant serving authentic Italian and Mexican food.',
  //   address: {
  //     street: 'Besant Nagar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600090',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.016, baseLat - 0.023],
  //     },
  //   },
  //   contact: { phone: '9876580047', email: 'littleitaly.chen@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Pizza',
  //     'Mexican',
  //     'Vegan',
  //     'Dinner',
  //     'Desserts',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Cream Centre',
  //   description:
  //     'A popular vegetarian restaurant known for its sizzlers, nachos, and channa bhatura.',
  //   address: {
  //     street: 'Nungambakkam',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.007],
  //     },
  //   },
  //   contact: { phone: '9876580048', email: 'creamcentre.chen@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Mexican',
  //     'Italian',
  //     'Fast-Food',
  //     'Dinner',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 6800,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Kobe Sizzlers',
  //   description:
  //     'A classic restaurant chain famous for its wide variety of sizzlers.',
  //   address: {
  //     street: 'Phoenix Marketcity, Velachery',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600042',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.006, baseLat - 0.031],
  //     },
  //   },
  //   contact: { phone: '9876580049', email: 'kobe.chen@example.com' },
  //   cuisine_type: ['BBQ', 'Italian', 'Mexican', 'Dinner', 'Soups'],
  //   rating: 4.3,
  //   numberOfReviews: 4100,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1300,
  //   delivery_time_mins: 48,
  // },
  // {
  //   name: 'Wow! Momo',
  //   description:
  //     'A fast-food chain specializing in a wide variety of momos, from steamed to fried to sizzlers.',
  //   address: {
  //     street: 'Anna Nagar',
  //     city: 'Chennai',
  //     state: 'Tamil Nadu',
  //     zip_code: '600040',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.028, baseLat + 0.028],
  //     },
  //   },
  //   contact: { phone: '9876580050', email: 'wowmomo.chen@example.com' },
  //   cuisine_type: ['Chinese', 'Fast-Food', 'Street-Food', 'Soups', 'Dinner'],
  //   rating: 4.0,
  //   numberOfReviews: 7500,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // all of the restaurants have been seeded
];

export default chennaiRestaurants;
