// Base coordinates for New Delhi (approximate center: Connaught Place)
const baseLat = 28.6448;
const baseLon = 77.2167;

const delhiRestaurants = [
  // --- Restaurants 1-10 (Iconic & North Indian) ---
  // {
  //   name: "Karim's",
  //   description:
  //     'An iconic Old Delhi institution, serving authentic Mughlai food since 1913. Famous for Nihari and Kebabs.',
  //   address: {
  //     street: 'Jama Masjid, Old Delhi',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9001120001', email: 'karims.delhi@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'BBQ',
  //     'Dinner',
  //     'Lunch',
  //     'Street-Food',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 18000,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Bukhara',
  //   description:
  //     'A world-renowned fine-dining restaurant at ITC Maurya, famous for Dal Bukhara and Frontier Cuisine.',
  //   address: {
  //     street: 'Chanakyapuri',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110021',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9001120002', email: 'bukhara.itc@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ'],
  //   rating: 4.8,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Tuesday', open: '12:30', close: '23:45' }],
  //   is_active: true,
  //   min_order_value: 2500,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 6500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Indian Accent',
  //   description:
  //     'Contemporary Indian cuisine with a global twist, located at The Lodhi Hotel.',
  //   address: {
  //     street: 'Lodhi Road',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9001120003', email: 'accent.del@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'North-Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Healthy',
  //     'Beverages',
  //   ],
  //   rating: 4.9,
  //   numberOfReviews: 7000,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 1500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 4000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: "Leo's Artisan Pizza",
  //   description:
  //     'One of the best pizzerias in Delhi, focusing on authentic Neapolitan wood-fired pizzas.',
  //   address: {
  //     street: 'Vasant Vihar',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110057',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat - 0.06],
  //     },
  //   },
  //   contact: { phone: '9001120004', email: 'leospizza@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Dinner', 'Lunch', 'Fast-Food'],
  //   rating: 4.6,
  //   numberOfReviews: 5200,
  //   opening_hours: [{ day: 'Thursday', open: '13:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Olive Bar & Kitchen',
  //   description:
  //     'Charming Mediterranean-inspired restaurant near Qutub Minar, perfect for a romantic evening.',
  //   address: {
  //     street: 'Mehrauli',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110030',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat - 0.08],
  //     },
  //   },
  //   contact: { phone: '9001120005', email: 'olive.qutub@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Dinner', 'Salads', 'Healthy'],
  //   rating: 4.7,
  //   numberOfReviews: 8800,
  //   opening_hours: [{ day: 'Friday', open: '12:30', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 1000,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 3500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'The Big Chill Cafe',
  //   description:
  //     'A favourite cafe chain known for its Pasta, Shakes, and decadent desserts.',
  //   address: {
  //     street: 'Khan Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9001120006', email: 'bigchill@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Desserts',
  //     'Sandwiches',
  //     'Lunch',
  //     'Dinner',
  //     'Beverages',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 10500,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Potbelly',
  //   description:
  //     'A cozy spot offering authentic regional Indian cuisine from Bihar and Jharkhand.',
  //   address: {
  //     street: '114, Shahpur Jat',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110049',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat - 0.08],
  //     },
  //   },
  //   contact: { phone: '9001120020', email: 'potbelly@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Healthy',
  //     'Breakfast',
  //     'North-Indian',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Saturday', open: '10:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Guppy',
  //   description:
  //     'Contemporary Japanese eatery in Lodhi Colony, known for its Sushi and quirky decor.',
  //   address: {
  //     street: 'Lodhi Colony Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.012, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9001120007', email: 'guppy.del@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Chinese', 'Dinner', 'Lunch', 'Soups'],
  //   rating: 4.6,
  //   numberOfReviews: 4100,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 2800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: "Berco's",
  //   description:
  //     'A classic Delhi spot for affordable and popular Indo-Chinese food.',
  //   address: {
  //     street: 'Connaught Place',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon, baseLat],
  //     },
  //   },
  //   contact: { phone: '9001120008', email: 'bercos@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Japanese',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //     'Beverages',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 11200,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 450,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Hauz Khas Social',
  //   description:
  //     'A popular workspace/café and bar known for its eclectic menu and scenic location.',
  //   address: {
  //     street: 'Hauz Khas Village',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat - 0.07],
  //     },
  //   },
  //   contact: { phone: '9001120009', email: 'social.hk@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Mexican',
  //     'Dinner',
  //     'Lunch',
  //     'Beverages',
  //     'Fast-Food',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 6800,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 50,
  // },
  // --- Restaurants 11-20 (Street Food & Veg) ---
  // {
  //   name: "Haldiram's",
  //   description:
  //     'A quick-service outlet famous for Chole Bhature, Indian snacks (chaat), and sweets.',
  //   address: {
  //     street: 'Connaught Place',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9001120010', email: 'haldirams@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Indian-Sweets',
  //     'North-Indian',
  //     'Breakfast',
  //     'Desserts',
  //     'Vegan',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 15400,
  //   opening_hours: [{ day: 'Wednesday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Kake Di Hatti',
  //   description:
  //     'A legendary vegetarian restaurant in Old Delhi known for its massive, fluffy Naans and rich curries.',
  //   address: {
  //     street: 'Chandni Chowk',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.045, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9001120011', email: 'kakedihatticw@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Street-Food',
  //     'Breakfast',
  //     'Vegan',
  //     'Lunch',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 9200,
  //   opening_hours: [{ day: 'Thursday', open: '09:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Saravana Bhavan',
  //   description:
  //     'The international chain for authentic South-Indian vegetarian delights like Dosas and Idlis.',
  //   address: {
  //     street: 'Janpath',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.002, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9001120012', email: 'sarvana.jan@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Breakfast',
  //     'Vegan',
  //     'Lunch',
  //     'Healthy',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 11000,
  //   opening_hours: [{ day: 'Friday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 750,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Moti Mahal Delux',
  //   description:
  //     'Claiming the origin of Butter Chicken, this Daryaganj classic offers timeless Mughlai flavors.',
  //   address: {
  //     street: 'Daryaganj',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9001120013', email: 'motimahal.dar@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'BBQ',
  //     'Fast-Food',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 7600,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Big Yellow Door (BYD)',
  //   description:
  //     'A popular youth hangout famous for budget-friendly burgers, pasta, and shakes.',
  //   address: {
  //     street: 'GTB Nagar',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat + 0.05],
  //     },
  //   },
  //   contact: { phone: '9001120014', email: 'byd.gtb@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Sandwiches',
  //     'Desserts',
  //     'Beverages',
  //     'Italian',
  //     'Fast-Food',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 13500,
  //   opening_hours: [{ day: 'Sunday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Yum Yum Cha',
  //   description:
  //     'Colorful and modern spot for pan-Asian cuisine, including dim sum, sushi, and fun molecular mocktails.',
  //   address: {
  //     street: 'Khan Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.011, baseLat - 0.012],
  //     },
  //   },
  //   contact: { phone: '9001120015', email: 'yyc.km@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Sushi', 'Lunch', 'Dinner', 'Soups'],
  //   rating: 4.5,
  //   numberOfReviews: 6100,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 750,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 2100,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Pind Balluchi',
  //   description:
  //     'North Indian restaurant with a village theme, known for its extensive Tandoori menu and Punjabi food.',
  //   address: {
  //     street: 'Connaught Place',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.001, baseLat + 0.001],
  //     },
  //   },
  //   contact: { phone: '9001120016', email: 'pind.balluchi@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'BBQ',
  //     'Dinner',
  //     'Lunch',
  //     'Street-Food',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 8900,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1300,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: "Elma's Bakery, Bar and Kitchen",
  //   description:
  //     'Vintage-style cafe offering delicious European breakfast, high tea, and comfort food.',
  //   address: {
  //     street: 'Mehar Chand Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9001120017', email: 'elmas@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Breakfast',
  //     'Beverages',
  //     'Sandwiches',
  //     'Italian',
  //     'Salads',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Wednesday', open: '09:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 1700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Johnny Rockets',
  //   description:
  //     'Classic American diner experience serving thick burgers, fries, and hand-spun shakes.',
  //   address: {
  //     street: 'Select City Walk Mall, Saket',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat - 0.1],
  //     },
  //   },
  //   contact: { phone: '9001120018', email: 'jr.saket@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Desserts',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Carnatic Cafe',
  //   description:
  //     'Highly-rated South Indian cafe known for its unique, thin, and crispy Dosas.',
  //   address: {
  //     street: 'Greater Kailash (GK) 2',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110048',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat - 0.06],
  //     },
  //   },
  //   contact: { phone: '9001120019', email: 'carnatic.gk@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Breakfast',
  //     'Vegan',
  //     'Lunch',
  //     'Healthy',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 4900,
  //   opening_hours: [{ day: 'Friday', open: '08:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 850,
  //   delivery_time_mins: 35,
  // },
  // seeded till here
  // // --- Restaurants 21-30 (More Variety) ---
  // {
  //   name: 'The Potbelly',
  //   description:
  //     'A cozy spot offering authentic regional Indian cuisine from Bihar and Jharkhand.',
  //   address: {
  //     street: 'Shahpur Jat',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110049',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat - 0.08],
  //     },
  //   },
  //   contact: { phone: '9001120020', email: 'potbelly@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Healthy',
  //     'Breakfast',
  //     'North-Indian',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Saturday', open: '10:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Wenger\'s Deli',
  //   description:
  //     'An iconic deli in Connaught Place, famous for its sandwiches, pastries, and shakes.',
  //   address: {
  //     street: 'A-Block, Connaught Place',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.003, baseLat - 0.003],
  //     },
  //   },
  //   contact: { phone: '9001120021', email: 'wengers@example.com' },
  //   cuisine_type: [
  //     'Sandwiches',
  //     'Desserts',
  //     'Breakfast',
  //     'Beverages',
  //     'Fast-Food',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 8500,
  //   opening_hours: [{ day: 'Sunday', open: '10:30', close: '20:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Al Jawahar',
  //   description:
  //     'Located opposite Karim\'s, another legendary spot for authentic Mughlai food.',
  //   address: {
  //     street: 'Jama Masjid, Old Delhi',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.041, baseLat + 0.021],
  //     },
  //   },
  //   contact: { phone: '9001120022', email: 'aljawahar@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'BBQ',
  //     'Street-Food',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 12000,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Diggin',
  //   description:
  //     'A beautiful cafe with a romantic ambiance, serving Italian food and desserts.',
  //   address: {
  //     street: 'Anand Lok',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110049',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat - 0.07],
  //     },
  //   },
  //   contact: { phone: '9001120023', email: 'diggin@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Pizza',
  //     'Desserts',
  //     'Beverages',
  //     'Salads',
  //     'Dinner',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 9800,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Paranthe Wali Gali',
  //   description:
  //     'A representation of the famous lane in Chandni Chowk, serving deep-fried parathas.',
  //   address: {
  //     street: 'Chandni Chowk',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.048, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9001120024', email: 'paranthegali@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'North-Indian',
  //     'Breakfast',
  //     'Indian',
  //     'Vegan',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 11500,
  //   opening_hours: [{ day: 'Wednesday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Kuremal Mohan Lal Kulfi Wale',
  //   description:
  //     'An iconic spot for unique and delicious fruit-stuffed kulfis.',
  //   address: {
  //     street: 'Sitaram Bazar, Chandni Chowk',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.042, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9001120025', email: 'kuremal@example.com' },
  //   cuisine_type: ['Desserts', 'Indian-Sweets', 'Street-Food', 'Vegan'],
  //   rating: 4.8,
  //   numberOfReviews: 8200,
  //   opening_hours: [{ day: 'Thursday', open: '10:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Rajinder Da Dhaba',
  //   description:
  //     'A legendary dhaba-style eatery famous for its Galouti Kebabs and non-veg curries.',
  //   address: {
  //     street: 'Safdarjung Enclave Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110029',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat - 0.06],
  //     },
  //   },
  //   contact: { phone: '9001120026', email: 'rajinderdhaba@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'BBQ',
  //     'Street-Food',
  //     'Dinner',
  //     'Indian',
  //     'Lunch',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 14000,
  //   opening_hours: [{ day: 'Friday', open: '16:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Sita Ram Diwan Chand',
  //   description:
  //     'A legendary spot in Paharganj, famous for serving one of the best Chole Bhature in Delhi.',
  //   address: {
  //     street: 'Paharganj',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110055',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9001120027', email: 'sitaram@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'North-Indian',
  //     'Breakfast',
  //     'Lunch',
  //     'Indian',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 16500,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '18:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Pa Pa Ya',
  //   description:
  //     'A modern Asian bistro offering a radical take on Asian cuisine with sushi and more.',
  //   address: {
  //     street: 'Select City Walk Mall, Saket',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.041, baseLat - 0.101],
  //     },
  //   },
  //   contact: { phone: '9001120028', email: 'papaya.del@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Chinese', 'Dinner', 'Desserts'],
  //   rating: 4.6,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'The Grammar Room',
  //   description:
  //     'A beautiful, serene cafe overlooking the Qutub Minar, perfect for coffee and brunch.',
  //   address: {
  //     street: 'Mehrauli',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110030',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.042, baseLat - 0.082],
  //     },
  //   },
  //   contact: { phone: '9001120029', email: 'grammarroom@example.com' },
  //   cuisine_type: [
  //     'Breakfast',
  //     'Healthy',
  //     'Beverages',
  //     'Salads',
  //     'Sandwiches',
  //     'Desserts',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 45,
  // },
  // // --- Restaurants 31-40 (Category Fillers) ---
  // {
  //   name: 'Gulati Restaurant',
  //   description:
  //     'A well-known restaurant at Pandara Road, famous for its North Indian buffet and Butter Chicken.',
  //   address: {
  //     street: 'Pandara Road Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9001120030', email: 'gulati@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'BBQ',
  //     'Desserts',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 7800,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Artusi Ristorante',
  //   description:
  //     'An authentic Italian fine-dining restaurant specializing in cuisine from the Emilia-Romagna region.',
  //   address: {
  //     street: 'Greater Kailash (GK) 2',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110048',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.022, baseLat - 0.062],
  //     },
  //   },
  //   contact: { phone: '9001120031', email: 'artusi@example.com' },
  //   cuisine_type: ['Italian', 'Dinner', 'Soups', 'Salads', 'Desserts'],
  //   rating: 4.8,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Wednesday', open: '13:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 1200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 3500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Nathu\'s Sweets',
  //   description:
  //     'A popular chain for sweets, chaat, and vegetarian North & South Indian meals.',
  //   address: {
  //     street: 'Bengali Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.008, baseLat + 0.008],
  //     },
  //   },
  //   contact: { phone: '9001120032', email: 'nathus@example.com' },
  //   cuisine_type: [
  //     'Indian-Sweets',
  //     'Street-Food',
  //     'North-Indian',
  //     'South-Indian',
  //     'Desserts',
  //     'Breakfast',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Thursday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The All American Diner',
  //   description:
  //     'A retro-style diner at India Habitat Centre, serving classic American breakfast, burgers, and shakes.',
  //   address: {
  //     street: 'India Habitat Centre, Lodhi Road',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.018, baseLat - 0.028],
  //     },
  //   },
  //   contact: { phone: '9001120033', email: 'americandiner@example.com' },
  //   cuisine_type: [
  //     'Breakfast',
  //     'Burgers',
  //     'Sandwiches',
  //     'Beverages',
  //     'Desserts',
  //     'Fast-Food',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 6200,
  //   opening_hours: [{ day: 'Friday', open: '07:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Fabcafe by Fabindia',
  //   description:
  //     'A cafe focusing on healthy, organic, and modern Indian food without refined sugar or oil.',
  //   address: {
  //     street: 'Vasant Kunj',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110070',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.06, baseLat - 0.08],
  //     },
  //   },
  //   contact: { phone: '9001120034', email: 'fabcafe.del@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Vegan',
  //     'Salads',
  //     'Breakfast',
  //     'Indian',
  //     'Soups',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Saturday', open: '08:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 1300,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Burger Singh',
  //   description:
  //     'Indian burger chain with a fusion of local flavors and classic burgers.',
  //   address: {
  //     street: 'Connaught Place',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.004, baseLat - 0.004],
  //     },
  //   },
  //   contact: { phone: '9001120035', email: 'burgersingh.del@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'North-Indian',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 7500,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Giani\'s Di Hatti',
  //   description:
  //     'An old and famous spot in Chandni Chowk for Rabri Falooda and other traditional desserts.',
  //   address: {
  //     street: 'Chandni Chowk',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.046, baseLat + 0.018],
  //     },
  //   },
  //   contact: { phone: '9001120036', email: 'gianis@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Indian-Sweets',
  //     'Beverages',
  //     'Street-Food',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 6800,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Andhra Bhavan',
  //   description:
  //     'A state canteen famous for its authentic, unlimited, and incredibly affordable Andhra thali.',
  //   address: {
  //     street: 'Ashoka Road',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.009, baseLat - 0.009],
  //     },
  //   },
  //   contact: { phone: '9001120037', email: 'andhrabhavan@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Breakfast',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 13000,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Cafe Lota',
  //   description:
  //     'A beautiful cafe at the Crafts Museum, serving regional Indian dishes with a modern twist.',
  //   address: {
  //     street: 'National Crafts Museum, Pragati Maidan',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat],
  //     },
  //   },
  //   contact: { phone: '9001120038', email: 'cafelota@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'Healthy',
  //     'Breakfast',
  //     'Lunch',
  //     'Beverages',
  //     'North-Indian',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Wednesday', open: '10:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Aslam Chicken',
  //   description:
  //     'A legendary spot in Old Delhi famous for its unique Butter Cream Chicken.',
  //   address: {
  //     street: 'Jama Masjid, Old Delhi',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.043, baseLat + 0.023],
  //     },
  //   },
  //   contact: { phone: '9001120039', email: 'aslamchicken@example.com' },
  //   cuisine_type: [
  //     'BBQ',
  //     'North-Indian',
  //     'Street-Food',
  //     'Dinner',
  //     'Indian',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 9800,
  //   opening_hours: [{ day: 'Thursday', open: '16:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 45,
  // },
  // // --- Restaurants 41-50 (More Category Fillers) ---
  // {
  //   name: 'The Blue Door Cafe',
  //   description:
  //     'A charming cafe in Khan Market known for its European cuisine and all-day breakfast.',
  //   address: {
  //     street: 'Khan Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.013, baseLat - 0.013],
  //     },
  //   },
  //   contact: { phone: '9001120040', email: 'bluedoor@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Breakfast',
  //     'Sandwiches',
  //     'Salads',
  //     'Desserts',
  //     'Beverages',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Friday', open: '07:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1700,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Chor Bizarre',
  //   description:
  //     'A unique, antique-filled restaurant serving authentic Kashmiri and North Indian cuisine.',
  //   address: {
  //     street: 'Bikaner House, Pandara Road',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110011',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.016, baseLat - 0.016],
  //     },
  //   },
  //   contact: { phone: '9001120041', email: 'chorbizarre@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Desserts',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2200,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Roshan Di Kulfi',
  //   description:
  //     'A legendary spot in Karol Bagh for Kulfi Falooda and Chole Bhature.',
  //   address: {
  //     street: 'Karol Bagh Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9001120042', email: 'roshankulfi@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Desserts',
  //     'Indian-Sweets',
  //     'North-Indian',
  //     'Beverages',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 8800,
  //   opening_hours: [{ day: 'Sunday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Imperial Spice',
  //   description:
  //     'A fine-dining restaurant with grand interiors, serving global and Indian cuisine.',
  //   address: {
  //     street: 'M-Block, Connaught Place',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.001, baseLat - 0.001],
  //     },
  //   },
  //   contact: { phone: '9001120043', email: 'imperialspice@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Chinese',
  //     'Italian',
  //     'Dinner',
  //     'Lunch',
  //     'Soups',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 4100,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 900,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Greenr Cafe',
  //   description:
  //     'A plant-based cafe serving innovative and delicious vegan and vegetarian food.',
  //   address: {
  //     street: 'Vasant Vihar',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110057',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.052, baseLat - 0.062],
  //     },
  //   },
  //   contact: { phone: '9001120044', email: 'greenr.del@example.com' },
  //   cuisine_type: [
  //     'Vegan',
  //     'Healthy',
  //     'Salads',
  //     'Soups',
  //     'Breakfast',
  //     'Italian',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Khan Chacha',
  //   description:
  //     'A legendary name in Delhi for delicious and juicy kebabs and rolls.',
  //   address: {
  //     street: 'Khan Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.014, baseLat - 0.014],
  //     },
  //   },
  //   contact: { phone: '9001120045', email: 'khanchacha@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'BBQ',
  //     'Street-Food',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 10200,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Dhaba - Estd 1986 Delhi',
  //   description:
  //     'A restaurant that recreates the rustic charm and flavors of a roadside dhaba.',
  //   address: {
  //     street: 'DLF Cyber City, Gurgaon',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '122002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.1, baseLat - 0.05],
  //     },
  //   },
  //   contact: { phone: '9001120046', email: 'dhaba1986@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Beverages',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 5800,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Ama Cafe',
  //   description:
  //     'A hugely popular cafe in Majnu-ka-tilla, famous for its breakfast, coffee, and desserts.',
  //   address: {
  //     street: 'Majnu-ka-tilla',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110054',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.08],
  //     },
  //   },
  //   contact: { phone: '9001120047', email: 'amacafe@example.com' },
  //   cuisine_type: [
  //     'Breakfast',
  //     'Desserts',
  //     'Beverages',
  //     'Sandwiches',
  //     'Fast-Food',
  //     'Healthy',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 12500,
  //   opening_hours: [{ day: 'Friday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Farzi Cafe',
  //   description:
  //     'A modern Indian bistro that creates an illusion with its food and decor.',
  //   address: {
  //     street: 'E-Block, Connaught Place',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.002, baseLat + 0.002],
  //     },
  //   },
  //   contact: { phone: '9001120048', email: 'farzicafe@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Beverages',
  //     'Fast-Food',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 7100,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2200,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Theobroma',
  //   description:
  //     'A beloved patisserie famous for its brownies, cakes, and desserts.',
  //   address: {
  //     street: 'Defence Colony Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110024',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9001120049', email: 'theobroma.del@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Sandwiches', 'Breakfast'],
  //   rating: 4.7,
  //   numberOfReviews: 9900,
  //   opening_hours: [{ day: 'Sunday', open: '08:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // // --- Restaurants 51-60 (Final Fillers) ---
  // {
  //   name: 'Changezi Chicken',
  //   description:
  //     'Famous for its unique, spicy, and tangy Changezi style chicken curry.',
  //   address: {
  //     street: 'Daryaganj',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.022, baseLat - 0.022],
  //     },
  //   },
  //   contact: { phone: '9001120050', email: 'changezi@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Street-Food',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Imperfecto',
  //   description:
  //     'A quirky, vibrant rooftop bar and restaurant with a multi-cuisine menu.',
  //   address: {
  //     street: 'Hauz Khas Village',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.031, baseLat - 0.071],
  //     },
  //   },
  //   contact: { phone: '9001120051', email: 'imperfecto@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Mexican',
  //     'North-Indian',
  //     'Dinner',
  //     'Beverages',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 7200,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1900,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Naivedyam',
  //   description:
  //     'A traditional South Indian restaurant with a temple-like ambiance.',
  //   address: {
  //     street: 'Hauz Khas Village',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.032, baseLat - 0.072],
  //     },
  //   },
  //   contact: { phone: '9001120052', email: 'naivedyam@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //     'Vegan',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 5100,
  //   opening_hours: [{ day: 'Wednesday', open: '10:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Evergreen Sweet House',
  //   description:
  //     'A popular spot in Green Park for sweets, chaat, and vegetarian meals.',
  //   address: {
  //     street: 'Green Park Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat - 0.065],
  //     },
  //   },
  //   contact: { phone: '9001120053', email: 'evergreen@example.com' },
  //   cuisine_type: [
  //     'Indian-Sweets',
  //     'Street-Food',
  //     'North-Indian',
  //     'Desserts',
  //     'Breakfast',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 8100,
  //   opening_hours: [{ day: 'Thursday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Artful Baker',
  //   description:
  //     'A patisserie and boulangerie known for its artisanal breads, croissants, and desserts.',
  //   address: {
  //     street: 'Khan Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.011, baseLat - 0.011],
  //     },
  //   },
  //   contact: { phone: '9001120054', email: 'artfulbaker@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Breakfast',
  //     'Sandwiches',
  //     'Beverages',
  //     'Healthy',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Friday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Punjab Grill',
  //   description:
  //     'A celebration of the culinary heritage of Punjab with a fine-dining experience.',
  //   address: {
  //     street: 'Select City Walk Mall, Saket',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.042, baseLat - 0.102],
  //     },
  //   },
  //   contact: { phone: '9001120055', email: 'punjabgrill.del@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'BBQ',
  //     'Dinner',
  //     'Lunch',
  //     'Desserts',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 6400,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 2200,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Wow! Momo',
  //   description:
  //     'A fast-food chain specializing in a wide variety of momos, from steamed to fried to sizzlers.',
  //   address: {
  //     street: 'Kamla Nagar Market',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110007',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat + 0.06],
  //     },
  //   },
  //   contact: { phone: '9001120056', email: 'wowmomo.del@example.com' },
  //   cuisine_type: ['Chinese', 'Fast-Food', 'Street-Food', 'Soups', 'Dinner'],
  //   rating: 4.0,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Chaayos',
  //   description:
  //     'A contemporary tea cafe serving a huge variety of customized teas and snacks.',
  //   address: {
  //     street: 'Connaught Place',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.003, baseLat - 0.002],
  //     },
  //   },
  //   contact: { phone: '9001120057', email: 'chaayos.del@example.com' },
  //   cuisine_type: [
  //     'Beverages',
  //     'Breakfast',
  //     'Street-Food',
  //     'Fast-Food',
  //     'Indian',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 8200,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Taco Bell',
  //   description:
  //     'Fast-food chain serving Mexican-inspired fare like tacos and burritos.',
  //   address: {
  //     street: 'Ambience Mall, Vasant Kunj',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110070',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.07, baseLat - 0.07],
  //     },
  //   },
  //   contact: { phone: '9001120058', email: 'tacobell.del@example.com' },
  //   cuisine_type: ['Mexican', 'Fast-Food', 'Dinner', 'Lunch', 'Beverages'],
  //   rating: 4.0,
  //   numberOfReviews: 6800,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'KFC',
  //   description:
  //     'Famous for its fried chicken, a global chain with a signature secret recipe.',
  //   address: {
  //     street: 'Connaught Place',
  //     city: 'New Delhi',
  //     state: 'Delhi',
  //     zip_code: '110001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.002, baseLat + 0.002],
  //     },
  //   },
  //   contact: { phone: '9001120059', email: 'kfc.del@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'BBQ',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 9900,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 35,
  // },
  // all of the the restaurant has been seeded
];

export default delhiRestaurants;
