// Base coordinates for New Delhi (approximate center: Connaught Place)
const baseLat = 28.6448;
const baseLon = 77.2167;

const delhiRestaurants = [
  // --- North Indian / Mughlai / Fine Dining ---
  {
    name: "Karim's",
    description:
      'An iconic Old Delhi institution, serving authentic Mughlai food since 1913. Famous for Nihari and Kebabs.',
    address: {
      street: '16, Urdu Bazar Road, Jama Masjid',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110006',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.05, baseLat - 0.01],
      },
    },
    contact: { phone: '9001120001', email: 'karims.delhi@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'Dinner',
      'Lunch',
      'BBQ',
      'Street-Food',
    ],
    rating: 4.5,
    numberOfReviews: 18000,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '23:30' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 1200,
    delivery_time_mins: 45,
  },
  {
    name: 'Bukhara',
    description:
      'A world-renowned fine-dining restaurant at ITC Maurya, famous for Dal Bukhara and Frontier Cuisine.',
    address: {
      street: 'ITC Maurya, Chanakyapuri',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110021',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.02, baseLat - 0.05],
      },
    },
    contact: { phone: '9001120002', email: 'bukhara.itc@example.com' },
    cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ', 'Soups'],
    rating: 4.8,
    numberOfReviews: 9500,
    opening_hours: [{ day: 'Tuesday', open: '12:30', close: '23:45' }],
    is_active: true,
    min_order_value: 2500,
    delivery_radius_km: 10,
    is_veg: false,
    cost_for_two: 6500,
    delivery_time_mins: 60,
  },
  {
    name: 'Indian Accent',
    description:
      'Contemporary Indian cuisine with a global twist, located at The Lodhi Hotel.',
    address: {
      street: 'The Lodhi, Lodhi Road',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110003',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.01, baseLat - 0.02],
      },
    },
    contact: { phone: '9001120003', email: 'accent.del@example.com' },
    cuisine_type: [
      'Indian',
      'North-Indian',
      'Healthy',
      'Dinner',
      'Lunch',
      'Beverages',
    ],
    rating: 4.9,
    numberOfReviews: 7000,
    opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 1500,
    delivery_radius_km: 5,
    is_veg: false,
    cost_for_two: 4000,
    delivery_time_mins: 40,
  },

  // --- Italian / Pizza / Cafe ---
  {
    name: "Leo's Artisan Pizza",
    description:
      'One of the best pizzerias in Delhi, focusing on authentic Neapolitan wood-fired pizzas.',
    address: {
      street: 'Market Complex, Vasant Vihar',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110057',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.05, baseLat - 0.06],
      },
    },
    contact: { phone: '9001120004', email: 'leospizza@example.com' },
    cuisine_type: [
      'Pizza',
      'Italian',
      'Dinner',
      'Lunch',
      'Fast-Food',
      'Salads',
    ],
    rating: 4.6,
    numberOfReviews: 5200,
    opening_hours: [{ day: 'Thursday', open: '13:00', close: '23:00' }],
    is_active: true,
    min_order_value: 700,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 2000,
    delivery_time_mins: 35,
  },
  {
    name: 'Olive Bar & Kitchen',
    description:
      'Charming Mediterranean-inspired restaurant near Qutub Minar, perfect for a romantic evening.',
    address: {
      street: 'One Style Mile, Mehrauli',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110030',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.03, baseLat - 0.08],
      },
    },
    contact: { phone: '9001120005', email: 'olive.qutub@example.com' },
    cuisine_type: ['Italian', 'Dinner', 'Lunch', 'Salads', 'Soups', 'Healthy'],
    rating: 4.7,
    numberOfReviews: 8800,
    opening_hours: [{ day: 'Friday', open: '12:30', close: '00:00' }],
    is_active: true,
    min_order_value: 1000,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 3500,
    delivery_time_mins: 55,
  },
  {
    name: 'The Big Chill Cafe',
    description:
      'A favourite cafe chain known for its Pasta, Shakes, and decadent desserts.',
    address: {
      street: '68, Khan Market',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.01, baseLat - 0.01],
      },
    },
    contact: { phone: '9001120006', email: 'bigchill@example.com' },
    cuisine_type: [
      'Italian',
      'Pizza',
      'Desserts',
      'Sandwiches',
      'Lunch',
      'Dinner',
    ],
    rating: 4.5,
    numberOfReviews: 10500,
    opening_hours: [{ day: 'Saturday', open: '11:00', close: '23:30' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 1800,
    delivery_time_mins: 40,
  },

  // --- Asian / International ---
  {
    name: 'Guppy',
    description:
      'Contemporary Japanese eatery in Lodhi Colony, known for its Sushi and quirky decor.',
    address: {
      street: '28, Lodhi Colony Market',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.015, baseLat - 0.03],
      },
    },
    contact: { phone: '9001120007', email: 'guppy.kol@example.com' },
    cuisine_type: ['Japanese', 'Sushi', 'Chinese', 'Dinner', 'Lunch', 'Soups'],
    rating: 4.6,
    numberOfReviews: 4100,
    opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 800,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 2800,
    delivery_time_mins: 50,
  },
  {
    name: "Berco's",
    description:
      'A classic Delhi spot for affordable and popular Indo-Chinese food.',
    address: {
      street: 'L-Block, Connaught Place',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.005, baseLat - 0.005],
      },
    },
    contact: { phone: '9001120008', email: 'bercos@example.com' },
    cuisine_type: [
      'Chinese',
      'Japanese',
      'Fast-Food',
      'Dinner',
      'Lunch',
      'Beverages',
    ],
    rating: 4.3,
    numberOfReviews: 11200,
    opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 450,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 1400,
    delivery_time_mins: 35,
  },
  {
    name: 'Hauz Khas Social',
    description:
      'A popular workspace/café and bar known for its eclectic menu and scenic location.',
    address: {
      street: '9A & 12, Hauz Khas Village',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110016',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.03, baseLat - 0.07],
      },
    },
    contact: { phone: '9001120009', email: 'social.hk@example.com' },
    cuisine_type: [
      'Burgers',
      'Mexican',
      'Dinner',
      'Lunch',
      'Beverages',
      'Fast-Food',
    ],
    rating: 4.4,
    numberOfReviews: 6800,
    opening_hours: [{ day: 'Tuesday', open: '11:00', close: '00:30' }],
    is_active: true,
    min_order_value: 700,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 1600,
    delivery_time_mins: 50,
  },

  // --- Street Food / Fast Food / Veg ---
  {
    name: "Haldiram's",
    description:
      'A quick-service outlet famous for Chole Bhature, Indian snacks (chaat), and sweets.',
    address: {
      street: 'L-1, Connaught Place',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110001',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.005, baseLat + 0.005],
      },
    },
    contact: { phone: '9001120010', email: 'haldirams@example.com' },
    cuisine_type: [
      'Fast-Food',
      'Indian-Sweets',
      'Street-Food',
      'Breakfast',
      'Sandwiches',
      'Vegan',
    ],
    rating: 4.3,
    numberOfReviews: 15400,
    opening_hours: [{ day: 'Wednesday', open: '08:00', close: '22:00' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 600,
    delivery_time_mins: 30,
  },
  {
    name: 'Kake Di Hatti',
    description:
      'A legendary vegetarian restaurant in Old Delhi known for its massive, fluffy Naans and rich curries.',
    address: {
      street: '654-655, Church Mission Road, Chandni Chowk',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110006',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.045, baseLat + 0.02],
      },
    },
    contact: { phone: '9001120011', email: 'kakedihatticw@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'Street-Food',
      'Breakfast',
      'Vegan',
      'Lunch',
    ],
    rating: 4.6,
    numberOfReviews: 9200,
    opening_hours: [{ day: 'Thursday', open: '09:00', close: '23:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 800,
    delivery_time_mins: 40,
  },
  {
    name: 'Saravana Bhavan',
    description:
      'The international chain for authentic South-Indian vegetarian delights like Dosas and Idlis.',
    address: {
      street: '46, Janpath',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.002, baseLat - 0.008],
      },
    },
    contact: { phone: '9001120012', email: 'sarvana.jan@example.com' },
    cuisine_type: [
      'South-Indian',
      'Indian',
      'Breakfast',
      'Vegan',
      'Lunch',
      'Healthy',
    ],
    rating: 4.4,
    numberOfReviews: 11000,
    opening_hours: [{ day: 'Friday', open: '08:00', close: '23:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 750,
    delivery_time_mins: 30,
  },

  // --- Mixed & Remaining ---
  {
    name: 'Moti Mahal',
    description:
      'Claiming the origin of Butter Chicken, this Daryaganj classic offers timeless Mughlai flavors.',
    address: {
      street: '3703, Netaji Subhash Marg, Daryaganj',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110002',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.02, baseLat - 0.02],
      },
    },
    contact: { phone: '9001120013', email: 'motimahal.dar@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'Dinner',
      'Lunch',
      'BBQ',
      'Fast-Food',
    ],
    rating: 4.2,
    numberOfReviews: 7600,
    opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:30' }],
    is_active: true,
    min_order_value: 600,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 1500,
    delivery_time_mins: 45,
  },
  {
    name: 'Big Yellow Door (BYD)',
    description:
      'A popular youth hangout famous for budget-friendly burgers, pasta, and shakes.',
    address: {
      street: 'H-8, Hudson Lane, GTB Nagar',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110009',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.01, baseLat + 0.05],
      },
    },
    contact: { phone: '9001120014', email: 'byd.gtb@example.com' },
    cuisine_type: [
      'Burgers',
      'Sandwiches',
      'Desserts',
      'Beverages',
      'Lunch',
      'Dinner',
    ],
    rating: 4.1,
    numberOfReviews: 13500,
    opening_hours: [{ day: 'Sunday', open: '10:00', close: '23:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 900,
    delivery_time_mins: 30,
  },
  {
    name: 'Yum Yum Cha',
    description:
      'Colorful and modern spot for pan-Asian cuisine, including dim sum, sushi, and fun molecular mocktails.',
    address: {
      street: 'Middle Lane, Khan Market',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.009, baseLat - 0.012],
      },
    },
    contact: { phone: '9001120015', email: 'yyc.km@example.com' },
    cuisine_type: ['Chinese', 'Japanese', 'Sushi', 'Lunch', 'Dinner', 'Soups'],
    rating: 4.5,
    numberOfReviews: 6100,
    opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 750,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 2100,
    delivery_time_mins: 40,
  },
  {
    name: 'Pind Balluchi',
    description:
      'North Indian restaurant with a village theme, known for its extensive Tandoori menu and Punjabi food.',
    address: {
      street: 'C-8, Connaught Place',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.001, baseLat + 0.001],
      },
    },
    contact: { phone: '9001120016', email: 'pind.balluchi@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'BBQ',
      'Dinner',
      'Lunch',
      'Street-Food',
    ],
    rating: 4.2,
    numberOfReviews: 8900,
    opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 1300,
    delivery_time_mins: 40,
  },
  {
    name: "Elma's Bakery, Bar and Kitchen",
    description:
      'Vintage-style cafe offering delicious European breakfast, high tea, and comfort food.',
    address: {
      street: '73, Mehar Chand Market',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110003',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.02, baseLat - 0.025],
      },
    },
    contact: { phone: '9001120017', email: 'elmas@example.com' },
    cuisine_type: [
      'Desserts',
      'Breakfast',
      'Beverages',
      'Sandwiches',
      'Italian',
      'Salads',
    ],
    rating: 4.4,
    numberOfReviews: 3800,
    opening_hours: [{ day: 'Wednesday', open: '09:00', close: '00:00' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 5,
    is_veg: false,
    cost_for_two: 1700,
    delivery_time_mins: 35,
  },
  {
    name: 'Johnny Rockets',
    description:
      'Classic American diner experience serving thick burgers, fries, and hand-spun shakes.',
    address: {
      street: 'Select City Walk Mall, Saket',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110017',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.04, baseLat - 0.1],
      },
    },
    contact: { phone: '9001120018', email: 'jr.saket@example.com' },
    cuisine_type: [
      'Burgers',
      'Fast-Food',
      'Desserts',
      'Beverages',
      'Lunch',
      'Dinner',
    ],
    rating: 4.0,
    numberOfReviews: 5500,
    opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 350,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 1100,
    delivery_time_mins: 30,
  },
  {
    name: 'Carnatic Cafe',
    description:
      'Highly-rated South Indian cafe known for its unique, thin, and crispy Dosas.',
    address: {
      street: 'M-21, Greater Kailash (GK) 2',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110048',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.02, baseLat - 0.06],
      },
    },
    contact: { phone: '9001120019', email: 'carnatic.gk@example.com' },
    cuisine_type: [
      'South-Indian',
      'Indian',
      'Breakfast',
      'Vegan',
      'Lunch',
      'Healthy',
    ],
    rating: 4.7,
    numberOfReviews: 4900,
    opening_hours: [{ day: 'Friday', open: '08:00', close: '22:30' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 850,
    delivery_time_mins: 35,
  },
  {
    name: 'The Potbelly',
    description:
      'A cozy spot offering authentic regional Indian cuisine from Bihar and Jharkhand.',
    address: {
      street: '114, Shahpur Jat',
      city: 'New Delhi',
      state: 'Delhi',
      zip_code: '110049',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.01, baseLat - 0.08],
      },
    },
    contact: { phone: '9001120020', email: 'potbelly@example.com' },
    cuisine_type: [
      'Indian',
      'Lunch',
      'Dinner',
      'Healthy',
      'Breakfast',
      'North-Indian',
    ],
    rating: 4.3,
    numberOfReviews: 3200,
    opening_hours: [{ day: 'Saturday', open: '10:30', close: '23:00' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 1200,
    delivery_time_mins: 40,
  },
];

export default delhiRestaurants;
