// Base coordinates for Hyderabad (approximate center - Banjara Hills/Jubilee Hills)
const baseLat = 17.412;
const baseLon = 78.474;

/**
 * Data structure for restaurants in Hyderabad, ensuring wide coverage of all 24 supported cuisine types.
 * 35 restaurants are generated, focusing heavily on Hyderabadi/South Indian specialties.
 */
const hyderabadRestaurants = [
  // --- Hyderabad Restaurant 1-5 (Biryani & South Indian Focus) ---
  // {
  //   name: 'Paradise Biryani',
  //   description:
  //     "Hyderabad's most famous biryani chain, known for its iconic Hyderabadi Dum Biryani.",
  //   address: {
  //     street: 'Opposite Secunderabad Railway Station',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '91402770001', email: 'paradise@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'North-Indian',
  //     'BBQ',
  //     'Dinner',
  //     'Lunch',
  //     'Fast-Food',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 55000,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 450,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Bawarchi',
  //   description:
  //     'A legendary spot for spicy, authentic Hyderabadi Biryani loved by locals.',
  //   address: {
  //     street: 'RTC Cross Road, Vidyanagar',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500020',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '91402770002', email: 'bawarchi@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'North-Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Fast-Food',
  //     'Street-Food',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 45000,
  //   opening_hours: [{ day: 'Tuesday', open: '11:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Chutneys',
  //   description:
  //     'A popular pure vegetarian spot famous for its unique variety of dosas and chutneys.',
  //   address: {
  //     street: 'Road No 3, Banjara Hills',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.002, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '91402770003', email: 'chutneys@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Breakfast',
  //     'Indian',
  //     'Vegan',
  //     'Lunch',
  //     'Healthy',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 22000,
  //   opening_hours: [{ day: 'Wednesday', open: '07:30', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Gokaraju Gari Ruchulu',
  //   description:
  //     'Authentic Andhra cuisine restaurant, known for its traditional spicy thalis and seafood.',
  //   address: {
  //     street: 'Kondapur, Near Kothaguda Junction',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500084',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '91402770004', email: 'gokaraju@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'South-Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Fast-Food',
  //     'Healthy',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 15000,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Karachi Bakery',
  //   description:
  //     'Famous for its fruit biscuits and a wide variety of baked goods and desserts.',
  //   address: {
  //     street: 'Mozamjahi Market',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '91402770005', email: 'karachi@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Beverages',
  //     'Indian-Sweets',
  //     'Breakfast',
  //     'Fast-Food',
  //     'Healthy',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 30000,
  //   opening_hours: [{ day: 'Friday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 20,
  // },
  // --- Hyderabad Restaurant 6-10 (International & Pub Food) ---
  // {
  //   name: "Absolute Barbecues (AB's)",
  //   description:
  //     'Popular live grill and buffet restaurant with an extensive "Wish Grill" selection.',
  //   address: {
  //     street: 'Jubilee Enclave, Madhapur',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500081',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '91402770006', email: 'absmadhapur@example.com' },
  //   cuisine_type: [
  //     'BBQ',
  //     'North-Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Indian',
  //     'Fast-Food',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 18000,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 900,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'KFC',
  //   description:
  //     'American fast-food chain specializing in fried chicken and sides.',
  //   address: {
  //     street: 'Inorbit Mall, Hitec City',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500081',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.05, baseLat + 0.035],
  //     },
  //   },
  //   contact: { phone: '91402770007', email: 'kfc@example.com' },
  //   cuisine_type: [
  //     'Fast-Food',
  //     'Burgers',
  //     'Dinner',
  //     'Lunch',
  //     'Sandwiches',
  //     'BBQ',
  //   ],
  //   rating: 3.9,
  //   numberOfReviews: 12000,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Taco Bell',
  //   description:
  //     'International quick-service Mexican restaurant known for tacos and burritos.',
  //   address: {
  //     street: 'Gachibowli, Near Bio-Diversity Park',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500032',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.06, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '91402770008', email: 'tacobell@example.com' },
  //   cuisine_type: [
  //     'Mexican',
  //     'Fast-Food',
  //     'Lunch',
  //     'Dinner',
  //     'Salads',
  //     'Vegan',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:45' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 750,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Doolally Taproom',
  //   description:
  //     'Brewery and casual dining serving pub grub, comfort food, and craft beer.',
  //   address: {
  //     street: 'Lower Tank Bund, Near Hussain Sagar',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat + 0.0],
  //     },
  //   },
  //   contact: { phone: '91402770009', email: 'doolally@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Sandwiches',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //     'Beverages',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 7000,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Tre-Forni',
  //   description:
  //     'Fine dining Italian restaurant inside Park Hyatt, known for wood-fired pizzas.',
  //   address: {
  //     street: 'Road No 2, Banjara Hills',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.005, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '91402770010', email: 'treforni@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Dinner', 'Lunch', 'Healthy', 'Soups'],
  //   rating: 4.7,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Wednesday', open: '19:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 1200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 3500,
  //   delivery_time_mins: 60,
  // },
  // // --- Hyderabad Restaurant 11-15 (Asian & Continental) ---
  // {
  //   name: 'Mainland China',
  //   description:
  //     'Premium chain offering authentic, high-quality Chinese and Oriental cuisine.',
  //   address: {
  //     street: 'Himayatnagar Main Road',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500029',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.008, baseLat + 0.008],
  //     },
  //   },
  //   contact: { phone: '91402770011', email: 'mainlandchina@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Soups',
  //     'Dinner',
  //     'Lunch',
  //     'Japanese',
  //     'Healthy',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 10000,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Minerva Coffee Shop',
  //   description:
  //     'A traditional spot famous for its filter coffee and South Indian snacks.',
  //   address: {
  //     street: 'Secunderabad, Near Clock Tower',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.008, baseLat + 0.003],
  //     },
  //   },
  //   contact: { phone: '91402770012', email: 'minervacoffee@example.com' },
  //   cuisine_type: [
  //     'Beverages',
  //     'South-Indian',
  //     'Breakfast',
  //     'Indian',
  //     'Fast-Food',
  //     'Healthy',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 11000,
  //   opening_hours: [{ day: 'Friday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Firenze',
  //   description:
  //     'Casual Italian dining focused on fresh pasta and gourmet salads.',
  //   address: {
  //     street: 'Road No 36, Jubilee Hills',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500033',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '91402770013', email: 'firenze@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Salads', 'Dinner', 'Lunch', 'Desserts'],
  //   rating: 4.4,
  //   numberOfReviews: 6000,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Utsav',
  //   description:
  //     'A fine-dining spot known for its pure vegetarian North Indian and Rajasthani thalis.',
  //   address: {
  //     street: 'Jubilee Hills, Film Nagar',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500096',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.035, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '91402770014', email: 'utsav@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Vegan',
  //     'Indian-Sweets',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 8500,
  //   opening_hours: [{ day: 'Sunday', open: '12:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 10,
  //   is_veg: true,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: "Ohri's Tiffins",
  //   description:
  //     'Dedicated outlet for South Indian breakfast items and local quick snacks.',
  //   address: {
  //     street: 'Banjara Hills, Road No 1',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.001, baseLat + 0.009],
  //     },
  //   },
  //   contact: { phone: '91402770015', email: 'ohristiffins@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Breakfast',
  //     'Fast-Food',
  //     'Indian',
  //     'Vegan',
  //     'Healthy',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 14000,
  //   opening_hours: [{ day: 'Monday', open: '07:00', close: '14:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 15,
  // },
  // // --- Hyderabad Restaurant 16-20 (Street Food & Desserts) ---
  // {
  //   name: 'Sarvi',
  //   description:
  //     'Famous for its Irani Haleem during Ramadan and all-day Mughlai delicacies.',
  //   address: {
  //     street: 'Banjara Hills, Road No 11',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '91402770016', email: 'sarvi@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Fast-Food',
  //     'BBQ',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 15500,
  //   opening_hours: [{ day: 'Tuesday', open: '12:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'DLF Street Food Point',
  //   description:
  //     'A cluster of popular night stalls offering diverse street foods from across India.',
  //   address: {
  //     street: 'DLF Road, Gachibowli',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500032',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.065, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '91402770017', email: 'dlfstreet@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Fast-Food',
  //     'Indian',
  //     'North-Indian',
  //     'Chinese',
  //     'Vegan',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 25000,
  //   opening_hours: [{ day: 'Wednesday', open: '18:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Pista House',
  //   description:
  //     'Another highly famous outlet, primarily known for its authentic Hyderabadi Haleem.',
  //   address: {
  //     street: 'Old City, Charminar Area',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '91402770018', email: 'pistahouse@example.com' },
  //   cuisine_type: [
  //     'Indian-Sweets',
  //     'Desserts',
  //     'North-Indian',
  //     'Fast-Food',
  //     'Indian',
  //     'Beverages',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 28000,
  //   opening_hours: [{ day: 'Thursday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Bombay Lassi & Juice Corner',
  //   description:
  //     'Popular spot for fresh juices, milkshakes, and traditional Indian yogurt drinks (Lassi).',
  //   address: {
  //     street: 'Koti, Near Womens College',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500095',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.0],
  //     },
  //   },
  //   contact: { phone: '91402770019', email: 'lassicorner@example.com' },
  //   cuisine_type: [
  //     'Beverages',
  //     'Desserts',
  //     'Street-Food',
  //     'Fast-Food',
  //     'Healthy',
  //     'Vegan',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 8800,
  //   opening_hours: [{ day: 'Friday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 15,
  // },
  // {
  //   name: 'Makizushi',
  //   description:
  //     'Specialty Japanese outlet focusing on high-quality sushi rolls and appetizers.',
  //   address: {
  //     street: 'Jubilee Hills, Road No 45',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500033',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '91402770020', email: 'makizushi@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Dinner', 'Lunch', 'Healthy', 'Soups'],
  //   rating: 4.5,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Saturday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 2200,
  //   delivery_time_mins: 45,
  // },
  // // --- Hyderabad Restaurant 21-25 (Global Cuisine & Salads) ---
  // {
  //   name: 'Healthy Bowl Co.',
  //   description:
  //     'Focuses on customized healthy bowls, protein salads, and nutritious wraps.',
  //   address: {
  //     street: 'Kondapur, Near Botanical Garden',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500084',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.07, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '91402770021', email: 'healthybowl@example.com' },
  //   cuisine_type: [
  //     'Salads',
  //     'Healthy',
  //     'Vegan',
  //     'Lunch',
  //     'Breakfast',
  //     'Sandwiches',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Sunday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 850,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Bake My Day',
  //   description:
  //     'Artisan bakery offering a range of European breads, cakes, and coffee.',
  //   address: {
  //     street: 'Banjara Hills, Road No 10',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.008, baseLat + 0.018],
  //     },
  //   },
  //   contact: { phone: '91402770022', email: 'bakemyday@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Beverages',
  //     'Breakfast',
  //     'Sandwiches',
  //     'Healthy',
  //     'Vegan',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 6800,
  //   opening_hours: [{ day: 'Monday', open: '08:30', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Rayalaseema Ruchulu',
  //   description:
  //     'Cuisine from the Rayalaseema region of Andhra Pradesh, known for intense spice levels.',
  //   address: {
  //     street: 'Lakdikapul, Near Assembly',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.002, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '91402770023', email: 'rayalaseema@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Fast-Food',
  //     'BBQ',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 450,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Subway',
  //   description:
  //     'International chain offering customizable, fresh submarine sandwiches and salads.',
  //   address: {
  //     street: 'Hitec City, Mindspace',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500081',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.055, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '91402770024', email: 'subway@example.com' },
  //   cuisine_type: [
  //     'Sandwiches',
  //     'Healthy',
  //     'Fast-Food',
  //     'Lunch',
  //     'Salads',
  //     'Vegan',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 11000,
  //   opening_hours: [{ day: 'Wednesday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Sardarji Malai Chaap Wala',
  //   description:
  //     'Northern Indian vegetarian specialty shop for marinated soya chaap (vegetarian kebabs).',
  //   address: {
  //     street: 'Kondapur, Near RTO Office',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500084',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.06, baseLat + 0.028],
  //     },
  //   },
  //   contact: { phone: '91402770025', email: 'sardarji@example.com' },
  //   cuisine_type: [
  //     'BBQ',
  //     'North-Indian',
  //     'Fast-Food',
  //     'Vegan',
  //     'Dinner',
  //     'Street-Food',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Thursday', open: '16:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 25,
  // },
  // // --- Hyderabad Restaurant 26-30 (Specialty & Fusion) ---
  // {
  //   name: 'Soups N Scoops',
  //   description:
  //     'A cafe specializing in a wide range of soups and gourmet ice cream scoops.',
  //   address: {
  //     street: 'Banjara Hills, Road No 12',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '91402770026', email: 'soupsnscoops@example.com' },
  //   cuisine_type: [
  //     'Soups',
  //     'Desserts',
  //     'Beverages',
  //     'Healthy',
  //     'Vegan',
  //     'Fast-Food',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Dimsum & Dumplings Co.',
  //   description:
  //     'Dedicated Asian eatery focusing on steamed and pan-fried dim sums and dumplings.',
  //   address: {
  //     street: 'Jubilee Hills, Peddamma Temple Road',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500033',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.035, baseLat + 0.035],
  //     },
  //   },
  //   contact: { phone: '91402770027', email: 'dimsumco@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Japanese',
  //     'Dinner',
  //     'Lunch',
  //     'Fast-Food',
  //     'Healthy',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 5300,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1300,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Pizza Express',
  //   description:
  //     'International chain offering Roman-style thin-crust pizzas and classic Italian appetizers.',
  //   address: {
  //     street: 'Gachibowli, Near D-Mart',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500032',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.075, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '91402770028', email: 'pizzaexpress@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Dinner', 'Lunch', 'Fast-Food', 'Vegan'],
  //   rating: 4.2,
  //   numberOfReviews: 7200,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:45' }],
  //   is_active: true,
  //   min_order_value: 450,
  //   delivery_radius_km: 10,
  //   is_veg: true,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'AtoZ Sweets & Bakers',
  //   description:
  //     'Local favorite for traditional Indian sweets (mithai) and Bengali desserts.',
  //   address: {
  //     street: 'Koti Main Road',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500095',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '91402770029', email: 'atozsweets@example.com' },
  //   cuisine_type: [
  //     'Indian-Sweets',
  //     'Desserts',
  //     'Indian',
  //     'Beverages',
  //     'Fast-Food',
  //     'Breakfast',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 10500,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Shadab Hotel',
  //   description:
  //     'Another highly rated spot, especially known for its Biryani and local Hyderabadi dishes.',
  //   address: {
  //     street: 'Ghansi Bazaar, Near Charminar',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '91402770030', email: 'shadab@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Fast-Food',
  //     'BBQ',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 35000,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 850,
  //   delivery_time_mins: 35,
  // },
  // // --- Hyderabad Restaurant 31-35 (Diversity Fillers) ---
  // {
  //   name: 'The Good Earth Cafe',
  //   description:
  //     'Organic cafe focusing on sustainability, serving vegan and health-focused meals.',
  //   address: {
  //     street: 'Jubilee Hills, Road No 4',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500033',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '91402770031', email: 'goodearth@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Vegan',
  //     'Salads',
  //     'Breakfast',
  //     'Lunch',
  //     'Beverages',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 3000,
  //   opening_hours: [{ day: 'Wednesday', open: '09:00', close: '20:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Burger King',
  //   description:
  //     'Another international fast-food chain for flame-grilled burgers and fries.',
  //   address: {
  //     street: 'Kothaguda, Near Sarath City Mall',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500084',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.07, baseLat + 0.035],
  //     },
  //   },
  //   contact: { phone: '91402770032', email: 'burgerking@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //     'Sandwiches',
  //     'BBQ',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 9000,
  //   opening_hours: [{ day: 'Thursday', open: '10:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Sizzling Woks',
  //   description:
  //     'Pan-Asian fusion restaurant with a focus on customizable noodle and rice bowls.',
  //   address: {
  //     street: 'Ameerpet, Near Big Bazaar',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.0, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '91402770033', email: 'sizzlingwoks@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Japanese',
  //     'Soups',
  //     'Dinner',
  //     'Lunch',
  //     'Fast-Food',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 6100,
  //   opening_hours: [{ day: 'Friday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'The Dosa Factory',
  //   description:
  //     'South Indian eatery famous for over 50 varieties of modern and traditional dosas.',
  //   address: {
  //     street: 'Banjara Hills, Road No 3',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.012, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '91402770034', email: 'dosafactory@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Breakfast',
  //     'Indian',
  //     'Fast-Food',
  //     'Vegan',
  //     'Healthy',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 15000,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Hyderabadi House',
  //   description:
  //     'Traditional restaurant focusing on authentic Hyderabadi Pulao and rich curries.',
  //   address: {
  //     street: 'Gachibowli, Near Wipro Circle',
  //     city: 'Hyderabad',
  //     state: 'Telangana',
  //     zip_code: '500032',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.08, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '91402770035', email: 'hyderabadihouse@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'BBQ',
  //     'Fast-Food',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 11000,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 950,
  //   delivery_time_mins: 45,
  // },
  // all of the restaruatns have been seeded
];

export default hyderabadRestaurants;
