// Base coordinates for Indore (approximate center)
const baseLat = 22.7196;
const baseLon = 75.8577;

export const IndoreRestaurants = [
  // --- First 15 Restaurants ---
  // {
  //   name: 'Maame Da Dhaba',
  //   description: 'Authentic North Indian cuisine with a modern twist.',
  //   address: {
  //     street: '10 AB Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon - 0.02, baseLat + 0.01] },
  //   },
  //   contact: { phone: '9876543210', email: 'maamedadhaba@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Lunch', 'Dinner', 'Street-Food'],
  //   rating: 4.5,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'SK Pizza Wala',
  //   description: 'Freshly baked Neapolitan pizzas and Italian pasta.',
  //   address: {
  //     street: '25 Palasia Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon + 0.03, baseLat - 0.01] },
  //   },
  //   contact: { phone: '9988776655', email: 'skpizzawala@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Pizza',
  //     'Fast-Food',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.8,
  //   numberOfReviews: 2000,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 750,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Burger Hub',
  //   description: 'Gourmet burgers and shakes for every craving.',
  //   address: {
  //     street: 'Bhawarkua Main Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon + 0.01, baseLat - 0.03] },
  //   },
  //   contact: { phone: '9123456789', email: 'burgerhub@example.com' },
  //   cuisine_type: [
  //     'Fast-Food',
  //     'Burgers',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //     'Sandwiches',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Wednesday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Chopstix Express',
  //   description: 'Quick and delicious Chinese stir-fries and noodles.',
  //   address: {
  //     street: 'Rajendra Nagar',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon - 0.03, baseLat - 0.01] },
  //   },
  //   contact: { phone: '9765432109', email: 'chopstix@example.com' },
  //   cuisine_type: ['Chinese', 'Fast-Food', 'Lunch', 'Dinner', 'Soups', 'Vegan'],
  //   rating: 4.0,
  //   numberOfReviews: 600,
  //   opening_hours: [{ day: 'Thursday', open: '11:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 220,
  //   delivery_radius_km: 4,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Sweet Tooth Cafe',
  //   description: 'Delightful desserts, pastries, and coffee.',
  //   address: {
  //     street: 'Vijay Nagar Square',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon + 0.04, baseLat + 0.02] },
  //   },
  //   contact: { phone: '9654321098', email: 'sweettooth@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Beverages',
  //     'Breakfast',
  //     'Indian-Sweets',
  //     'Fast-Food',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Friday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'El Fuego Mexican Grill',
  //   description: 'Spicy Mexican tacos, burritos, and quesadillas.',
  //   address: {
  //     street: 'New Palasia Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9112233445', email: 'elfuego@example.com' },
  //   cuisine_type: ['Mexican', 'Fast-Food', 'Lunch', 'Dinner', 'Beverages'],
  //   rating: 4.6,
  //   numberOfReviews: 700,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Green Leaf Vegan Cafe',
  //   description: 'Purely vegan and organic meals for a healthy lifestyle.',
  //   address: {
  //     street: 'Sudama Nagar Main Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.035, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9113344556', email: 'greenleaf@example.com' },
  //   cuisine_type: [
  //     'Vegan',
  //     'Healthy',
  //     'Salads',
  //     'Soups',
  //     'Breakfast',
  //     'Lunch',
  //   ],
  //   rating: 4.9,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Wednesday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Sushi Bar',
  //   description: 'Freshly prepared sushi and authentic Japanese rolls.',
  //   address: {
  //     street: 'Scheme No. 78',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9114455667', email: 'sushibar@example.com' },
  //   cuisine_type: ['Sushi', 'Japanese', 'Dinner', 'Lunch', 'Healthy'],
  //   rating: 4.7,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Thursday', open: '18:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: "Mama's BBQ Joint",
  //   description: 'Classic American BBQ with smoky ribs and chicken.',
  //   address: {
  //     street: 'Race Course Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon - 0.01, baseLat - 0.03] },
  //   },
  //   contact: { phone: '9115566778', email: 'mamasbbq@example.com' },
  //   cuisine_type: ['BBQ', 'Dinner', 'Lunch', 'Fast-Food', 'Sandwiches'],
  //   rating: 4.4,
  //   numberOfReviews: 600,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Panini Place',
  //   description: 'Artisanal sandwiches and gourmet paninis.',
  //   address: {
  //     street: 'AB Road, near C21 Mall',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9012345678', email: 'paniniplace@example.com' },
  //   cuisine_type: ['Sandwiches', 'Healthy', 'Breakfast', 'Lunch', 'Beverages'],
  //   rating: 4.3,
  //   numberOfReviews: 350,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'The Wok Master',
  //   description: 'Customizable stir-fry bowls and authentic Asian street food.',
  //   address: {
  //     street: 'Malhar Mall Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon + 0.01, baseLat + 0.02] },
  //   },
  //   contact: { phone: '9123456780', email: 'wokmaster@example.com' },
  //   cuisine_type: ['Chinese', 'Street-Food', 'Fast-Food', 'Lunch', 'Dinner'],
  //   rating: 4.6,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Cheesy Corner',
  //   description: 'Indulgent pasta dishes and cheesy garlic bread.',
  //   address: {
  //     street: 'Scheme No. 114',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon + 0.05, baseLat + 0.03] },
  //   },
  //   contact: { phone: '9234567890', email: 'cheesycorner@example.com' },
  //   cuisine_type: [
  //     'Italian',
  //     'Pizza',
  //     'Fast-Food',
  //     'Dinner',
  //     'Desserts',
  //     'Lunch',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 500,
  //   opening_hours: [{ day: 'Monday', open: '13:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Bombay Kulfi & Falooda',
  //   description: 'Traditional Indian kulfi and creamy falooda.',
  //   address: {
  //     street: 'Sarafa Bazaar',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9345678901', email: 'bombaykulfi@example.com' },
  //   cuisine_type: ['Desserts', 'Indian-Sweets', 'Beverages', 'Street-Food'],
  //   rating: 4.8,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Tuesday', open: '18:00', close: '02:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 3,
  //   is_veg: true,
  //   cost_for_two: 150,
  //   delivery_time_mins: 15,
  // },
  // {
  //   name: 'The Brew & Grind',
  //   description: 'Artisan coffee, cold brews, and fresh pastries.',
  //   address: {
  //     street: 'Press Complex',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.035, baseLat + 0.035],
  //     },
  //   },
  //   contact: { phone: '9456789012', email: 'brewandgrind@example.com' },
  //   cuisine_type: [
  //     'Beverages',
  //     'Desserts',
  //     'Breakfast',
  //     'Sandwiches',
  //     'Fast-Food',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 850,
  //   opening_hours: [{ day: 'Wednesday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Sagar Ratna',
  //   description: 'Authentic South Indian vegetarian food.',
  //   address: {
  //     street: 'MG Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon - 0.02, baseLat - 0.02] },
  //   },
  //   contact: { phone: '9567890123', email: 'sagar.ratna@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //     'Vegan',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Thursday', open: '08:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  //   second 10
  // {
  //   name: 'Burger Singh',
  //   description: 'Indian-inspired burgers and fusion sides.',
  //   address: {
  //     street: 'New Palasia, Sector B',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9678901234', email: 'burgersingh@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Indian',
  //     'Street-Food',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Salad Factory',
  //   description: 'Create your own fresh and healthy salads and bowls.',
  //   address: {
  //     street: 'Lalbagh Palace Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon - 0.03, baseLat + 0.02] },
  //   },
  //   contact: { phone: '9789012345', email: 'saladfactory@example.com' },
  //   cuisine_type: ['Salads', 'Healthy', 'Vegan', 'Soups', 'Lunch', 'Breakfast'],
  //   rating: 4.7,
  //   numberOfReviews: 600,
  //   opening_hours: [{ day: 'Saturday', open: '10:30', close: '20:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'The Pasta Bowl Co.',
  //   description: 'Authentic Italian pasta made with fresh ingredients.',
  //   address: {
  //     street: 'Race Course Road, near City Center',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9890123456', email: 'pastabowlco@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Dinner', 'Lunch', 'Soups', 'Salads'],
  //   rating: 4.5,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 650,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Bake House',
  //   description: 'Freshly baked breads, cakes, and coffee.',
  //   address: {
  //     street: 'Vijay Nagar, Scheme 54',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.045, baseLat + 0.045],
  //     },
  //   },
  //   contact: { phone: '9901234567', email: 'bakehouse@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Beverages',
  //     'Breakfast',
  //     'Sandwiches',
  //     'Indian-Sweets',
  //   ],
  //   rating: 4.9,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Monday', open: '07:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'The Grand Wok',
  //   description: 'Fine dining Chinese and pan-Asian cuisine.',
  //   address: {
  //     street: 'South Tukoganj, near Treasure Island',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon - 0.01, baseLat - 0.01] },
  //   },
  //   contact: { phone: '9112233446', email: 'grandwok@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Dinner', 'Lunch', 'Soups'],
  //   rating: 4.3,
  //   numberOfReviews: 1000,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Healthy Hub',
  //   description: 'Customizable meal plans and healthy bowls.',
  //   address: {
  //     street: 'Navlakha Square',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9113344557', email: 'healthyhub@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Salads',
  //     'Vegan',
  //     'Soups',
  //     'Lunch',
  //     'Breakfast',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 400,
  //   opening_hours: [{ day: 'Wednesday', open: '10:00', close: '20:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Soup Kitchen',
  //   description: 'Hearty and fresh soups, stews, and bread.',
  //   address: {
  //     street: 'Ring Road, near Velocity',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon + 0.03, baseLat - 0.03] },
  //   },
  //   contact: { phone: '9114455668', email: 'soupkitchen@example.com' },
  //   cuisine_type: [
  //     'Soups',
  //     'Healthy',
  //     'Sandwiches',
  //     'Lunch',
  //     'Dinner',
  //     'Vegan',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 300,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The BBQ Shack',
  //   description: 'Smoky, slow-cooked BBQ and grilled meats.',
  //   address: {
  //     street: 'Vijay Nagar, behind Sayaji Hotel',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon + 0.04, baseLat + 0.01] },
  //   },
  //   contact: { phone: '9115566779', email: 'bbqshack@example.com' },
  //   cuisine_type: ['BBQ', 'Dinner', 'Lunch', 'Fast-Food', 'North-Indian'],
  //   rating: 4.6,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Friday', open: '18:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Taco Fiesta',
  //   description: 'Authentic Mexican flavors with a modern twist.',
  //   address: {
  //     street: 'Scheme No. 140',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon + 0.05, baseLat - 0.01] },
  //   },
  //   contact: { phone: '9116677880', email: 'tacofiesta@example.com' },
  //   cuisine_type: ['Mexican', 'Fast-Food', 'Lunch', 'Dinner', 'Salads'],
  //   rating: 4.4,
  //   numberOfReviews: 550,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Vegan Vibe',
  //   description: 'Plant-based comfort food and delicious desserts.',
  //   address: {
  //     street: 'Sudama Nagar, near Holkar Stadium',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.035, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9117788990', email: 'veganvibe@example.com' },
  //   cuisine_type: ['Vegan', 'Healthy', 'Desserts', 'Lunch', 'Salads', 'Soups'],
  //   rating: 4.8,
  //   numberOfReviews: 700,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 450,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Samurai Sushi',
  //   description: 'Elegant and authentic Japanese sushi and rolls.',
  //   address: {
  //     street: 'Navlakha, near Medanta Hospital',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.045, baseLat - 0.045],
  //     },
  //   },
  //   contact: { phone: '9118899001', email: 'samuraisushi@example.com' },
  //   cuisine_type: ['Sushi', 'Japanese', 'Healthy', 'Dinner', 'Lunch', 'Soups'],
  //   rating: 4.9,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Monday', open: '18:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 12,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 55,
  // },
  // third 10
  // {
  //   name: 'The Deli Club',
  //   description: 'Gourmet sandwiches and fresh salads.',
  //   address: {
  //     street: 'MG Road, near 56 Dukan',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.005, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9119900112', email: 'deliclub@example.com' },
  //   cuisine_type: [
  //     'Sandwiches',
  //     'Salads',
  //     'Healthy',
  //     'Breakfast',
  //     'Lunch',
  //     'Beverages',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 450,
  //   opening_hours: [{ day: 'Tuesday', open: '10:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Pind Balluchi',
  //   description: 'Traditional Punjabi and North Indian food.',
  //   address: {
  //     street: "Vijay Nagar, above Domino's",
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.055, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '9120011223', email: 'pindballuchi@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'Desserts'],
  //   rating: 4.5,
  //   numberOfReviews: 2000,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Pizza Box',
  //   description: 'Customizable pizzas with a variety of toppings.',
  //   address: {
  //     street: 'Malhar Mall, Food Court',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '9121122334', email: 'pizzabox@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Lunch', 'Dinner'],
  //   rating: 4.0,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Burger Factory',
  //   description: 'Hand-crafted burgers with fresh, local ingredients.',
  //   address: {
  //     street: 'Scheme No. 78, AB Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9122233445', email: 'burgerfactory@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Pizza',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 1400,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The South Indian Rasoi',
  //   description: 'Crispy dosas, idlis, and authentic South Indian thalis.',
  //   address: {
  //     street: 'MG Road, near C21 Mall',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9129900112', email: 'southrasoi@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Breakfast', 'Lunch', 'Dinner'],
  //   rating: 4.6,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Friday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Cakes & Bakes',
  //   description: 'Freshly baked cakes, pastries, and desserts.',
  //   address: {
  //     street: 'Mahalaxmi Nagar',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.06, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9124455667', email: 'cakesandbakes@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Beverages',
  //     'Sandwiches',
  //     'Indian-Sweets',
  //     'Street-Food',
  //   ],
  //   rating: 4.8,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Sunday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'The Organic Kitchen',
  //   description: 'All-organic, farm-to-table healthy meals.',
  //   address: {
  //     street: 'Rau, Bypass Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat - 0.05],
  //     },
  //   },
  //   contact: { phone: '9125566778', email: 'organickitchen@example.com' },
  //   cuisine_type: ['Healthy', 'Vegan', 'Salads', 'Soups', 'Breakfast'],
  //   rating: 4.9,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '20:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 9,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Mexican Burrito House',
  //   description: 'Hearty burritos, nachos, and quesadillas.',
  //   address: {
  //     street: 'Vijay Nagar, Near Bombay Hospital',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.045, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9126677889', email: 'burritohouse@example.com' },
  //   cuisine_type: ['Mexican', 'Fast-Food', 'Lunch', 'Dinner', 'Beverages'],
  //   rating: 4.3,
  //   numberOfReviews: 600,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Sizzling Grill',
  //   description: 'Grilled food and BBQ platters.',
  //   address: {
  //     street: 'Kanchan Bagh, AB Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '9127788990', email: 'sizzlinggrill@example.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Dinner', 'Lunch', 'Beverages'],
  //   rating: 4.7,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 950,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Veggie World',
  //   description: 'All-vegetarian, traditional and modern dishes.',
  //   address: {
  //     street: 'Sapna Sangeeta, near Treasure Island',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat + 0.035],
  //     },
  //   },
  //   contact: { phone: '9128899001', email: 'veggieworld@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'North-Indian',
  //     'Vegan',
  //     'Healthy',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // fourth 10
  // {
  //   name: 'The Healthy Cafe',
  //   description: 'Wholesome and nutritious meals for a healthy life.',
  //   address: {
  //     street: 'Scheme No. 114, near Bombay Hospital',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.055, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9133344556', email: 'healthycafe@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Breakfast',
  //     'Lunch',
  //     'Salads',
  //     'Soups',
  //     'Vegan',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 600,
  //   opening_hours: [{ day: 'Tuesday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Soup Spot',
  //   description: 'Daily fresh soups and grilled sandwiches.',
  //   address: {
  //     street: 'Ring Road, near Velocity',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon + 0.02, baseLat - 0.04] },
  //   },
  //   contact: { phone: '9134455667', email: 'soupspot@example.com' },
  //   cuisine_type: [
  //     'Soups',
  //     'Sandwiches',
  //     'Healthy',
  //     'Lunch',
  //     'Dinner',
  //     'Vegan',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 350,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '20:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The BBQ House',
  //   description: 'Classic BBQ ribs, chicken, and steaks.',
  //   address: {
  //     street: 'Vijay Nagar, Scheme 54',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.035, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9135566778', email: 'bbqhouse@example.com' },
  //   cuisine_type: ['BBQ', 'Dinner', 'North-Indian', 'Lunch'],
  //   rating: 4.8,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Thursday', open: '18:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'The Indian Street Food',
  //   description: 'Authentic Indian street food and snacks.',
  //   address: {
  //     street: 'Sarafa Bazaar, Main Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: { type: 'Point', coordinates: [baseLon - 0.01, baseLat - 0.01] },
  //   },
  //   contact: { phone: '9136677889', email: 'indianstreetfood@example.com' },
  //   cuisine_type: ['Street-Food', 'Indian', 'Fast-Food', 'Breakfast', 'Lunch'],
  //   rating: 4.4,
  //   numberOfReviews: 2000,
  //   opening_hours: [{ day: 'Friday', open: '16:00', close: '02:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 4,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'The Italian Bistro',
  //   description: 'Classic Italian dishes and desserts.',
  //   address: {
  //     street: 'MG Road, near Regal Square',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9137788990', email: 'italianbistro@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Desserts', 'Dinner', 'Lunch'],
  //   rating: 4.6,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Burger Joint',
  //   description: 'Juicy, gourmet burgers and crispy fries.',
  //   address: {
  //     street: 'Scheme No. 54, near Vijay Nagar',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9138899001', email: 'burgerjoint@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Beverages', 'Lunch', 'Dinner'],
  //   rating: 4.3,
  //   numberOfReviews: 900,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Japanese Wok',
  //   description: 'Authentic Chinese and Thai stir-fries.',
  //   address: {
  //     street: 'Malhar Mall Road, near C21 Mall',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9139900112', email: 'asianwok@example.com' },
  //   cuisine_type: ['Japanese', 'Chinese', 'Soups', 'Dinner', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 700,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Dessert Spot',
  //   description: 'Delicious cakes, pastries, and ice creams.',
  //   address: {
  //     street: 'Sudama Nagar, near Holkar Stadium',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat - 0.035],
  //     },
  //   },
  //   contact: { phone: '9140011223', email: 'dessertspot@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Beverages',
  //     'Indian-Sweets',
  //     'Breakfast',
  //     'Fast-Food',
  //   ],
  //   rating: 4.9,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'The Breakfast House',
  //   description: 'All-day breakfast with classic and modern options.',
  //   address: {
  //     street: 'Rajendra Nagar, near DAVV',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9141122334', email: 'breakfasthouse@example.com' },
  //   cuisine_type: [
  //     'Breakfast',
  //     'Sandwiches',
  //     'Healthy',
  //     'Desserts',
  //     'Beverages',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Wednesday', open: '08:00', close: '20:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Harsh Cafe',
  //   description: 'Experience the best Indian breakfast but in different way',
  //   address: {
  //     street: 'Vijay Nagar',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9141122334', email: 'breakfasthouse@example.com' },
  //   cuisine_type: ['Breakfast', 'Sandwiches', 'Desserts', 'Beverages'],
  //   rating: 4.6,
  //   numberOfReviews: 800,
  //   opening_hours: [{ day: 'Wednesday', open: '08:00', close: '20:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // fifth 10
  // {
  //   name: 'Sankalp Restaurant',
  //   description: 'Famous for its long dosas and authentic South Indian cuisine.',
  //   address: {
  //     street: 'C21 Mall, AB Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452010',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.042, baseLat + 0.018],
  //     },
  //   },
  //   contact: { phone: '9142233445', email: 'sankalp.ind@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Vegan', 'Breakfast', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Indian Coffee House',
  //   description: 'A classic spot with old-world charm, serving South Indian staples.',
  //   address: {
  //     street: 'MG Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452007',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat - 0.002],
  //     },
  //   },
  //   contact: { phone: '9143344556', email: 'ich.ind@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Breakfast',
  //     'Beverages',
  //     'Fast-Food',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Tuesday', open: '09:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Shizusan Shophouse & Bar',
  //   description: 'A trendy spot for innovative sushi and Pan-Asian dishes.',
  //   address: {
  //     street: 'Phoenix Citadel Mall',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.06, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9144455667', email: 'shizusan.ind@example.com' },
  //   cuisine_type: ['Sushi', 'Japanese', 'Chinese', 'Dinner', 'Beverages'],
  //   rating: 4.7,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Oye! Papacito',
  //   description: 'Vibrant and modern Mexican kitchen with lively music.',
  //   address: {
  //     street: 'Bhawarkua',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.012, baseLat - 0.035],
  //     },
  //   },
  //   contact: { phone: '9145566778', email: 'oyepapacito@example.com' },
  //   cuisine_type: ['Mexican', 'Tacos', 'Fast-Food', 'Dinner', 'Beverages'],
  //   rating: 4.4,
  //   numberOfReviews: 950,
  //   opening_hours: [{ day: 'Thursday', open: '13:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Nafees Restaurant',
  //   description: 'A legendary spot in Indore for authentic Mughlai cuisine.',
  //   address: {
  //     street: '30, Old Palasia',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.028, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9146677889', email: 'nafees@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'BBQ', 'Dinner', 'Lunch'],
  //   rating: 4.6,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Kebabsville - Sayaji Hotel',
  //   description: 'Live grills and lavish BBQ buffets by the poolside.',
  //   address: {
  //     street: 'H/1, Scheme No. 54, Vijay Nagar',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452010',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.048, baseLat + 0.012],
  //     },
  //   },
  //   contact: { phone: '9147788990', email: 'kebabsville@sayaji.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Indian', 'Dinner', 'Salads'],
  //   rating: 4.8,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Saturday', open: '19:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Johny Hot Dog',
  //   description: "Indore's iconic street food joint, famous for its unique hot dogs.",
  //   address: {
  //     street: '56 Dukan, New Palasia',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.022, baseLat - 0.011],
  //     },
  //   },
  //   contact: { phone: '9148899001', email: 'johnyhotdog@example.com' },
  //   cuisine_type: ['Street-Food', 'Fast-Food', 'Burgers', 'Sandwiches'],
  //   rating: 4.9,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 50,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 150,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Mainland China',
  //   description: 'Fine dining restaurant offering authentic Chinese cuisine.',
  //   address: {
  //     street: 'C21 Mall, AB Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452010',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.041, baseLat + 0.019],
  //     },
  //   },
  //   contact: { phone: '9149900112', email: 'mainlandchina.ind@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Dinner', 'Lunch', 'Soups'],
  //   rating: 4.5,
  //   numberOfReviews: 2400,
  //   opening_hours: [{ day: 'Monday', open: '12:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Little Italy',
  //   description: 'Authentic vegetarian Italian & Mexican cuisine.',
  //   address: {
  //     street: 'Brilliant Convention Centre, Scheme 78',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452010',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.05, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9150011223', email: 'littleitaly.ind@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Mexican', 'Vegan', 'Salads', 'Dinner'],
  //   rating: 4.6,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Vijay Chaat House',
  //   description: "A legendary name in Indore for all kinds of chaat and street food.",
  //   address: {
  //     street: 'Sarafa Bazaar',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.008, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9151122334', email: 'vijaychaat@example.com' },
  //   cuisine_type: ['Street-Food', 'Indian', 'Fast-Food', 'Snacks'],
  //   rating: 4.8,
  //   numberOfReviews: 8000,
  //   opening_hours: [{ day: 'Wednesday', open: '19:00', close: '02:00' }],
  //   is_active: true,
  //   min_order_value: 60,
  //   delivery_radius_km: 4,
  //   is_veg: true,
  //   cost_for_two: 150,
  //   delivery_time_mins: 25,
  // },
  // next 10
  // {
  //   name: 'Dosa Craft',
  //   description: 'Modern and creative varieties of dosas.',
  //   address: {
  //     street: 'Anand Bazaar',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9152233445', email: 'dosacraft@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Fast-Food', 'Breakfast'],
  //   rating: 4.4,
  //   numberOfReviews: 850,
  //   opening_hours: [{ day: 'Thursday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Ni Hao',
  //   description: 'Authentic Japanese and Pan-Asian fine dining.',
  //   address: {
  //     street: 'Radisson Blu Hotel, Vijay Nagar',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452010',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.052, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9153344556', email: 'nihao@radisson.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Chinese', 'Dinner'],
  //   rating: 4.6,
  //   numberOfReviews: 1300,
  //   opening_hours: [{ day: 'Friday', open: '19:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 1000,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 3000,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'The Burrito Bar',
  //   description: 'Build-your-own burritos and bowls with fresh ingredients.',
  //   address: {
  //     street: 'Geeta Bhawan',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9154455667', email: 'burritobar@example.com' },
  //   cuisine_type: ['Mexican', 'Healthy', 'Fast-Food', 'Lunch', 'Dinner'],
  //   rating: 4.3,
  //   numberOfReviews: 780,
  //   opening_hours: [{ day: 'Saturday', open: '11:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Shreemaya Celebrity',
  //   description: 'A popular choice for family dining with a multi-cuisine menu.',
  //   address: {
  //     street: 'RNT Marg',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.002, baseLat - 0.009],
  //     },
  //   },
  //   contact: { phone: '9155566778', email: 'shreemaya@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Chinese',
  //     'Lunch',
  //     'Dinner',
  //     'Desserts',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Barbeque Nation',
  //   description: 'The original live-on-the-table grill restaurant.',
  //   address: {
  //     street: 'Malhar Mega Mall, AB Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452010',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.038, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9156677889', email: 'bbqnation.ind@example.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Indian', 'Dinner', 'Lunch'],
  //   rating: 4.7,
  //   numberOfReviews: 5000,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'The Burger Crew',
  //   description: 'Craft burgers with premium patties and unique sauces.',
  //   address: {
  //     street: 'LIG Colony',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452008',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9157788990', email: 'burgercrew@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Beverages', 'Snacks'],
  //   rating: 4.5,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Haochi',
  //   description: 'A casual dining spot for delicious and quick Chinese meals.',
  //   address: {
  //     street: 'Bhawarkua Main Rd',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat - 0.032],
  //     },
  //   },
  //   contact: { phone: '9158899001', email: 'haochi@example.com' },
  //   cuisine_type: ['Chinese', 'Fast-Food', 'Soups', 'Lunch', 'Dinner'],
  //   rating: 4.1,
  //   numberOfReviews: 1400,
  //   opening_hours: [{ day: 'Wednesday', open: '11:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 180,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: "Domino's Pizza",
  //   description: 'Your favorite pizza delivery chain.',
  //   address: {
  //     street: 'Multiple Locations',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452010',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.045, baseLat + 0.009],
  //     },
  //   },
  //   contact: { phone: '9159900112', email: 'dominos.ind@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Desserts', 'Beverages'],
  //   rating: 4.0,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Apna Sweets',
  //   description: 'A trusted name for Indian sweets, snacks, and vegetarian meals.',
  //   address: {
  //     street: '56 Dukan, New Palasia',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.021, baseLat - 0.012],
  //     },
  //   },
  //   contact: { phone: '9160011223', email: 'apnasweets@example.com' },
  //   cuisine_type: [
  //     'Indian-Sweets',
  //     'Street-Food',
  //     'Desserts',
  //     'North-Indian',
  //     'Breakfast',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 6000,
  //   opening_hours: [{ day: 'Friday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // next 10
  // {
  //   name: 'Idli Bhavan',
  //   description: 'A dedicated place for soft, fluffy idlis and crispy vadas.',
  //   address: {
  //     street: 'Annapurna Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452009',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.045, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9161122334', email: 'idlibhavan@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Healthy', 'Snacks'],
  //   rating: 4.6,
  //   numberOfReviews: 1100,
  //   opening_hours: [{ day: 'Saturday', open: '07:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 22,
  // },
  // {
  //   name: 'Tokyo Table',
  //   description: 'Experience authentic Japanese dining with sushi, sashimi, and more.',
  //   address: {
  //     street: 'South Tukoganj',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.008, baseLat - 0.011],
  //     },
  //   },
  //   contact: { phone: '9162233445', email: 'tokyotable@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Dinner', 'Healthy'],
  //   rating: 4.5,
  //   numberOfReviews: 980,
  //   opening_hours: [{ day: 'Sunday', open: '18:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2200,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Taco Cantina',
  //   description: 'Lively cantina serving a wide range of tacos and margaritas.',
  //   address: {
  //     street: 'Satya Sai Square',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452010',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.055, baseLat + 0.002],
  //     },
  //   },
  //   contact: { phone: '9163344556', email: 'tacocantina@example.com' },
  //   cuisine_type: ['Mexican', 'Fast-Food', 'Dinner', 'Beverages'],
  //   rating: 4.2,
  //   numberOfReviews: 650,
  //   opening_hours: [{ day: 'Monday', open: '13:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 220,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 750,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Punjabi Roots',
  //   description: 'Homely and authentic Punjabi food that tastes like grandma\'s cooking.',
  //   address: {
  //     street: 'Airport Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.06, baseLat + 0.04],
  //     },
  //   },
  //   contact: { phone: '9164455667', email: 'punjabiroots@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Lunch', 'Dinner'],
  //   rating: 4.6,
  //   numberOfReviews: 1700,
  //   opening_hours: [{ day: 'Tuesday', open: '11:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Smokin\' Hot BBQ',
  //   description: 'American-style smoked meats and classic BBQ sides.',
  //   address: {
  //     street: 'Rau Circle',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '453331',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.07, baseLat - 0.06],
  //     },
  //   },
  //   contact: { phone: '9165566778', email: 'smokinhot@example.com' },
  //   cuisine_type: ['BBQ', 'American', 'Fast-Food', 'Dinner'],
  //   rating: 4.5,
  //   numberOfReviews: 880,
  //   opening_hours: [{ day: 'Wednesday', open: '17:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Patty & Bun',
  //   description: 'Simple, delicious, and juicy burgers made with love.',
  //   address: {
  //     street: 'Tilak Nagar',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452018',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.018, baseLat + 0.028],
  //     },
  //   },
  //   contact: { phone: '9166677889', email: 'pattyandbun@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Snacks', 'Beverages'],
  //   rating: 4.3,
  //   numberOfReviews: 920,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 130,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Schezwan Express',
  //   description: 'Serving fiery and authentic Schezwan cuisine.',
  //   address: {
  //     street: 'Bengali Square',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.065, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9167788990', email: 'schezwanex@example.com' },
  //   cuisine_type: ['Chinese', 'Fast-Food', 'Lunch', 'Dinner'],
  //   rating: 4.0,
  //   numberOfReviews: 1150,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 170,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Pasta Project',
  //   description: 'A heaven for pasta lovers with customizable sauces and shapes.',
  //   address: {
  //     street: 'Saket Nagar',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9168899001', email: 'pastaproject@example.com' },
  //   cuisine_type: ['Italian', 'Salads', 'Desserts', 'Dinner'],
  //   rating: 4.5,
  //   numberOfReviews: 850,
  //   opening_hours: [{ day: 'Saturday', open: '13:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'JMB - Jodhpur Misthan Bhandar',
  //   description: 'Authentic Rajasthani sweets and savory snacks.',
  //   address: {
  //     street: 'Jail Road',
  //     city: 'Indore',
  //     state: 'Madhya Pradesh',
  //     zip_code: '452007',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.012, baseLat + 0.008],
  //     },
  //   },
  //   contact: { phone: '9169900112', email: 'jmb.ind@example.com' },
  //   cuisine_type: ['Indian-Sweets', 'Street-Food', 'Desserts', 'Breakfast'],
  //   rating: 4.6,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Sunday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 25,
  // },
];
