// Base coordinates for Jaipur (approximate center - C Scheme/Pink City area)
const baseLat = 26.9124;
const baseLon = 75.7873;

/**
 * Data structure for restaurants in Jaipur, ensuring wide coverage of all 24 supported cuisine types.
 * Each restaurant has 4-6 cuisine_types to satisfy the requirement that at least 9-10 restaurants
 * are available for every supported category.
 */
const jaipurRestaurants = [
  // --- Jaipur Restaurant 1-5 ---
  {
    name: 'Tapri Central',
    description:
      'Rooftop cafe famous for its diverse teas, snacks, and great views.',
    address: {
      street: 'C Scheme, Near Central Park',
      city: 'Jaipur',
      state: 'Rajasthan',
      zip_code: '302001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.02, baseLat + 0.01],
      },
    },
    contact: { phone: '9001120001', email: 'tapri.jpr@example.com' },
    cuisine_type: [
      'Breakfast',
      'Beverages',
      'Sandwiches',
      'Salads',
      'Healthy',
      'Street-Food',
    ],
    rating: 4.5,
    numberOfReviews: 15200,
    opening_hours: [{ day: 'Monday', open: '07:30', close: '22:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 800,
    delivery_time_mins: 35,
  },
  {
    name: 'Handi Restaurant',
    description:
      'Known for its authentic North Indian cuisine, especially Laal Maas and BBQ kebabs.',
    address: {
      street: 'M.I. Road, Near Badi Chopar',
      city: 'Jaipur',
      state: 'Rajasthan',
      zip_code: '302003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.01, baseLat + 0.005],
      },
    },
    contact: { phone: '9001120002', email: 'handi.jpr@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'BBQ',
      'Dinner',
      'Lunch',
      'Indian-Sweets',
    ],
    rating: 4.4,
    numberOfReviews: 9100,
    opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:30' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 1200,
    delivery_time_mins: 45,
  },
  {
    name: 'Niros Restaurant',
    description:
      'A classic M.I. Road spot serving Continental and Mughlai dishes for decades.',
    address: {
      street: 'M.I. Road, Opposite Raj Mandir',
      city: 'Jaipur',
      state: 'Rajasthan',
      zip_code: '302001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.005, baseLat - 0.005],
      },
    },
    contact: { phone: '9001120003', email: 'niros.jpr@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'Dinner',
      'Lunch',
      'Soups',
      'Beverages',
    ],
    rating: 4.3,
    numberOfReviews: 7500,
    opening_hours: [{ day: 'Wednesday', open: '11:30', close: '23:00' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 1100,
    delivery_time_mins: 40,
  },
  {
    name: 'Gaurav Kulfi House',
    description: 'The best place for traditional Indian Kulfi and ice creams.',
    address: {
      street: 'Raja Park, Near Pink Square Mall',
      city: 'Jaipur',
      state: 'Rajasthan',
      zip_code: '302004',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.03, baseLat - 0.02],
      },
    },
    contact: { phone: '9001120004', email: 'gaurav.kulfi@example.com' },
    cuisine_type: ['Desserts', 'Indian-Sweets', 'Fast-Food', 'Beverages'], // Niche, 4 categories
    rating: 4.7,
    numberOfReviews: 11200,
    opening_hours: [{ day: 'Thursday', open: '11:00', close: '00:00' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 300,
    delivery_time_mins: 30,
  },
  {
    name: 'The Yellow Door',
    description:
      'Contemporary spot for gourmet pizzas and Italian comfort food.',
    address: {
      street: 'Tonk Road, Lal Kothi',
      city: 'Jaipur',
      state: 'Rajasthan',
      zip_code: '302015',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.015, baseLat - 0.03],
      },
    },
    contact: { phone: '9001120005', email: 'yellowdoor@example.com' },
    cuisine_type: ['Pizza', 'Italian', 'Dinner', 'Lunch', 'Salads', 'Desserts'],
    rating: 4.4,
    numberOfReviews: 6800,
    opening_hours: [{ day: 'Friday', open: '12:30', close: '23:30' }],
    is_active: true,
    min_order_value: 550,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 1400,
    delivery_time_mins: 45,
  },
  // --- Jaipur Restaurant 6-10 ---
  // {
  //   name: 'Chokhi Dhani',
  //   description:
  //     'A village resort providing an authentic Rajasthani dining experience.',
  //   address: {
  //     street: '12 Mile, Tonk Road, Via Vatika',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '303903',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.05, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9001120006', email: 'chokhidhani@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'North-Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Indian-Sweets',
  //     'BBQ',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 18000,
  //   opening_hours: [{ day: 'Saturday', open: '17:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 10,
  //   is_veg: true,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'The Bullet Cafe',
  //   description:
  //     'Casual biker-themed cafe serving hearty burgers and sandwiches.',
  //   address: {
  //     street: 'Mansarovar, Near Shipra Path',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302020',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9001120007', email: 'bulletcafe@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Sandwiches',
  //     'Beverages',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Dragon House',
  //   description:
  //     'Authentic Chinese and Japanese cuisine with a modern interior.',
  //   address: {
  //     street: 'Malviya Nagar, Near WTP',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9001120008', email: 'dragonhouse@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Sushi', 'Dinner', 'Lunch', 'Soups'],
  //   rating: 4.5,
  //   numberOfReviews: 8900,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:45' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Anokhi Cafe',
  //   description:
  //     'Farm-to-table cafe focused on organic, healthy, and fresh meals.',
  //   address: {
  //     street: 'C Scheme, Near M.I. Road',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9001120009', email: 'anokhicafe@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Vegan',
  //     'Breakfast',
  //     'Salads',
  //     'Sandwiches',
  //     'Soups',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 10500,
  //   opening_hours: [{ day: 'Tuesday', open: '09:30', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Sankalp South Indian',
  //   description:
  //     'A dedicated restaurant chain serving crispy dosas and authentic South Indian fare.',
  //   address: {
  //     street: 'Gopalbari, Near Civil Lines',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9001120010', email: 'sankalp.jpr@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //     'Street-Food',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Wednesday', open: '08:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 25,
  // },

  // --- Jaipur Restaurant 11-15 ---
  // {
  //   name: 'Pizza Hut (M.I. Road)',
  //   description: 'Global pizza chain serving classic and pan pizzas.',
  //   address: {
  //     street: 'M.I. Road, Near Government Hostel',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.001],
  //     },
  //   },
  //   contact: { phone: '9001120011', email: 'pizzahut.jpr@example.com' },
  //   cuisine_type: [
  //     'Pizza',
  //     'Italian',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //     'Beverages',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: "Domino's Pizza (Bani Park)",
  //   description:
  //     'Fast delivery pizza specializing in oven-baked pies and sides.',
  //   address: {
  //     street: 'Bani Park, Near Collectorate Circle',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9001120012', email: 'dominos.jpr@example.com' },
  //   cuisine_type: [
  //     'Pizza',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //     'Desserts',
  //     'Beverages',
  //   ],
  //   rating: 3.9,
  //   numberOfReviews: 5000,
  //   opening_hours: [{ day: 'Friday', open: '10:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Burger King (JLN Marg)',
  //   description: 'International chain for flame-grilled burgers and fries.',
  //   address: {
  //     street: 'Jawahar Lal Nehru Marg, Malviya Nagar',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.035, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9001120013', email: 'burgerking.jpr@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Lunch',
  //     'Dinner',
  //     'Sandwiches',
  //     'Beverages',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 6100,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '23:45' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'KFC (Raja Park)',
  //   description: 'Famous for its fried chicken and fast food specialties.',
  //   address: {
  //     street: 'Raja Park, Near Pink Square',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat + 0.008],
  //     },
  //   },
  //   contact: { phone: '9001120014', email: 'kfc.jpr@example.com' },
  //   cuisine_type: [
  //     'Fast-Food',
  //     'BBQ',
  //     'Lunch',
  //     'Dinner',
  //     'Beverages',
  //     'Salads',
  //   ],
  //   rating: 3.8,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Sunday', open: '10:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 650,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Mexican Twist',
  //   description:
  //     'Casual eatery specializing in authentic Tacos, Burritos, and Nachos.',
  //   address: {
  //     street: 'Vaishali Nagar, Near Amrapali Circle',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302021',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9001120015', email: 'mexicantwist@example.com' },
  //   cuisine_type: [
  //     'Mexican',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //     'Vegan',
  //     'Salads',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 7200,
  //   opening_hours: [{ day: 'Monday', open: '11:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 9,
  //   is_veg: true,
  //   cost_for_two: 850,
  //   delivery_time_mins: 40,
  // },
  // // --- Jaipur Restaurant 16-20 ---
  // {
  //   name: 'Sushi Zen',
  //   description:
  //     'Fine-dining Japanese restaurant offering fresh Sashimi and Nigiri.',
  //   address: {
  //     street: 'C Scheme, Near Statue Circle',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.04],
  //     },
  //   },
  //   contact: { phone: '9001120016', email: 'sushizen@example.com' },
  //   cuisine_type: ['Sushi', 'Japanese', 'Dinner', 'Lunch', 'Soups', 'Healthy'],
  //   rating: 4.6,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Tuesday', open: '12:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'The Italian Bistro',
  //   description: 'Authentic Italian pasta, risottos, and thin-crust pizzas.',
  //   address: {
  //     street: 'Malviya Nagar, Girdhar Marg',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.018, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9001120017', email: 'italianbistro@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Dinner', 'Lunch', 'Soups', 'Vegan'],
  //   rating: 4.4,
  //   numberOfReviews: 5800,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1300,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Vegan Delights',
  //   description:
  //     '100% plant-based cafe offering creative and wholesome dishes.',
  //   address: {
  //     street: 'C Scheme, Near Jaipur Inn',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat + 0.002],
  //     },
  //   },
  //   contact: { phone: '9001120018', email: 'vegandelights@example.com' },
  //   cuisine_type: [
  //     'Vegan',
  //     'Healthy',
  //     'Breakfast',
  //     'Sandwiches',
  //     'Salads',
  //     'Soups',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Thursday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 950,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: "Chawla's",
  //   description: 'A popular spot for Mughlai and North Indian cuisine.',
  //   address: {
  //     street: 'Raja Park, Lane 1',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.032, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9001120019', email: 'chawlas.jpr@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'BBQ',
  //     'Chinese',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 8000,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 450,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Bikanervala',
  //   description:
  //     'Chain famous for Indian sweets, snacks, and vegetarian meals.',
  //   address: {
  //     street: 'Gopalpura Bypass, Near Gujjar Ki Thadi',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302019',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.045, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9001120020', email: 'bikanervala.jpr@example.com' },
  //   cuisine_type: [
  //     'Indian-Sweets',
  //     'Indian',
  //     'Fast-Food',
  //     'Desserts',
  //     'Breakfast',
  //     'Street-Food',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 10,
  //   is_veg: true,
  //   cost_for_two: 750,
  //   delivery_time_mins: 35,
  // },
  // // --- Jaipur Restaurant 21-25 ---
  // {
  //   name: 'The Burger Factory',
  //   description:
  //     'Gourmet burger joint known for unique toppings and fresh patties.',
  //   address: {
  //     street: 'C Scheme, Near Museum',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.008, baseLat + 0.018],
  //     },
  //   },
  //   contact: { phone: '9001120021', email: 'burgerfactory@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Lunch',
  //     'Dinner',
  //     'Beverages',
  //     'Pizza',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 4900,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Marwari Bhojanalaya',
  //   description:
  //     'Traditional Marwari thali and pure vegetarian North Indian food.',
  //   address: {
  //     street: 'Sodala, Near Ajmer Road',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9001120022', email: 'marwari.bhojan@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Vegan',
  //     'Indian-Sweets',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 6200,
  //   opening_hours: [{ day: 'Monday', open: '11:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Dosa Planet',
  //   description: 'A huge variety of South Indian Dosas and Uttapams.',
  //   address: {
  //     street: 'Adarsh Nagar, Near Pink Square',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9001120023', email: 'dosaplanet@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Breakfast',
  //     'Lunch',
  //     'Fast-Food',
  //     'Indian',
  //     'Street-Food',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 5400,
  //   opening_hours: [{ day: 'Tuesday', open: '08:30', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Chai Katta',
  //   description:
  //     'Popular spot for different types of chai, coffee, and light snacks.',
  //   address: {
  //     street: 'Bapu Nagar, Opposite Vidhan Sabha',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat - 0.035],
  //     },
  //   },
  //   contact: { phone: '9001120024', email: 'chaikatta@example.com' },
  //   cuisine_type: [
  //     'Beverages',
  //     'Breakfast',
  //     'Desserts',
  //     'Sandwiches',
  //     'Fast-Food',
  //     'Street-Food',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 7000,
  //   opening_hours: [{ day: 'Wednesday', open: '07:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Wok Master',
  //   description:
  //     'Quick-service restaurant offering customizable Chinese wok bowls.',
  //   address: {
  //     street: 'Vaishali Nagar, Near Elements Mall',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302021',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.06, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9001120025', email: 'wokmaster@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Fast-Food',
  //     'Lunch',
  //     'Dinner',
  //     'Soups',
  //     'Healthy',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // // --- Jaipur Restaurant 26-30 ---
  // {
  //   name: 'The Belgian Waffle Co.',
  //   description: 'Specializes in freshly baked waffles and sweet treats.',
  //   address: {
  //     street: 'C Scheme, Hawa Sadak',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.002, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9001120026', email: 'waffleco@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Breakfast',
  //     'Beverages',
  //     'Fast-Food',
  //     'Sandwiches',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 5100,
  //   opening_hours: [{ day: 'Friday', open: '10:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Biryani Express',
  //   description:
  //     'Dedicated outlet for flavorful Hyderabadi and Lucknowi Biryani.',
  //   address: {
  //     street: 'Lal Kothi, Near Tonk Road',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302015',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.045, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9001120027', email: 'biryaniexpress@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'BBQ',
  //     'Fast-Food',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 4000,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 750,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Om Sweet Home',
  //   description: 'Local favorite for traditional Rajasthani sweets and snacks.',
  //   address: {
  //     street: 'Badi Chopar, Pink City',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.001, baseLat + 0.001],
  //     },
  //   },
  //   contact: { phone: '9001120028', email: 'omsweethome@example.com' },
  //   cuisine_type: [
  //     'Indian-Sweets',
  //     'Desserts',
  //     'Street-Food',
  //     'Breakfast',
  //     'Indian',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 10100,
  //   opening_hours: [{ day: 'Sunday', open: '07:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 4,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Pizzaria Locale',
  //   description: 'Gourmet pizza place focusing on fresh, regional ingredients.',
  //   address: {
  //     street: 'Malviya Nagar, Sector 4',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.05, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9001120029', email: 'pizzarialocale@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Dinner', 'Lunch', 'Salads', 'Soups'],
  //   rating: 4.5,
  //   numberOfReviews: 4100,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 450,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'The Healthy Bowl',
  //   description:
  //     'A dedicated health food outlet for customizable bowls, smoothies, and juices.',
  //   address: {
  //     street: 'Civil Lines, Near Metro Station',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302006',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.035],
  //     },
  //   },
  //   contact: { phone: '9001120030', email: 'healthybowl@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Vegan',
  //     'Breakfast',
  //     'Salads',
  //     'Beverages',
  //     'Sandwiches',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Tuesday', open: '08:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 30,
  // },
  // // --- Jaipur Restaurant 31-35 (Buffer to ensure all categories are hit 9+ times) ---
  // {
  //   name: 'South Indian Corner',
  //   description: 'Simple, authentic South Indian breakfast and meals.',
  //   address: {
  //     street: 'Jhotwara Road, Shastri Nagar',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.035, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9001120031', email: 'si.corner@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Lunch', 'Indian', 'Fast-Food'],
  //   rating: 4.1,
  //   numberOfReviews: 3000,
  //   opening_hours: [{ day: 'Wednesday', open: '07:30', close: '21:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Mughal Mahal',
  //   description:
  //     'A grand restaurant specializing in Mughlai and Awadhi cuisine.',
  //   address: {
  //     street: 'Near Ajmeri Gate, Pink City',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9001120032', email: 'mughal.mahal@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ'],
  //   rating: 4.3,
  //   numberOfReviews: 5900,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'The Dessert Cart',
  //   description:
  //     'A small outlet for fresh cakes, pastries, and artisanal desserts.',
  //   address: {
  //     street: 'Malviya Nagar, Near Gaurav Tower',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302017',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat - 0.001],
  //     },
  //   },
  //   contact: { phone: '9001120033', email: 'dessertcart@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Indian-Sweets', 'Breakfast'],
  //   rating: 4.6,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Friday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 450,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Noodle Bar',
  //   description:
  //     'A modern Asian eatery focusing on noodles, dim sum, and sushi.',
  //   address: {
  //     street: 'C Scheme, Sardar Patel Marg',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '9001120034', email: 'noodlebar@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Sushi', 'Dinner', 'Lunch', 'Soups'],
  //   rating: 4.4,
  //   numberOfReviews: 5300,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 550,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Jaipur Grill House',
  //   description:
  //     'A premium destination for grilled meats, kebabs, and continental fare.',
  //   address: {
  //     street: 'Tonk Road, Durgapura',
  //     city: 'Jaipur',
  //     state: 'Rajasthan',
  //     zip_code: '302018',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.06, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9001120035', email: 'jaipurgillhouse@example.com' },
  //   cuisine_type: [
  //     'BBQ',
  //     'North-Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Italian',
  //     'Pizza',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 6000,
  //   opening_hours: [{ day: 'Sunday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 50,
  // },
];
