// Base coordinates for Lucknow (approximate center - Hazratganj/Gomti Nagar)
const baseLat = 26.8522;
const baseLon = 80.9467;

/**
 * Data structure for restaurants in Lucknow, ensuring wide coverage of all 24 supported cuisine types.
 * 35 restaurants are generated, focusing heavily on Awadhi/Mughlai specialties.
 */
const lucknowRestaurants = [
  // --- Lucknow Restaurant 1-5 (Awadhi & North Indian Focus) ---
  {
    name: 'Tunday Kababi (Chowk)',
    description:
      'The legendary spot famous globally for its melt-in-the-mouth Galouti Kebabs.',
    address: {
      street: 'Chowk, Near Akbari Gate',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.015, baseLat - 0.01],
      },
    },
    contact: { phone: '9122010001', email: 'tunday.chowk@example.com' },
    cuisine_type: [
      'North-Indian',
      'BBQ',
      'Dinner',
      'Lunch',
      'Fast-Food',
      'Indian',
    ],
    rating: 4.8,
    numberOfReviews: 25500,
    opening_hours: [{ day: 'Monday', open: '12:00', close: '23:30' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 600,
    delivery_time_mins: 45,
  },
  {
    name: 'Idrees Biryani',
    description:
      'Iconic spot for traditional Awadhi Biryani, cooked in the authentic *dum* style.',
    address: {
      street: 'Jahaz Island, Chowk',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.01, baseLat - 0.005],
      },
    },
    contact: { phone: '9122010002', email: 'idreesbiryani@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'Dinner',
      'Lunch',
      'BBQ',
      'Street-Food',
    ],
    rating: 4.6,
    numberOfReviews: 18900,
    opening_hours: [{ day: 'Tuesday', open: '12:30', close: '22:00' }],
    is_active: true,
    min_order_value: 350,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 550,
    delivery_time_mins: 40,
  },
  {
    name: 'Royal Cafe',
    description:
      'Famous for its Basket Chaat, a Lucknow street food delicacy, and North Indian meals.',
    address: {
      street: 'Hazratganj, Near Sapru Marg',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.005, baseLat + 0.002],
      },
    },
    contact: { phone: '9122010003', email: 'royalcafe@example.com' },
    cuisine_type: [
      'Street-Food',
      'North-Indian',
      'Fast-Food',
      'Lunch',
      'Indian-Sweets',
      'Desserts',
    ],
    rating: 4.5,
    numberOfReviews: 15100,
    opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 8,
    is_veg: true,
    cost_for_two: 700,
    delivery_time_mins: 30,
  },
  {
    name: 'Dastarkhwan',
    description:
      'A classic Awadhi dining experience, specializing in Mutton Nihari and Kakori Kebabs.',
    address: {
      street: 'Cantonment Road, Lalbagh',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226001',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.002, baseLat + 0.005],
      },
    },
    contact: { phone: '9122010004', email: 'dastarkhwan@example.com' },
    cuisine_type: [
      'North-Indian',
      'BBQ',
      'Dinner',
      'Lunch',
      'Indian',
      'Fast-Food',
    ],
    rating: 4.7,
    numberOfReviews: 11200,
    opening_hours: [{ day: 'Thursday', open: '13:00', close: '23:00' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 950,
    delivery_time_mins: 50,
  },
  {
    name: 'Sardarji Malai Chaap',
    description:
      'Specialty shop for various marinated and grilled soy (Malai) chaap preparations.',
    address: {
      street: 'Gomti Nagar, Near Manoj Pandey Chauraha',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226010',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.02, baseLat + 0.015],
      },
    },
    contact: { phone: '9122010005', email: 'sardarji@example.com' },
    cuisine_type: [
      'BBQ',
      'North-Indian',
      'Fast-Food',
      'Street-Food',
      'Lunch',
      'Vegan',
    ],
    rating: 4.3,
    numberOfReviews: 7800,
    opening_hours: [{ day: 'Friday', open: '15:00', close: '23:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 450,
    delivery_time_mins: 25,
  },
  // --- Lucknow Restaurant 6-10 (Diversity & International) ---
  {
    name: 'The Vintage Kitchen',
    description:
      'Casual fine dining offering a mix of Italian and Continental dishes.',
    address: {
      street: 'Vibhuti Khand, Gomti Nagar',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226010',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.03, baseLat + 0.025],
      },
    },
    contact: { phone: '9122010006', email: 'vintagekitchen@example.com' },
    cuisine_type: ['Italian', 'Pizza', 'Dinner', 'Lunch', 'Soups', 'Healthy'],
    rating: 4.2,
    numberOfReviews: 6100,
    opening_hours: [{ day: 'Saturday', open: '11:00', close: '23:30' }],
    is_active: true,
    min_order_value: 600,
    delivery_radius_km: 8,
    is_veg: true,
    cost_for_two: 1400,
    delivery_time_mins: 40,
  },
  {
    name: 'Momos Magic Point',
    description:
      'Quick-service Chinese and Tibetan outlet specializing in various momos and noodles.',
    address: {
      street: 'Bhootnath Market, Indira Nagar',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226016',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.025, baseLat + 0.04],
      },
    },
    contact: { phone: '9122010007', email: 'momosmagic@example.com' },
    cuisine_type: [
      'Chinese',
      'Fast-Food',
      'Street-Food',
      'Soups',
      'Dinner',
      'Lunch',
    ],
    rating: 4.1,
    numberOfReviews: 7500,
    opening_hours: [{ day: 'Sunday', open: '15:00', close: '22:30' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 400,
    delivery_time_mins: 20,
  },
  {
    name: 'The Healthy Hub',
    description:
      'Restaurant focused on clean eating, offering detox bowls, wraps, and fresh juices.',
    address: {
      street: 'Hazratganj, Near Sahara Ganj Mall',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.008, baseLat + 0.008],
      },
    },
    contact: { phone: '9122010008', email: 'healthyhub@example.com' },
    cuisine_type: [
      'Healthy',
      'Salads',
      'Vegan',
      'Breakfast',
      'Lunch',
      'Beverages',
    ],
    rating: 4.4,
    numberOfReviews: 4500,
    opening_hours: [{ day: 'Monday', open: '09:30', close: '21:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 850,
    delivery_time_mins: 30,
  },
  {
    name: 'Biggies Burger',
    description:
      'Popular chain for customizable, large, messy burgers and quick meals.',
    address: {
      street: 'Aminabad Market',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226018',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.005, baseLat - 0.015],
      },
    },
    contact: { phone: '9122010009', email: 'biggies.aminabad@example.com' },
    cuisine_type: [
      'Burgers',
      'Fast-Food',
      'Dinner',
      'Lunch',
      'BBQ',
      'Sandwiches',
    ],
    rating: 4.1,
    numberOfReviews: 8200,
    opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:45' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 650,
    delivery_time_mins: 35,
  },
  {
    name: 'The Japanese Corner',
    description:
      'Exclusive spot for sushi, ramen, and authentic Japanese appetizers.',
    address: {
      street: 'Gomti Nagar Extension, Near Lulu Mall',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226030',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.04, baseLat + 0.01],
      },
    },
    contact: { phone: '9122010010', email: 'japanesecorner@example.com' },
    cuisine_type: ['Japanese', 'Sushi', 'Dinner', 'Lunch', 'Healthy', 'Soups'],
    rating: 4.5,
    numberOfReviews: 3500,
    opening_hours: [{ day: 'Wednesday', open: '12:30', close: '23:00' }],
    is_active: true,
    min_order_value: 700,
    delivery_radius_km: 10,
    is_veg: false,
    cost_for_two: 1800,
    delivery_time_mins: 55,
  },
  // --- Lucknow Restaurant 11-15 (Quick Bites & Desserts) ---
  {
    name: 'South Indian Aroma',
    description:
      'Popular joint for traditional South Indian cuisine like dosas and uttapams.',
    address: {
      street: 'Aliganj, Near IT College',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226024',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.01, baseLat + 0.035],
      },
    },
    contact: { phone: '9122010011', email: 'siaroma@example.com' },
    cuisine_type: [
      'South-Indian',
      'Breakfast',
      'Indian',
      'Fast-Food',
      'Lunch',
      'Vegan',
    ],
    rating: 4.3,
    numberOfReviews: 9500,
    opening_hours: [{ day: 'Thursday', open: '07:30', close: '22:30' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 500,
    delivery_time_mins: 30,
  },
  {
    name: 'Radhey Lal Premium Paan',
    description:
      'Famous local outlet for authentic paan (betel leaf preparation) and sweet treats.',
    address: {
      street: 'Hazratganj, Janpath Market',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.005, baseLat + 0.0],
      },
    },
    contact: { phone: '9122010012', email: 'radheylal@example.com' },
    cuisine_type: [
      'Indian-Sweets',
      'Desserts',
      'Street-Food',
      'Beverages',
      'Fast-Food',
      'Breakfast',
    ],
    rating: 4.7,
    numberOfReviews: 14000,
    opening_hours: [{ day: 'Friday', open: '10:00', close: '00:30' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 300,
    delivery_time_mins: 20,
  },
  {
    name: 'Pizza Hut',
    description:
      'International pizza chain offering classic and contemporary pizzas.',
    address: {
      street: 'Wave Mall, Gomti Nagar',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226010',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.035, baseLat + 0.03],
      },
    },
    contact: { phone: '9122010013', email: 'pizzahut@example.com' },
    cuisine_type: [
      'Pizza',
      'Italian',
      'Fast-Food',
      'Dinner',
      'Lunch',
      'Burgers',
    ],
    rating: 4.0,
    numberOfReviews: 8900,
    opening_hours: [{ day: 'Saturday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 800,
    delivery_time_mins: 35,
  },
  {
    name: 'Gali Paranthe Wali',
    description:
      'A dedicated outlet for Indian stuffed flatbreads (Parathas) and curries.',
    address: {
      street: 'Chowk, Near Bada Imambada',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.02, baseLat - 0.008],
      },
    },
    contact: { phone: '9122010014', email: 'gali.paranthe@example.com' },
    cuisine_type: [
      'North-Indian',
      'Breakfast',
      'Indian',
      'Lunch',
      'Dinner',
      'Vegan',
    ],
    rating: 4.2,
    numberOfReviews: 5300,
    opening_hours: [{ day: 'Sunday', open: '08:00', close: '22:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 500,
    delivery_time_mins: 30,
  },
  {
    name: 'Sweet Tooth Bakery',
    description:
      'European-style patisserie offering cakes, pastries, and croissants.',
    address: {
      street: 'Hazratganj, Near Residency',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.002, baseLat + 0.006],
      },
    },
    contact: { phone: '9122010015', email: 'sweettooth@example.com' },
    cuisine_type: [
      'Desserts',
      'Beverages',
      'Breakfast',
      'Sandwiches',
      'Healthy',
      'Vegan',
    ],
    rating: 4.6,
    numberOfReviews: 5900,
    opening_hours: [{ day: 'Monday', open: '09:00', close: '21:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 650,
    delivery_time_mins: 25,
  },
  // --- Lucknow Restaurant 16-20 (More Awadhi & Diverse) ---
  {
    name: 'Wahid Biryani',
    description:
      'A contender for the best Biryani, known for its distinct aromatic spices.',
    address: {
      street: 'Aminabad, Near Mohan Market',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226018',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.008, baseLat - 0.012],
      },
    },
    contact: { phone: '9122010016', email: 'wahidbiryani@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'Dinner',
      'Lunch',
      'BBQ',
      'Fast-Food',
    ],
    rating: 4.5,
    numberOfReviews: 10500,
    opening_hours: [{ day: 'Tuesday', open: '13:00', close: '23:00' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 750,
    delivery_time_mins: 40,
  },
  {
    name: 'Mexican Burrito Shop',
    description:
      'Authentic Mexican quick-service with tacos, nachos, and loaded burritos.',
    address: {
      street: 'Gomti Nagar, Patrakarpuram',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226010',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.02, baseLat + 0.03],
      },
    },
    contact: { phone: '9122010017', email: 'mexicanburrito@example.com' },
    cuisine_type: [
      'Mexican',
      'Fast-Food',
      'Lunch',
      'Dinner',
      'Salads',
      'Soups',
    ],
    rating: 4.3,
    numberOfReviews: 3800,
    opening_hours: [{ day: 'Wednesday', open: '11:00', close: '22:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 850,
    delivery_time_mins: 35,
  },
  {
    name: 'Bikanerwala',
    description:
      'Well-known chain for Indian street food, traditional sweets, and North Indian meals.',
    address: {
      street: 'Hazratganj, Near Parivartan Chowk',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.0, baseLat + 0.004],
      },
    },
    contact: { phone: '9122010018', email: 'bikanerwala@example.com' },
    cuisine_type: [
      'Indian-Sweets',
      'Street-Food',
      'North-Indian',
      'Desserts',
      'Indian',
      'Breakfast',
    ],
    rating: 4.4,
    numberOfReviews: 12100,
    opening_hours: [{ day: 'Thursday', open: '09:00', close: '22:30' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 600,
    delivery_time_mins: 30,
  },
  {
    name: 'Green South Dosa',
    description:
      'Vegetarian spot specializing in crispy, thin South Indian dosas and idlis.',
    address: {
      street: 'Indira Nagar, Near Lekhraj Market',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226016',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.03, baseLat + 0.05],
      },
    },
    contact: { phone: '9122010019', email: 'greensouth@example.com' },
    cuisine_type: [
      'South-Indian',
      'Breakfast',
      'Fast-Food',
      'Indian',
      'Lunch',
      'Vegan',
    ],
    rating: 4.1,
    numberOfReviews: 6500,
    opening_hours: [{ day: 'Friday', open: '07:00', close: '22:00' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 400,
    delivery_time_mins: 25,
  },
  {
    name: 'Gomti Chhole Bhature',
    description:
      'Simple, popular vendor serving the best Chhole Bhature in the city.',
    address: {
      street: 'Gomti Nagar, Near Dr. Ram Manohar Lohia Hospital',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226010',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.015, baseLat + 0.02],
      },
    },
    contact: { phone: '9122010020', email: 'gomti.chhole@example.com' },
    cuisine_type: [
      'North-Indian',
      'Street-Food',
      'Breakfast',
      'Fast-Food',
      'Lunch',
      'Vegan',
    ],
    rating: 4.5,
    numberOfReviews: 9200,
    opening_hours: [{ day: 'Saturday', open: '09:00', close: '16:00' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 250,
    delivery_time_mins: 15,
  },
  // --- Lucknow Restaurant 21-25 (Global & Specific Cuisines) ---
  {
    name: 'Mandarin Delight',
    description:
      'High-quality Chinese and Thai restaurant with fine-dining ambiance.',
    address: {
      street: 'Hazratganj, Near Halwasiya Market',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.003, baseLat + 0.005],
      },
    },
    contact: { phone: '9122010021', email: 'mandarin@example.com' },
    cuisine_type: [
      'Chinese',
      'Soups',
      'Dinner',
      'Lunch',
      'Japanese',
      'Healthy',
    ],
    rating: 4.3,
    numberOfReviews: 5000,
    opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 600,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 1300,
    delivery_time_mins: 45,
  },
  {
    name: 'The French Loaf',
    description:
      'Bakery chain providing European breads, sandwiches, and coffee.',
    address: {
      street: 'Gomti Nagar, Near Cinepolis',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226010',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.028, baseLat + 0.018],
      },
    },
    contact: { phone: '9122010022', email: 'frenchloaf@example.com' },
    cuisine_type: [
      'Sandwiches',
      'Desserts',
      'Beverages',
      'Breakfast',
      'Healthy',
      'Vegan',
    ],
    rating: 4.4,
    numberOfReviews: 4800,
    opening_hours: [{ day: 'Monday', open: '08:00', close: '22:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 700,
    delivery_time_mins: 30,
  },
  {
    name: 'Kulfi King',
    description:
      'Specializes in traditional Indian frozen desserts (Kulfi) and Rabri.',
    address: {
      street: 'Aminabad, Near Press Club',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226018',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.009, baseLat - 0.018],
      },
    },
    contact: { phone: '9122010023', email: 'kulfiking@example.com' },
    cuisine_type: [
      'Indian-Sweets',
      'Desserts',
      'Street-Food',
      'Fast-Food',
      'Beverages',
      'Indian',
    ],
    rating: 4.6,
    numberOfReviews: 10500,
    opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:30' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 350,
    delivery_time_mins: 20,
  },
  {
    name: 'Cafe Coffee Day',
    description: 'Popular cafe chain for coffee, pastries, and light snacks.',
    address: {
      street: 'Hazratganj, Near Parivartan Chowk',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.006, baseLat + 0.009],
      },
    },
    contact: { phone: '9122010024', email: 'ccd@example.com' },
    cuisine_type: [
      'Beverages',
      'Desserts',
      'Sandwiches',
      'Breakfast',
      'Fast-Food',
      'Healthy',
    ],
    rating: 4.0,
    numberOfReviews: 6200,
    opening_hours: [{ day: 'Wednesday', open: '09:00', close: '23:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 500,
    delivery_time_mins: 25,
  },
  {
    name: 'Noodle House',
    description:
      'Casual eatery specializing in customizable Asian noodle bowls and broths.',
    address: {
      street: 'Indira Nagar, Near Munshi Pulia',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226016',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.038, baseLat + 0.045],
      },
    },
    contact: { phone: '9122010025', email: 'noodlehouse@example.com' },
    cuisine_type: [
      'Chinese',
      'Soups',
      'Dinner',
      'Lunch',
      'Japanese',
      'Healthy',
    ],
    rating: 4.2,
    numberOfReviews: 4100,
    opening_hours: [{ day: 'Thursday', open: '12:30', close: '22:00' }],
    is_active: true,
    min_order_value: 350,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 900,
    delivery_time_mins: 35,
  },
  // --- Lucknow Restaurant 26-30 (Specialty & Fusion) ---
  {
    name: 'The Mexican Salsa Bar',
    description:
      'Dedicated outlet for fresh salads, dips, and quick customizable Mexican bowls.',
    address: {
      street: 'Gomti Nagar, Near Fun Republic Mall',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226010',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.03, baseLat + 0.005],
      },
    },
    contact: { phone: '9122010026', email: 'salsabar@example.com' },
    cuisine_type: [
      'Mexican',
      'Salads',
      'Healthy',
      'Vegan',
      'Fast-Food',
      'Lunch',
    ],
    rating: 4.4,
    numberOfReviews: 3200,
    opening_hours: [{ day: 'Friday', open: '10:30', close: '21:30' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 8,
    is_veg: true,
    cost_for_two: 750,
    delivery_time_mins: 30,
  },
  {
    name: 'Khana Khazana',
    description:
      'Affordable North Indian restaurant popular for its combo meals and curries.',
    address: {
      street: 'Alambagh Market',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226005',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.018, baseLat - 0.03],
      },
    },
    contact: { phone: '9122010027', email: 'khanakhazana@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'Lunch',
      'Dinner',
      'Fast-Food',
      'Vegan',
    ],
    rating: 4.0,
    numberOfReviews: 7100,
    opening_hours: [{ day: 'Saturday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 9,
    is_veg: true,
    cost_for_two: 550,
    delivery_time_mins: 40,
  },
  {
    name: 'Oudhi Cuisine',
    description:
      'Premium Awadhi fine dining with emphasis on traditional royal recipes.',
    address: {
      street: 'Hazratganj, Near Capitol Cinema',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.008, baseLat + 0.001],
      },
    },
    contact: { phone: '9122010028', email: 'oudhi@example.com' },
    cuisine_type: [
      'BBQ',
      'North-Indian',
      'Dinner',
      'Indian',
      'Lunch',
      'Indian-Sweets',
    ],
    rating: 4.6,
    numberOfReviews: 4500,
    opening_hours: [{ day: 'Sunday', open: '12:30', close: '23:30' }],
    is_active: true,
    min_order_value: 800,
    delivery_radius_km: 10,
    is_veg: false,
    cost_for_two: 1800,
    delivery_time_mins: 55,
  },
  {
    name: 'The Pizza Box',
    description:
      'Local pizzeria offering unique toppings and cheesy garlic bread.',
    address: {
      street: 'Faizabad Road, Near Polytechnic',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.025, baseLat + 0.055],
      },
    },
    contact: { phone: '9122010029', email: 'pizzabox@example.com' },
    cuisine_type: [
      'Pizza',
      'Italian',
      'Fast-Food',
      'Dinner',
      'Lunch',
      'Burgers',
    ],
    rating: 4.1,
    numberOfReviews: 5300,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '23:45' }],
    is_active: true,
    min_order_value: 350,
    delivery_radius_km: 8,
    is_veg: true,
    cost_for_two: 700,
    delivery_time_mins: 30,
  },
  {
    name: 'Babu Lal Chaat',
    description:
      'Famous street stall for Tikkis, Papdi Chaat, and spicy street snacks.',
    address: {
      street: 'Chowk, Near Rumi Gate',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.025, baseLat - 0.005],
      },
    },
    contact: { phone: '9122010030', email: 'babulalchaat@example.com' },
    cuisine_type: [
      'Street-Food',
      'Indian',
      'Fast-Food',
      'Vegan',
      'North-Indian',
      'Indian-Sweets',
    ],
    rating: 4.7,
    numberOfReviews: 19500,
    opening_hours: [{ day: 'Tuesday', open: '16:00', close: '22:00' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 200,
    delivery_time_mins: 15,
  },
  // --- Lucknow Restaurant 31-35 (Buffer for Category Saturation) ---
  {
    name: 'The Waffle Factory',
    description:
      'Dessert parlor specializing in sweet and savory waffles, crepes, and shakes.',
    address: {
      street: 'Hazratganj, Near Mayfair Cinema',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.001, baseLat + 0.007],
      },
    },
    contact: { phone: '9122010031', email: 'wafflefactory@example.com' },
    cuisine_type: [
      'Desserts',
      'Beverages',
      'Breakfast',
      'Fast-Food',
      'Sandwiches',
      'Healthy',
    ],
    rating: 4.4,
    numberOfReviews: 4900,
    opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 600,
    delivery_time_mins: 25,
  },
  {
    name: 'Indian Tadka Pure Veg',
    description:
      'Family restaurant serving a vast menu of vegetarian Indian food.',
    address: {
      street: 'Gomti Nagar, Near Ambedkar Memorial',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226010',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.018, baseLat + 0.008],
      },
    },
    contact: { phone: '9122010032', email: 'indiantadka@example.com' },
    cuisine_type: [
      'Indian',
      'North-Indian',
      'South-Indian',
      'Lunch',
      'Dinner',
      'Vegan',
    ],
    rating: 4.2,
    numberOfReviews: 8100,
    opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 350,
    delivery_radius_km: 8,
    is_veg: true,
    cost_for_two: 800,
    delivery_time_mins: 40,
  },
  {
    name: 'The Burger Cafe',
    description: 'Simple, popular burger and fries joint with fast service.',
    address: {
      street: 'Chowk, Near King George Medical University',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.012, baseLat - 0.002],
      },
    },
    contact: { phone: '9122010033', email: 'burgercafe@example.com' },
    cuisine_type: [
      'Burgers',
      'Fast-Food',
      'Lunch',
      'Dinner',
      'Sandwiches',
      'BBQ',
    ],
    rating: 4.0,
    numberOfReviews: 5500,
    opening_hours: [{ day: 'Friday', open: '11:30', close: '23:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 450,
    delivery_time_mins: 25,
  },
  {
    name: 'Mughlai Darbar',
    description:
      'A grand restaurant specializing in Mughlai curries, bread, and desserts.',
    address: {
      street: 'Alambagh, Near Singar Nagar',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226005',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.025, baseLat - 0.035],
      },
    },
    contact: { phone: '9122010034', email: 'mughlaidarbar@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'Dinner',
      'Lunch',
      'BBQ',
      'Indian-Sweets',
    ],
    rating: 4.5,
    numberOfReviews: 6500,
    opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 10,
    is_veg: false,
    cost_for_two: 1200,
    delivery_time_mins: 50,
  },
  {
    name: 'The Oriental Box',
    description:
      'Customizable bowls with Chinese, Japanese, and healthy Asian options.',
    address: {
      street: 'Gomti Nagar, Near Indira Gandhi Pratishthan',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      zip_code: '226010',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.045, baseLat + 0.015],
      },
    },
    contact: { phone: '9122010035', email: 'orientalbox@example.com' },
    cuisine_type: [
      'Chinese',
      'Japanese',
      'Healthy',
      'Lunch',
      'Dinner',
      'Soups',
    ],
    rating: 4.3,
    numberOfReviews: 3900,
    opening_hours: [{ day: 'Sunday', open: '12:00', close: '22:30' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 1000,
    delivery_time_mins: 40,
  },
];

export default lucknowRestaurants;
