// Base coordinates for Mumbai (approximate center)
const baseLat = 18.9582;
const baseLon = 72.8321;

const mumbaiRestaurants = [
  // --- Restaurants 1-10 ---
  {
    name: 'Leopold Cafe',
    description:
      'An iconic and bustling cafe in Colaba, serving a wide range of multi-cuisine dishes and beverages.',
    address: {
      street: 'Colaba Causeway',
      city: 'Mumbai',
      state: 'Maharashtra',
      zip_code: '400001',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.04, baseLat - 0.06],
      },
    },
    contact: { phone: '9876550001', email: 'leopoldcafe.mum@example.com' },
    cuisine_type: [
      'Indian',
      'Chinese',
      'Beverages',
      'Dinner',
      'Lunch',
      'Fast-Food',
    ],
    rating: 4.5,
    numberOfReviews: 7500,
    opening_hours: [{ day: 'Monday', open: '08:00', close: '00:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 1600,
    delivery_time_mins: 45,
  },
  {
    name: 'Pizza By The Bay',
    description:
      'Enjoy delicious pizzas with a stunning view of the Marine Drive.',
    address: {
      street: 'Marine Drive, Churchgate',
      city: 'Mumbai',
      state: 'Maharashtra',
      zip_code: '400020',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.05, baseLat - 0.05],
      },
    },
    contact: { phone: '9876550002', email: 'pizzabythebay@example.com' },
    cuisine_type: ['Pizza', 'Italian', 'Salads', 'Beverages', 'Dinner'],
    rating: 4.6,
    numberOfReviews: 3200,
    opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:30' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 2000,
    delivery_time_mins: 50,
  },
  {
    name: 'The Burger Pit',
    description:
      'A trendy spot in Bandra for gourmet burgers, loaded fries, and thick shakes.',
    address: {
      street: 'Linking Road, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      zip_code: '400050',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.03, baseLat + 0.01],
      },
    },
    contact: { phone: '9876550003', email: 'burgerpit.mum@example.com' },
    cuisine_type: [
      'Burgers',
      'Fast-Food',
      'Beverages',
      'Sandwiches',
      'Desserts',
    ],
    rating: 4.4,
    numberOfReviews: 1800,
    opening_hours: [{ day: 'Wednesday', open: '11:00', close: '01:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 800,
    delivery_time_mins: 35,
  },
  {
    name: 'Bademiya Kebab',
    description:
      'A legendary late-night eatery famous for its succulent kebabs and rolls.',
    address: {
      street: 'Tulloch Road, Apollo Bunder, Colaba',
      city: 'Mumbai',
      state: 'Maharashtra',
      zip_code: '400039',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.045, baseLat - 0.065],
      },
    },
    contact: { phone: '9876550004', email: 'bademiya@example.com' },
    cuisine_type: ['BBQ', 'North-Indian', 'Street-Food', 'Dinner', 'Indian'],
    rating: 4.7,
    numberOfReviews: 9800,
    opening_hours: [{ day: 'Thursday', open: '18:00', close: '03:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 900,
    delivery_time_mins: 40,
  },
  {
    name: 'Madras Cafe',
    description:
      'An iconic, no-frills restaurant serving authentic South Indian comfort food.',
    address: {
      street: "King's Circle, Matunga East",
      city: 'Mumbai',
      state: 'Maharashtra',
      zip_code: '400019',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.01, baseLat - 0.01],
      },
    },
    contact: { phone: '9876550005', email: 'madrascafe@example.com' },
    cuisine_type: ['South-Indian', 'Breakfast', 'Indian', 'Beverages', 'Lunch'],
    rating: 4.8,
    numberOfReviews: 6500,
    opening_hours: [{ day: 'Friday', open: '07:00', close: '22:30' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 400,
    delivery_time_mins: 30,
  },
  {
    name: 'The Yoga House',
    description:
      'A tranquil cafe offering healthy, organic, and delicious vegetarian meals.',
    address: {
      street: 'Chimbai Road, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      zip_code: '400050',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.035, baseLat + 0.015],
      },
    },
    contact: { phone: '9876550006', email: 'yogahouse@example.com' },
    cuisine_type: [
      'Healthy',
      'Vegan',
      'Salads',
      'Soups',
      'Breakfast',
      'Beverages',
    ],
    rating: 4.7,
    numberOfReviews: 1200,
    opening_hours: [{ day: 'Saturday', open: '08:00', close: '22:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 1200,
    delivery_time_mins: 40,
  },
  {
    name: 'Wasabi by Morimoto',
    description:
      'An award-winning fine-dining restaurant for authentic Japanese cuisine.',
    address: {
      street: 'The Taj Mahal Palace, Apollo Bunder',
      city: 'Mumbai',
      state: 'Maharashtra',
      zip_code: '400001',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.042, baseLat - 0.062],
      },
    },
    contact: { phone: '9876550007', email: 'wasabi.taj@example.com' },
    cuisine_type: ['Japanese', 'Sushi', 'Dinner', 'Soups', 'Healthy'],
    rating: 4.9,
    numberOfReviews: 2500,
    opening_hours: [{ day: 'Sunday', open: '19:00', close: '23:45' }],
    is_active: true,
    min_order_value: 2000,
    delivery_radius_km: 10,
    is_veg: false,
    cost_for_two: 8000,
    delivery_time_mins: 60,
  },
  {
    name: 'Elco Pani Puri Centre',
    description:
      'A famous spot for hygienic and delicious Mumbai street food, especially Pani Puri.',
    address: {
      street: 'Hill Road, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      zip_code: '400050',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.032, baseLat + 0.012],
      },
    },
    contact: { phone: '9876550008', email: 'elco@example.com' },
    cuisine_type: [
      'Street-Food',
      'Indian',
      'Fast-Food',
      'Beverages',
      'Desserts',
    ],
    rating: 4.6,
    numberOfReviews: 8200,
    opening_hours: [{ day: 'Monday', open: '10:00', close: '23:30' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 500,
    delivery_time_mins: 25,
  },
  {
    name: 'Britannia & Co. Restaurant',
    description:
      'A legendary Parsi cafe known for its Berry Pulao and Sali Boti.',
    address: {
      street: 'Ballard Estate, Fort',
      city: 'Mumbai',
      state: 'Maharashtra',
      zip_code: '400001',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.02, baseLat - 0.04],
      },
    },
    contact: { phone: '9876550009', email: 'britannia@example.com' },
    cuisine_type: ['Indian', 'Dinner', 'Lunch', 'Desserts', 'Beverages'],
    rating: 4.5,
    numberOfReviews: 4500,
    opening_hours: [{ day: 'Tuesday', open: '12:00', close: '16:00' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 1000,
    delivery_time_mins: 40,
  },
  {
    name: 'Gajalee',
    description:
      'Renowned for its authentic and delicious coastal and seafood specialties.',
    address: {
      street: 'Vile Parle East',
      city: 'Mumbai',
      state: 'Maharashtra',
      zip_code: '400057',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.01, baseLat + 0.04],
      },
    },
    contact: { phone: '9876550010', email: 'gajalee@example.com' },
    cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ', 'Soups'],
    rating: 4.7,
    numberOfReviews: 5500,
    opening_hours: [{ day: 'Wednesday', open: '11:30', close: '23:30' }],
    is_active: true,
    min_order_value: 600,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 1800,
    delivery_time_mins: 50,
  },
];

export default mumbaiRestaurants;
