// Base coordinates for Mumbai (approximate center)
const baseLat = 18.9582;
const baseLon = 72.8321;

const mumbaiRestaurants = [
  // --- Restaurants 1-10 ---
  // {
  //   name: 'Leopold Cafe',
  //   description:
  //     'An iconic and bustling cafe in Colaba, serving a wide range of multi-cuisine dishes and beverages.',
  //   address: {
  //     street: 'Colaba Causeway',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat - 0.06],
  //     },
  //   },
  //   contact: { phone: '9876550001', email: 'leopoldcafe.mum@example.com' },
  //   cuisine_type: [
  //     'Indian',
  //     'Chinese',
  //     'Beverages',
  //     'Dinner',
  //     'Lunch',
  //     'Fast-Food',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 7500,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Pizza By The Bay',
  //   description:
  //     'Enjoy delicious pizzas with a stunning view of the Marine Drive.',
  //   address: {
  //     street: 'Marine Drive, Churchgate',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400020',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat - 0.05],
  //     },
  //   },
  //   contact: { phone: '9876550002', email: 'pizzabythebay@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Salads', 'Beverages', 'Dinner'],
  //   rating: 4.6,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'The Burger Pit',
  //   description:
  //     'A trendy spot in Bandra for gourmet burgers, loaded fries, and thick shakes.',
  //   address: {
  //     street: 'Linking Road, Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9876550003', email: 'burgerpit.mum@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Beverages',
  //     'Sandwiches',
  //     'Desserts',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Bademiya Kebab',
  //   description:
  //     'A legendary late-night eatery famous for its succulent kebabs and rolls.',
  //   address: {
  //     street: 'Tulloch Road, Apollo Bunder, Colaba',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400039',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.045, baseLat - 0.065],
  //     },
  //   },
  //   contact: { phone: '9876550004', email: 'bademiya@example.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Street-Food', 'Dinner', 'Indian'],
  //   rating: 4.7,
  //   numberOfReviews: 9800,
  //   opening_hours: [{ day: 'Thursday', open: '18:00', close: '03:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Madras Cafe',
  //   description:
  //     'An iconic, no-frills restaurant serving authentic South Indian comfort food.',
  //   address: {
  //     street: "King's Circle, Matunga East",
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400019',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9876550005', email: 'madrascafe@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Indian', 'Beverages', 'Lunch'],
  //   rating: 4.8,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Friday', open: '07:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Yoga House',
  //   description:
  //     'A tranquil cafe offering healthy, organic, and delicious vegetarian meals.',
  //   address: {
  //     street: 'Chimbai Road, Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.035, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9876550006', email: 'yogahouse@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Vegan',
  //     'Salads',
  //     'Soups',
  //     'Breakfast',
  //     'Beverages',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Wasabi by Morimoto',
  //   description:
  //     'An award-winning fine-dining restaurant for authentic Japanese cuisine.',
  //   address: {
  //     street: 'The Taj Mahal Palace, Apollo Bunder',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.042, baseLat - 0.062],
  //     },
  //   },
  //   contact: { phone: '9876550007', email: 'wasabi.taj@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Dinner', 'Soups', 'Healthy'],
  //   rating: 4.9,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Sunday', open: '19:00', close: '23:45' }],
  //   is_active: true,
  //   min_order_value: 2000,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 8000,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Elco Pani Puri Centre',
  //   description:
  //     'A famous spot for hygienic and delicious Mumbai street food, especially Pani Puri.',
  //   address: {
  //     street: 'Hill Road, Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.032, baseLat + 0.012],
  //     },
  //   },
  //   contact: { phone: '9876550008', email: 'elco@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Indian',
  //     'Fast-Food',
  //     'Beverages',
  //     'Desserts',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 8200,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Britannia & Co. Restaurant',
  //   description:
  //     'A legendary Parsi cafe known for its Berry Pulao and Sali Boti.',
  //   address: {
  //     street: 'Ballard Estate, Fort',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9876550009', email: 'britannia@example.com' },
  //   cuisine_type: ['Indian', 'Dinner', 'Lunch', 'Desserts', 'Beverages'],
  //   rating: 4.5,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '16:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Gajalee',
  //   description:
  //     'Renowned for its authentic and delicious coastal and seafood specialties.',
  //   address: {
  //     street: 'Vile Parle East',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400057',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat + 0.04],
  //     },
  //   },
  //   contact: { phone: '9876550010', email: 'gajalee@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ', 'Soups'],
  //   rating: 4.7,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Wednesday', open: '11:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // --- Restaurants 11-20 ---
  //  seeded till here
  // {
  //   name: 'The Bombay Canteen',
  //   description:
  //     'A celebrated restaurant offering a modern take on classic Indian dishes.',
  //   address: {
  //     street: 'Kamala Mills, Lower Parel',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400013',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9876550011', email: 'bombaycanteen@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Lunch', 'Beverages'],
  //   rating: 4.8,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Trishna',
  //   description:
  //     'A legendary seafood restaurant famous for its butter garlic crab.',
  //   address: {
  //     street: 'Kala Ghoda, Fort',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.038, baseLat - 0.058],
  //     },
  //   },
  //   contact: { phone: '9876550012', email: 'trishna.mum@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ'],
  //   rating: 4.7,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:45' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 3000,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Kyani & Co.',
  //   description: 'One of Mumbai’s oldest Irani cafes, known for its bun maska and chai.',
  //   address: {
  //     street: 'Marine Lines',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.048, baseLat - 0.048],
  //     },
  //   },
  //   contact: { phone: '9876550013', email: 'kyani@example.com' },
  //   cuisine_type: ['Breakfast', 'Beverages', 'Desserts', 'Fast-Food'],
  //   rating: 4.5,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Saturday', open: '07:00', close: '20:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 250,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Joey’s Pizza',
  //   description: 'A local favorite in Malad, famous for its loaded, cheesy pizzas.',
  //   address: {
  //     street: 'Malad West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400064',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.08, baseLat + 0.08],
  //     },
  //   },
  //   contact: { phone: '9876550014', email: 'joeyspizza@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Beverages'],
  //   rating: 4.8,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Candies',
  //   description: 'A charming, multi-level cafe in Bandra with a vast menu and lovely ambiance.',
  //   address: {
  //     street: 'Pali Hill, Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.033, baseLat + 0.013],
  //     },
  //   },
  //   contact: { phone: '9876550015', email: 'candies.bandra@example.com' },
  //   cuisine_type: ['Desserts', 'Sandwiches', 'Salads', 'Beverages', 'Breakfast'],
  //   rating: 4.6,
  //   numberOfReviews: 8800,
  //   opening_hours: [{ day: 'Monday', open: '08:30', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Bastian',
  //   description: 'A high-end restaurant known for its seafood and decadent cheesecakes.',
  //   address: {
  //     street: 'Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.028, baseLat + 0.018],
  //     },
  //   },
  //   contact: { phone: '9876550016', email: 'bastian@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Desserts', 'Dinner', 'Beverages'],
  //   rating: 4.7,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 1500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 4500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Anand Stall',
  //   description: 'A famous street food stall opposite Mithibai College, known for its dosas and sandwiches.',
  //   address: {
  //     street: 'Vile Parle West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400056',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.05],
  //     },
  //   },
  //   contact: { phone: '9876550017', email: 'anandstall@example.com' },
  //   cuisine_type: ['Street-Food', 'South-Indian', 'Sandwiches', 'Fast-Food'],
  //   rating: 4.8,
  //   numberOfReviews: 7200,
  //   opening_hours: [{ day: 'Wednesday', open: '09:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'K. Rustom & Co. Ice Cream',
  //   description: 'A legendary ice cream parlour famous for its ice cream sandwiches.',
  //   address: {
  //     street: 'Churchgate',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400020',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.052, baseLat - 0.052],
  //     },
  //   },
  //   contact: { phone: '9876550018', email: 'krustom@example.com' },
  //   cuisine_type: ['Desserts', 'Indian-Sweets', 'Beverages'],
  //   rating: 4.9,
  //   numberOfReviews: 6800,
  //   opening_hours: [{ day: 'Thursday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 150,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Burma Burma',
  //   description: 'An authentic Burmese vegetarian restaurant offering unique flavors and dishes.',
  //   address: {
  //     street: 'Kala Ghoda, Fort',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.041, baseLat - 0.059],
  //     },
  //   },
  //   contact: { phone: '9876550019', email: 'burmaburma.mum@example.com' },
  //   cuisine_type: ['Healthy', 'Vegan', 'Soups', 'Salads', 'Dinner', 'Lunch'],
  //   rating: 4.8,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Yauatcha',
  //   description: 'A high-end London-based dim sum teahouse with a modern touch.',
  //   address: {
  //     street: 'BKC, Bandra East',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400051',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9876550020', email: 'yauatcha.mum@example.com' },
  //   cuisine_type: ['Chinese', 'Desserts', 'Dinner', 'Soups', 'Beverages'],
  //   rating: 4.6,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 1200,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 3500,
  //   delivery_time_mins: 55,
  // },
  // --- Restaurants 21-30 ---
  // {
  //   name: 'Pali Bhavan',
  //   description: 'An elegantly decorated restaurant serving authentic North Indian cuisine.',
  //   address: {
  //     street: 'Pali Hill, Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.031, baseLat + 0.011],
  //     },
  //   },
  //   contact: { phone: '9876550021', email: 'palibhavan@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'Beverages'],
  //   rating: 4.5,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Sunday', open: '12:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 2200,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'O Pedro',
  //   description: 'A vibrant restaurant celebrating Goan cuisine with a modern twist.',
  //   address: {
  //     street: 'BKC, Bandra East',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400051',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.022, baseLat + 0.022],
  //     },
  //   },
  //   contact: { phone: '9876550022', email: 'opedro@example.com' },
  //   cuisine_type: ['Indian', 'South-Indian', 'Dinner', 'Lunch', 'Beverages'],
  //   rating: 4.7,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 48,
  // },
  // {
  //   name: 'The Table',
  //   description: 'A fine-dining restaurant in Colaba offering a global, farm-to-table menu.',
  //   address: {
  //     street: 'Colaba',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.043, baseLat - 0.063],
  //     },
  //   },
  //   contact: { phone: '9876550023', email: 'thetable@example.com' },
  //   cuisine_type: ['Italian', 'Salads', 'Dinner', 'Healthy', 'Soups'],
  //   rating: 4.6,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 1000,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 5000,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Hakkasan',
  //   description: 'A Michelin-starred restaurant offering world-class modern Cantonese cuisine.',
  //   address: {
  //     street: 'Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.029, baseLat + 0.019],
  //     },
  //   },
  //   contact: { phone: '9876550024', email: 'hakkasan.mum@example.com' },
  //   cuisine_type: ['Chinese', 'Dinner', 'Soups', 'Desserts', 'Beverages'],
  //   rating: 4.8,
  //   numberOfReviews: 3300,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 2000,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 6000,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Amar Juice Centre',
  //   description: 'A famous late-night spot for fresh juices, milkshakes, and pav bhaji.',
  //   address: {
  //     street: 'Vile Parle West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400056',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.012, baseLat + 0.052],
  //     },
  //   },
  //   contact: { phone: '9876550025', email: 'amarjuice@example.com' },
  //   cuisine_type: ['Beverages', 'Street-Food', 'Fast-Food', 'Desserts'],
  //   rating: 4.4,
  //   numberOfReviews: 6200,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '02:00' }],
  //   is_active: true,
  //   min_order_value: 120,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Bade Bhai’s Veg Grill',
  //   description: 'A vegetarian-only spot for delicious grilled sandwiches and snacks.',
  //   address: {
  //     street: 'Matunga',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400019',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.012, baseLat - 0.012],
  //     },
  //   },
  //   contact: { phone: '9876550026', email: 'badebhais@example.com' },
  //   cuisine_type: ['Sandwiches', 'Fast-Food', 'Street-Food', 'Beverages'],
  //   rating: 4.5,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 22,
  // },
  // {
  //   name: 'The Pantry',
  //   description: 'A charming cafe in Kala Ghoda with a focus on healthy, organic food.',
  //   address: {
  //     street: 'Kala Ghoda, Fort',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat - 0.057],
  //     },
  //   },
  //   contact: { phone: '9876550027', email: 'thepantry@example.com' },
  //   cuisine_type: ['Healthy', 'Salads', 'Breakfast', 'Beverages', 'Soups'],
  //   rating: 4.4,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Saturday', open: '08:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Global Fusion',
  //   description: 'A massive buffet restaurant offering a wide array of global cuisines.',
  //   address: {
  //     street: 'Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9876550028', email: 'globalfusion@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Sushi', 'North-Indian', 'Desserts'],
  //   rating: 4.3,
  //   numberOfReviews: 5800,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 1000,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Kofuku',
  //   description: 'An authentic Japanese restaurant with a traditional Izakaya-style setting.',
  //   address: {
  //     street: 'Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.027, baseLat + 0.017],
  //     },
  //   },
  //   contact: { phone: '9876550029', email: 'kofuku@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Soups', 'Dinner', 'Healthy'],
  //   rating: 4.6,
  //   numberOfReviews: 2600,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 2800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Bachelorss',
  //   description: 'A legendary late-night spot near Marine Drive for juices, shakes, and ice creams.',
  //   address: {
  //     street: 'Chowpatty',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400007',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.055, baseLat - 0.045],
  //     },
  //   },
  //   contact: { phone: '9876550030', email: 'bachelorss@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Indian-Sweets', 'Fast-Food'],
  //   rating: 4.5,
  //   numberOfReviews: 7100,
  //   opening_hours: [{ day: 'Tuesday', open: '11:00', close: '02:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 25,
  // },
  // seeded till here :
  // --- Restaurants 31-40 ---
  // {
  //   name: 'Mahesh Lunch Home',
  //   description: 'A premier destination for authentic Mangalorean seafood.',
  //   address: {
  //     street: 'Fort',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat - 0.05],
  //     },
  //   },
  //   contact: { phone: '9876550031', email: 'maheshlunchhome@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ'],
  //   rating: 4.6,
  //   numberOfReviews: 6200,
  //   opening_hours: [{ day: 'Wednesday', open: '11:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Cafe Mondegar',
  //   description: 'An iconic cafe in Colaba with retro vibes, a jukebox, and multi-cuisine food.',
  //   address: {
  //     street: 'Colaba Causeway',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.041, baseLat - 0.061],
  //     },
  //   },
  //   contact: { phone: '9876550032', email: 'mondy@example.com' },
  //   cuisine_type: ['Indian', 'Chinese', 'Fast-Food', 'Beverages', 'Breakfast'],
  //   rating: 4.4,
  //   numberOfReviews: 5900,
  //   opening_hours: [{ day: 'Thursday', open: '08:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Peshawri - ITC Maratha',
  //   description: 'A fine-dining restaurant offering the robust flavors of the North-West Frontier.',
  //   address: {
  //     street: 'Sahar, Andheri East',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400099',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat + 0.06],
  //     },
  //   },
  //   contact: { phone: '9876550033', email: 'peshawri.itc@example.com' },
  //   cuisine_type: ['North-Indian', 'BBQ', 'Dinner', 'Indian', 'Lunch'],
  //   rating: 4.8,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Friday', open: '12:30', close: '23:45' }],
  //   is_active: true,
  //   min_order_value: 1500,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 5000,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Sardar Pav Bhaji',
  //   description: 'A legendary eatery famous for its buttery and flavorful pav bhaji.',
  //   address: {
  //     street: 'Tardeo',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400034',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9876550034', email: 'sardarpavbhaji@example.com' },
  //   cuisine_type: ['Street-Food', 'Fast-Food', 'Indian', 'Dinner'],
  //   rating: 4.7,
  //   numberOfReviews: 11000,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '02:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'The Nutcracker',
  //   description: 'A cozy cafe serving all-day breakfast, comfort food, and delicious desserts.',
  //   address: {
  //     street: 'Kala Ghoda, Fort',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.039, baseLat - 0.059],
  //     },
  //   },
  //   contact: { phone: '9876550035', email: 'nutcracker@example.com' },
  //   cuisine_type: ['Breakfast', 'Desserts', 'Salads', 'Beverages', 'Healthy'],
  //   rating: 4.6,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Sunday', open: '09:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Jaffer Bhai’s Delhi Darbar',
  //   description: 'A well-known restaurant for authentic Mughlai cuisine and biryanis.',
  //   address: {
  //     street: 'Grant Road',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400008',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat - 0.04],
  //     },
  //   },
  //   contact: { phone: '9876550036', email: 'delhidarbar@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch', 'BBQ'],
  //   rating: 4.4,
  //   numberOfReviews: 5200,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Haji Ali Juice Centre',
  //   description: 'An iconic juice and snack bar near the Haji Ali Dargah.',
  //   address: {
  //     street: 'Haji Ali',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400026',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9876550037', email: 'hajialijuice@example.com' },
  //   cuisine_type: ['Beverages', 'Desserts', 'Fast-Food', 'Street-Food'],
  //   rating: 4.3,
  //   numberOfReviews: 6900,
  //   opening_hours: [{ day: 'Tuesday', open: '10:00', close: '01:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Bayroute',
  //   description: 'A fine-dining restaurant offering an authentic Middle Eastern and Mediterranean experience.',
  //   address: {
  //     street: 'Juhu',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400049',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.06],
  //     },
  //   },
  //   contact: { phone: '9876550038', email: 'bayroute@example.com' },
  //   cuisine_type: ['Dinner', 'Healthy', 'Salads', 'BBQ', 'Desserts'],
  //   rating: 4.8,
  //   numberOfReviews: 3900,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 1000,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 3500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Prithvi Cafe',
  //   description: 'A vibrant, open-air cafe attached to the famous Prithvi Theatre.',
  //   address: {
  //     street: 'Juhu',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400049',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.022, baseLat + 0.062],
  //     },
  //   },
  //   contact: { phone: '9876550039', email: 'prithvicafe@example.com' },
  //   cuisine_type: ['Fast-Food', 'Beverages', 'Desserts', 'Street-Food', 'Indian'],
  //   rating: 4.6,
  //   numberOfReviews: 7500,
  //   opening_hours: [{ day: 'Thursday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Fatty Bao',
  //   description: 'A vibrant and quirky Asian gastropub known for its baos, ramen, and sushi.',
  //   address: {
  //     street: 'Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.026, baseLat + 0.016],
  //     },
  //   },
  //   contact: { phone: '9876550040', email: 'fattybao.mum@example.com' },
  //   cuisine_type: ['Japanese', 'Chinese', 'Sushi', 'Soups', 'Dinner'],
  //   rating: 4.5,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 50,
  // },
  // seeded till here
  // // --- Restaurants 41-50 ---
  // {
  //   name: 'Social',
  //   description: 'A popular chain of spaces that blend work and play, with a quirky food and drinks menu.',
  //   address: {
  //     street: 'Colaba',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.044, baseLat - 0.064],
  //     },
  //   },
  //   contact: { phone: '9876550041', email: 'social.colaba@example.com' },
  //   cuisine_type: ['Fast-Food', 'Burgers', 'Indian', 'Beverages', 'Breakfast'],
  //   rating: 4.3,
  //   numberOfReviews: 8500,
  //   opening_hours: [{ day: 'Saturday', open: '09:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Gaylord',
  //   description: 'A classic restaurant in Churchgate serving North Indian and Continental food for decades.',
  //   address: {
  //     street: 'Churchgate',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400020',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.051, baseLat - 0.051],
  //     },
  //   },
  //   contact: { phone: '9876550042', email: 'gaylord@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Desserts', 'Dinner', 'Lunch'],
  //   rating: 4.4,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Pancham Puriwala',
  //   description: 'A century-old eatery near CST, famous for its puris and vegetable thalis.',
  //   address: {
  //     street: 'Fort',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat - 0.045],
  //     },
  //   },
  //   contact: { phone: '9876550043', email: 'panchampuri@example.com' },
  //   cuisine_type: ['Indian', 'Street-Food', 'Lunch', 'Breakfast'],
  //   rating: 4.5,
  //   numberOfReviews: 7200,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Theobroma',
  //   description: 'A beloved patisserie famous for its brownies, cakes, and desserts.',
  //   address: {
  //     street: 'Colaba Causeway',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.043, baseLat - 0.063],
  //     },
  //   },
  //   contact: { phone: '9876550044', email: 'theobroma@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Sandwiches', 'Breakfast'],
  //   rating: 4.7,
  //   numberOfReviews: 9900,
  //   opening_hours: [{ day: 'Tuesday', open: '08:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Delhi Highway',
  //   description: 'A vegetarian restaurant serving authentic North Indian and Mughlai cuisine.',
  //   address: {
  //     street: 'Andheri West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400053',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.07],
  //     },
  //   },
  //   contact: { phone: '9876550045', email: 'delhihighway@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Vegan', 'Dinner', 'Lunch'],
  //   rating: 4.4,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: true,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Jamjar Diner',
  //   description: 'A quirky, colorful diner serving American and Italian comfort food.',
  //   address: {
  //     street: 'Versova, Andheri West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400061',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat + 0.075],
  //     },
  //   },
  //   contact: { phone: '9876550046', email: 'jamjardiner@example.com' },
  //   cuisine_type: ['Italian', 'Burgers', 'Pizza', 'Desserts', 'Beverages'],
  //   rating: 4.5,
  //   numberOfReviews: 4100,
  //   opening_hours: [{ day: 'Thursday', open: '09:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 48,
  // },
  // {
  //   name: 'Ramashray',
  //   description: 'A legendary and busy spot in Matunga for authentic Udupi-style South Indian breakfast.',
  //   address: {
  //     street: 'Matunga East',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400019',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.011, baseLat - 0.011],
  //     },
  //   },
  //   contact: { phone: '9876550047', email: 'ramashray@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Indian', 'Beverages'],
  //   rating: 4.8,
  //   numberOfReviews: 8500,
  //   opening_hours: [{ day: 'Friday', open: '05:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Pa Pa Ya',
  //   description: 'A modern Asian bistro offering a radical take on Asian cuisine.',
  //   address: {
  //     street: 'Palladium Mall, Lower Parel',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400013',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.012, baseLat - 0.022],
  //     },
  //   },
  //   contact: { phone: '9876550048', email: 'papaya@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Chinese', 'Dinner', 'Desserts'],
  //   rating: 4.6,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2500,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'Natural Ice Cream',
  //   description: 'Famous for its ice creams made from real fruits, milk, and sugar.',
  //   address: {
  //     street: 'Juhu',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400049',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.021, baseLat + 0.061],
  //     },
  //   },
  //   contact: { phone: '9876550049', email: 'naturalicecream@example.com' },
  //   cuisine_type: ['Desserts', 'Indian-Sweets', 'Beverages'],
  //   rating: 4.8,
  //   numberOfReviews: 12000,
  //   opening_hours: [{ day: 'Sunday', open: '10:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Cannon Pav Bhaji',
  //   description: 'A simple, popular stall opposite CST station known for its delicious pav bhaji.',
  //   address: {
  //     street: 'Fort',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.026, baseLat - 0.046],
  //     },
  //   },
  //   contact: { phone: '9876550050', email: 'cannonpavbhaji@example.com' },
  //   cuisine_type: ['Street-Food', 'Fast-Food', 'Indian', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 28,
  // },
  // seeded till here ;
  // // --- Restaurants 51-60 ---
  // {
  //   name: '145 Cafe & Bar',
  //   description: 'A vibrant cafe and bar known for its freakshakes, comfort food, and lively atmosphere.',
  //   address: {
  //     street: 'Kala Ghoda, Fort',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.037, baseLat - 0.057],
  //     },
  //   },
  //   contact: { phone: '9876550051', email: '145cafe@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Burgers', 'Fast-Food', 'Dinner'],
  //   rating: 4.4,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '01:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Goila Butter Chicken',
  //   description: 'A delivery-focused kitchen by Chef Saransh Goila, famous for its signature butter chicken.',
  //   address: {
  //     street: 'Andheri West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400053',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.008, baseLat + 0.072],
  //     },
  //   },
  //   contact: { phone: '9876550052', email: 'goilabutterchicken@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Dinner', 'Lunch'],
  //   rating: 4.6,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Guru Kripa',
  //   description: 'A legendary eatery in Sion, famous for its Samosa Chole and other Sindhi snacks.',
  //   address: {
  //     street: 'Sion',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400022',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9876550053', email: 'gurukripa@example.com' },
  //   cuisine_type: ['Street-Food', 'Indian', 'Breakfast', 'Fast-Food'],
  //   rating: 4.5,
  //   numberOfReviews: 9200,
  //   opening_hours: [{ day: 'Thursday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Izumi',
  //   description: 'An authentic, intimate Japanese restaurant known for its high-quality sushi and ramen.',
  //   address: {
  //     street: 'Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.034, baseLat + 0.014],
  //     },
  //   },
  //   contact: { phone: '9876550054', email: 'izumi@example.com' },
  //   cuisine_type: ['Japanese', 'Sushi', 'Soups', 'Dinner'],
  //   rating: 4.8,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 1200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 3000,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'La Folie Lab',
  //   description: 'A chic patisserie and cafe offering exquisite French desserts and savory bites.',
  //   address: {
  //     street: 'Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.032, baseLat + 0.016],
  //     },
  //   },
  //   contact: { phone: '9876550055', email: 'lafolie@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Breakfast', 'Sandwiches'],
  //   rating: 4.6,
  //   numberOfReviews: 2100,
  //   opening_hours: [{ day: 'Saturday', open: '09:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Tanjore Tiffin Room',
  //   description: 'A beautiful restaurant serving authentic Tamilian cuisine in a homely setting.',
  //   address: {
  //     street: 'Versova, Andheri West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400061',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.016, baseLat + 0.076],
  //     },
  //   },
  //   contact: { phone: '9876550056', email: 'tanjoretiffin@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Dinner', 'Lunch', 'Healthy'],
  //   rating: 4.5,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Poetry by Love & Cheesecake',
  //   description: 'A charming cafe known for its cheesecakes, all-day breakfast, and healthy meals.',
  //   address: {
  //     street: 'Juhu',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400049',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.023, baseLat + 0.063],
  //     },
  //   },
  //   contact: { phone: '9876550057', email: 'poetry@example.com' },
  //   cuisine_type: ['Desserts', 'Breakfast', 'Healthy', 'Salads', 'Beverages'],
  //   rating: 4.4,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Monday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Barbeque Nation',
  //   description: 'The original live-on-the-table grill restaurant with a lavish buffet.',
  //   address: {
  //     street: 'Andheri West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400053',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.009, baseLat + 0.071],
  //     },
  //   },
  //   contact: { phone: '9876550058', email: 'bbqnation.mum@example.com' },
  //   cuisine_type: ['BBQ', 'North-Indian', 'Indian', 'Dinner', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 9500,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Kailash Parbat',
  //   description: 'A popular vegetarian restaurant serving chaat, North Indian, and Chinese food.',
  //   address: {
  //     street: 'Colaba',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.045, baseLat - 0.065],
  //     },
  //   },
  //   contact: { phone: '9876550059', email: 'kailashparbat@example.com' },
  //   cuisine_type: ['Street-Food', 'North-Indian', 'Chinese', 'Desserts', 'Indian'],
  //   rating: 4.2,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Estella',
  //   description: 'A stunning beachfront restaurant in Juhu offering modern Australian cuisine.',
  //   address: {
  //     street: 'Juhu Tara Road',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400049',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.024, baseLat + 0.064],
  //     },
  //   },
  //   contact: { phone: '9876550060', email: 'estella@example.com' },
  //   cuisine_type: ['Dinner', 'Beverages', 'Salads', 'Soups', 'Desserts'],
  //   rating: 4.6,
  //   numberOfReviews: 2200,
  //   opening_hours: [{ day: 'Thursday', open: '18:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 1500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 4000,
  //   delivery_time_mins: 60,
  // },
  // seeded till here :
  // // --- Restaurants 61-70 ---
  // {
  //   name: 'Mexican Express',
  //   description: 'A quick-service spot for affordable tacos, burritos, and nachos.',
  //   address: {
  //     street: 'Carter Road, Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.036, baseLat + 0.018],
  //     },
  //   },
  //   contact: { phone: '9876550061', email: 'mexicanexpress@example.com' },
  //   cuisine_type: ['Mexican', 'Fast-Food', 'Salads', 'Beverages'],
  //   rating: 4.1,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Kitchen Garden by Suzette',
  //   description: 'A health-focused cafe offering fresh salads, sandwiches, and smoothies.',
  //   address: {
  //     street: 'Pali Hill, Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat + 0.014],
  //     },
  //   },
  //   contact: { phone: '9876550062', email: 'kitchengarden@example.com' },
  //   cuisine_type: ['Healthy', 'Salads', 'Sandwiches', 'Vegan', 'Breakfast'],
  //   rating: 4.5,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Saturday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Hundo Pizza',
  //   description: 'A delivery-focused pizzeria known for its artisanal, thin-crust pizzas.',
  //   address: {
  //     street: 'Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.028, baseLat + 0.012],
  //     },
  //   },
  //   contact: { phone: '9876550063', email: 'hundopizza@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Fast-Food', 'Desserts'],
  //   rating: 4.6,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Good Flippin’ Burgers',
  //   description: 'A popular burger joint serving delicious, high-quality burgers.',
  //   address: {
  //     street: 'Andheri West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400053',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.007, baseLat + 0.073],
  //     },
  //   },
  //   contact: { phone: '9876550064', email: 'goodflippin@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Beverages', 'Sandwiches'],
  //   rating: 4.7,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Monday', open: '11:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 700,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Salad Bar & Walnut Cafe',
  //   description: 'A cafe dedicated to healthy salads, sandwiches, and wholesome meals.',
  //   address: {
  //     street: 'Vashi',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400703',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.1, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9876550065', email: 'saladbar@example.com' },
  //   cuisine_type: ['Salads', 'Healthy', 'Sandwiches', 'Beverages', 'Soups'],
  //   rating: 4.3,
  //   numberOfReviews: 1200,
  //   opening_hours: [{ day: 'Tuesday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 38,
  // },
  // {
  //   name: 'Foo',
  //   description: 'A trendy restaurant offering a vibrant mix of modern Asian tapas.',
  //   address: {
  //     street: 'Phoenix Mills, Lower Parel',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400013',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.011, baseLat - 0.021],
  //     },
  //   },
  //   contact: { phone: '9876550066', email: 'foo@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Sushi', 'Dinner', 'Beverages'],
  //   rating: 4.6,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '00:30' }],
  //   is_active: true,
  //   min_order_value: 800,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2200,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Shree Thaker Bhojanalay',
  //   description: 'A legendary place for an authentic, unlimited Gujarati thali experience.',
  //   address: {
  //     street: 'Kalbadevi',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400002',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.035, baseLat - 0.045],
  //     },
  //   },
  //   contact: { phone: '9876550067', email: 'shreethaker@example.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Lunch', 'Dinner', 'Desserts'],
  //   rating: 4.8,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Thursday', open: '11:30', close: '15:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Cafe Madras',
  //   description: 'Another iconic Matunga eatery serving authentic South Indian food.',
  //   address: {
  //     street: 'Matunga East',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400019',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.013, baseLat - 0.013],
  //     },
  //   },
  //   contact: { phone: '9876550068', email: 'cafemadras@example.com' },
  //   cuisine_type: ['South-Indian', 'Breakfast', 'Indian', 'Beverages'],
  //   rating: 4.7,
  //   numberOfReviews: 7800,
  //   opening_hours: [{ day: 'Friday', open: '07:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 28,
  // },
  // {
  //   name: 'Persian Darbar',
  //   description: 'Known for its Raan Biryani and authentic Mughlai and Persian cuisine.',
  //   address: {
  //     street: 'Byculla',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400027',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9876550069', email: 'persiandarbar@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'BBQ', 'Dinner', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 6100,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'The Ice-Cream Factory',
  //   description: 'A dessert parlour offering a wide range of innovative ice creams and desserts.',
  //   address: {
  //     street: 'Carter Road, Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.037, baseLat + 0.019],
  //     },
  //   },
  //   contact: { phone: '9876550070', email: 'icecreamfactory@example.com' },
  //   cuisine_type: ['Desserts', 'Beverages', 'Indian-Sweets'],
  //   rating: 4.3,
  //   numberOfReviews: 2500,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 25,
  // },
  // seeded till here
  // // --- Restaurants 71-85 ---
  // {
  //   name: 'Hitchki',
  //   description: 'A retro-themed bar and restaurant with a nostalgic Bollywood vibe and fusion Indian food.',
  //   address: {
  //     street: 'Powai',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400076',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.05, baseLat + 0.05],
  //     },
  //   },
  //   contact: { phone: '9876550071', email: 'hitchki@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'Fast-Food', 'Dinner', 'Beverages'],
  //   rating: 4.4,
  //   numberOfReviews: 5200,
  //   opening_hours: [{ day: 'Monday', open: '12:00', close: '01:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Mabruk - Hotel Sahara Star',
  //   description: 'An award-winning Lebanese restaurant with a beautiful Mediterranean ambiance.',
  //   address: {
  //     street: 'Vile Parle East',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400099',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat + 0.045],
  //     },
  //   },
  //   contact: { phone: '9876550072', email: 'mabruk@saharastar.com' },
  //   cuisine_type: ['Dinner', 'Healthy', 'Salads', 'BBQ', 'Desserts'],
  //   rating: 4.7,
  //   numberOfReviews: 1900,
  //   opening_hours: [{ day: 'Tuesday', open: '19:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 1500,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 4500,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Jimis Burger',
  //   description: 'A cult-favorite burger joint known for its massive, juicy, and flavorful burgers.',
  //   address: {
  //     street: 'Andheri West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400053',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat + 0.075],
  //     },
  //   },
  //   contact: { phone: '9876550073', email: 'jimisburger@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Beverages', 'Dinner'],
  //   rating: 4.8,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Wednesday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Dakshinayan',
  //   description: 'A popular restaurant serving authentic and high-quality South Indian vegetarian cuisine.',
  //   address: {
  //     street: 'Juhu',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400049',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.024, baseLat + 0.064],
  //     },
  //   },
  //   contact: { phone: '9876550074', email: 'dakshinayan@example.com' },
  //   cuisine_type: ['South-Indian', 'Indian', 'Breakfast', 'Lunch', 'Healthy'],
  //   rating: 4.6,
  //   numberOfReviews: 4100,
  //   opening_hours: [{ day: 'Thursday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'The Sassy Spoon',
  //   description: 'A chic restaurant with eclectic decor, serving modern European cuisine.',
  //   address: {
  //     street: 'Nariman Point',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400021',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.055, baseLat - 0.055],
  //     },
  //   },
  //   contact: { phone: '9876550075', email: 'sassyspoon@example.com' },
  //   cuisine_type: ['Italian', 'Desserts', 'Salads', 'Dinner', 'Beverages'],
  //   rating: 4.5,
  //   numberOfReviews: 3200,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Gokul',
  //   description: 'A legendary, no-frills bar in Colaba, popular among college students and tourists.',
  //   address: {
  //     street: 'Colaba',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.046, baseLat - 0.066],
  //     },
  //   },
  //   contact: { phone: '9876550076', email: 'gokulbar@example.com' },
  //   cuisine_type: ['North-Indian', 'Chinese', 'Fast-Food', 'Beverages'],
  //   rating: 4.1,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Saturday', open: '11:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Aaswad',
  //   description: 'An award-winning restaurant famous for its authentic Maharashtrian cuisine.',
  //   address: {
  //     street: 'Dadar West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400028',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon, baseLat],
  //     },
  //   },
  //   contact: { phone: '9876550077', email: 'aaswad@example.com' },
  //   cuisine_type: ['Indian', 'South-Indian', 'Breakfast', 'Lunch', 'Street-Food'],
  //   rating: 4.6,
  //   numberOfReviews: 6800,
  //   opening_hours: [{ day: 'Sunday', open: '10:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Celini - Grand Hyatt',
  //   description: 'An authentic Italian fine-dining restaurant with a show kitchen.',
  //   address: {
  //     street: 'Santacruz East',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400055',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9876550078', email: 'celini@hyatt.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Dinner', 'Soups', 'Desserts'],
  //   rating: 4.7,
  //   numberOfReviews: 1500,
  //   opening_hours: [{ day: 'Monday', open: '19:00', close: '23:45' }],
  //   is_active: true,
  //   min_order_value: 1500,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 4500,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Mamagoto',
  //   description: 'A fun, quirky Asian restaurant serving street-style food from across Asia.',
  //   address: {
  //     street: 'Bandra West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400050',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.027, baseLat + 0.013],
  //     },
  //   },
  //   contact: { phone: '9876550079', email: 'mamagoto@example.com' },
  //   cuisine_type: ['Chinese', 'Japanese', 'Soups', 'Salads', 'Dinner'],
  //   rating: 4.4,
  //   numberOfReviews: 4300,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Prakash Shakahari Uphar Kendra',
  //   description: 'A legendary spot in Dadar for authentic Maharashtrian snacks and breakfast.',
  //   address: {
  //     street: 'Dadar West',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400028',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.001, baseLat - 0.001],
  //     },
  //   },
  //   contact: { phone: '9876550080', email: 'prakashuphar@example.com' },
  //   cuisine_type: ['Indian', 'Breakfast', 'Street-Food', 'Fast-Food'],
  //   rating: 4.7,
  //   numberOfReviews: 5800,
  //   opening_hours: [{ day: 'Wednesday', open: '07:30', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 80,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Rolling Pin',
  //   description: 'A spacious bakery and cafe in Lower Parel offering a wide range of desserts and savory items.',
  //   address: {
  //     street: 'Lower Parel',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400013',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.013, baseLat - 0.023],
  //     },
  //   },
  //   contact: { phone: '9876550081', email: 'rollingpin@example.com' },
  //   cuisine_type: ['Desserts', 'Bakery', 'Breakfast', 'Beverages', 'Fast-Food'],
  //   rating: 4.3,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Thursday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'San-Qi - Four Seasons',
  //   description: 'A stylish restaurant offering the best of Japanese, Chinese, and Indian cuisine.',
  //   address: {
  //     street: 'Worli',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400018',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9876550082', email: 'sanqi@fourseasons.com' },
  //   cuisine_type: ['Japanese', 'Chinese', 'North-Indian', 'Sushi', 'Dinner'],
  //   rating: 4.7,
  //   numberOfReviews: 2800,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 2000,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 6000,
  //   delivery_time_mins: 60,
  // },
  // {
  //   name: 'Sodabottleopenerwala',
  //   description: 'A quirky, modern take on the classic Bombay Irani cafe and Parsi food.',
  //   address: {
  //     street: 'BKC, Bandra East',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400051',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.021, baseLat + 0.021],
  //     },
  //   },
  //   contact: { phone: '9876550083', email: 'sbow@example.com' },
  //   cuisine_type: ['Indian', 'Street-Food', 'Breakfast', 'Desserts', 'Beverages'],
  //   rating: 4.4,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Saturday', open: '11:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Taftoon Bar & Kitchen',
  //   description: 'A restaurant that takes you on a culinary journey along the Grand Trunk Road.',
  //   address: {
  //     street: 'BKC, Bandra East',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400051',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.023, baseLat + 0.023],
  //     },
  //   },
  //   contact: { phone: '9876550084', email: 'taftoon@example.com' },
  //   cuisine_type: ['North-Indian', 'Indian', 'BBQ', 'Dinner', 'Lunch'],
  //   rating: 4.6,
  //   numberOfReviews: 2900,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '00:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 2200,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Ziya - The Oberoi',
  //   description: 'A contemporary Indian restaurant by Michelin-starred chef Vineet Bhatia.',
  //   address: {
  //     street: 'Nariman Point',
  //     city: 'Mumbai',
  //     state: 'Maharashtra',
  //     zip_code: '400021',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.056, baseLat - 0.056],
  //     },
  //   },
  //   contact: { phone: '9876550085', email: 'ziya@oberoi.com' },
  //   cuisine_type: ['Indian', 'North-Indian', 'Dinner', 'Desserts', 'Healthy'],
  //   rating: 4.8,
  //   numberOfReviews: 1800,
  //   opening_hours: [{ day: 'Monday', open: '19:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 2500,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 7000,
  //   delivery_time_mins: 60,
  // },
  // this entire file has been seeded
];

export default mumbaiRestaurants;
