const baseLat = 21.1458;
const baseLon = 79.0882;

const nagpurRestaurants = [
  {
    name: 'Mintleaf Restaurant',
    description: 'Upscale multi-cuisine fine dining with elegant ambience.',
    address: {
      street: 'Sadar, Nagpur',
      city: 'Nagpur',
      state: 'Maharashtra',
      zip_code: '440001',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.004, baseLat + 0.003],
      },
    },
    contact: { phone: '0712-1234567', email: 'contact@mintleafnagpur.com' },
    cuisine_type: [
      'Indian',
      'North-Indian',
      'Chinese',
      'Desserts',
      'Beverages',
    ],
    rating: 4.7,
    numberOfReviews: 1800,
    opening_hours: [{ day: 'Everyday', open: '12:00', close: '23:30' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 1200,
    delivery_time_mins: 45,
  },
  {
    name: 'Latest Recipe',
    description: 'Contemporary cuisine, bar & international dishes.',
    address: {
      street: 'Civil Lines',
      city: 'Nagpur',
      state: 'Maharashtra',
      zip_code: '440001',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.005, baseLat + 0.005],
      },
    },
    contact: { phone: '0712-7654321', email: 'info@latestrecipe.com' },
    cuisine_type: [
      'Indian',
      'Italian',
      'Beverages',
      'Desserts',
      'Lunch',
      'Dinner',
    ],
    rating: 4.8,
    numberOfReviews: 1600,
    opening_hours: [{ day: 'Everyday', open: '11:30', close: '23:00' }],
    is_active: true,
    min_order_value: 350,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 1000,
    delivery_time_mins: 40,
  },
  {
    name: 'Barbeque Nation – Amravati Road',
    description: 'Buffet BBQ and grill experience — veg & non-veg.',
    address: {
      street: 'Amravati Road',
      city: 'Nagpur',
      state: 'Maharashtra',
      zip_code: '440015',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.02, baseLat - 0.002],
      },
    },
    contact: { phone: '0712-9988776', email: 'nagpur@barbque.com' },
    cuisine_type: ['BBQ', 'Indian', 'North-Indian', 'Dinner', 'Lunch'],
    rating: 4.6,
    numberOfReviews: 2200,
    opening_hours: [{ day: 'Everyday', open: '12:00', close: '23:59' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 1500,
    delivery_time_mins: 50,
  },
  {
    name: 'Uttar Dakshin by Naivedhyam',
    description: 'Specializes in South & North Indian cuisine, family style.',
    address: {
      street: 'Pratap Nagar',
      city: 'Nagpur',
      state: 'Maharashtra',
      zip_code: '440015',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.003, baseLat - 0.004],
      },
    },
    contact: { phone: '0712-2233445', email: 'contact@naivedhyam.com' },
    cuisine_type: ['Indian', 'South-Indian', 'North-Indian', 'Lunch', 'Dinner'],
    rating: 4.4,
    numberOfReviews: 900,
    opening_hours: [{ day: 'Everyday', open: '11:00', close: '22:30' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 700,
    delivery_time_mins: 35,
  },
  {
    name: 'Little Italy Nagpur',
    description: 'Italian restaurant — pizzas, pastas, desserts.',
    address: {
      street: 'Ramdaspeth',
      city: 'Nagpur',
      state: 'Maharashtra',
      zip_code: '440010',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.006, baseLat + 0.001],
      },
    },
    contact: { phone: '0712-5566778', email: 'info@littleitalynagpur.com' },
    cuisine_type: ['Italian', 'Pizza', 'Desserts', 'Beverages'],
    rating: 4.3,
    numberOfReviews: 800,
    opening_hours: [{ day: 'Everyday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 900,
    delivery_time_mins: 30,
  },
  {
    name: 'The Breakfast Story Nagpur',
    description: 'All-day breakfast, café style, pancakes, egg dishes, coffee.',
    address: {
      street: 'Hingna Road',
      city: 'Nagpur',
      state: 'Maharashtra',
      zip_code: '440028',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.007, baseLat + 0.007],
      },
    },
    contact: { phone: '0712-3344556', email: 'hello@breakfaststory.com' },
    cuisine_type: ['Breakfast', 'Desserts', 'Sandwiches', 'Beverages'],
    rating: 4.5,
    numberOfReviews: 1200,
    opening_hours: [{ day: 'Everyday', open: '07:30', close: '16:00' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 5,
    is_veg: false,
    cost_for_two: 500,
    delivery_time_mins: 25,
  },
  {
    name: 'Vishnuji Ki Rasoi',
    description: 'Pure vegetarian Indian restaurant with home style food.',
    address: {
      street: 'Sitabuldi',
      city: 'Nagpur',
      state: 'Maharashtra',
      zip_code: '440012',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.001, baseLat - 0.005],
      },
    },
    contact: { phone: '0712-4455667', email: 'contact@vishnujirasoi.in' },
    cuisine_type: [
      'Indian',
      'North-Indian',
      'Indian-Sweets',
      'Lunch',
      'Dinner',
    ],
    rating: 4.2,
    numberOfReviews: 700,
    opening_hours: [{ day: 'Everyday', open: '11:00', close: '22:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 600,
    delivery_time_mins: 30,
  },
  {
    name: 'Raasta Nagpur',
    description: 'Trendy café & bar, global flavours, pizzas & Asian fusion.',
    address: {
      street: 'Dharampeth',
      city: 'Nagpur',
      state: 'Maharashtra',
      zip_code: '440001',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.004, baseLat + 0.002],
      },
    },
    contact: { phone: '0712-7788990', email: 'hello@raasta.in' },
    cuisine_type: ['Indian', 'Pizza', 'Mexican', 'Beverages'],
    rating: 4.3,
    numberOfReviews: 950,
    opening_hours: [{ day: 'Everyday', open: '11:30', close: '23:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 850,
    delivery_time_mins: 33,
  },
  {
    name: 'Saoji Express (dummy)',
    description: 'Local Nagpuri style spicy cuisine with saoji dishes.',
    address: {
      street: 'Jawahar Nagar',
      city: 'Nagpur',
      state: 'Maharashtra',
      zip_code: '440025',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.009, baseLat - 0.002],
      },
    },
    contact: { phone: '0712-6655443', email: 'contact@saojiexpress.com' },
    cuisine_type: ['Indian', 'Street-Food', 'Indian-Sweets', 'Lunch', 'Dinner'],
    rating: 4.1,
    numberOfReviews: 500,
    opening_hours: [{ day: 'Everyday', open: '12:00', close: '22:30' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 5,
    is_veg: false,
    cost_for_two: 400,
    delivery_time_mins: 28,
  },
];

export default nagpurRestaurants;
