// Base coordinates for Pune (approximate center - Deccan/Koregaon Park area)
const baseLat = 18.5204;
const baseLon = 73.8567;

/**
 * Data structure for restaurants in Pune, ensuring wide coverage of all 24 supported cuisine types.
 * 35 restaurants are generated to ensure at least 9-10 restaurants are available for every supported category.
 */
const puneRestaurants = [
  // --- Pune Restaurant 1-5 ---
  // {
  //   name: 'Vohuman Cafe',
  //   description:
  //     'Iconic Irani cafe famous for its Cheese Omelette and Bun Maska.',
  //   address: {
  //     street: 'Near Jehangir Hospital, Sassoon Road',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.015, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9021030001', email: 'vohuman.pune@example.com' },
  //   cuisine_type: ['Breakfast', 'Beverages', 'Fast-Food', 'Sandwiches'],
  //   rating: 4.7,
  //   numberOfReviews: 14500,
  //   opening_hours: [{ day: 'Monday', open: '06:00', close: '18:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: false,
  //   cost_for_two: 350,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'German Bakery',
  //   description:
  //     'A popular cafe and bakery known for its desserts, pastries, and Continental food.',
  //   address: {
  //     street: 'Koregaon Park, Lane 1',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.02, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9021030002', email: 'germanbakery@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Breakfast',
  //     'Healthy',
  //     'Sandwiches',
  //     'Beverages',
  //     'Italian',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 12100,
  //   opening_hours: [{ day: 'Tuesday', open: '08:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Vaishali',
  //   description:
  //     'A legendary Deccan Gymkhana eatery serving delicious South Indian snacks.',
  //   address: {
  //     street: 'Fergusson College Road, Deccan Gymkhana',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.002],
  //     },
  //   },
  //   contact: { phone: '9021030003', email: 'vaishali.pune@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Indian',
  //     'Street-Food',
  //     'Breakfast',
  //     'Lunch',
  //     'Dinner',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 18500,
  //   opening_hours: [{ day: 'Wednesday', open: '07:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 450,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Shreyas Hotel',
  //   description:
  //     'Known for its authentic Maharashtrian and North Indian thalis.',
  //   address: {
  //     street: 'Apte Road, Deccan Gymkhana',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411004',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat - 0.008],
  //     },
  //   },
  //   contact: { phone: '9021030004', email: 'shreyas.pune@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Indian-Sweets',
  //     'Vegan',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 9200,
  //   opening_hours: [{ day: 'Thursday', open: '11:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 9,
  //   is_veg: true,
  //   cost_for_two: 800,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Malaka Spice',
  //   description:
  //     'Fine-dining South East Asian restaurant with a reputation for bold flavors.',
  //   address: {
  //     street: 'North Main Road, Koregaon Park',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.025, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9021030005', email: 'malakaspice@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Japanese',
  //     'Soups',
  //     'Dinner',
  //     'Lunch',
  //     'Healthy',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 7800,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 50,
  // },
  // --- Pune Restaurant 6-10 ---
  // {
  //   name: 'Effingut Brewerkz',
  //   description:
  //     'Pub and microbrewery known for its BBQ and continental snacks.',
  //   address: {
  //     street: 'Koregaon Park, Lane 6',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9021030006', email: 'effingut@example.com' },
  //   cuisine_type: ['BBQ', 'Burgers', 'Dinner', 'Lunch', 'Fast-Food', 'Pizza'],
  //   rating: 4.3,
  //   numberOfReviews: 6500,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '01:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Little Italy',
  //   description:
  //     'Authentic Italian fine-dining experience with vegetarian options.',
  //   address: {
  //     street: 'Bund Garden Road',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.005, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9021030007', email: 'littleitaly.pune@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Vegan', 'Healthy', 'Dinner', 'Lunch'],
  //   rating: 4.5,
  //   numberOfReviews: 5800,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 1400,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Burger King (FC Road)',
  //   description:
  //     'Global chain for flame-grilled burgers and fast-food favorites.',
  //   address: {
  //     street: 'Fergusson College Road, Shivajinagar',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.015, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9021030008', email: 'bk.pune@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Lunch',
  //     'Dinner',
  //     'Sandwiches',
  //     'Beverages',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 8900,
  //   opening_hours: [{ day: 'Monday', open: '10:30', close: '23:45' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Good News Kitchen',
  //   description:
  //     'A dedicated health food and salad bar with fresh ingredients.',
  //   address: {
  //     street: 'Koregaon Park, Lane 5',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9021030009', email: 'goodnews@example.com' },
  //   cuisine_type: [
  //     'Healthy',
  //     'Vegan',
  //     'Salads',
  //     'Soups',
  //     'Breakfast',
  //     'Sandwiches',
  //   ],
  //   rating: 4.7,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Tuesday', open: '08:30', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 850,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Mexican Salsa',
  //   description:
  //     'Colorful spot for authentic Mexican tacos, burritos, and quesadillas.',
  //   address: {
  //     street: 'Hinjewadi, Phase 1',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411057',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat - 0.03],
  //     },
  //   },
  //   contact: { phone: '9021030010', email: 'mexicansalsa@example.com' },
  //   cuisine_type: [
  //     'Mexican',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //     'Vegan',
  //     'Salads',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 5100,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 750,
  //   delivery_time_mins: 40,
  // },
  // // --- Pune Restaurant 11-15 ---
  // {
  //   name: "Dario's Trattoria",
  //   description:
  //     'Fine-dining Italian restaurant in a garden setting, focusing on wood-fired pizza.',
  //   address: {
  //     street: 'Koregaon Park, Lane 1',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.022, baseLat - 0.012],
  //     },
  //   },
  //   contact: { phone: '9021030011', email: 'darios@example.com' },
  //   cuisine_type: ['Italian', 'Pizza', 'Dinner', 'Vegan', 'Lunch', 'Desserts'],
  //   rating: 4.6,
  //   numberOfReviews: 6200,
  //   opening_hours: [{ day: 'Thursday', open: '12:30', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 600,
  //   delivery_radius_km: 9,
  //   is_veg: true,
  //   cost_for_two: 1600,
  //   delivery_time_mins: 50,
  // },
  // {
  //   name: 'Shizusan',
  //   description:
  //     'Pan-Asian diner serving Japanese, Chinese, and other regional dishes.',
  //   address: {
  //     street: 'Phoenix Marketcity, Viman Nagar',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411014',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9021030012', email: 'shizusan@example.com' },
  //   cuisine_type: ['Japanese', 'Chinese', 'Sushi', 'Dinner', 'Lunch', 'Soups'],
  //   rating: 4.4,
  //   numberOfReviews: 5900,
  //   opening_hours: [{ day: 'Friday', open: '12:00', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 550,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1500,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Bedekar Misal',
  //   description:
  //     'Famous for its authentic and spicy Maharashtrian Misal Pav (Street-Food).',
  //   address: {
  //     street: 'Narayan Peth, Bajirao Road',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411030',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.001, baseLat - 0.001],
  //     },
  //   },
  //   contact: { phone: '9021030013', email: 'bedekar@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Indian',
  //     'Breakfast',
  //     'Fast-Food',
  //     'South-Indian',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 10500,
  //   opening_hours: [{ day: 'Saturday', open: '07:00', close: '15:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 4,
  //   is_veg: true,
  //   cost_for_two: 200,
  //   delivery_time_mins: 15,
  // },
  // {
  //   name: 'Barbeque Nation (Wakdewadi)',
  //   description:
  //     'All-you-can-eat grill and buffet with a focus on BBQ and Indian cuisine.',
  //   address: {
  //     street: 'Wakdewadi, Shivaji Nagar',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411003',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.01, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9021030014', email: 'bbqnation@example.com' },
  //   cuisine_type: [
  //     'BBQ',
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'Fast-Food',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 8100,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 700,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1800,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Marz-o-rin',
  //   description:
  //     'Vintage cafe known for its cold sandwiches, rolls, and mayonnaise dishes.',
  //   address: {
  //     street: 'Main Street, Camp',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.035, baseLat + 0.001],
  //     },
  //   },
  //   contact: { phone: '9021030015', email: 'marzorin@example.com' },
  //   cuisine_type: [
  //     'Sandwiches',
  //     'Fast-Food',
  //     'Desserts',
  //     'Beverages',
  //     'Healthy',
  //     'Salads',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 11000,
  //   opening_hours: [{ day: 'Monday', open: '09:00', close: '21:30' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: false,
  //   cost_for_two: 400,
  //   delivery_time_mins: 30,
  // },
  // // --- Pune Restaurant 16-20 ---
  // {
  //   name: 'Kaka Halwai Sweets',
  //   description:
  //     'Traditional sweet shop specializing in Indian mithai and snacks.',
  //   address: {
  //     street: 'Karve Road, Kothrud',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.03, baseLat - 0.005],
  //     },
  //   },
  //   contact: { phone: '9021030016', email: 'kaka.halwai@example.com' },
  //   cuisine_type: [
  //     'Indian-Sweets',
  //     'Desserts',
  //     'Indian',
  //     'Street-Food',
  //     'Breakfast',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 8800,
  //   opening_hours: [{ day: 'Tuesday', open: '08:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: true,
  //   cost_for_two: 300,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'Kalyani Veg Thali',
  //   description:
  //     'Simple and affordable pure vegetarian North Indian thali joint.',
  //   address: {
  //     street: 'Pimple Saudagar, Aundh Road',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411027',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.02, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9021030017', email: 'kalyani@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Vegan',
  //     'Soups',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 3900,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 650,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Sushi World',
  //   description:
  //     'A dedicated sushi bar with high-quality imported fish and traditional rolls.',
  //   address: {
  //     street: 'Baner Road, Near Balewadi',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411045',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat + 0.008],
  //     },
  //   },
  //   contact: { phone: '9021030018', email: 'sushiworld@example.com' },
  //   cuisine_type: ['Sushi', 'Japanese', 'Dinner', 'Healthy', 'Lunch', 'Soups'],
  //   rating: 4.5,
  //   numberOfReviews: 4200,
  //   opening_hours: [{ day: 'Thursday', open: '12:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 750,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 2000,
  //   delivery_time_mins: 55,
  // },
  // {
  //   name: 'The Good Earth',
  //   description:
  //     'Organic cafe focusing on sustainability, serving vegan and health-conscious food.',
  //   address: {
  //     street: 'Wakad, Near Dange Chowk',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411033',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat - 0.01],
  //     },
  //   },
  //   contact: { phone: '9021030019', email: 'goodearth@example.com' },
  //   cuisine_type: [
  //     'Vegan',
  //     'Healthy',
  //     'Breakfast',
  //     'Salads',
  //     'Beverages',
  //     'Sandwiches',
  //   ],
  //   rating: 4.6,
  //   numberOfReviews: 3100,
  //   opening_hours: [{ day: 'Friday', open: '09:00', close: '20:00' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 950,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Yana Sizzlers',
  //   description:
  //     'Famous local restaurant for unique sizzler combinations and grills.',
  //   address: {
  //     street: 'M.G. Road, Camp',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9021030020', email: 'yana@example.com' },
  //   cuisine_type: ['BBQ', 'Dinner', 'Lunch', 'Italian', 'Burgers', 'Soups'],
  //   rating: 4.3,
  //   numberOfReviews: 6900,
  //   opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 450,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 40,
  // },
  // --- Pune Restaurant 21-25 ---
  // {
  //   name: 'Punekar Dosa & Idli',
  //   description:
  //     'Simple street-side joint offering budget-friendly South Indian snacks.',
  //   address: {
  //     street: 'Sinhagad Road, Near Manikbaug',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411051',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.06, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9021030021', email: 'punekardosa@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Street-Food',
  //     'Breakfast',
  //     'Fast-Food',
  //     'Indian',
  //     'Lunch',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 5400,
  //   opening_hours: [{ day: 'Sunday', open: '07:30', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 100,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 250,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'The Cake Studio',
  //   description:
  //     'Specialty bakery for custom cakes, pastries, and French desserts.',
  //   address: {
  //     street: 'Aundh, ITI Road',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411007',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9021030022', email: 'cakestudio@example.com' },
  //   cuisine_type: [
  //     'Desserts',
  //     'Beverages',
  //     'Breakfast',
  //     'Indian-Sweets',
  //     'Vegan',
  //   ],
  //   rating: 4.5,
  //   numberOfReviews: 4800,
  //   opening_hours: [{ day: 'Monday', open: '10:00', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 500,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Chinese Palace',
  //   description:
  //     'Long-standing restaurant serving classic Indian-Chinese cuisine.',
  //   address: {
  //     street: 'Camp, East Street',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.04, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9021030023', email: 'chinesepalace@example.com' },
  //   cuisine_type: [
  //     'Chinese',
  //     'Fast-Food',
  //     'Dinner',
  //     'Lunch',
  //     'Soups',
  //     'North-Indian',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 7000,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1000,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Burger Pit Stop',
  //   description:
  //     'Quick-service spot specializing in customizable sliders and shakes.',
  //   address: {
  //     street: 'Pimple Gurav, Kalewadi',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411061',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.035, baseLat + 0.035],
  //     },
  //   },
  //   contact: { phone: '9021030024', email: 'burgerpitstop@example.com' },
  //   cuisine_type: ['Burgers', 'Fast-Food', 'Lunch', 'Dinner', 'BBQ', 'Mexican'],
  //   rating: 4.0,
  //   numberOfReviews: 3500,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 600,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'World of Wraps',
  //   description:
  //     'Outlet for Kathi Rolls, Shawarmas, and other quick, rolled snacks.',
  //   address: {
  //     street: 'Kothrud, Paud Road',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.04, baseLat - 0.015],
  //     },
  //   },
  //   contact: { phone: '9021030025', email: 'worldofwraps@example.com' },
  //   cuisine_type: [
  //     'Street-Food',
  //     'Fast-Food',
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Sandwiches',
  //   ],
  //   rating: 4.2,
  //   numberOfReviews: 5000,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 25,
  // },
  // // --- Pune Restaurant 26-30 ---
  // {
  //   name: 'Pizza Express',
  //   description: 'Chain famous for its traditional thin-crust Italian pizzas.',
  //   address: {
  //     street: 'Senapati Bapat Road, Pavilion Mall',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.005, baseLat + 0.025],
  //     },
  //   },
  //   contact: { phone: '9021030026', email: 'pizzaexpress@example.com' },
  //   cuisine_type: ['Pizza', 'Italian', 'Dinner', 'Lunch', 'Healthy', 'Salads'],
  //   rating: 4.4,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Friday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 1200,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Pure Vegetarian Hub',
  //   description: 'Wide variety of North and South Indian vegetarian dishes.',
  //   address: {
  //     street: 'Hadapsar, Near Magarpatta',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411013',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.05, baseLat - 0.02],
  //     },
  //   },
  //   contact: { phone: '9021030027', email: 'veg.hub@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'South-Indian',
  //     'Indian',
  //     'Lunch',
  //     'Dinner',
  //     'Indian-Sweets',
  //   ],
  //   rating: 4.1,
  //   numberOfReviews: 4500,
  //   opening_hours: [{ day: 'Saturday', open: '10:00', close: '22:30' }],
  //   is_active: true,
  //   min_order_value: 300,
  //   delivery_radius_km: 10,
  //   is_veg: true,
  //   cost_for_two: 700,
  //   delivery_time_mins: 45,
  // },
  // {
  //   name: 'Juice & Shake Express',
  //   description:
  //     'Fresh fruit juices, health shakes, and quick breakfast items.',
  //   address: {
  //     street: 'Shivaji Nagar, Bhamburda',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411005',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.025, baseLat + 0.015],
  //     },
  //   },
  //   contact: { phone: '9021030028', email: 'juiceexpress@example.com' },
  //   cuisine_type: [
  //     'Beverages',
  //     'Healthy',
  //     'Breakfast',
  //     'Vegan',
  //     'Desserts',
  //     'Fast-Food',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 6000,
  //   opening_hours: [{ day: 'Sunday', open: '07:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 5,
  //   is_veg: true,
  //   cost_for_two: 350,
  //   delivery_time_mins: 20,
  // },
  // {
  //   name: 'Taco Bar',
  //   description:
  //     'Casual Mexican spot with focus on customizable bowl and taco combos.',
  //   address: {
  //     street: 'Koregaon Park, N Main Road',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.03, baseLat - 0.001],
  //     },
  //   },
  //   contact: { phone: '9021030029', email: 'tacobar@example.com' },
  //   cuisine_type: [
  //     'Mexican',
  //     'Burgers',
  //     'Lunch',
  //     'Dinner',
  //     'Fast-Food',
  //     'Salads',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 4100,
  //   opening_hours: [{ day: 'Monday', open: '11:30', close: '23:30' }],
  //   is_active: true,
  //   min_order_value: 350,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 800,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'Kyoto Sushi & Ramen',
  //   description:
  //     'Japanese specialty restaurant offering sushi, sashimi, and warm ramen.',
  //   address: {
  //     street: 'Viman Nagar, Datta Mandir Chowk',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411014',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.05, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9021030030', email: 'kyoto@example.com' },
  //   cuisine_type: ['Sushi', 'Japanese', 'Chinese', 'Dinner', 'Lunch', 'Soups'],
  //   rating: 4.5,
  //   numberOfReviews: 3800,
  //   opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 650,
  //   delivery_radius_km: 9,
  //   is_veg: false,
  //   cost_for_two: 1700,
  //   delivery_time_mins: 45,
  // },
  // // --- Pune Restaurant 31-35 (Buffer to ensure all categories are hit 10+ times) ---
  // {
  //   name: 'The Burger Cafe',
  //   description: 'Simple, popular spot for a quick and affordable burger meal.',
  //   address: {
  //     street: 'Pimpri-Chinchwad, Nigdi',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411044',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.07, baseLat + 0.02],
  //     },
  //   },
  //   contact: { phone: '9021030031', email: 'burgercafe@example.com' },
  //   cuisine_type: [
  //     'Burgers',
  //     'Fast-Food',
  //     'Lunch',
  //     'Dinner',
  //     'Pizza',
  //     'Beverages',
  //   ],
  //   rating: 3.9,
  //   numberOfReviews: 4000,
  //   opening_hours: [{ day: 'Wednesday', open: '11:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 200,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 450,
  //   delivery_time_mins: 35,
  // },
  // {
  //   name: 'North Point',
  //   description: 'Reliable delivery spot for Indian and North Indian curries.',
  //   address: {
  //     street: 'Camp, Pune Cantonment',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411001',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon + 0.045, baseLat + 0.01],
  //     },
  //   },
  //   contact: { phone: '9021030032', email: 'northpoint@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian',
  //     'Dinner',
  //     'Lunch',
  //     'BBQ',
  //     'Street-Food',
  //   ],
  //   rating: 4.0,
  //   numberOfReviews: 5500,
  //   opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 400,
  //   delivery_radius_km: 8,
  //   is_veg: false,
  //   cost_for_two: 900,
  //   delivery_time_mins: 40,
  // },
  // {
  //   name: 'Madras Cafe',
  //   description:
  //     'Authentic South Indian restaurant, great for filter coffee and light meals.',
  //   address: {
  //     street: 'Model Colony, Shivajinagar',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411016',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.01, baseLat + 0.03],
  //     },
  //   },
  //   contact: { phone: '9021030033', email: 'madrascafe@example.com' },
  //   cuisine_type: [
  //     'South-Indian',
  //     'Breakfast',
  //     'Indian',
  //     'Beverages',
  //     'Street-Food',
  //     'Lunch',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 7200,
  //   opening_hours: [{ day: 'Friday', open: '06:30', close: '22:00' }],
  //   is_active: true,
  //   min_order_value: 150,
  //   delivery_radius_km: 7,
  //   is_veg: true,
  //   cost_for_two: 400,
  //   delivery_time_mins: 25,
  // },
  // {
  //   name: 'The Artisan Sandwich Co.',
  //   description: 'Gourmet sandwich shop with fresh breads and custom fillings.',
  //   address: {
  //     street: 'Kothrud, Dahanukar Colony',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411038',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.05, baseLat - 0.025],
  //     },
  //   },
  //   contact: { phone: '9021030034', email: 'artisan.sandwich@example.com' },
  //   cuisine_type: [
  //     'Sandwiches',
  //     'Healthy',
  //     'Breakfast',
  //     'Lunch',
  //     'Fast-Food',
  //     'Salads',
  //   ],
  //   rating: 4.4,
  //   numberOfReviews: 3600,
  //   opening_hours: [{ day: 'Saturday', open: '09:00', close: '21:00' }],
  //   is_active: true,
  //   min_order_value: 250,
  //   delivery_radius_km: 6,
  //   is_veg: false,
  //   cost_for_two: 550,
  //   delivery_time_mins: 30,
  // },
  // {
  //   name: 'Pista House',
  //   description:
  //     'Famous for its seasonal Haleem and year-round Mughlai dishes and sweets.',
  //   address: {
  //     street: 'Wakad, Near Bhumkar Chowk',
  //     city: 'Pune',
  //     state: 'Maharashtra',
  //     zip_code: '411057',
  //     location: {
  //       type: 'Point',
  //       coordinates: [baseLon - 0.065, baseLat + 0.005],
  //     },
  //   },
  //   contact: { phone: '9021030035', email: 'pistahouse@example.com' },
  //   cuisine_type: [
  //     'North-Indian',
  //     'Indian-Sweets',
  //     'Dinner',
  //     'Lunch',
  //     'Indian',
  //     'BBQ',
  //   ],
  //   rating: 4.3,
  //   numberOfReviews: 6000,
  //   opening_hours: [{ day: 'Sunday', open: '12:00', close: '23:00' }],
  //   is_active: true,
  //   min_order_value: 500,
  //   delivery_radius_km: 10,
  //   is_veg: false,
  //   cost_for_two: 1100,
  //   delivery_time_mins: 45,
  // },
  // seede all these restaunrants
];

export default puneRestaurants;
