// Base coordinates for Surat (approximate center - Athwa/Piplod area)
const baseLat = 21.1702;
const baseLon = 72.8311;

/**
 * Data structure for restaurants in Surat, ensuring wide coverage of all 24 supported cuisine types.
 * 35 restaurants are generated to ensure at least 9-10 restaurants are available for every supported category.
 */
const suratRestaurants = [
  // --- Surat Restaurant 1-5 ---
  {
    name: 'Sasumaa Gujarati Thali',
    description: 'Premier destination for authentic, unlimited Gujarati Thali.',
    address: {
      street: 'Ring Road, Near Surat Railway Station',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.005, baseLat + 0.01],
      },
    },
    contact: { phone: '9121040001', email: 'sasumaa.surat@example.com' },
    cuisine_type: [
      'Indian',
      'North-Indian',
      'Lunch',
      'Dinner',
      'Vegan',
      'Indian-Sweets',
    ],
    rating: 4.6,
    numberOfReviews: 15100,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '22:30' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 700,
    delivery_time_mins: 35,
  },
  {
    name: 'Gopal Locho Khaman',
    description:
      "Famous local eatery for Surat's iconic steamed snacks: Locho and Surti Sev Khamani.",
    address: {
      street: 'Near Navyug College, Rander Road',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395005',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.015, baseLat + 0.015],
      },
    },
    contact: { phone: '9121040002', email: 'gopallocho@example.com' },
    cuisine_type: [
      'Street-Food',
      'Indian',
      'Fast-Food',
      'Breakfast',
      'Sandwiches',
      'Vegan',
    ],
    rating: 4.7,
    numberOfReviews: 18900,
    opening_hours: [{ day: 'Tuesday', open: '08:00', close: '21:00' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 250,
    delivery_time_mins: 20,
  },
  {
    name: 'The Chocolate Room',
    description:
      'Cafe specializing in desserts, hot beverages, shakes, and quick bites.',
    address: {
      street: 'Piplod, Near Rahul Raj Mall',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.02, baseLat - 0.015],
      },
    },
    contact: { phone: '9121040003', email: 'tcr.surat@example.com' },
    cuisine_type: [
      'Desserts',
      'Beverages',
      'Sandwiches',
      'Fast-Food',
      'Italian',
      'Pizza',
    ],
    rating: 4.3,
    numberOfReviews: 9800,
    opening_hours: [{ day: 'Wednesday', open: '10:00', close: '23:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 600,
    delivery_time_mins: 30,
  },
  {
    name: 'Kansar Thali',
    description:
      'Another high-quality Gujarati Thali restaurant with seasonal specialties.',
    address: {
      street: 'Citylight Road, Near Mahalaxmi Temple',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.005, baseLat - 0.02],
      },
    },
    contact: { phone: '9121040004', email: 'kansar.surat@example.com' },
    cuisine_type: [
      'Indian',
      'North-Indian',
      'Lunch',
      'Dinner',
      'Indian-Sweets',
      'Vegan',
    ],
    rating: 4.5,
    numberOfReviews: 11200,
    opening_hours: [{ day: 'Thursday', open: '11:00', close: '22:00' }],
    is_active: true,
    min_order_value: 350,
    delivery_radius_km: 8,
    is_veg: true,
    cost_for_two: 750,
    delivery_time_mins: 40,
  },
  {
    name: 'The Daily Bowl',
    description:
      'Healthy food kitchen focusing on customized salads, protein bowls, and wraps.',
    address: {
      street: 'Vesu Road, Near VR Mall',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.03, baseLat - 0.025],
      },
    },
    contact: { phone: '9121040005', email: 'dailybowl@example.com' },
    cuisine_type: ['Healthy', 'Salads', 'Vegan', 'Soups', 'Lunch', 'Dinner'],
    rating: 4.4,
    numberOfReviews: 4500,
    opening_hours: [{ day: 'Friday', open: '10:30', close: '21:30' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 850,
    delivery_time_mins: 25,
  },
  // --- Surat Restaurant 6-10 ---
  {
    name: 'Burger Factory',
    description:
      'Gourmet burger joint known for massive, juicy patties and custom toppings.',
    address: {
      street: 'Adajan Gam, Near Pal',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395009',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.01, baseLat + 0.03],
      },
    },
    contact: { phone: '9121040006', email: 'burgerfactory@example.com' },
    cuisine_type: [
      'Burgers',
      'Fast-Food',
      'Dinner',
      'Lunch',
      'BBQ',
      'Sandwiches',
    ],
    rating: 4.2,
    numberOfReviews: 6100,
    opening_hours: [{ day: 'Saturday', open: '11:00', close: '23:30' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 950,
    delivery_time_mins: 40,
  },
  {
    name: 'That Food Truck',
    description:
      'Popular spot for Indo-Chinese street favorites and quick noodles.',
    address: {
      street: 'VIP Road, Vesu',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.035, baseLat - 0.01],
      },
    },
    contact: { phone: '9121040007', email: 'thatfoodtruck@example.com' },
    cuisine_type: [
      'Chinese',
      'Street-Food',
      'Fast-Food',
      'Soups',
      'Dinner',
      'Lunch',
    ],
    rating: 4.1,
    numberOfReviews: 7500,
    opening_hours: [{ day: 'Sunday', open: '17:00', close: '00:00' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 500,
    delivery_time_mins: 30,
  },
  {
    name: 'Green Leaf Pure Veg',
    description:
      'Family restaurant serving a wide variety of North Indian and South Indian cuisines.',
    address: {
      street: 'Ghoddod Road, Near Iscon Mall',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.002, baseLat - 0.005],
      },
    },
    contact: { phone: '9121040008', email: 'greenleaf@example.com' },
    cuisine_type: [
      'North-Indian',
      'South-Indian',
      'Indian',
      'Lunch',
      'Dinner',
      'Vegan',
    ],
    rating: 4.4,
    numberOfReviews: 10100,
    opening_hours: [{ day: 'Monday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 9,
    is_veg: true,
    cost_for_two: 800,
    delivery_time_mins: 45,
  },
  {
    name: "La Pino'z Pizza",
    description:
      'Popular pizza chain known for its massive, fully loaded pizzas.',
    address: {
      street: 'Adajan, Opposite LP Savani School',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395009',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.025, baseLat + 0.025],
      },
    },
    contact: { phone: '9121040009', email: 'lapinoz.surat@example.com' },
    cuisine_type: [
      'Pizza',
      'Italian',
      'Fast-Food',
      'Dinner',
      'Lunch',
      'Burgers',
    ],
    rating: 4.1,
    numberOfReviews: 8200,
    opening_hours: [{ day: 'Tuesday', open: '11:00', close: '23:45' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 650,
    delivery_time_mins: 30,
  },
  {
    name: 'Mad Over Donuts',
    description:
      'Specialty shop for various flavors of donuts and coffee beverages.',
    address: {
      street: 'VR Mall, Dumas Road',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.018, baseLat - 0.03],
      },
    },
    contact: { phone: '9121040010', email: 'mod.surat@example.com' },
    cuisine_type: [
      'Desserts',
      'Beverages',
      'Fast-Food',
      'Breakfast',
      'Indian-Sweets',
      'Sandwiches',
    ],
    rating: 4.5,
    numberOfReviews: 5300,
    opening_hours: [{ day: 'Wednesday', open: '10:00', close: '22:00' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 400,
    delivery_time_mins: 25,
  },
  // --- Surat Restaurant 11-15 ---
  {
    name: 'Kobe Sizzlers',
    description:
      'Classic restaurant known for its hot-plate sizzler presentations.',
    address: {
      street: 'Athwa Gate, Near Science Centre',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395001',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.008, baseLat + 0.003],
      },
    },
    contact: { phone: '9121040011', email: 'kobe.surat@example.com' },
    cuisine_type: ['BBQ', 'Dinner', 'Lunch', 'Fast-Food', 'Italian', 'Soups'],
    rating: 4.3,
    numberOfReviews: 7800,
    opening_hours: [{ day: 'Thursday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 1200,
    delivery_time_mins: 40,
  },
  {
    name: 'South Indian Delight',
    description:
      'Authentic South Indian restaurant, famous for its ghee roast dosa and idli.',
    address: {
      street: 'Ambawadi, Near Palanpur',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395009',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.01, baseLat + 0.04],
      },
    },
    contact: { phone: '9121040012', email: 'southdelight@example.com' },
    cuisine_type: [
      'South-Indian',
      'Breakfast',
      'Indian',
      'Street-Food',
      'Lunch',
      'Vegan',
    ],
    rating: 4.2,
    numberOfReviews: 6500,
    opening_hours: [{ day: 'Friday', open: '07:00', close: '22:00' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 400,
    delivery_time_mins: 25,
  },
  {
    name: 'Fauji Niwasi (The Army Mess)',
    description:
      'Simple, rustic spot popular for its non-vegetarian North Indian curries and kebabs.',
    address: {
      street: 'Opposite Railway Station, Station Road',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.01, baseLat + 0.015],
      },
    },
    contact: { phone: '9121040013', email: 'fauji@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'Dinner',
      'Lunch',
      'BBQ',
      'Fast-Food',
    ],
    rating: 4.0,
    numberOfReviews: 4900,
    opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:30' }],
    is_active: true,
    min_order_value: 450,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 1000,
    delivery_time_mins: 45,
  },
  {
    name: 'Fresh Mex Grill',
    description:
      'Quick-service outlet for customized burritos, nachos, and quesadillas.',
    address: {
      street: 'Vesu Main Road, Near Reliance Mall',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.04, baseLat - 0.015],
      },
    },
    contact: { phone: '9121040014', email: 'freshmex@example.com' },
    cuisine_type: [
      'Mexican',
      'Fast-Food',
      'Lunch',
      'Dinner',
      'Salads',
      'Vegan',
    ],
    rating: 4.3,
    numberOfReviews: 3800,
    opening_hours: [{ day: 'Sunday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 8,
    is_veg: false,
    cost_for_two: 750,
    delivery_time_mins: 35,
  },
  {
    name: 'Kwality Walls Swirls',
    description:
      'Ice cream and dessert parlor offering sundaes and classic frozen treats.',
    address: {
      street: 'Gaurav Path, Pal',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395009',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.02, baseLat + 0.035],
      },
    },
    contact: { phone: '9121040015', email: 'kwality.surat@example.com' },
    cuisine_type: [
      'Desserts',
      'Beverages',
      'Fast-Food',
      'Indian-Sweets',
      'Sandwiches',
      'Breakfast',
    ],
    rating: 4.4,
    numberOfReviews: 6900,
    opening_hours: [{ day: 'Monday', open: '10:00', close: '23:00' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 6,
    is_veg: true,
    cost_for_two: 350,
    delivery_time_mins: 20,
  },
  // --- Surat Restaurant 16-20 ---
  {
    name: 'Sushi Nation',
    description:
      'Dedicated Japanese restaurant serving fresh sushi, sashimi, and udon.',
    address: {
      street: 'Dumas Road, Near Airport',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.05, baseLat - 0.02],
      },
    },
    contact: { phone: '9121040016', email: 'sushination@example.com' },
    cuisine_type: ['Japanese', 'Sushi', 'Dinner', 'Healthy', 'Lunch', 'Soups'],
    rating: 4.5,
    numberOfReviews: 4100,
    opening_hours: [{ day: 'Tuesday', open: '12:30', close: '23:30' }],
    is_active: true,
    min_order_value: 700,
    delivery_radius_km: 10,
    is_veg: false,
    cost_for_two: 1900,
    delivery_time_mins: 55,
  },
  {
    name: 'The Italian Bistro',
    description:
      'Casual fine dining offering pasta, gourmet pizzas, and Italian mains.',
    address: {
      street: 'Adajan Gam, Near Adajan Patia',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395009',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.03, baseLat + 0.03],
      },
    },
    contact: { phone: '9121040017', email: 'italianbistro@example.com' },
    cuisine_type: ['Italian', 'Pizza', 'Dinner', 'Lunch', 'Soups', 'Healthy'],
    rating: 4.3,
    numberOfReviews: 5500,
    opening_hours: [{ day: 'Wednesday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 8,
    is_veg: true,
    cost_for_two: 1300,
    delivery_time_mins: 40,
  },
  {
    name: 'Kathiawadi Kitchen',
    description:
      'Specializes in spicy, rich Kathiawadi cuisine, a sub-type of Gujarati food.',
    address: {
      street: 'Udhna Main Road, Near Sachin GIDC',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395002',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.015, baseLat - 0.01],
      },
    },
    contact: { phone: '9121040018', email: 'kathiawadi@example.com' },
    cuisine_type: [
      'Indian',
      'North-Indian',
      'Lunch',
      'Dinner',
      'Street-Food',
      'Vegan',
    ],
    rating: 4.1,
    numberOfReviews: 3200,
    opening_hours: [{ day: 'Thursday', open: '11:30', close: '22:30' }],
    is_active: true,
    min_order_value: 350,
    delivery_radius_km: 10,
    is_veg: true,
    cost_for_two: 700,
    delivery_time_mins: 50,
  },
  {
    name: 'The Kebab Corner',
    description:
      'Takeaway spot for Mughlai and North Indian grilled meats and curries.',
    address: {
      street: 'Ring Road, Near Millennium Mall',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395002',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.01, baseLat + 0.005],
      },
    },
    contact: { phone: '9121040019', email: 'kebabcorner@example.com' },
    cuisine_type: [
      'BBQ',
      'North-Indian',
      'Indian',
      'Dinner',
      'Fast-Food',
      'Lunch',
    ],
    rating: 4.0,
    numberOfReviews: 4800,
    opening_hours: [{ day: 'Friday', open: '18:00', close: '01:00' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 900,
    delivery_time_mins: 35,
  },
  {
    name: 'Malgudi Dosa Center',
    description:
      'Late-night spot for innovative and classic South Indian dosas.',
    address: {
      street: 'Vesu, Near University',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.045, baseLat - 0.005],
      },
    },
    contact: { phone: '9121040020', email: 'malgudi.dosa@example.com' },
    cuisine_type: [
      'South-Indian',
      'Street-Food',
      'Fast-Food',
      'Dinner',
      'Breakfast',
      'Indian',
    ],
    rating: 4.3,
    numberOfReviews: 7000,
    opening_hours: [{ day: 'Saturday', open: '17:00', close: '02:00' }],
    is_active: true,
    min_order_value: 150,
    delivery_radius_km: 8,
    is_veg: true,
    cost_for_two: 450,
    delivery_time_mins: 30,
  },
  // --- Surat Restaurant 21-25 ---
  {
    name: 'Surati Farsan Mart',
    description:
      'Iconic store for local snacks like Ghari, Sutarfeni, and various farsan.',
    address: {
      street: 'Chowk Bazaar, Near Sardar Bridge',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.02, baseLat + 0.002],
      },
    },
    contact: { phone: '9121040021', email: 'suratifarsan@example.com' },
    cuisine_type: [
      'Indian-Sweets',
      'Desserts',
      'Street-Food',
      'Breakfast',
      'Indian',
      'Vegan',
    ],
    rating: 4.6,
    numberOfReviews: 12500,
    opening_hours: [{ day: 'Sunday', open: '09:00', close: '21:00' }],
    is_active: true,
    min_order_value: 200,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 400,
    delivery_time_mins: 25,
  },
  {
    name: 'Cafe De Flora',
    description:
      'A contemporary cafe offering quick healthy snacks, coffee, and shakes.',
    address: {
      street: 'Adajan, Near Star Bazaar',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395009',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.005, baseLat + 0.025],
      },
    },
    contact: { phone: '9121040022', email: 'cafedeflora@example.com' },
    cuisine_type: [
      'Beverages',
      'Healthy',
      'Breakfast',
      'Sandwiches',
      'Desserts',
      'Salads',
    ],
    rating: 4.4,
    numberOfReviews: 5800,
    opening_hours: [{ day: 'Monday', open: '09:00', close: '22:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 550,
    delivery_time_mins: 30,
  },
  {
    name: 'Peking Wok',
    description:
      'Traditional Chinese restaurant with a large menu of Indo-Chinese favorites.',
    address: {
      street: 'Ring Road, Near Central Mall',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395003',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.002, baseLat + 0.008],
      },
    },
    contact: { phone: '9121040023', email: 'pekingwok@example.com' },
    cuisine_type: [
      'Chinese',
      'Fast-Food',
      'Dinner',
      'Lunch',
      'Soups',
      'Japanese',
    ],
    rating: 4.1,
    numberOfReviews: 6500,
    opening_hours: [{ day: 'Tuesday', open: '12:00', close: '23:00' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 1100,
    delivery_time_mins: 45,
  },
  {
    name: 'Jalebi Express',
    description:
      'Sweet shop known for its fresh, crisp jalebis, fafda, and other morning snacks.',
    address: {
      street: 'Nana Varachha, Opp. Krishna Hospital',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395006',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.01, baseLat + 0.05],
      },
    },
    contact: { phone: '9121040024', email: 'jalebiexpress@example.com' },
    cuisine_type: [
      'Indian-Sweets',
      'Desserts',
      'Breakfast',
      'Street-Food',
      'Indian',
      'Vegan',
    ],
    rating: 4.5,
    numberOfReviews: 9000,
    opening_hours: [{ day: 'Wednesday', open: '07:00', close: '21:00' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 8,
    is_veg: true,
    cost_for_two: 300,
    delivery_time_mins: 30,
  },
  {
    name: 'Burger Singh',
    description: 'Indian-style burger chain with fusion flavors.',
    address: {
      street: 'Majura Gate, Next to Reliance Trends',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395001',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.012, baseLat - 0.001],
      },
    },
    contact: { phone: '9121040025', email: 'burgersingh@example.com' },
    cuisine_type: [
      'Burgers',
      'Fast-Food',
      'North-Indian',
      'Lunch',
      'Dinner',
      'Beverages',
    ],
    rating: 4.1,
    numberOfReviews: 4500,
    opening_hours: [{ day: 'Thursday', open: '11:00', close: '23:00' }],
    is_active: true,
    min_order_value: 250,
    delivery_radius_km: 6,
    is_veg: false,
    cost_for_two: 550,
    delivery_time_mins: 25,
  },
  // --- Surat Restaurant 26-30 ---
  {
    name: 'The Artisan Bakery',
    description:
      'High-end bakery with specialty breads, tarts, and European desserts.',
    address: {
      street: 'Vesu, Near Avadh Utopia',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.05, baseLat - 0.03],
      },
    },
    contact: { phone: '9121040026', email: 'artisanbakery@example.com' },
    cuisine_type: [
      'Desserts',
      'Beverages',
      'Breakfast',
      'Sandwiches',
      'Healthy',
      'Vegan',
    ],
    rating: 4.7,
    numberOfReviews: 3900,
    opening_hours: [{ day: 'Friday', open: '08:30', close: '21:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 900,
    delivery_time_mins: 35,
  },
  {
    name: 'Kobe House',
    description: 'Asian grill focusing on Japanese teriyaki and BBQ dishes.',
    address: {
      street: 'Piplod, Near Pal Gam',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.03, baseLat - 0.035],
      },
    },
    contact: { phone: '9121040027', email: 'kobehouse@example.com' },
    cuisine_type: ['Japanese', 'BBQ', 'Dinner', 'Lunch', 'Chinese', 'Soups'],
    rating: 4.4,
    numberOfReviews: 4200,
    opening_hours: [{ day: 'Saturday', open: '12:00', close: '23:30' }],
    is_active: true,
    min_order_value: 600,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 1400,
    delivery_time_mins: 45,
  },
  {
    name: 'Punjabi Tadka',
    description: 'Classic North Indian comfort food and rich gravies.',
    address: {
      street: 'Adajan, Near TP-10',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395009',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.02, baseLat + 0.045],
      },
    },
    contact: { phone: '9121040028', email: 'punjabitadka@example.com' },
    cuisine_type: [
      'North-Indian',
      'Indian',
      'Dinner',
      'Lunch',
      'BBQ',
      'Fast-Food',
    ],
    rating: 4.2,
    numberOfReviews: 5100,
    opening_hours: [{ day: 'Sunday', open: '11:30', close: '23:00' }],
    is_active: true,
    min_order_value: 450,
    delivery_radius_km: 8,
    is_veg: true,
    cost_for_two: 900,
    delivery_time_mins: 40,
  },
  {
    name: 'The Salad Bar',
    description: 'Dedicated counter for custom-built fresh salads and wraps.',
    address: {
      street: 'Ghoddod Road, Near TGB',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.005, baseLat - 0.015],
      },
    },
    contact: { phone: '9121040029', email: 'saladbar@example.com' },
    cuisine_type: [
      'Salads',
      'Healthy',
      'Vegan',
      'Lunch',
      'Dinner',
      'Sandwiches',
    ],
    rating: 4.5,
    numberOfReviews: 3000,
    opening_hours: [{ day: 'Monday', open: '10:00', close: '21:00' }],
    is_active: true,
    min_order_value: 350,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 750,
    delivery_time_mins: 25,
  },
  {
    name: 'Chennai Express',
    description:
      'Quick counter for South Indian breakfast items and filter coffee.',
    address: {
      street: 'Udhna Main Road, Near GIDC',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395002',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.025, baseLat - 0.005],
      },
    },
    contact: { phone: '9121040030', email: 'chennaiexpress@example.com' },
    cuisine_type: [
      'South-Indian',
      'Breakfast',
      'Beverages',
      'Indian',
      'Street-Food',
      'Fast-Food',
    ],
    rating: 4.3,
    numberOfReviews: 5900,
    opening_hours: [{ day: 'Tuesday', open: '06:30', close: '22:00' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 7,
    is_veg: true,
    cost_for_two: 350,
    delivery_time_mins: 20,
  },
  // --- Surat Restaurant 31-35 (Buffer to ensure all categories are hit 10+ times) ---
  {
    name: 'The Mexican House',
    description:
      'Fine-dining Mexican experience with traditional mole and enchiladas.',
    address: {
      street: 'Dumas Road, Near Rahul Raj Mall',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.04, baseLat - 0.025],
      },
    },
    contact: { phone: '9121040031', email: 'mexicanhouse@example.com' },
    cuisine_type: ['Mexican', 'Dinner', 'Lunch', 'Healthy', 'Salads', 'Soups'],
    rating: 4.5,
    numberOfReviews: 2800,
    opening_hours: [{ day: 'Wednesday', open: '12:30', close: '23:30' }],
    is_active: true,
    min_order_value: 600,
    delivery_radius_km: 10,
    is_veg: false,
    cost_for_two: 1500,
    delivery_time_mins: 50,
  },
  {
    name: 'Pasta & Beyond',
    description:
      'Italian specialist, focusing on handmade pasta dishes and risottos.',
    address: {
      street: 'Piplod, Near Big Bazaar',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.01, baseLat - 0.035],
      },
    },
    contact: { phone: '9121040032', email: 'pasta.beyond@example.com' },
    cuisine_type: ['Italian', 'Lunch', 'Dinner', 'Vegan', 'Pizza', 'Soups'],
    rating: 4.4,
    numberOfReviews: 4800,
    opening_hours: [{ day: 'Thursday', open: '12:00', close: '22:30' }],
    is_active: true,
    min_order_value: 400,
    delivery_radius_km: 8,
    is_veg: true,
    cost_for_two: 1100,
    delivery_time_mins: 40,
  },
  {
    name: 'Cold Coco Corner',
    description:
      'A local Surat institution famous for its thick, rich Cold Cocoa beverage.',
    address: {
      street: 'Nanpura, Near Tapti River',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395001',
      location: {
        type: 'Point',
        coordinates: [baseLon - 0.018, baseLat + 0.018],
      },
    },
    contact: { phone: '9121040033', email: 'coldcoco@example.com' },
    cuisine_type: [
      'Beverages',
      'Desserts',
      'Fast-Food',
      'Street-Food',
      'Indian-Sweets',
      'Breakfast',
    ],
    rating: 4.6,
    numberOfReviews: 14000,
    opening_hours: [{ day: 'Friday', open: '10:00', close: '23:00' }],
    is_active: true,
    min_order_value: 100,
    delivery_radius_km: 5,
    is_veg: true,
    cost_for_two: 200,
    delivery_time_mins: 15,
  },
  {
    name: 'Sushimi Sushi & Roll',
    description: 'Casual spot for quick sushi rolls and Asian appetizers.',
    address: {
      street: 'Adajan, Near Gujarat Gas Circle',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395009',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.035, baseLat + 0.04],
      },
    },
    contact: { phone: '9121040034', email: 'sushimi@example.com' },
    cuisine_type: [
      'Sushi',
      'Japanese',
      'Chinese',
      'Lunch',
      'Dinner',
      'Healthy',
    ],
    rating: 4.3,
    numberOfReviews: 3500,
    opening_hours: [{ day: 'Saturday', open: '11:30', close: '22:30' }],
    is_active: true,
    min_order_value: 500,
    delivery_radius_km: 9,
    is_veg: false,
    cost_for_two: 1200,
    delivery_time_mins: 40,
  },
  {
    name: 'The All-Day Grill',
    description:
      'Barbeque and Continental cafe offering all-day breakfast and grills.',
    address: {
      street: 'Ghoddod Road, Near VIP Plaza',
      city: 'Surat',
      state: 'Gujarat',
      zip_code: '395007',
      location: {
        type: 'Point',
        coordinates: [baseLon + 0.008, baseLat - 0.008],
      },
    },
    contact: { phone: '9121040035', email: 'alldaygrill@example.com' },
    cuisine_type: [
      'BBQ',
      'Breakfast',
      'Sandwiches',
      'Burgers',
      'Lunch',
      'Dinner',
    ],
    rating: 4.2,
    numberOfReviews: 4000,
    opening_hours: [{ day: 'Sunday', open: '08:00', close: '23:00' }],
    is_active: true,
    min_order_value: 300,
    delivery_radius_km: 7,
    is_veg: false,
    cost_for_two: 950,
    delivery_time_mins: 35,
  },
];

export default suratRestaurants;
