import React from 'react';

// Importing all the lucide icons that are being used thorugh out the app
import {
  ArrowLeft,
  Menu,
  ChevronLeft,
  ChevronRight,
  MapPin,
  Star,
  Heart,
  Bell,
  Home,
  CheckCircle,
  AlertCircle,
  Clock,
  User,
  Tag,
  Search,
  Building2,
  X,
  ChevronDown,
  Facebook,
  Instagram,
  Twitter,
  Linkedin,
  Youtube,
  ShoppingBag,
  CreditCard,
  Settings,
  HelpCircle,
  LogOut,
  Eye,
  EyeOff,
  Mail,
  Lock,
  ArrowRight,
  Truck,
  Plus,
  Minus,
  Trash2,
  Info,
  Building,
  RotateCcw,
  Store,
  Filter,
  Check,
  Zap,
  TrendingUp,
  Award,
  Shield,
  BarChart3,
  Coffee,
  Play,
  Headphones,
  Gift,
  Users2,
  Briefcase,
  Newspaper,
  Percent,
  Crown,
  PizzaIcon,
  Sandwich,
  EggFried,
  Cake,
  Leaf,
  FireExtinguisherIcon,
  Clipboard,
  LucideEdit3,
  LucideTrash2,
  Camera,
  Save,
  List,
  Grid3X3,
  FilterIcon,
  MessageCircle,
  Phone,
  Send,
  Paperclip,
  ThumbsUp,
  ThumbsDown,
  Book,
  FileText,
  Video,
  ExternalLink,
  Package,
  ChevronUp,
  XCircle,
  Calendar,
  Navigation,
  Receipt,
  DollarSign,
  Download,
  Wallet,
  AlertTriangle,
  RefreshCw,
  Database,
  Sparkles,
  ShoppingCart,
  LogIn,
} from 'lucide-react';

// A map from a friendly string name to the actual Lucide React component
const iconMap = {
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  search: Search,
  'shopping-cart': ShoppingCart,
  user: User,
  'map-pin': MapPin,
  star: Star,
  heart: Heart,
  bell: Bell,
  home: Home,
  menu: Menu,
  x: X,
  'check-circle': CheckCircle,
  'alert-circle': AlertCircle,
  clock: Clock,
  tag: Tag,
  building2: Building2,
  'chevron-down': ChevronDown,
  facebook: Facebook,
  instagram: Instagram,
  twitter: Twitter,
  linkedin: Linkedin,
  youtube: Youtube,
  'arrow-left': ArrowLeft,
  'credit-card': CreditCard,
  settings: Settings,
  'help-circle': HelpCircle,
  logout: LogOut,
  'shopping-bag': ShoppingBag,
  eye: Eye,
  'eye-off': EyeOff,
  mail: Mail,
  lock: Lock,
  'arrow-right': ArrowRight,
  truck: Truck,
  plus: Plus,
  minus: Minus,
  'trash-2': Trash2,
  info: Info,
  building: Building,
  'rotate-ccw': RotateCcw,
  store: Store,
  filter: Filter,
  check: Check,
  zap: Zap,
  'trending-up': TrendingUp,
  award: Award,
  shield: Shield,
  'bar-chart-3': BarChart3,
  coffee: Coffee,
  play: Play,
  'head-phones': Headphones,
  gift: Gift,
  'users-2': Users2,
  users: User,
  'building-2': Building2,
  briefcase: Briefcase,
  newspaper: Newspaper,
  login: LogIn,
  percent: Percent,
  crown: Crown,
  pizza: PizzaIcon,
  sandwich: Sandwich,
  'egg-fried': EggFried,
  cake: Cake,
  leaf: Leaf,
  fire: FireExtinguisherIcon,
  clipboard: Clipboard,
  'lucide-edit-3': LucideEdit3,
  'lucide-trash-2': LucideTrash2,
  camera: Camera,
  save: Save,
  'grid-3x3': Grid3X3,
  list: List,
  'message-circle': MessageCircle,
  phone: Phone,
  send: Send,
  'paper-clip': Paperclip,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  book: Book,
  'file-text': FileText,
  video: Video,
  'external-Link': ExternalLink,
  package: Package,
  'chevron-up': ChevronUp,
  'x-circel': XCircle,
  calendar: Calendar,
  navigation: Navigation,
  receipt: Receipt,
  'dollar-sign': DollarSign,
  download: Download,
  wallet: Wallet,
  'alert-triangle': AlertTriangle,
  'refresh-cw': RefreshCw,
  database: Database,
  sparkles: Sparkles,
};

const Icon = ({
  name,
  size = 20, // Default size
  color = 'currentColor', // Default color (inherits from text color)
  className = '', // For additional Tailwind or custom classes
  ...props // rest props
}) => {
  const LucideIconComponent = iconMap[name.toLowerCase()];

  if (!LucideIconComponent) {
    // Log a warning in development if an unmapped icon name is used
    if (process.env.NODE_ENV === 'development') {
      console.warn(
        `Icon "${name}" not found or not mapped in components/ui/Icon.jsx. ` +
          `Please import it from 'lucide-react' and add it to the 'iconMap'.`
      );
    }
    return null;
  }

  // Rendering the specific Lucide icon component with the given props
  return (
    <LucideIconComponent
      size={size}
      color={color}
      className={className}
      {...props}
    />
  );
};

export default Icon;
